### ISSUE TITLE
Parallel makes are unreliable

### ISSUE THREAD

**Issue by jchampio** [icing/mod_md#10]
Probably not very critical at this point, but `make -j` often fails for me because the top-level rule for making `src/libapachemd.la` overlaps with the work done by the recursive `SUBDIRS`. This leads to errors like

    mv: cannot stat 'acme/.deps/libapachemd_la-md_acme.Tpo': No such file or directory
    Makefile:540: recipe for target 'acme/libapachemd_la-md_acme.lo' failed
    make[1]: *** [acme/libapachemd_la-md_acme.lo] Error 1

At the same time that the top-level Makefile recurses into the `src` subdirectory to start its work (it does this because we've set the `SUBDIRS` variable), the rule for `src/libapachemd.la` is spawning a second process to do the same work with `$(MAKE) -C src`. They step on each other.

**Comment by icing** [comment]
I see. Best solution? Remove that dependency and rely on subdir order?

**Comment by icing** [comment]
Talking about makefiles: @jchampio, do you have a recommendation how to bring this best into the httpd subversion tree?

**Comment by jchampio** [comment]
> I see. Best solution? Remove that dependency and rely on subdir order?

IMHO the *best* solution is to move from a recursive build solution to one in which a single Make invocation has the entire dependency graph, but honestly that's a lot of work for a module that you're hoping to fold into the httpd build system anyway. So yeah, removing the duped .PHONY targets works fine for me. See 411d3e8 (linked above); I'll open a pull request.

> Talking about makefiles: @jchampio, do you have a recommendation how to bring this best into the httpd subversion tree?

Hmm... not sure. `a2md` belongs in the `support/` tree, `mod_md` belongs in the `modules/` tree, and the tests need to be folded into httpd's `make check`, which hopefully shouldn't be too hard. You're making use of a lot of Automake magic -- which is good in that it's less work, but we'll have to reconcile it with the ancient httpd build cruft... much of which duplicates Automake stuff. Maybe this is a good time to modernize those pieces of httpd?
