### ISSUE TITLE
503 error on renewals

### ISSUE THREAD

**Issue by MrDini123** [icing/mod_md#102]
Hi,

I am using this module since last November and it worked perfectly. However in like May it stopped generating the new certs to my domain, and I can see this in the apache log:

```
Init: mydomain.tld:443 will respond with '503 Service Unavailable' for now. This host is part of a Managed Domain, but no SSL certificate is available (yet).
```

And the renewal itself seems to be unsuccessfull too:

```
Invalid response from http://mydomain.tld/.well-known/acme-challenge/<snip>: \"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service\"
```

That's what the https://acme-v01.api.letsencrypt.org/acme/authz/<snip> returns for the http-01 method. I am using the latest, 1.1.16 version of mod_md but it still gives me 503 service unavailable for everything... 🤔 

What can I do?

**Comment by MrDini123** [comment]
No, it gives me 503 aswell. But the config worked before, so not Apache misconfiguration.

**Comment by icing** [comment]
Well, if you are certain then this is a mystery.

**Comment by icing** [comment]
In regard to your question. You need to find out where the 503 come from:

 * you can raise ```LogLevel md:trace1``` to see if it tells you anything for such requests
 * you can disable the port 443 vhost for that domain
 * you can remove that domain from ```mod_md```
 * You can post the relevant configuration parts in this ticket and have us look at things that may cause this

I am not aware of any bugs in mod_md that may cause this, nor any recent changes. 

One possible explanation is that:
 
 * you once had a setup that worked and got certificates
 * you made a change that redirects all http: to https:
 * this continued to work as long as the Let's Encrypt certificate was valid
 * the certificates expired and now you get 503

**Comment by Diniboy1123** [comment]
Here is the current config:

```
#MDCAChallenges http-01
MDomain mydomain.tld
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
MDPortMap 80:1234 443:1234
MDRequireHttps temporary
#SSLProtocol +SSLv3 +TLSv1 +TLSv1.1 +TLSv1.2
SSLSessionCache "shmcb:/a/random/path(512000)"
SSLSessionCacheTimeout 600

<VirtualHost *:1234>
    DocumentRoot "/a/random/path"
    Alias /path /a/random/path/
    ServerName mydomain.tld
    ServerAlias mydomain.tld
    SSLEngine on
</VirtualHost>
```

Before that the `MDCAChallenges http-01` was uncomented but I tried to test without that too.

And I know it is a really bad practice to use custom ports, but I am using a router and a port forward to send these things to the correct port. Because this machine has another webserver on port 80 & 443.

**Comment by icing** [comment]
This one
```
MDPortMap 80:1234 443:1234
```
means you server http: and https: traffic on the same port.

**Comment by MrDini123** [comment]
Yeah. And it is a bad idea?

**Comment by icing** [comment]
There is a reason that both use different ports, 80 vs. 443.

Map 80 to 1233, define an extra vhost for that, like the other one _without_ ```SSLEngine```, and you should see improvements.

**Comment by icing** [comment]
Did you have a chance to test your server on two ports?

**Comment by MrDini123** [comment]
Yes, I tried to use two different ports, but now the port which is forwarded to our 80 port is completely unreachable from the WAN side. I guess it is an ISP issue that I have to solve first...

**Comment by icing** [comment]
OK, just checking. We can leave this open for now.

**Comment by icing** [comment]
@MrDini123 any news on this? Otherwise I'd like to close now.
