### ISSUE TITLE
library apr-1 not found

### ISSUE THREAD

**Issue by jmwebservices** [icing/mod_md#107]
@icing @studersi 
I ran into this same issue today. I also compile from source and I do not remove the install directory. The following is the output of `apxs -q` and I confirmed that the directories and files do exist. Any help would be appreciated!
```
[root@XX mod_md]# ./configure --enable-werror --with-apxs=/WAMP/apache/bin/apxs
```
```
[root@XX mod_md]# /WAMP/apache/bin/apxs -q | fgrep APR
APR_BINDIR=/WAMP/apache/bin
APR_INCLUDEDIR=/WAMP/apache/include
APR_CONFIG=/WAMP/apache/bin/apr-1-config
APR_VERSION=1.6.3
```

P.S.
Nevermind the references to WAMP in the path. It's on CentOS 7.

_Originally posted by @jmwebservices in https://github.com/icing/mod_md/issues/88#issuecomment-453842505_

**Comment by icing** [comment]
In ```configure.ac``` there are checks that the library can be linked:

```
AC_CHECK_LIB([apr-1], [apr_pool_create_ex], [LIB_APR=apr-1], [AC_MSG_ERROR("library apr-1 not found")])
```

For some reason, this does not seem to work on your installation. In ```config.log``` you'll find the command that was used to make this test. On my machine, this looks like:

```
configure:14500: checking for apr_pool_create_ex in -lapr-1
configure:14525: gcc -o conftest -g -O2  -I/opt/apache-2.4.x/include -I/opt/apache-2.4.x/include  -L/opt/apache-2.4.x/lib conftest.c -lapr-1  -ljansson -lcrypto  >&5
configure:14525: $? = 0
```

You can try running this command directly and see if it gives you any details. Maybe apr-1 is not the problem but something else is?

**Comment by jmwebservices** [comment]
I ended up just recompiling Apache 2.4.37 `--with-md` and it compiled just fine. I did, however, have to update curl since compiling `--with-md` initially failed stating that curl >= 7.50 was required. This notice was not triggered when compiling Apache without md support.

**Comment by icing** [comment]
I just added the same version check to the configure here. Anything else you propose for improvement?
