### ISSUE TITLE
mod_md and wildcard certificates

### ISSUE THREAD

**Issue by jmwebservices** [icing/mod_md#108]
I am setting up mod_md and I ran into an issue where the server threw the following warning regarding a wildcard domain.

> [md:error] (22)Invalid argument: md www.domain.com with invalid domain name: *.domain.com

Are wildcard domains not supported by mod_md or did I make a mistake somewhere? I found the following reference to wildcard domains and it appears that they are not supported.

> https://github.com/icing/mod_md/issues/103#issuecomment-420181837
> That sounds like the use case for a wildcard certificate when you have a (almost) unlimited number of subdomains to serve. That can be obtained from Let's Encrypt, but not via `mod_md`.

Thanks.

**Comment by icing** [comment]
Wildcard certificates are indeed not supported (yet) by mod_md. Let's Encrypt issues wildcards only when the domain is authenticated via special DNS records, so you need some special setup. The server cannot do it by itself alone.

You'll find various articles on the net regarding possible implementations.
