### ISSUE TITLE
503 Service Unavailable after reboot

### ISSUE THREAD

**Issue by alvaro-octal** [icing/mod_md#110]
Hi,

I'm  facing what _probably_ is not a `mod_md` bug by itself, and I running out of ideas. Environment:

- Raspberry PI 3B
- Fedora 29 AARCH64
- Apache 2.4.37
- Mod_MD 1.1.17 and 1.99

I've successfully created my certificates, and everything works fine in fact, but when I reboot the system all the hosts return a `503 - Service Unavailable` page. Digging a bit in the logs, it seems that mod_md is refusing to serve those hosts due to a `certificate valid in future`.

```
[Sat Jan 19 02:39:07.042023 2019] [mpm_event:notice] [pid 520:tid 281473233395712] AH00492: caught SIGWINCH, shutting down gracefully
[...] Did reboot here
[Fri Jan 11 12:41:18.048329 2019] [suexec:notice] [pid 501:tid 281473077350400] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Jan 11 12:41:18.090692 2019] [md:error] [pid 501:tid 281473077350400] md{my-domain.com}: error, certificate valid in future (clock wrong?)
[...]
[Fri Jan 11 12:41:19.015604 2019] [md:error] [pid 501:tid 281473077350400] md{my-domain.com}: error, certificate valid in future (clock wrong?)
[Fri Jan 11 12:41:19.017793 2019] [md:error] [pid 501:tid 281473077350400] md(my-domain.com): in error state, unable to drive forward. If unable to  detect the cause, you may remove the staging or even domain  sub-directory for this MD and start all over.
[Fri Jan 11 12:41:19.017878 2019] [md:warn] [pid 501:tid 281473077350400] AH10063: md(my-domain.com): seems errored. Will not process this any further.
[Fri Jan 11 12:41:19.022056 2019] [md:error] [pid 501:tid 281473077350400] md{my-domain.com}: error, certificate valid in future (clock wrong?)
[...]
[Fri Jan 11 12:41:19.320590 2019] [md:error] [pid 501:tid 281473077350400] md{my-domain.com}: error, certificate valid in future (clock wrong?)
[Fri Jan 11 12:41:19.352584 2019] [lbmethod_heartbeat:notice] [pid 501:tid 281473077350400] AH02282: No slotmem from mod_heartmonitor
[Fri Jan 11 12:41:19.379974 2019] [mpm_event:notice] [pid 501:tid 281473077350400] AH00489: Apache/2.4.37 (Fedora) OpenSSL/1.1.1a configured -- resuming normal operations
[Fri Jan 11 12:41:19.380373 2019] [core:notice] [pid 501:tid 281473077350400] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
dc1:~ root$ hwclock -r
hwclock: Cannot access the Hardware Clock via any known method.
hwclock: Use the --verbose option to see the details of our search for an access method.
dc1:~ root$ hwclock -r --verbose
hwclock from util-linux 2.32.1
System Time: 1547862219.273937
Trying to open: /dev/rtc0
Trying to open: /dev/rtc
Trying to open: /dev/misc/rtc
No usable clock interface found.
hwclock: Cannot access the Hardware Clock via any known method.
dc1:~ root$ date
Sat Jan 19 02:43:59 CET 2019
```

NTP daemon was enabled before reboot, and doing a `systemctl restart httpd` solves the issue. Seems that the module checks check the certificates validity before the system can set the correct date, and is unable to provide a valid one before due to a missing hardware clock.

**Comment by icing** [comment]
If I read that correct, your server clock was lagging 8 days behind the date-time of the rest of the world. (Log entries show Jan 11, date command gives Jan 19.)

The dates in the certificate come from Let's Encrypt. They set the "valid-from" and "valid-until" dates. mod_md sees that the certificate is not valid yet and refuses to use it. That is what the error messages in the log are about.

The only real solution - as you found yourself - is to have a correct server clock.

**Comment by icing** [comment]
Assuming it works for you now, let's close this issue.

**Comment by alvaro-octal** [comment]
Yep, will investigate a bit on how the Raspberry PI determined the clock on startup, as you can see, the system clock was fine when I did `date` (a workaround could be to wait until de system corrects the date to do the check). Closing for now.
