### ISSUE TITLE
503 Service Unavailable / This host is part of a Managed Domain, but no SSL certificate is available (yet)

### ISSUE THREAD

**Issue by EIKAInc** [icing/mod_md#112]
Dear @icing

I followed [the Let's Encrypt for Apache :: mod_md artice](https://www.apachelounge.com/viewtopic.php?p=35959) on Apache Lounge and can't get it wokring. In SSL log I see:

`[Tue Jan 22 15:51:34.841123 2019] [ssl:warn] [pid 176:tid 340] AH10085: Init: domain.dom:443 will respond with '503 Service Unavailable' for now. This host is part of a Managed Domain, but no SSL certificate is available (yet). 
[Tue Jan 22 15:51:35.203143 2019] [md:debug] [pid 4236:tid 236] mod_md.c(1109): AH10076: domain.dom: manages server domain.dom 
[Tue Jan 22 15:51:35.204143 2019] [md:debug] [pid 4236:tid 236] mod_md.c(1161): AH10113: md_get_certificate called for vhost domain.dom. 
[Tue Jan 22 15:51:35.204143 2019] [md:debug] [pid 4236:tid 236] mod_md.c(1222): AH10116: domain.dom: providing fallback certificate for server domain.dom`

The author of this artice isn't using this module and can't help. The rest deatails posted at [Apache Lounge's thread](https://www.apachelounge.com/viewtopic.php?p=37768l).

Please help!

**Comment by icing** [comment]
Reading the thread, the problem seems to have been resolved.

Looks like the DNS records for the host needed some cleanup. When Let's Encrypt tries to verify a domain and sees something that looks fishy, they might not believe you and will not hand over a certificate. As they should.
