### ISSUE TITLE
httpd can not be started with mod_md enabled

### ISSUE THREAD

**Issue by uhliarik** [icing/mod_md#115]
Hey Stefan,

is it true, that httpd can not be started, if mod_md is enabled and httpd is run under different user than root (e.g.. test suit - run under test user). 

If I try to run httpd with mod_md loaded, md_try_chown function is executed and therefore chown is returning an error (non-root user can not change permission of directory - (1)Operation not permitted: AH10082: Can't change owner of /var/lib/httpd/state/md/challenges).

**Comment by icing** [comment]
The problem is, I think, that you tell your server to impersonate user ```apache```, group ```nobody``` after startup. And ```mod_md``` has to make the directories ```challenges``` and ```staging``` writeable for that user. But ```test``` does not have permissions to do that.

**Comment by uhliarik** [comment]
Thanks for the answer. It indeed works, if I comment out ```User``` and ```Group``` directives. But according to manual (https://httpd.apache.org/docs/2.4/mod/mod_unixd.html#user):

If you start the server as a non-root user, it will fail to change to the lesser privileged user, and will instead continue to run as that original user. If you do start the server as root, then it is normal for the parent process to remain running as root.

So I'm just wondering, if User and Group directives are not taken into consideration (httpd is executed under non-root user), should not skip mod_md trying chowning directories?

**Comment by icing** [comment]
You are correct! Please try v1.99.6. It suppresses the chown() when not started as root.

**Comment by uhliarik** [comment]
Thanks for the fix Stefan! Test is now passing even with loaded mod_md :). So the patch works!

**Comment by icing** [comment]
Great! Thanks!
