### ISSUE TITLE
Version2: ACMEv2 Support

### ISSUE THREAD

**Issue by icing** [icing/mod_md#118]
[See the description of the upcoming ACMEv2 support in the wiki](https://github.com/icing/mod_md/wiki/V2Design#acmev2-support).

Please provide feedback to the feature plan here in this issue. I will update the description. If you want more interactive/lengthy discussion, the [Apache users mailing list](https://httpd.apache.org/userslist.html) may be better suited.

Thanks!

**Comment by MBfromOK** [comment]
If possible, please implement the ability to validate over https.
or the ability to use a string / page served by my server.

Why:
In my case, my ISP blocks all HTTP (port 80) traffic forcing me to validate with DNS (as all HTTP-01 or webroot responses are dropped on return).  The forces me to manually renew my my certs by manually updating TXT dns records.

**Comment by icing** [comment]
Hi @MBfromOK, the upcoming version2 will indeed support that. If you know how to patch and compile your own Apache, you might already try the v1.99.x pre-releases.

**Comment by icing** [comment]
Released in v2.0.0 and following.
