### ISSUE TITLE
Version2: OCSP Stapling

### ISSUE THREAD

**Issue by icing** [icing/mod_md#119]
[See the description of the upcoming OCSP stapling support in the wiki](https://github.com/icing/mod_md/wiki/V2Design#ocsp-stapling).

Please provide feedback to the feature plan here in this issue. I will update the description. If you want more interactive/lengthy discussion, the [Apache users mailing list](https://httpd.apache.org/userslist.html) may be better suited.

Thanks!

**Comment by bazzadp** [comment]
Thanks! Sounds good. Longer term are there plans to also fix the mod_ssl functionality for those not using mod_md or do you think these will always be separate?

**Comment by icing** [comment]
For backward compatibility, the existing on will need to remain in the 2.4.x release line. We cannot break existing behaviour - even with good intentions.

The argument can be made that it should be standalone in mod_ssl. But I want to write it using the libcurl as client and a mod_watchdog dependency is also needed. Basically what mod_md requires today already. So, not much to lose here.

As to the use of ```MDomain```s or plain vhosts: it needs to be available for virtual hosts that do not have a Let's Encrypt cert, for sure. How such configuration directives may look, I do not know yet.

**Comment by icing** [comment]
Released in v2.1.0 and following.
