### ISSUE TITLE
Version 0.3.0 does not build on Windows

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#12]
I am not native English speaking, so I hope I am clear.

The current 0.3.0 not build on Windows:

 md_os.c(121): error C2371: 'mpm_signal_service': redefinition; different basic types
  C:\VC15\Win32\httpd-2.4.27\server\mpm\winnt\mpm_winnt.h(56): note: see declaration of 'mpm_signal_service'
md_os.c(128): error C2561: 'md_server_graceful': function must return a value
  md_os.c(126): note: see declaration of 'md_server_graceful'

note:
Version 0.2.0 did not have a compiler error, but a link error.  It was building by commenting in md_os.c 
/*    mpm_signal_service(p, 1); */

**Comment by SteffenAL** [comment]
Is there coming a v2 2.4 openssl patch (not running trunk here) ?

**Comment by icing** [comment]
Please try v0.5.0 (the current master).

**Comment by SteffenAL** [comment]
No new mod_ssl patch for 2.4.x ? Running 2.4.27 (no trunk)

**Comment by icing** [comment]
Just checked in a 2.4.x patch (the trunk v2 would have worked, as other already reported), but for you I go the extra mile.

**Comment by SteffenAL** [comment]
Saw that Win32 restart code is removed and now mod_md builds.

Also a2md and the patched mod_ssl works.
