### ISSUE TITLE
md_acme fails on apache: Unable to understand ACME server response. Wrong ACME protocol version?

### ISSUE THREAD

**Issue by aprich** [icing/mod_md#121]
I am trying to set up Let's Encrypt using tls-alpn-01 challenge on a CentOS 7 running apache (2.4.39) only listening on port 443 (https). I have built apache and mod_md (v1.1.18) from source.

At apache start up I will only get a fallback certificate for my domain. I have attached the apache log from my latest test. At the end of the log file there is a warning
```
[md:warn] [pid 54152:tid 140190995031808] Unable to understand ACME server response. Wrong ACME protocol version?
```
but an Internet search does not yield anything interesting.

Has anyone encountered this is issue? Or have any hints on what to try next.

My mod_md.conf contains
```
Protocols h2 http/1.1 acme-tls/1

<IfModule mod_md.c>
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
MDPortMap 80:- 443:443
MDCAChallenges tls-alpn-01
MDRequireHttps temporary

# Test                                                                                                                              
MDCertificateAuthority https://acme-staging-v02.api.letsencrypt.org/directory
# Production                                                                                                                        
#MDCertificateAuthority https://acme-v02.api.letsencrypt.org/directory                                                              
</IfModule>
```
and my vhost has MDomain and SSLEngine set:

```
MDomain host.domain.com
SSLEngine on
```

[apache.log](https://github.com/icing/mod_md/files/3166424/apache.log)

**Comment by icing** [comment]
The ACMEv2 procotol is not supported in the Apache release of mod_md. The project to implement this is just about to start and early experience versions are available here. But be aware that for tls-alpn-01 you also need a patched mod_ssl, so it is really only usable for someone who can build the complete server herself.

**Comment by icing** [comment]
Just read you message once more: since you build yourself, take a 1.99.x version of the module and apply the mod_ssl patch contain in it. Your configuration looks fine otherwise.

**Comment by aprich** [comment]
Thanks for the pointer. I should of course have used the 1.99.x version, a stupid mistake. I even spell out that I use the wrong version in my report above.

So, switching to mod_md v1.99.x resolves my issue and apache with mod_md is now renewing our letsencrypt certicates perfectly.
