### ISSUE TITLE
v1.99.10 - httpd crash on /server-status [Windows]

### ISSUE THREAD

**Issue by nono303** [icing/mod_md#122]
Hi @icing,

Testing v1.99.10 and had a crash with /server-status with current stack
```
**** Crash at 2019-05-15 09:57:21
Process id:        5068
Exception code:    EXCEPTION_ACCESS_VIOLATION
Exception address: 0x7FEF27029C3

md_status_print+0x123 0x7FEF27029C3
md_status_hook+0x13E 0x7FEF27027EE
ap_run_status_hook+0x47 0x7FEF2513A27
status_handler+0x168F 0x7FEF25136DF
ap_run_handler+0x35 0x7FEF3081DA5
ap_invoke_handler+0xCE 0x7FEF308289E
ap_process_async_request+0x23A 0x7FEF307C5EA
ap_process_request+0xF 0x7FEF307C67F
h2_task_process_request+0x132 0x7FEF279C302
h2_task_process_conn+0x7D 0x7FEF279C15D
ap_run_process_connection+0x35 0x7FEF30832C5
h2_task_do+0x22D 0x7FEF279D8CD
slot_run+0x4E 0x7FEF279842E
o__realloc_base+0x60 0x7FEF965CD70
BaseThreadInitThunk+0xD 0x7709556D
RtlUserThreadStart+0x1D 0x771F385D
```
does I miss some config ?

Regards

**Comment by icing** [comment]
Hmm, can you make a report with line numbers? That would help. 

Otherwise, I am working in that area anyway and will make a new version today.

**Comment by nono303** [comment]
mod_whatkillus just provide these stack frame information.
Compiling httpd in debug result is the attached core dump.
[AppCrash_httpd.exe_205692e2a45da610ede684d3c022fb8f3abae620_cab_1ecbd781.zip](https://github.com/icing/mod_md/files/3182310/AppCrash_httpd.exe_205692e2a45da610ede684d3c022fb8f3abae620_cab_1ecbd781.zip)

I’m quite rusty for these kind of analyse but i didn’t see something interesting about mod_md line number in stack...

[mod_md-1.99.10_vs16-x64-avx-debug.zip](https://github.com/icing/mod_md/files/3182312/mod_md-1.99.10_vs16-x64-avx-debug.zip)

**Comment by icing** [comment]
Please give v1.99.11 a try.

**Comment by nono303** [comment]
v1.99.11 sounds great!
No more crash on `/server-status` and `Managed Domains` appear at the end
`serial` is present in `md.json`.
Thanks @icing !
