### ISSUE TITLE
Conflict with LogLevel

### ISSUE THREAD

**Issue by jmwebservices** [icing/mod_md#123]
In my server conf, I have `LogLevel warn` but `mod_md` logged the following _notice_ `[md:notice] AH10051: DOMAIN: has been renewed successfully and should be activated at...`.

I am certainly glad that the `notice` was logged but according to the [manual](https://httpd.apache.org/docs/2.4/mod/core.html#loglevel), notices should be ignored when `LogLevel` is set to `warn`.

Am I missing something here?

**Comment by icing** [comment]
Do you have multiple ```LogLevel``` directives in your config? I am not certain how these overwrite each other, but I think module specific ones serve as exemptions from a general one.

For more details, you'd have to ask on the Apache mailing lists.

**Comment by jmwebservices** [comment]
Nope, I double-checked the only instance of `LogLevel` in my server conf is

```
LogLevel warn allowmethods:crit authz_core:crit autoindex:crit
````

If this does turn out to be a bug and, consequently fixed, should I append `md:notice` to `LogLevel`? I **do** want certificate renewal notices to be logged.
 
I will try to submit this to the Apache mailing lists. Thanks!
