### ISSUE TITLE
mod_md does not renewal certificates since 05/2019

### ISSUE THREAD

**Issue by radekcz** [icing/mod_md#129]
I have been using apache httpd (2.4.29) with _md_module_ for more than 1 year without problem, everything was working fine (renewals certs too), but now (since may 2019) I have a problem with renewals certs.

Till now:
`[md:notice] [pid 856:tid 1324] AH10051: testserver.company.com: has been renewed successfully and should be activated at Mon, xx xx 2019 12:15:04 GMT (this requires a server restart latest in 23:00:06 hours)`
`[md:notice] [pid 856:tid 1324] AH10059: The Managed Domain testserver.company.com has been setup and changes will be activated on next (graceful) server restart.`

But now:
`[md:error] [pid 6980:tid 512] (70007)The timeout specified has expired: AH10056: processing testserver.company.com`

5 times in a row after 1 min

... and follow: 

`(70013)Missing parameter for the specified command line option: acme problem urn:acme:error:rateLimited: Error creating new cert :: too many certificates already issued for exact set of domains: testserver.company.com: see https://letsencrypt.org/docs/rate-limits/`

I haven't changed anything in httpd.conf. Could you please give me advice, what is wrong? Thanks a lot!

**Comment by Jan-E** [comment]
My reply here: https://www.apachelounge.com/viewtopic.php?p=38303#38303

I am using mod_md with Apache 2.4.39 with success. The latest scheduled renewal with Apache VC9 x86 (OpenSSL 1.0.2) happened to be on July 3rd. And I just tested the same with Apache 2.4.39 VC15 x64 + OpenSSL 1.1.1: renewal OK as well.

**Comment by radekcz** [comment]
Yes, I can confirm that when I tried to run 2.4.39 version apache with included version of mod_md, renewals are OK. So I have to migrate to new version of apache with newer version mod_md...
Thanks @Jan-E

**Comment by Jan-E** [comment]
OK. Please close this issue.
