### ISSUE TITLE
[solved]  Windows :: server reports that it is not reachable 

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#13]
In the apache error.log I get: the server reports that is is not reachable via http (port 80) or https (port 443). The ACME protocol needs at least one of those so the CA can talk to the server and verify a domain ownership.

It is def reachable on port 80 and port 443.

Every few hours it is trying again, with the same error. 

My config:

Listen 80
Listen 443
LoadModule watchdog_module modules/mod_watchdog.so
LoadModule md_module modules/mod_md.so

ManagedDomain domain.nl www.domain.nl
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf

**Comment by icing** [comment]
I hope v0.5.0 compiles for you. I do not have the time to debug old version. If you can reproduce the fault in v0.5.0, please say so here or close the ticket if it is fixed. thanks.

**Comment by SteffenAL** [comment]
On 0.5.0 same:

mod_md.c(706): AH: initializing post config dry run
mod_md.c(100): AH: server seems not reachable via http: (port 80->80) and reachable via https: (port 443->443) 

**Looks false alarm, further on in the log and it is communicating with letsencrypt.org**:

md_acme_drive.c(680): domainD.com: staging started, state=1, **can_http=1, can_https=1,** challenges='tls-sni-01 http-01' 

In httpd.json now with 0.5.0   "https": true (v0.2.0 was setting it to false)

Closing issue.

**Comment by SteffenAL** [comment]
With a2md version 0.6.0 also now all fine:

>a2md -vvv -a https://acme-staging.api.letsencrypt.org/directory -d D:\servers\apache\md  drive vosadministraties.nl

[D:\servers\apacheS\bin>a2md -vvv -a https://acme-staging.api.letsencrypt.org/directory -d D:\servers\apaches\md  drive vosadministraties.nl
[md_store_fs.c:356 trace2][ok] loading type 1 from D:\servers\apaches\md/domains/vosadministraties.nl/md.json 
[md_store_fs.c:356 trace2][ok] loading type 2 from D:\servers\apaches\md/domains/vosadministraties.nl/cert.pem
[md_store_fs.c:356 trace2][ok] loading type 3 from D:\servers\apaches\md/domains/vosadministraties.nl/pkey.pem
[md_store_fs.c:356 trace2][ok] loading type 4 from D:\servers\apaches\md/domains/vosadministraties.nl/chain.pem
[md_reg.c:214 debug][ok] md{vosadministraties.nl}: is complete
[md_cmd_reg.c:297 info][ok] vosadministraties.nl: up-to-date

**Comment by icing** [comment]
> With a2md version 0.6.0 also now all fine:

What exactly is the issue reported now? Is there still a problem or not?

**Comment by SteffenAL** [comment]
Just to let you know that a2md with 0.6.0 gives no errors anymore.
