### ISSUE TITLE
Release 2.0.9  has 2.1.0 version info

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#134]
The download of 2.0.9 has a version.h with  2.1.0-git. 

And httpd 2.4.41 has 2.0.10.

**Comment by icing** [comment]
I do not see the file `src/md_version.h.in` in the distribution mod_md-2.0.9.tar.gz. Could you check again?

**Comment by SteffenAL** [comment]
I said  version.h (not the .in). Which is in the .zip file.

**Comment by icing** [comment]
I correct myself: I do not see the file src/md_version.h` in the distribution mod_md-2.0.9.tar.gz. Could you check again?

**Comment by SteffenAL** [comment]
In the zip.

**Comment by icing** [comment]
Ah, I usually never look at these since github generates those. But you are right, the zip contains sources from the master branch. I will do a re-release of 2.0.9 with the correct tag in a minute.

**Comment by icing** [comment]
Updated the v2.0.9 comments and released a v2.0.10 from the correct branch. 

Thanks for checking!
