### ISSUE TITLE
OSCP Responses in log with every client

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#136]
In the Docu I read about Stapling:

.....This prevents having client connections waiting. Either response data is there or not. Renewals of the data are continuously happening in the background. They are attempted when less than a third of the response lifetime are left (configurable). **Let's Encrypt responses have a life time of several days, for example.** This gives more than a day to get a new one.

Using the config with no_vhost as I posted on the dev list and running v2.1.1-git.

Now my log are filled with response, is this a intended behavior ?

Steffen

...
...
[md:trace2] [pid 12008:tid 3172] md_ocsp.c(393): md[apachelounge.com]: OCSP, get_status
[md:trace2] [pid 12008:tid 3172] md_ocsp.c(444): md[apachelounge.com]: OCSP, returning 527 bytes of response
[md:trace2] [pid 12008:tid 3196] mod_md_ocsp.c(86): [client 157.55.39.139:16574] get stapling for: apachelounge.com
[md:trace2] [pid 12008:tid 3196] md_ocsp.c(393): md[apachelounge.com]: OCSP, get_status
[md:trace2] [pid 12008:tid 3196] md_ocsp.c(444): md[apachelounge.com]: OCSP, returning 527 bytes of response
[md:trace2] [pid 12008:tid 3188] mod_md_ocsp.c(86): [client 157.55.39.139:18234] get stapling for: apachelounge.com
[md:trace2] [pid 12008:tid 3188] md_ocsp.c(393): md[apachelounge.com]: OCSP, get_status
[md:trace2] [pid 12008:tid 3188] md_ocsp.c(444): md[apachelounge.com]: OCSP, returning 527 bytes of response
[md:trace2] [pid 12008:tid 3212] mod_md_ocsp.c(86): [client 13.66.139.0:36672] get stapling for: apachelounge.com
....
...

**Comment by icing** [comment]
On `LogLevel md:trace2` it is. You have other settings?

**Comment by SteffenAL** [comment]
No.

Looks like this is the logging for the response to the client.  And not what I first thought that is was a retrieve  of a new response from the CA.

So it looks normal.

Now I am running mod_md with Apachelounge in production, it works great so far ! 

Thanks! Stefan for the great module !

ps.
With  install no need to do a manual copy certificate step as I mentioned on the dev list.. There the servername was wrong.

My config (no vhosts, all goes to backend(s))
MDomain apachelounge.com www.apachelounge.com land10web.com .... mta-sts.apachelounge.com
MDBaseServer on
MDPortMap https:443
Listen 443
MDCertificateAgreement accepted
MDRenewMode Always
MDRenewWindow   85d
MDWarnWindow 86

MDStapling on

MDNotifyCmd D:/servers/apacheS/bin/MDNotifyCmd.bat
MDMessageCmd D:/servers/apacheS/bin/MDMessageCmd.bat

<Location "/md_status">
  SetHandler md-status
</Location>

Notify works also great on Windows, get the following mail :

MdNotifyCmd : apachelounge.com
MDMessageCmd : ocsp-renewed apachelounge.com and reneweda pachelounge.com

**Comment by icing** [comment]
OK, so we are - for now - error free in your setup? Great!

**Comment by SteffenAL** [comment]
One thingy with Check@ :

In mod_status the Certificate is 92ad373d685967237ae5d6db5ae81a4c995e6962 with Status good.

And when I click check@ it goes to https://crt.sh/?q=bda52185e0d24711d61e2204db3bfeec45380124adc5530c6706aea2b8f752c9

I get Certificate not found

When I Query https://crt.sh/?q=apachelounge.com

Then I see on top the certificate https://crt.sh/?id=1818994786 today (the only one generated today)

SHA-256(Certificate)	2DFA9D71D66DCA7A0E853E18B90E0D8080E4B650A7F9C99595FA0F3399AFB0CC
SHA-1(Certificate)	0D1B3A10D55A051BCD01FF52562B52961B7A3DEB

With md_status I see :
"serial": "03ADFF3ACA0055A938703978A7C442F7C06A",
"sha256-fingerprint": "bda52185e0d24711d61e2204db3bfeec45380124adc5530c6706aea2b8f752c9",
"activity": "status of certid 92ad373d685967237ae5d6db5ae81a4c995e6962, reading response"

**Comment by icing** [comment]
crt.sh is rather slow and it can take a day or two for a new cert to appear. There are other monitors faster thatn this.

**Comment by SteffenAL** [comment]
Saw  a typos in Readme: 
Directive MDStapleOthers says MDStapling on|off should be MDStaplingOthers on|off

In Directive the following links are not working:
MDCertificateFile
MDCertificateKeyFile
MDCertificateAgreement

There is a bouble # in the href.

Also see that the Readme is not complete inline yet with 2.1.1, like the layout columns Server-Status page.

ps.
Maybe have to wait longer or after a renew : Still no certificate found with Check@ while it is  there at https://crt.sh/?q=apachelounge.com

**Comment by icing** [comment]
I see your certificate at https://crt.sh/?q=2DFA9D71D66DCA7A0E853E18B90E0D8080E4B650A7F9C99595FA0F3399AFB0CC

Which link does apache give you?

**Comment by SteffenAL** [comment]
See 3 posts above.

**Comment by icing** [comment]
It's dangerous to give people like you new toys:

if you look at the list in https://crt.sh/?q=apachelounge.com, the top-most certificate is from 2019-008-28, but it is not the certificate your site is using. 

A certificate is uniquely identified (for any practical purposes at least) by its SHA-256 fingerprint. If you check those, you see that they are different.

**Comment by SteffenAL** [comment]
Why dangerous ?

I am using that top most one  certificate !

The serial at that top most  certificate https://crt.sh/?id=1818994786 is :

        Serial Number:
            03:ad:ff:3a:ca:00:55:a9:38:70:39:78:a7:c4:42:f7:c0:6a

And https://www.apachelounge.com/.httpd/certificate-status

Gives also   "serial": "03ADFF3ACA0055A938703978A7C442F7C06A",

So is is the same.

The serial number is assigned by LE to each certificate. It it is unique for each certificate (together with Issuers name) issued.

**Comment by SteffenAL** [comment]
Now "suddenly" check@ is working !

At https://crt.sh/?q=apachelounge.com   **at the top is now added** 1826825385 with the logged at date of 2019-08-30 and the same valid date. And that is now the good one.

So, we have  two entries with the **same certificate Serial Number** with different SHA-256 and SHA1. For more then two days the we had a wrong one for Check@

All ok now, my observations were not Dangerous  :)

Waiting for Stapling Renew and Certificate Renew

Topic can be closed

Cheers

Steffen

ps.
Reminder typos in Readme.md:
Directive MDStapleOthers says MDStapling on|off should be MDStaplingOthers on|off

In Directives the following links are not working:
MDCertificateFile
MDCertificateKeyFile
MDCertificateAgreement

There is a double # in the href.

Also see that the Readme is not complete inline yet with 2.1.1, like the layout columns Server-Status page.
