### ISSUE TITLE
README.md file with dead link for "trouble shooting"

### ISSUE THREAD

**Issue by jschleus** [icing/mod_md#137]
The main README.md file contains the markdown string
```
Assume that this worked (and if not, check [trouble shooting](Trouble) to find out ...
```
For e.g. on GitHub the resulting HTML page contains an according link to https://github.com/icing/mod_md/blob/master/Trouble but such a  file or directory doesn't exist.

**Comment by icing** [comment]
Should be fixed now. Thanks.
