### ISSUE TITLE
mod_md fails after updating to 2.0.8 from bundled mod_md in 2.4.39

### ISSUE THREAD

**Issue by notroj** [icing/mod_md#138]
Not sure what's going on here.  I have a test server for the Fedora packages working and with certs obtained using 2.4.39's bundled modules/md.  After updating to separately packaged mod_md 2.0.8, it no longer starts up.

Last log entries at trace7 are:

```
[Thu Aug 29 14:53:58.717701 2019] [md:trace3] [pid 29380:tid 140085954091264] md_store_fs.c(566): storing in /var/lib/httpd/md/domains/acme.mytestsslserver.site/md.json
[Thu Aug 29 14:53:58.718080 2019] [md:trace3] [pid 29380:tid 140085954091264] mod_md.c(148): store event=0 on file /var/lib/httpd/md/domains/acme.mytestsslserver.site/md.json (group 3)
[Thu Aug 29 14:53:58.718151 2019] [md:debug] [pid 29380:tid 140085954091264] md_reg.c(223): md{acme.mytestsslserver.site}: is complete
[Thu Aug 29 14:53:58.718201 2019] [md:debug] [pid 29380:tid 140085954091264] md_reg.c(884): md acme.mytestsslserver.site updated
[Thu Aug 29 14:53:58.718275 2019] [md:trace2] [pid 29380:tid 140085954091264] md_reg.c(1092): (2)No such file or directory: acme.mytestsslserver.site: nothing staged
[Thu Aug 29 14:53:58.718325 2019] [md:debug] [pid 29380:tid 140085954091264] md_reg.c(1123): (2)No such file or directory: acme.mytestsslserver.site: load done
[Thu Aug 29 14:53:58.720102 2019] [ssl:emerg] [pid 29380:tid 140085954091264] AH02311: Fatal error initialising mod_ssl, exiting. See /etc/httpd/logs/ssl_error_log for more information
```

mod_ssl is complaining because no certs are configured for the (single) SSL vhost.  Running a2md:

```
# a2md -v -d /var/lib/httpd/md/ list
[md_reg.c:223 debug][ok] md{acme.mytestsslserver.site}: is complete
md: acme.mytestsslserver.site [acme.mytestsslserver.site]
```

And certs appear present and correct:

```
# ls -l /var/lib/httpd/md/domains/acme.mytestsslserver.site/
total 12
-rw-------. 1 root root  575 Aug 29 14:53 md.json
-rw-------. 1 root root 1704 Aug 29 14:51 privkey.pem
-rw-------. 1 root root 3586 Aug 29 14:51 pubcert.pem
```

**Comment by notroj** [comment]
I did temporarily have "Protocols h2 http/1.1 acme-tls/1" configured but removing it makes no difference

```
# cat /var/lib/httpd/md/domains/acme.mytestsslserver.site/md.json
{
  "name": "acme.mytestsslserver.site",
  "domains": [
    "acme.mytestsslserver.site"
  ],
  "contacts": [
    "mailto:jorton@redhat.com"
  ],
  "transitive": 1,
  "ca": {
    "account": "ACME-.letsencrypt.org-0000",
    "proto": "ACME",
    "url": "https://acme-v02.api.letsencrypt.org/directory",
    "agreement": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
  },
  "state": 2,
  "renew-mode": 1,
  "renew-window": "33%",
  "warn-window": "10%",
  "must-staple": false
}
```

**Comment by icing** [comment]
I think it did not see the new ssl hooks during compilation and the mod_ssl is using them or vice versa. Could that be?

**Comment by notroj** [comment]
Ah yes of course, thanks as always.  It was built against 2.4.39, I will rebuild.  Should we have a configure/runtime check for this?

**Comment by icing** [comment]
Hmm, I am open to suggestions. Is there a macro to check if an optional hook is there or not?

In the 2.1 line, I disabled the old behaviour and give an #error at compile time if it is missing.

**Comment by notroj** [comment]
Actually can't get my head around it, we need a runtime check as well?  If it fails at compile time in 2.1 that sounds enough to me.  Anyway the rebuild works, https://acme.mytestsslserver.site is back online, all good ;)  

I owe you another one @icing

**Comment by icing** [comment]
> Am 30.08.2019 um 09:28 schrieb Joe Orton <notifications@github.com>:
> 
> Actually can't get my head around it, we need a runtime check as well? If it fails at compile time in 2.1 that sounds enough to me.  Anyway the rebuild works, https://acme.mytestsslserver.site is back online, all good ;)
> 
> I owe you another one @icing

I exchange 10 beers for a bottle of wine, if that helps. ;)
