### ISSUE TITLE
Curl certificate error on windows

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#14]
In the readme is stressed that you need a curl with openssl.

On windows then we get:

Peer certificate cannot be authenticated with given CA certificates.

Building with Winssl it works !

**Comment by Jan-E** [comment]
@SteffenAL Cound you try if adding something like
`curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);`
is a workaround?

Best place could be
https://github.com/icing/mod_md/blob/master/src/md_curl.c#L210

Or maybe a few lines later.

**Comment by SteffenAL** [comment]
I think that does not work, needs CA certs.

Gregg and I had back the same discussion with mod_security. Therefore we ship mod_security with WinSSL. 

It is  curl's really lousy certificate store.

This is the message: curl: (60) SSL certificate problem: unable to get local issuer certificate

Curl performs SSL certificate verification by default, using a "bundle"  of Certificate Authority (CA) public keys (CA certs). If the default bundle file isn't adequate, you can specify an alternate file using the --cacert option.

**Comment by Jan-E** [comment]
It does not need CA certs if you set CURLOPT_SSL_VERIFYPEER to 0. It is more or less the same as running curl.exe with '-k' or '--insecure'.

**Comment by SteffenAL** [comment]
I think we do not want --insecure.

With WinSSL no  the problem, and no code change specific for Windows in mod_md necessary. When it is sofar we ship it with WinSSL, like mod_security.

**Comment by Jan-E** [comment]
You could mitigate the insecurity by setting CURLOPT_SSL_VERIFYHOST to 1.
`curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 1L);`
See https://curl.haxx.se/mail/lib-2015-07/0036.html

Or just close this issue, because it is not an issue.

**Comment by SteffenAL** [comment]
No. not closing yet, first the mod_md Readme should be updated.

It is a issue.  mod_md is not working with curl/openssl.  I disagree with you to use something like -k, the call must be secure.

**Comment by Jan-E** [comment]
Then change the Issue Title to something like:

Update doc: mod_md on Windows should use Winssl

**Comment by icing** [comment]
I have no recommendation for Windows, guys. You are the testers and find out how it best works there. And then you write some documentation maybe to help other people? Thanks!

**Comment by qgustavor** [comment]
I'm having the same (or a similar) issue. Here is the Apache logs:

```
[Thu Jan 16 11:13:21.718100 2020] [md:debug] [pid 3060:tid 2524] md_curl.c(385): (20014)Internal error (specific information not available): request failed(60): SSL peer certificate or SSH remote key was not OK
[Thu Jan 16 11:13:21.719099 2020] [md:warn] [pid 3060:tid 2524] (20014)Internal error (specific information not available): md[redacted.example.com] while[Contacting ACME server for redacted.example.com at https://acme-v02.api.letsencrypt.org/directory] detail[Unsuccessful in contacting ACME server at <https://acme-v02.api.letsencrypt.org/directory>. If this problem persists, please check your network connectivity from your Apache server to the ACME server. Also, older servers might have trouble verifying the certificates of the ACME server. You can check if you are able to contact it manually via the curl command. Sometimes, the ACME server might be down for maintenance, so failing to contact it is not an immediate problem. Apache will continue retrying this.]
```

```
C:\xampp\apache\bin>curl https://acme-v02.api.letsencrypt.org/directory
{
  "Pn_1pMezyco": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  rest of the response omitted
}
```

I'm using Apache 2.4.41 on Windows 10 and I've tested all latest [nono303 mod_md builds](https://github.com/nono303/mod_md). I checked Windows Certificate Store and ISRG Root X1 and DST Root CA X3 certificates are installed. I also tried placing `curl-ca-bundle.crt` and `cacert.pem` in `C:\Windows\System32\` and Apache root, `bin` and `module` paths. I tried using the Windows 10 built-in curl and ["the curl project" curl](https://curl.haxx.se/windows/).

**Comment by SteffenAL** [comment]
Looks like you are using xampp. They use the ApacheLounge binaries.

But their curl is build against OpenSSL, and that works not with mod_md.

Try to copy the libcurl.dll (WinSSL version)  to your bin from https://www.apachelounge.com/download/  VC15 or VC16 depending the version of xampp you use.

**Comment by qgustavor** [comment]
That worked, thanks!

**Comment by nono303** [comment]
I'll add WinSSL version of libcurl.dll in my [repository](https://github.com/nono303/mod_md) to avoid this issue...
