### ISSUE TITLE
Crash at begin renew and just after renew

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#141]
Running 2.1.1 -git, log attached including job.json. Unfortunate Windows gives now no trace/dump files.

At the start of the Renew a Crash:
 ` AH00428: Parent: child process 8896 exited with status 3221225477 -- Restarting.`

And it is Renewing the Certificate, and when it is renewed again a Crash : 
```
md_result.c(254): md[apachelounge.com] detail[The certificate for the managed domain has been renewed successfully and can be used from Tue, 03 Sep 2019 08:36:17 GMT on. A graceful server restart in 22 hours 59 minutes 58 seconds is recommended.]
md_reg.c(1078): apachelounge.com: staging done
mod_md_drive.c(161): apachelounge.com: saving job props
mod_md_drive.c(222): AH10107: next run in 11 hours 59 minutes 27 seconds
AH00428: Parent: child process 12536 exited with status 3221225477 -- Restarting
```
**The End Result after the Second crash is that all is running fine with a new Certificate !**

I miss the mail messages from  MDNotifyCmd MDMessageCmd,  my MDWarnWindow is set one day before renew, and yes it mailed that it was expiring. So  MDMessageCmd is working.

A feeling(?) is that it has some to do with the Notify

Early today  I had also a OCSP renew and that went fine, including mail from MDMessageCmd

[serrorCrache.log](https://github.com/icing/mod_md/files/3565781/serrorCrache.log)

**Comment by SteffenAL** [comment]
Running now 2.1.2-git

Removed the Directives MDNotifyCmd,  MDMessageCmd and MDWarnWindow.

Set MDRenewWindow   89d , so to morrow again a Renew.

**Comment by icing** [comment]
Yes, the notify is missing from the log, but the finish of the renewal is there. This points to a crash sometime between or directly connected to invoking your notify/mesage commands. 

Which one did you use? Both?

**Comment by SteffenAL** [comment]
I had both:

MDNotifyCmd D:/servers/apacheS/bin/MDNotifyCmd.bat
MDMessageCmd D:/servers/apacheS/bin/MDMessageCmd.bat

MDWarnWindow was set **one day before renew**, and yes and the executable  mailed that it was expiring. So MDMessageCmd  executable is working as you can see in job.json:
```
        "when": "Sun, 01 Sep 2019 11:41:51 GMT",
        "type": "message-expiring"
```
And MDNotifyCmd is the same executable

**Comment by SteffenAL** [comment]
Again two crashes when removed  MDNotifyCmd, MDMessageCmd.

I followed:  before start-cert renew  and then at before start of ocsp-renew.

[ErrorLogRenew.txt](https://github.com/icing/mod_md/files/3573712/ErrorLogRenew.txt)
[job-domain.json.txt](https://github.com/icing/mod_md/files/3573713/job-domain.json.txt)
[job-oscp.json.jso.txt](https://github.com/icing/mod_md/files/3573714/job-oscp.json.jso.txt)

All runs fine with the new cert:
```
  "valid": {
    "until": "Tue, 03 Dec 2019 07:39:14 GMT",
    "from": "Wed, 04 Sep 2019 07:39:14 GMT"
  },
  "serial": "03BCAC1032DDA42B0642842FC4F582FB282A",
  "sha256-fingerprint": "9c5a761c7250c41f6fe4588bb256e28c5efe25086ce49ab14fd3f539ff08874f"
```

**Comment by icing** [comment]
I have trouble understanding your description of what happened. I try to summarize:

1. You had not configured MDNotifyCmd or MDMessageCmd.
2. The renewal went through, but crashed before the notification part was logged (it always logged, if you configure commands or not)
3. After the restart, the new certificate was activated and worked.
4. The OCSP stapling response was retrieved successfully (see it in the log)
5. In the OCSP log, I also see an entry ` "type": "message-ocsp-renewed"` which means it was called and logged here.

What I do not understand:

```
I followed: before start-cert renew and then at before start of ocsp-renew.
```

You mean there was 1 crash at the start of cert renew  and 1 crash at the start of ocsp-renew?

What I see in the log is 1 crash *at the end* of cert renew and no other. Maybe I misunderstood?

**Comment by SteffenAL** [comment]
1. yes
2. crashed  during starting the renew
3. No, after crash, Apache does a start auto, and all work
4. yes
5. ?


_You mean there was 1 crash at the start of cert renew and 1 crash at the start of ocsp-renew?_
Yes, yes:

_What I see in the log is 1 crash at the end of cert renew and no other._
See top at the log the first at  10:38:44 and at 10:43:42 .

Btw.
Lets stop this conversation, GIT-issues is not meant to debug crashes.

**Comment by icing** [comment]
Ok, the restart at the first line of the log. Thanks for the times.

**Comment by icing** [comment]
This:

```
[Wed Sep 04 10:39:17.332496 2019] [md:debug] [pid 11660:tid 2264] mod_md_drive.c(222): AH10107: next run in 11 hours 59 minutes 27 seconds

<nothing>

[Wed Sep 04 10:43:42.883725 2019] [mpm_winnt:notice] [pid 3032:tid 684] AH00428: Parent: child process 11660 exited with status 3221225477 -- Restarting.
```
Means that the crash happened 4.5 minutes *after* `mod_md` had renewed your certificate. Could it be that I introduced a bug in the `server-status` page and you had reloaded it at that time?

**Comment by SteffenAL** [comment]
Yep, to follow the proces, during the time frame of the renew I was reloading **server-status** and **.httpd/certificate-status**  

From some I made a screen shot mod_status

            **Activity**
10:33 Renew in ~3 minutes
...
10:36 Renew  ~4 seconds ago
....
10:38 Renew  ~01 minutes ago
....
**10:38 First Crash mod_md**
    Apache starting and certificate renewing
...
10:39  The certificate for the managed domain has been renewed.....
....
**10:43 Second Crash mod_md**
    Apache starting and ocsp renewing
....
10:44  Renew in ~1  days

btw.  
The rest of Today during "normal" running I looked quite a few times mod_status, no crashes.

**Comment by icing** [comment]
I added some more logging when collecting the status information in v.2.1.3. If you could give this a try sometime, maybe I can get a better idea where it is crashing.

I also fixed a but in json handling, but I *think* this should not affect server-status.

**Comment by icing** [comment]
Any news on this?

**Comment by SteffenAL** [comment]
Wait for the renew Tomorrow evening, and then I am not going to use/load mod_status. 

Today there was an ocsp-renew, all fine, including MDMessageCmd.

**Comment by SteffenAL** [comment]
Crashed again two times.  Was not at home, so no one  looking/loading  mod_status.

[serror-renew.log](https://github.com/icing/mod_md/files/3597306/serror-renew.log)

Renew time was 19:06:30

crashes:
 
19:09:15 [md:trace1] mod_md_status.c(481): [client 127.0.0.1:59] server-status for managed domains, start
**Crash1** 19:09:19 after the  trace1 ...server-status for managed domains, start
...
...
19:14:16 [md:trace1] mod_md_status.c(481): [client 127.0.0.1:59] server-status for managed domains, start
**Crash2** 19:14:19  after the trace1 ... server-status for managed domains, start

All runs fine with the new certificate.

**Comment by icing** [comment]
Thanks for the log. I think you have a browser tab open somewhere that periodically refreshes the status page. At least your log says that the crash happened during the creation of such a page.

But whatever the cause, the crash is in mod_md's contribution to server-status. I'll read the code again and look for my mistakes.

**Comment by SteffenAL** [comment]
No crashes with v2.1.5.

All went fine, only the script MDNotifyCmd is **not** executed.

The MDMessageCmd  is excuted for MDWarnWindow and ocp-renew.

[Renew.log](https://github.com/icing/mod_md/files/3613616/Renew.log)

**Comment by icing** [comment]
Thanks for testing and verification.
