### ISSUE TITLE
Version 2..1.3 :: no info in mod_ststus and md_status

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#142]
**mod_status** gives only the headings, no info.

**md_status** gives only:
```
{
  "version": "2.1.3-git"
}
```

PS.
Build Warning since 2.1.2: mod_md_ocsp.c(177): warning C4700:  uninitialized local variable 'keep' used

**Comment by icing** [comment]
This seems to indicate that mod_md no longer found your MDomain configuration? I assume that server-status also lists no Managed Domains? Can you provide a log with `LogLevel md:trace2` from a server restart and access to md-status page, please?

**Comment by icing** [comment]
Wait, can now reproduce.

**Comment by SteffenAL** [comment]
mod_status only the headings, and no info under the headings.

I have only log with trace1

[Trace1 2.1.3.txt](https://github.com/icing/mod_md/files/3583061/Trace1.2.1.3.txt)

**Comment by icing** [comment]
Sorry for the bug in v2.1.3, please check the new v2.1.4.

**Comment by SteffenAL** [comment]
Fine again.

With trace2 my log are filling quick with :
```
[Fri Sep 06 11:24:31.219602 2019] [md:trace2] [pid 7820:tid 3224] md_ocsp.c(444): md[apachelounge.com]: OCSP, returning 527 bytes of response
[Fri Sep 06 11:24:34.321949 2019] [md:trace2] [pid 7820:tid 3208] mod_md_ocsp.c(90): [client 66.249.90.156:37081] get stapling for: apachelounge.com
```
So I go back to trace1

**Comment by icing** [comment]
Sure.

I do not know how long I will be available here today. Will definitely be back on Monday.
