### ISSUE TITLE
Apache crash on cert creation with bad configuration

### ISSUE THREAD

**Issue by FV-Valraiso** [icing/mod_md#143]
Hi Stefan,

We created a Vhost, with a domain that point on the VM, and set on the ServerName.
On the ServerAlias we put 2 domains that are pointing on another VM.
On restart of Apache and execution of MD, we have a crash that stop the restart and all other sites hosted on the VM are not available.
We fix the problem by commenting the ServerAlias line but it would be nice to fix the crash.
Seems not the same problem than #141.

Sep  7 12:32:41 vmName kernel: [9767533.537087] apache2[28996]: segfault at 0 ip 00007f774cbe786d sp 00007fff3a54a610 error 4 in **mod_md.so.0.0.0**[7f774cbcf000+31000]
Sep  7 12:32:41 vmName apachectl[28984]: Segmentation fault (core dumped)

Regards

**Comment by icing** [comment]
Could you give a sample configuration on what you have set up and does not work? What do you mean by "VM"?

Also: which version are you using?

**Comment by FV-Valraiso** [comment]
Apache Server version: Apache/2.4.29 (Ubuntu)
VM --> Virtual Machine, our servers

Sample of configuration :
MDomain my_dev.domain.net
<VirtualHost *:80>
  ServerName my_dev.domain.net
  ServerAlias my_prod.domain.net www.my_prod.domain.net

  RewriteEngine On
  RewriteCond %{HTTP_HOST} !^www\.
  RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</VirtualHost>
<VirtualHost *:443>
  ServerName my_dev.domain.net
  ServerAlias my_prod.domain.net www.my_prod.domain.net

  Protocols h2 http/1.1
  SSLEngine On

  ErrorLog /var/log/apache2/domain.net.error.log
  TransferLog /var/log/apache2/domain.net.access.log

  <Directory /PATH_TO_FILES>
    Require all granted
  </Directory>

  DocumentRoot /PATH_TO_FILES
  Alias /_next /PATH_TO_FILES/_next
  Alias /static /PATH_TO_FILES/static
</VirtualHost>

ServerName my_dev.domain.net --> IP of current server
ServerAlias my_prod.domain.net www.my_prod.domain.net --> IP of other server

**If ServerAlias is not commented, MD crash**

Is there a way to send you the real configuration in private ?

**Comment by icing** [comment]
Sure, use `stefan.eissing` at `greenbytes.de`.

**Comment by icing** [comment]
Do you know the mod_md version you are running? Logged on level `md:info` at startup.

**Comment by FV-Valraiso** [comment]
We are on v1.1.0

**Comment by icing** [comment]
I see. The latest version in that release line is [v1.1.19](https://github.com/icing/mod_md/releases/tag/v1.1.19) and there have been various fixes. For example, there was a memory issue when collecting names from `ServerAlias`. Which could be the issue you are looking at.

I'd advise to build the v1.1.19 and try that or open a bug report at ubuntu so that they integrate a newer version/relevant fixes. If your problems persist in v1.1.19 I will look at those and work on a fix.

Sounds good?

**Comment by FV-Valraiso** [comment]
I'll test to update and make a test in order to validate that it works fine.
I'll give you a feedback asap

**Comment by icing** [comment]
Any news on this? Otherwise I'll close this one.

**Comment by FV-Valraiso** [comment]
Sorry Stefan,

I though I told you about it.
My boss don't want to change the Apache version for a rebuild one on the production server.
