### ISSUE TITLE
Loop when after renew no restart within a  day

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#145]
On Sat Sep 21 02:51:26 the certificate was renewed and in the log: 

` md_result.c(254): md[apachelounge.com] detail[The certificate for the managed domain has been renewed successfully and can be used from Sat, 21 Sep 2019 23:51:24 GMT on. A graceful server restart in 22 hours 59 minutes 58 seconds is recommended.]`

Did not do a  restart.

After a few hours did a check with mod_status it gives:

`The certificate for the managed domain has been renewed successfully and can be used from Sat, 21 Sep 2019 23:51:24 GMT on.  A graceful server restart in 22 hours 59 minutes 58 seconds is recommended. **Next in ~6 hours** `

Did not do a restart.

And at the **~ 6 hours** mod_md  starts looping, with each time the notice : 

`md_result.c(254): md[apachelounge.com] detail[The certificate for the managed domain has been renewed successfully and can be used. A graceful server restart now is recommended.]`

and due to the MDNotifyCmd script which is sending a message, my mailbox was flooded with a few thousand ! messages. Also  the memory usage of Apache was going sky high.

After restart all fine.

[serrorRenewAfter-a-day.log](https://github.com/icing/mod_md/files/3639497/serrorRenewAfter-a-day.log)

Config:

MDomain apachelounge.com www.apachelounge.com land10.nl .....................
MDBaseServer on
MDCertificateAgreement accepted
MDRenewMode Always
MDRenewWindow   84d
MDWarnWindow 85d
MDStapling on
MDNotifyCmd bin/MDNotifyCmd.bat
MDMessageCmd bin/MDMessageCmd.bat

**Comment by icing** [comment]
Nice catch. Working on a fix.

**Comment by icing** [comment]
Please try v2.1.6.

**Comment by SteffenAL** [comment]
Next renew is on next Thursday.

Still the warning  : 
`mod_md_ocsp.c(177): warning C4700:  uninitialized local variable 'keep' used`

Reminder the APLOGNO warnings : 
```
md\mod_md.c(831,52): warning C4003:  not enough arguments for function-like macro invocation 'APLOGNO'
md\mod_md_ocsp.c(136,63): warning C4003:  not enough arguments for function-like macro invocation 'APLOGNO'
md\mod_md_ocsp.c(142,63): warning C4003:  not enough arguments for function-like macro invocation 'APLOGNO'
md\mod_md_ocsp.c(156,67): warning C4003:  not enough arguments for function-like macro invocation 'APLOGNO'
mod_md_ocsp.c(164,63): warning C4003:  not enough arguments for function-like macro invocation 'APLOGNO'
mod_md_ocsp.c(195,52): warning C4003:  not enough arguments for function-like macro invocation 'APLOGNO'
md\mod_md_ocsp.c(239,53): warning C4003:  not enough arguments for function-like macro invocation 'APLOGNO'
md\mod_md_ocsp.c(244,67): warning C4003:  not enough arguments for function-like macro invocation 'APLOGNO'
mod_md_status.c(90,53): warning C4003:  not enough arguments for function-like macro invocation 'APLOGNO'
```

**Comment by SteffenAL** [comment]
Running v2.1.7

While waiting on the Renew I notified some other strange,  : see  #146

**Comment by SteffenAL** [comment]
Renewed at 12:58:

The certificate for the managed domain has been renewed successfully and can be used from Sat, 28 Sep 2019 09:58:23 GMT on.Next in ~21 hours

So now wait to see if it loops again what  after ~21 hours

**Comment by icing** [comment]
All well?

**Comment by SteffenAL** [comment]
No loop seen anymore
