### ISSUE TITLE
MDMessageCmd script exit code 1

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#146]
While waiting for the Renew from #145

There was an error with the script of MDMessageCMD.  In the script I send a mail. 

When MDWarnWindow 85 arrived, the Log:

```
[Thu Sep 26 12:42:23.960479 2019] [md:trace1] [pid 5948:tid 2976] mod_md_status.c(618): [client 127.0.0.1:65344] server-status for ocsp stapling, end
[md:debug] [pid 5948:tid 2268] mod_md_drive.c(203): AH10055: md watchdog run, auto drive 1 mds
[md:debug] [pid 5948:tid 2268] mod_md_drive.c(115): AH10052: md(apachelounge.com): state=2, driving
[md:debug] [pid 5948:tid 2268] mod_md_drive.c(119): AH10053: md(apachelounge.com): no need to renew
[md:trace1] [pid 5948:tid 2268] mod_md_drive.c(74): md(apachelounge.com): check expiration
[md:info] [pid 5948:tid 2268] cmd(D:/servers/apacheS/bin/MDMessageCmd.bat) stderr: Winsock error[10060]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\r\r\n
[md:info] [pid 5948:tid 2268] cmd(D:/servers/apacheS/bin/MDMessageCmd.bat) stderr: \r\n
[md:info] [pid 5948:tid 2268] cmd(D:/servers/apacheS/bin/MDMessageCmd.bat) stderr: Error: Connection is closed unexpectedly\r\n
[md:info] [pid 5948:tid 2268] cmd(D:/servers/apacheS/bin/MDMessageCmd.bat) stderr: Error: Expected smtp code 250, got -1\r\n
[md:info] [pid 5948:tid 2268] cmd(D:/servers/apacheS/bin/MDMessageCmd.bat) stderr: \r\n
[md:error] [pid 5948:tid 2268] (20014)Internal error (specific information not available): md[apachelounge.com] problem[urn:org:apache:httpd:log:AH10109:] detail[MDMessageCmd D:/servers/apacheS/bin/MDMessageCmd.bat failed with exit code 1.]
[md:trace1] [pid 5948:tid 2268] mod_md_drive.c(164): apachelounge.com: saving job props
[md:debug] [pid 5948:tid 2268] mod_md_drive.c(225): AH10107: next run in 11 hours 59 minutes 53 seconds
```
Strange it is that **the mail is send** from the script.

**mod_status Activity :**   Renew in ~13 hours (Thu, 26 Sep 2019 23:51:24 GMT)

After the 11 hours it is checking again and receive  not a error in the log:
```

[md:debug] [pid 5948:tid 2268] mod_md_drive.c(203): AH10055: md watchdog run, auto drive 1 mds
[md:debug] [pid 5948:tid 2268] mod_md_drive.c(115): AH10052: md(apachelounge.com): state=2, driving
[md:debug] [pid 5948:tid 2268] mod_md_drive.c(119): AH10053: md(apachelounge.com): no need to renew
[md:trace1] [pid 5948:tid 2268] mod_md_drive.c(74): md(apachelounge.com): check expiration
[md:trace1] [pid 5948:tid 2268] mod_md_drive.c(164): apachelounge.com: saving job props
[md:debug] [pid 5948:tid 2268] mod_md_drive.c(225): AH10107: next run in 11 hours 59 minutes 57 seconds
```
**Mail is send** from the script.

**Now  mod_status  Activity** :   Error[Internal error (specific information not available)]: urn:org:apache:httpd:log:AH10109:MDMessageCmd D:/servers/apacheS/bin/MDMessageCmd.bat failed with exit code 1.

That is strange because the script was now executed fine, you can see it in the job.json:
```

{
  "name": "apachelounge.com",
  "finished": false,
  "errors": 0,
  "last": {
    "status": 20014,
    "status-description": "Internal error (specific information not available)",
    "problem": "urn:org:apache:httpd:log:AH10109:",
    "detail": "MDMessageCmd D:/servers/apacheS/bin/MDMessageCmd.bat failed with exit code 1."
  },
  "log": {
    "entries": [
      {
        "when": "Thu, 26 Sep 2019 22:52:26 GMT",
        "type": "message-expiring"
      },
      {
        "when": "Thu, 26 Sep 2019 10:47:03 GMT",
        "type": "message-error",
        "status": "expiring",
        "detail": "MDMessageCmd D:/servers/apacheS/bin/MDMessageCmd.bat failed with exit code 1."
      }
    ]
  }
}
```

**Comment by SteffenAL** [comment]
md_status says:
```
      "renew-at": "Thu, 26 Sep 2019 23:51:24 GMT",
      "watched": true,
      "renew": true,
      "renewal": {
        "name": "apachelounge.com",
        "finished": false,
        "errors": 0,
        "last": {
          "status": 20014,
          "status-description": "Internal error (specific information not available)",
          "problem": "urn:org:apache:httpd:log:AH10109:",
```

Renew at Thu, 26 Sep 2019 23:51:24 GMT, so it should have renewed by now, I keep waiting.

**Comment by icing** [comment]
It sounds as if the error in warning you about the expiring certificate is stalling the renewal. That should be changed.

If the warn message now gets sent, does the renewal start?

**Comment by SteffenAL** [comment]
[Fri Sep 27 00:52:26.285442 2019] [md:debug] [pid 5948:tid 2268] mod_md_drive.c(225): AH10107: next run in 11 hours 59 minutes 57 seconds

I wait till 11:52 today, that is after latest  next run in 11 hours 59 minutes 53 second.

But I was a renew expecting at 00:52.

Complete log see bottom log

[serror-Start2.1.7.log](https://github.com/icing/mod_md/files/3661963/serror-Start2.1.7.log)

**Comment by icing** [comment]
Thanks. In the log it says:

```
[Fri Sep 27 00:52:23.631399 2019] [md:debug] [pid 5948:tid 2268] mod_md_drive.c(119): AH10053: md(apachelounge.com): no need to renew
```

so,  mod_md seems to think all is well? `apachelounge.com` certificate is from 21th September and valid until 20th December. What are you settings for `MDRenewWindow` and `MDWarnWindow`?

**Comment by icing** [comment]
And, while we are at it, what does server-status page show you?

**Comment by SteffenAL** [comment]
MDRenewWindow   84d
MDWarnWindow 85d

Now server-status     Activity : Error[Internal error (specific information not available)]: urn:org:apache:httpd:log:AH10109:MDMessageCmd D:/servers/apacheS/bin/MDMessageCmd.bat failed with exit code 1.

**Comment by icing** [comment]
Ok, the expiration warning triggered yesterday at
`[Thu Sep 26 12:46:57.576554 2019]` and the renewal should start sometime today or early tomorrow. There is a bit of fuzziness involved.

That the error is reported is good. It does not seem to prevent renewal (and should not) - so let's see what the day brings.

**Comment by SteffenAL** [comment]
I think server-status should **not show** the error, because the last mdmessagecmd was good, it is showing now the first script error.

**Comment by SteffenAL** [comment]
It renewed at 12:58

server-status Activity now : 
The certificate for the managed domain has been renewed successfully and can be used from Sat, 28 Sep 2019 09:58:23 GMT on.Next in ~21 hours

Looks good now.

I continue now at #145 for waiting if it loops after a day.
