### ISSUE TITLE
server-status Activity blank  ?

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#147]
All fine here till now with mod_md, only some little server status Activity:

Wed Oct 02 11:58 server-status Activity : **Renew in ~9 seconds**

Little confusing,  looks like it is calculated from the  Validity (valid to/not after) of the current certificate. But in real the renew is started when there is the next run. So the renew can happen hours later. Maybe better an message that explains more. 

After the **~9 seconds** the server-status **Activity  is blank**, we do not see what the status is.  When I recall, formerly the activity was : Renew ~01 minutes ago.  Instead of blank maybe message like : Renew ~nn ttttt ago, next run ??? renewing 

When the time for the next run is reached, it is renewed and the Activity is filled again":

Wed Oct 02 15:57 server-status Activity : The certificate for the managed domain has been renewed successfully and can be used from Thu, 03 Oct 2019 12:56:02 GMT on.Next in ~22 hours.

Also this message is not easy understand .... **and can be used from**... But it can be used already by restarting Apache, at least here.

**Comment by icing** [comment]
Please give v2.1.9 a try.

**Comment by SteffenAL** [comment]
Activity not blank anymore. Says now Ongoing...  

Question is now Ongoing what ? 

But.. the renew now errors, open an new issue.
