### ISSUE TITLE
Not possible to use when you have already a certifcate.

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#15]
Running a2md 0.2.0.
Complaining server not reachable.  With this trick I could run command line a2md:  edited in md/httpd.json http and https to true.

Lot is going on, but no certificate.

In the output I see the error:  ... Received 2 certificate(s)....

Does this mean that I cannot have one with mod_md/a2md if I have already one with an other tool ?

**Comment by icing** [comment]
You can use mod_md in parallel with other ACME tools, just not on the same list of domain names.

So, you may manager mydomainA.com via certbot and mydomainB.com via mod_md, but not mixed.

Does that answer your question?

**Comment by SteffenAL** [comment]
With 0.5.0 same: 

Server is running with certificates mydomainA.com  mydomainB.com  mydomainC.com ...

On this server, tried to get a certificate for a new mydomainD.com which not included in the existing certificate on the server, mydomainD.com has  no certificate.

In the log:

Received 2 certificate(s), first certificate had names  mydomainA.com   mydomainB.com  domainC.com ...

Config:
MDDriveMode always
ManagedDomain mydomainD.com www.mydomainD.com
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf

Loos like what I want is not supported with my setup, closing issue.
