### ISSUE TITLE
Renew Error v2.1.9 :: challenge-mismatch

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#150]
server-status Activity : Renew  in ~8 minutes 
After that ~8 minutes the server-status Activity : Ongoing...

When the time for the next run is reached, it is starting  renewing:

Gives errors:
```
[md:debug] [pid 5516:tid 2264] md_acme_authz.c(215): ACME server authz: challenge 'pending' for apachelounge.com at https://acme-v02.api.letsencrypt.org/acme/authz-v3/767248432. Exact response was: {"identifier":{"type":"dns","value":"apachelounge.com"},"status":"pending","expires":"2019-10-21T00:08:59Z","challenges":[{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/767248432/UCXiaw","token":"a5IoE8vdYqwm0_nDPDBoRzf-yQ98GRTeWTPUKp6z80w"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/767248432/CESIGA","token":"a5IoE8vdYqwm0_nDPDBoRzf-yQ98GRTeWTPUKp6z80w"},{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/767248432/bTtkDA","token":"a5IoE8vdYqwm0_nDPDBoRzf-yQ98GRTeWTPUKp6z80w"}]}
[md:debug] [pid 5516:tid 2264] md_acme_authz.c(355): (70023)This function has not been implemented on this platform: apachelounge.com: protocol 'acme-tls/1' not enabled for this domain.
[md:info] [pid 5516:tid 2264] (70023)This function has not been implemented on this platform: md[apachelounge.com] while[Setting up challenge 'tls-alpn-01' for domain apachelounge.com] detail[error setting up challenge 'tls-alpn-01', for domain apachelounge.com, looking for other option]
[md:error] [pid 5516:tid 2264] (22)Invalid argument: md[apachelounge.com] while[Setting up challenge 'tls-alpn-01' for domain apachelounge.com] problem[challenge-mismatch] detail[None of offered challenge types for domain apachelounge.com are supported. The server offered 'http-01 dns-01 tls-alpn-01' and available are: 'tls-alpn-01'.]
[md:debug] [pid 5516:tid 2264] md_result.c(254): (22)Invalid argument: md[apachelounge.com] while[Setting up challenge 'tls-alpn-01' for domain apachelounge.com] problem[challenge-mismatch] detail[None of offered challenge types for domain apachelounge.com are supported. The server offered 'http-01 dns-01 tls-alpn-01' and available are: 'tls-alpn-01'.]
[md:debug] [pid 5516:tid 2264] md_result.c(254): (22)Invalid argument: md[apachelounge.com] while[Setting up challenge 'tls-alpn-01' for domain apachelounge.com] problem[challenge-mismatch] detail[None of offered challenge types for domain apachelounge.com are supported. The server offered 'http-01 dns-01 tls-alpn-01' and available are: 'tls-alpn-01'.]
[md:debug] [pid 5516:tid 2264] md_reg.c(1068): (22)Invalid argument: apachelounge.com: staging done
[md:error] [pid 5516:tid 2264] (22)Invalid argument: AH10056: processing apachelounge.com: None of offered challenge types for domain apachelounge.com are supported. The server offered 'http-01 dns-01 tls-alpn-01' and available are: 'tls-alpn-01'.
[md:info] [pid 5516:tid 2264] AH10057: apachelounge.com: encountered error for the 1. time, next run in 3 seconds
```
MDMessageCmd gives a mail: errored apachelounge.com

And mod_md is repeating/trying **again and again**.

After stop/start Apache same trying loop.

[serror-v219.log](https://github.com/icing/mod_md/files/3723549/serror-v219.log)

[staging.zip](https://github.com/icing/mod_md/files/3723559/staging.zip)

I removed mod_md

**Config:**
Protocols h2 http/1.1 acme-tls/1
MDomain apachelounge.com www.apachelounge.com land10.nl.............. 
Listen 443
MDCertificateAgreement accepted
MDRenewMode Always
MDRenewWindow   79d
MDWarnWindow 80d
MDStapling on
MDNotifyCmd D:/servers/apacheS/bin/MDNotifyCmd.bat
MDMessageCmd D:/servers/apacheS/bin/MDMessageCmd.bat

**Comment by icing** [comment]
There was no change regarding the challenge handling in recent versions that I am aware of.

The error says that it could not find a supported challenge for the domain ```apachelounge.com``` because it does not seem to support the ```acme-tls/1``` protocol. Since this worked in the last weeks several times, I wonder if something changed.

I do not see the ```MDBaseServer``` configuration in the config above, for example.

As to the *again and again*: what do you propose should happen?

**Comment by SteffenAL** [comment]
Nothing changed here, still the same Apache. Renew was working with v2.1.8

MDBaseServer was there 

again and again : no problem for me. Was a worried about the limit Pending Authorizations, but that is 300.

**Comment by SteffenAL** [comment]
This is strange:

This function has not been implemented on this platform: apachelounge.com: protocol 'acme-tls/1' not enabled for this domain.

and this one says it is enabled/available:

processing apachelounge.com: None of offered challenge types for domain apachelounge.com are supported. The server offered 'http-01 dns-01 tls-alpn-01' and available are: 'tls-alpn-01'.

**Comment by icing** [comment]
Did you get the error mail every time or once an hour? (There is a rate limit on the notification call  at least there should be...).

Anyway, thanks for the data. I made a change in v2.1.10 that adds some more special handling for the base server setup you use. The support for the tls-alpn-01 challenges will now fall back to check the base server now and that should solve your issue.

**Comment by SteffenAL** [comment]
Cannot recall the mail frequency, I deleted all.

Coming time I cannot test anymore mod_md.

I had  to switch to an other client because I must test the auto LE with the author of the SurgeMail server. I reported in #144 already that mod_md conflicts with other clients.
