### ISSUE TITLE
Default to RSA 4096 bits?

### ISSUE THREAD

**Issue by Jan-E** [icing/mod_md#155]
I noticed that Directadmin has switched to RSA 4096 bits for letsencrypt certificates. Is it an idea to do the same switch in mod_md? As far as I can see this needs a change in line 35 of md.h:

https://github.com/icing/mod_md/blob/master/src/md.h#L35

Or would it be an idea to make the default bitsize configurable?

**Comment by icing** [comment]
You [can configure it, see here.](https://github.com/icing/mod_md#mdprivatekeys)

At the time, 2048 seemed to be - from what I read - the best compromise in security and performance. That depends on a lot of factors, of course.

**Comment by Jan-E** [comment]
OK, I missed that. Thanks.
