### ISSUE TITLE
Wrong priorities of the challenges

### ISSUE THREAD

**Issue by mkauf** [icing/mod_md#156]
The documentation at https://httpd.apache.org/docs/trunk/en/mod/mod_md.html#mdcachallenges says that the default priority of the challenges is like this:
```
MDCAChallenges tls-alpn-01 http-01 dns-01
```

In ``md_acme_drive.c`` I found a different order:
```
/* free to chose. Add all we support and see what we get offered */
APR_ARRAY_PUSH(ad->ca_challenges, const char*) = MD_AUTHZ_TYPE_HTTP01;
APR_ARRAY_PUSH(ad->ca_challenges, const char*) = MD_AUTHZ_TYPE_TLSALPN01;
APR_ARRAY_PUSH(ad->ca_challenges, const char*) = MD_AUTHZ_TYPE_DNS01;
```

Is this a bug or are the priorities of the challenges defined elsewhere?

**Comment by icing** [comment]
You are correct. The question now is, which order do we want? *scratch*

**Comment by mkauf** [comment]
"tls-alpn-01" needs a special configuration (``Protocols h2 http/1.1 acme-tls/1``) and is automatically skipped if this configuration is missing, so the default "tls-alpn-01 http-01 dns-01" is probably safe.

I've noticed that there is no fallback to a different challenge type if the Let's Encrypt server responds that the validation failed, maybe this could be improved too...? ;)

**Comment by icing** [comment]
I agree with the ordering.

As to the "on error resume next" approach. I am not certain. This could be used for some sort of downgrade attack. maybe. not sure. Security is hard.
