### ISSUE TITLE
Crashes with 0.2.0 on Windows

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#16]
Crash: a2md drive with no domain:  a2md -vvv -a https://acme-staging.api.letsencrypt.org/directory -d C:\apache24\md drive 

Crash;  mod_md ServerName is equal to name ManagedDomain

**Comment by icing** [comment]
I hope v0.5.0 compiles for you. I do not have the time to debug old version. If you can reproduce the fault in v0.5.0, please say so here or close the ticket if it is fixed. thanks.

**Comment by SteffenAL** [comment]
With 0.5.0:

a2md: no crash anymore

mod_md still crashes when ServerName is equal to name ManagedDomain

Closing
