### ISSUE TITLE
MDRequireHttps not allowed in <If> context

### ISSUE THREAD

**Issue by nono303** [icing/mod_md#160]
Hi Stefan,
I would like to disable only one specific vhost, managed by mod_macro, `MDRequireHttps  permanent`.
Here is my idea ; which don't work with startup error message: `MDRequireHttps not allowed in <If> context`?

```
<Macro VHostLets $vh>
  <IfModule md_module>
    MDomain $vh
    <If "'$vh' == 'vhost.accepting.http">
      MDRequireHttps off
    </If>
    <Else>
      MDRequireHttps permanent
    </Else>
  </IfModule>
...
```

- Is that a 'normal' behavior?
- Should I use other way to exclude a vhost of `MDRequireHttps permanent` in mod_macro?

Thanks for your feedback!

Arnaud

**Comment by icing** [comment]
Hi Arnaud,

interesting use! I think mod_md is too restrictive here and that use inside <If|Macro|etc> should not cause any errors or warnings.

**Comment by icing** [comment]
Could you check the current master, if it does what you need? (And not breaks anything else...)

**Comment by nono303** [comment]
Hi Stefan,
It exactly does what I want and as far as now with a certificates renew, I didn't see any break.
Just an update for the good configuration in my use case, according to your documention, MDRequireHttps must be include in a MDomain element to work (not like I write it upper)
```
<Macro VHostLets $vh>
  <IfModule md_module>
    <MDomain $vh>
      <If "'$vh' == 'vhost.accepting.http">
        MDRequireHttps off
      </If>
      <Else>
        MDRequireHttps permanent
      </Else>
    </MDomain>
  </IfModule>
  ...
```
