### ISSUE TITLE
MDCertificateFile/keyfile errors when no vhosts 

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#161]
There is  an installation independent of mod_md LE and **no vhosts** and is running fine.

Now they like to have  the monitoring and status reporting of mod_md.

Tried:
```
LoadModule md_module modules/mod_md.so
MDCertificateFile conf/domain.com-chain.pem
MDCertificateKeyFile conf/domain.com-key.pem 
```

Gives:
MDCertificateFile is only valid inside a '<MDomainSet' context, not here

Then tried:
```
LoadModule md_module modules/mod_md.so
<MDomain domain.com www.domain.com> 
MDCertificateFile conf/domain.com-chain.pem
MDCertificateKeyFile conf/domain.com-key.pem 
</MDomain>
```

Gives:
[ssl:emerg] [pid 10152:tid 720] AH02572: Failed to configure at least one certificate and key for www.domain.com:443
[ssl:emerg] [pid 10152:tid 720] SSL Library Error: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no certificate assigned
[ssl:emerg] [pid 10152:tid 720] AH02312: Fatal error initialising mod_ssl, exiting.

**Comment by Karm** [comment]
@SteffenAL Isn't it related to https://github.com/icing/mod_md#mdbaseserver  ?  i.e. that your base server (main_server) is not managed by default?

**Comment by icing** [comment]
Yeah, that currently does not work. Hmm. Thinking...

**Comment by icing** [comment]
I have to correct myself: just setup a test case like your second approach. `MDBaseServer on` and it works.

Could you check this on your end?

**Comment by SteffenAL** [comment]
@Karm Thanks for the pointer, working now here also.  Also /.httpd/certificate-status works.

I assume that mod_md is not doing renew attempts ?

Have set  **MDStapling on** and see  it also in mod_status and it looks that mod_md  refreshes it.

**Comment by icing** [comment]
An 'MDomain' with static cert/key files switches to Renew Mode 'manual'. So,  no renew attempts by the module.

**Comment by icing** [comment]
Are we good? May I close this?

**Comment by SteffenAL** [comment]
All fine
