### ISSUE TITLE
"Managed Domains have an overlap" shuts down apache

### ISSUE THREAD

**Issue by sophie-h** [icing/mod_md#165]
If I'm reloading apache, I'm not expecting a crash due to a trivial config change:

```
Dec 22 20:14:51 apache2[30636]: [mpm_prefork:notice] [pid 30636] AH00171: Graceful restart requested, doing restart
Dec 22 20:14:52 systemd[1]: Reloaded The Apache HTTP Server.
Dec 22 20:14:52 apache2[30636]: [md:error] [pid 30636] AH10038: two Managed Domains have an overlap in domain 'example.org', first definition in unknown(line 0), second in unknown(line 0)
Dec 22 20:14:52 systemd[1]: apache2.service: Main process exited, code=exited, status=1/FAILURE
Dec 22 20:14:52 systemd[1]: apache2.service: Failed with result 'exit-code'.
```

**Comment by icing** [comment]
Neither do I. Normally, on a reload the server checks the new configuration and, if there are errors, rejects those and keeps running with the old one.

If this failed for you, can you give me instructions on how to reproduce this? You did a `systemd reload apache2` after moving a ServerAlias from von vhost to another?

**Comment by icing** [comment]
No answer received, closing.
