### ISSUE TITLE
postfix/dovecot

### ISSUE THREAD

**Issue by Jancs-E** [icing/mod_md#171]
Hi!
Would it be possible to use the same set of certificates also for postfix and dovecot?
Would it be enough just to script a bit in order to get dovecot -usable certificate and get everything updates when apache gets its update? May be some how to already exists?

**Comment by icing** [comment]
Indeed, such a thing exists on my own server. There are two ways to tackle this

  1. Point the certificate configurations of `postfix` and `dovecot` to the places where `mod_md` keeps them.
  2. Use the `MDMessageCmd` to copy them where there are needed.

Which one works best depends also on the versions of programs you use. Earlier postfix versions wanted key and certs in a single file, current ones allow separate configurations.

## Linking Files

To keep all the md data in a nicer place, I changed Apache config (this is not necessary):
```
MDStoreDir  /etc/md
```

In dovecot:

```
/etc/dovecot/conf.d/10-ssl.conf:ssl_cert = </etc/md/domains/greenbytes.de/pubcert.pem
/etc/dovecot/conf.d/10-ssl.conf:ssl_key = </etc/md/domains/greenbytes.de/privkey.pem
```

In postfix:

```
> fgrep -ri ssl /etc/postfix
/etc/postfix/main.cf:smtpd_tls_CAfile = /etc/postfix/ssl/fullchain.pem
/etc/postfix/main.cf:smtp_tls_CAfile = /etc/postfix/ssl/fullchain.pem
/etc/postfix/main.cf:smtpd_tls_cert_file = /etc/postfix/ssl/cert.pem
/etc/postfix/main.cf:smtpd_tls_key_file = /etc/postfix/ssl/privkey.pem
> ls -l /etc/postfix/ssl/
cert.pem -> /etc/md/domains/greenbytes.de/pubcert.pem
fullchain.pem -> /etc/md/domains/greenbytes.de/pubcert.pem
privkey.pem -> /etc/md/domains/greenbytes.de/privkey.pem
```

## Post-Processing New Certificates

If you want to go the copy route, add in your Apache config:

```
MDMessageCmd _your_path_/md_message
```
The script, where you would do the copying of new certs somewhere. Use the "installed" case:

```
#!/bin/bash

USER=youremail@yourdomain

action="$1"
domain="$2"

case "$action" in
    "renewed")
        subject="renewed $domain certificate"
        msg="Your Apache renewed the certificate for '$domain'. It will become active after a server reload."
        ;;
    "installed")
        subject="installed $domain certificate"
        msg="Your Apache installed the certificate for '$domain'. It is now active."
        ;;
    "expiring")
        subject="expiring $domain certificate"
        msg="Your Apache reports that the certificate for '$domain' will soon expire."
        ;;
    "errored")
        subject="error renewing $domain certificate"
        msg="There was an error renewing the certificate for '$domain'. Apache will continue trying. Please check the md-status resources or the server log for more information should this repeat."
        ;;
    "ocsp-renewed")
        subject="refreshed OCSP stapling for $domain"
        msg="The OCSP stapling information for '$domain' was successfully refreshed."
        ;;
    "ocsp-errored")
        subject="error refreshing OCSP stapling for $domain"
        msg="The was an error refreshing the OCSP stapling information for '$domain'. Apache will continue trying. Please check the md-status resources or the server log for more information should this repeat."
        ;;
    *)
        subject="unknown action in MD message"
        msg="Your Apache reported action '$action' for domain '$domain'."
esac

if test "x$msg" = "x"; then exit 0; fi

mail -s "$subject" $USER <<EOF
$msg
EOF
```

**Comment by Jancs-E** [comment]
Thank you for the hints!

Janis

Citēts Stefan Eissing <notifications@github.com>
Mon, 13 Jan 2020 01:10:44 -0800:

> Indeed, such a thing exists on my own server. There are two ways to  
> tackle this
>
>   1. Point the certificate configurations of `postfix` and `dovecot`  
> to the places where `mod_md` keeps them.
>   2. Use the `MDMessageCmd` to copy them where there are needed.
>
> Which one works best depends also on the versions of programs you  
> use. Earlier postfix versions wanted key and certs in a single file,  
> current ones allow separate configurations.
>
> ## Linking Files
>
> To keep all the md data in a nicer place, I changed Apache config  
> (this is not necessary):
> ```
> MDStoreDir  /etc/md
> ```
>
> In dovecot:
>
> ```
> /etc/dovecot/conf.d/10-ssl.conf:ssl_cert =  
> </etc/md/domains/greenbytes.de/pubcert.pem
> /etc/dovecot/conf.d/10-ssl.conf:ssl_key =  
> </etc/md/domains/greenbytes.de/privkey.pem
> ```
>
> In postfix:
>
> ```
>> fgrep -ri ssl /etc/postfix
> /etc/postfix/main.cf:smtpd_tls_CAfile = /etc/postfix/ssl/fullchain.pem
> /etc/postfix/main.cf:smtp_tls_CAfile = /etc/postfix/ssl/fullchain.pem
> /etc/postfix/main.cf:smtpd_tls_cert_file = /etc/postfix/ssl/cert.pem
> /etc/postfix/main.cf:smtpd_tls_key_file = /etc/postfix/ssl/privkey.pem
>> ls -l /etc/postfix/ssl/
> cert.pem -> /etc/md/domains/greenbytes.de/pubcert.pem
> fullchain.pem -> /etc/md/domains/greenbytes.de/pubcert.pem
> privkey.pem -> /etc/md/domains/greenbytes.de/privkey.pem
> ```
>
> ## Post-Processing New Certificates
>
> If you want to go the copy route, add in your Apache config:
>
> ```
> MDMessageCmd _your_path_/md_message
> ```
> The script, where you would do the copying of new certs somewhere.  
> Use the "installed" case:
>
> ```
> #!/bin/bash
>
> USER=youremail@yourdomain
>
> action="$1"
> domain="$2"
>
> case "$action" in
>     "renewed")
>         subject="renewed $domain certificate"
>         msg="Your Apache renewed the certificate for '$domain'. It  
> will become active after a server reload."
>         ;;
>     "installed")
>         subject="installed $domain certificate"
>         msg="Your Apache installed the certificate for '$domain'. It  
> is now active."
>         ;;
>     "expiring")
>         subject="expiring $domain certificate"
>         msg="Your Apache reports that the certificate for '$domain'  
> will soon expire."
>         ;;
>     "errored")
>         subject="error renewing $domain certificate"
>         msg="There was an error renewing the certificate for  
> '$domain'. Apache will continue trying. Please check the md-status  
> resources or the server log for more information should this repeat."
>         ;;
>     "ocsp-renewed")
>         subject="refreshed OCSP stapling for $domain"
>         msg="The OCSP stapling information for '$domain' was  
> successfully refreshed."
>         ;;
>     "ocsp-errored")
>         subject="error refreshing OCSP stapling for $domain"
>         msg="The was an error refreshing the OCSP stapling  
> information for '$domain'. Apache will continue trying. Please check  
> the md-status resources or the server log for more information  
> should this repeat."
>         ;;
>     *)
>         subject="unknown action in MD message"
>         msg="Your Apache reported action '$action' for domain '$domain'."
> esac
>
> if test "x$msg" = "x"; then exit 0; fi
>
> mail -s "$subject" $USER <<EOF
> $msg
> EOF
> ```
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/icing/mod_md/issues/171#issuecomment-573568463


-- 
ph. +37129203061

http://dict.dv.lv

**Comment by Jancs-E** [comment]
Hi!

for the case 1 - is it not required to reload dovecot and postfix for  
new certs to work?

Janis

Citēts Stefan Eissing <notifications@github.com>
Mon, 13 Jan 2020 01:10:44 -0800:

> Indeed, such a thing exists on my own server. There are two ways to  
> tackle this
>
>   1. Point the certificate configurations of `postfix` and `dovecot`  
> to the places where `mod_md` keeps them.
>   2. Use the `MDMessageCmd` to copy them where there are needed.
>
> Which one works best depends also on the versions of programs you  
> use. Earlier postfix versions wanted key and certs in a single file,  
> current ones allow separate configurations.
>
> ## Linking Files
>
> To keep all the md data in a nicer place, I changed Apache config  
> (this is not necessary):
> ```
> MDStoreDir  /etc/md
> ```
>
> In dovecot:
>
> ```
> /etc/dovecot/conf.d/10-ssl.conf:ssl_cert =  
> </etc/md/domains/greenbytes.de/pubcert.pem
> /etc/dovecot/conf.d/10-ssl.conf:ssl_key =  
> </etc/md/domains/greenbytes.de/privkey.pem
> ```
>
> In postfix:
>
> ```
>> fgrep -ri ssl /etc/postfix
> /etc/postfix/main.cf:smtpd_tls_CAfile = /etc/postfix/ssl/fullchain.pem
> /etc/postfix/main.cf:smtp_tls_CAfile = /etc/postfix/ssl/fullchain.pem
> /etc/postfix/main.cf:smtpd_tls_cert_file = /etc/postfix/ssl/cert.pem
> /etc/postfix/main.cf:smtpd_tls_key_file = /etc/postfix/ssl/privkey.pem
>> ls -l /etc/postfix/ssl/
> cert.pem -> /etc/md/domains/greenbytes.de/pubcert.pem
> fullchain.pem -> /etc/md/domains/greenbytes.de/pubcert.pem
> privkey.pem -> /etc/md/domains/greenbytes.de/privkey.pem
> ```
>
> ## Post-Processing New Certificates
>
> If you want to go the copy route, add in your Apache config:
>
> ```
> MDMessageCmd _your_path_/md_message
> ```
> The script, where you would do the copying of new certs somewhere.  
> Use the "installed" case:
>
> ```
> #!/bin/bash
>
> USER=youremail@yourdomain
>
> action="$1"
> domain="$2"
>
> case "$action" in
>     "renewed")
>         subject="renewed $domain certificate"
>         msg="Your Apache renewed the certificate for '$domain'. It  
> will become active after a server reload."
>         ;;
>     "installed")
>         subject="installed $domain certificate"
>         msg="Your Apache installed the certificate for '$domain'. It  
> is now active."
>         ;;
>     "expiring")
>         subject="expiring $domain certificate"
>         msg="Your Apache reports that the certificate for '$domain'  
> will soon expire."
>         ;;
>     "errored")
>         subject="error renewing $domain certificate"
>         msg="There was an error renewing the certificate for  
> '$domain'. Apache will continue trying. Please check the md-status  
> resources or the server log for more information should this repeat."
>         ;;
>     "ocsp-renewed")
>         subject="refreshed OCSP stapling for $domain"
>         msg="The OCSP stapling information for '$domain' was  
> successfully refreshed."
>         ;;
>     "ocsp-errored")
>         subject="error refreshing OCSP stapling for $domain"
>         msg="The was an error refreshing the OCSP stapling  
> information for '$domain'. Apache will continue trying. Please check  
> the md-status resources or the server log for more information  
> should this repeat."
>         ;;
>     *)
>         subject="unknown action in MD message"
>         msg="Your Apache reported action '$action' for domain '$domain'."
> esac
>
> if test "x$msg" = "x"; then exit 0; fi
>
> mail -s "$subject" $USER <<EOF
> $msg
> EOF
> ```
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/icing/mod_md/issues/171#issuecomment-573568463


-- 
ph. +37129203061

http://dict.dv.lv

**Comment by icing** [comment]
As far as I know, yes. But I would restart them regularly anyway ([systemd allows to configure this, for example](https://stackoverflow.com/questions/31055194/how-can-i-configure-a-systemd-service-to-restart-periodically#31064649). 

Certificates are renewed usually 30 days before expiry of the previous one. So, if dovecot/postfix restarts at least once a week, you are fine.

**Comment by Jancs-E** [comment]
Hi!

I used to restart/reload postfix/dovecot only at upgrades/setting changes.

So, to keep it that way, the involvement of the script as for case 2  
is necessary.

Thank you very much!

Janis

Citēts Stefan Eissing <notifications@github.com>
Wed, 05 Feb 2020 00:56:43 -0800:

> As far as I know, yes. But I would restart them regularly anyway  
> ([systemd allows to configure this, for  
> example](https://stackoverflow.com/questions/31055194/how-can-i-configure-a-systemd-service-to-restart-periodically#31064649).
>
> Certificates are renewed usually 30 days before expiry of the  
> previous one. So, if dovecot/postfix restarts at least once a week,  
> you are fine.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/icing/mod_md/issues/171#issuecomment-582305419


-- 
ph. +37129203061

http://dict.dv.lv

**Comment by Jancs-E** [comment]
Just a small question - if I'd wanted to restart postfix and dovecot from md_message - md_message
would be executed as user apache.apache?

**Comment by icing** [comment]
You can find this in [MDMessageCmd description](https://github.com/icing/mod_md#mdmessagecmd). Ususally, this command is invoked by the server child processes, which are all ```apache.apache``` or on other platforms ```www-data.www-data```.

When invoked with argument ```installed```, this call is made by the main httpd process and it is made with the privileges that process started with, normally ```root```. This would be the correct time to restart any processes using those certificates.

**Comment by Jancs-E** [comment]
Thank you once more!

Janis

Citēts Stefan Eissing <notifications@github.com>
Tue, 11 Feb 2020 23:46:36 -0800:

> You can find this in [MDMessageCmd  
> description](https://github.com/icing/mod_md#mdmessagecmd).  
> Ususally, this command is invoked by the server child processes,  
> which are all ```apache.apache``` or on other platforms  
> ```www-data.www-data```.
>
> When invoked with argument ```installed```, this call is made by the  
> main httpd process and it is made with the privileges that process  
> started with, normally ```root```. This would be the correct time to  
> restart any processes using those certificates.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/icing/mod_md/issues/171#issuecomment-585075009


-- 
ph. +37129203061

http://dict.dv.lv
