### ISSUE TITLE
Best practice for using mod_md for single domain with multiple hosts

### ISSUE THREAD

**Issue by ingarb** [icing/mod_md#176]
Hi!

I have a working Apache / mod_md setup today in Azure, with a single host behind a Basic Azure Load Balancer.

The amount of traffic is a bit high for one host, so I would like to have two hosts behind the Azure Load Balancer.

However, reading the documentation it seems this is not supported using the http-01 acme-v1 challenge that I am currently using.

Looking at it, seems that the dns01 challenge could be used, but I was unable to figure out a practical way of doing this, as I am hosting many websites for 3rd parties and each 3rd party has their own DNS provider.

Any tips/suggestions on a possible setup is welcome, but I would like it to be very straightforward and automated, avoiding scripts and batch files where possible.

Current working setup:

MDomain mydomain.here
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
MDPortMap 80:9023 443:9022
MDRequireHttps temporary

**Comment by icing** [comment]
There are two issues here:

1. the module uses `mod_watchdog` to supervise the state of certificates. Ideally, this would only run on one of your instances.
2. the module persists everything in the file system. Having that shared among instances might not be easy.

With the latest versions from here, you can use MDomain with [certificate files](https://github.com/icing/mod_md#mdcertificatefile) on all your "secondary" instances. Alternatively you could use it like that on all instances and get the certificates only with `certbot`.

I never worked with Azure, so I have no expertise what is best in their setup.
