### ISSUE TITLE
wildcard Lets Encrypt

### ISSUE THREAD

**Issue by tf-ansible** [icing/mod_md#177]
I'm sorry to log this, but i just can't find what i am looking for in the documentation.
I am trying to setup mod_md to request a letsencrypt wildcard certificate.
I am happy with the external script to create the required DNS records, but i cannot work out how/where to put the domain to get the challenge details i need to put in the DNS records..

I have tried in the md.conf file and the vhost files.:
 mdomain *.domainname.com 
 mdomain domainname.com 
and other variations but the logs show it can't find a vhost with a matching domain.

Where/what am i supposed to set to request a wildcard certificate?

**Comment by icing** [comment]
Most people declare `VirtualHost` sections, such as:

```
<VirtualHost *:443>
   ServerName domainname.com
   ServerAlias *.domainname.com
   DocumentRoot...
   SSLEngine on
   ...
</VirtualHost>
```

If you have that and add:

```
MDomain domainname.com
MDCertificateAgreement accepted
```

it should try to get a wildcard cert.
