### ISSUE TITLE
MDRequireHttps doesn't exclude status

### ISSUE THREAD

**Issue by tlhackque** [icing/mod_md#187]
MDRequireHttps doesn't exclude status pages.

This is a problem if one needs to diagnose a failure when there is no valid certificate.  One would like to access the status when the lack of certificate causes responses to SSL to be 503s.

`server-status`, `MDCertificateStatus`, `server-info`, `md-status` , and possibly `http2-status` should be accessible via http.  It's not obvious how to identify `<Location>`s that invoke these handlers...

I experienced this issue - but as I wasn't using MDRequireHttps, I could switch to `http` to diagnose.

**Comment by nodiscc** [comment]
@tlhackque can you share the configuration you did use to selectively enable HTTP->HTTPS redirections, while leaving MDRequireHttps off? I am migrating my apache setup to mod_md but am concerned with the problem you described.

Ar you using mod_rewrite and `RewriteCond ! ...` to achieve this?

**Comment by icing** [comment]
This will not work in case you configure ```MDRequireHttps permanent``` as the browser will refuse to talk plain http: to that domain.

I recommend to have the status pages (only or also) on a domain that is restricted to admin use, maybe localhost if you have ssh access to your server anyway. But if you prefer the http: access for certain things, a ```RewriteSomething...``` is probably what you want to use.
