### ISSUE TITLE
New argument for MDMessageCmd

### ISSUE THREAD

**Issue by tlhackque** [icing/mod_md#188]
It would be helpful if `MDMessageCmd` provided the (full path) to `MDStoreDir` as a 3rd argument.

This would facilitate having the called program move  certificates to other users.  (E.g. on other servers.)  This is a common use case.

Currently, the location of the certificates must be hard-coded in the program.  `MDStoreDir` is not
available from the server.  (Except if `server-info` is enabled, and you parse HTML... Or if you duplicate the value as an "optional" argument to `MDMessageCmd`.)  

If a program had the value of `MDStoreDir`, it could use that to find `.../domains/$domain/*{key,cert}.pem`.

I have implemented this is my sources.

**Comment by icing** [comment]
Maybe an environment variable?

**Comment by tlhackque** [comment]
That had been my first thought, but it's more work.  No real payback, unless we forsee MANY more items to be passed.

Would change  md_util_exec in md_util, plus callers in md_acme_authz as well as mod_md.

Only impact to current users of adding the arg would be if someone accessed from the end (to skip optional args).  But it's more likely that they know what optional args they expect.  Or are sensible and pass optional args as switches (options), so they can be distinguished from the supplied args.  And in that case, the natural thing is to take them left to right.  If anyone uses them.

I had clarified the README before realizing this need, since it wasn't obvious whether the optional args were provided before or after the reason and domain.  When I did that, I noted that additional fixed args might be a possiblity and should be accounted for,

Given that mod_md is new (and MDMessageCmd is only a few months old), it seemed to me that the risk is low.  I'd prefer to stay with adding the third argument - and the doc change allows for any future additions.

If you feel strongly enough that an environment variable should be used, and are willing to accept the larger change that it involves, I can implement that.

(This came up because I'm writing a general script for handling MDMessageCmd events, which highlights the interface challenges...)

**Comment by icing** [comment]
I definitely like the idea of providing a nice MDMessageCmd that works in all environments. *thumbsup*

Since I foresee that more information to pass on might come up, I like the environment much more. I just pushed an implementation with tests that does this. What do you think?

**Comment by tlhackque** [comment]
Looking at your commit confirms that it **was** a lot more work than my 1 1/2 line change...

Did you consider ap_create_environment()?  It takes a table of key/value pairs and creates the environment array.    Tables are a better match for environment variables - they are key/value, and have functions for unset, compress, add (with or without copy), etc.  

Of course, the README/doc will need to reflect this.

I will push my script when it's closer to working, and hope you'll have some time to test & review.

There are some more challenges with the interface to `mod_md`, but I'll see what I can do with what we have.

One challenge is that keys on `staging` are encrypted, which means that they can't be deployed to other consumers on a `renewed` event, but have to wait for the `installed` event.

**Comment by tlhackque** [comment]
Since you're passing environment variables - how about `MD_VERSION` (the version of `mod_md`)?

It wasn't worth a positional argument, but since envars are cheap...

Including the mod_md version would let the program adapt easily to any changes in `mod_md` - or at least log the version in case of issues.

**Comment by icing** [comment]
See? ;-)

Will add that.

**Comment by icing** [comment]
Done.

**Comment by tlhackque** [comment]
I saw :-)  but priority was minimal change.

Thanks.
