### ISSUE TITLE
Misleading & misplaced text in README

### ISSUE THREAD

**Issue by tlhackque** [icing/mod_md#190]
The README says (somewhat humorously):
> If your DNS provider does not offer an interface that you can script, he will offer at least a web interface where you can enter records manually. You can then configure a script that mails you the the information, so you can do it yourself. Welcome to the machine age!

Of course, this is nonsense.  `mod_md` can not wait while e-mail is delivered, you return from vacation, get your password reset, and try to persuade the web interfact to accept your TXT record.  Even if it could, by the time you do that, the validation server may have expired the challenge :-)

There are a number of DNS update scripts  supporting various providers that are used by other clients.  I will provide a wrapper for some of them in `md_events`...

In the meantime, please remove the misleading text.

Also, the `MDChallengeDns01` description should have a description of how the executable is called.  You can just move the text from the "Wildcard Certificates" section:
````
/usr/bin/acme-setup-dns setup mydomain.com challenge-data
# this needs to remove all existing DNS TXT records for 
# _acme-challenge.mydomain.com and create a new one with 
# content "challenge-data"
and afterwards it will call

/usr/bin/acme-setup-dns teardown mydomain.com
# this needs to remove all existing DNS TXT records for 
# _acme-challenge.mydomain.com
````

**Comment by icing** [comment]
Done in 4604c6f81c79fd88fc944fb7581085a577322d9e.
