### ISSUE TITLE
Version 2.3.1 build warning

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#192]
Building get warning  : 

md_crypt.c(533): warning C4715: 'md_pkey_spec_name': not all control paths return a value 
potentially we do not have a return a value

md_version.h still says 2.2.7

**Comment by icing** [comment]
@tlhackque made a fix for the first. pbly release soon.

md_version.h looks ok in github. can you double check?

**Comment by SteffenAL** [comment]
Ah.. was using mod_md-2.3.1.tar.gz there is no md_version.h, and was using the old mod_version.h

With mod_md-2.3.1.zip is a mod_version.h, and is ok.
