### ISSUE TITLE
Renew/replace certs affected by LE CAA Bug

### ISSUE THREAD

**Issue by jmwebservices** [icing/mod_md#195]
Per this [bug](https://community.letsencrypt.org/t/2020-02-29-caa-rechecking-bug/114591), LE will start revoking certificates. They have advised to renew/replace certificates that may have been affected. I am using `mod_md`, so how can I force a renew?

**Comment by tlhackque** [comment]
I don't think there's a friendly way.  What I did: delete the "domains" directory (or move it elsewhere if you need to keep the history).  Restart httpd.  mod_md will see that it has no certificates, so it will request new ones.

The downside is that your site will be off-line until the new certificates arrive - visitors will get a 503 - service unavailable.   Depending on what validation method you use, this could be a few seconds or a few minutes...

I put a better way to force renewal  (using this example) on a wish list earlier today...

**Comment by jmwebservices** [comment]
> What I did: delete the "domains" directory (or move it elsewhere if you need to keep the history). Restart httpd. mod_md will see that it has no certificates, so it will request new ones.

Other than having to restart about 3 times to resolve issuance errors, it worked like a charm.

**Comment by tlhackque** [comment]
Glad you were successful.

One restart should have done it if you were patient.  What were the errors?

P.S. The reason I just delete domains instead of the whole tree is to re-use the LE account.
