### ISSUE TITLE
Clarification regarding mod_md and mod_status

### ISSUE THREAD

**Issue by ZerooCool** [icing/mod_md#196]
Debian 10 stable
Apache 2.4

mod_md + mod_status enabled

My VHost : https://wiki.visionduweb.fr/index.php?title=VirtualHosts_des_domaines_enregistr%C3%A9s#visionduweb.fr_.C3.A9coute_du_port_SSL_443

I just wish I could see my certificate in my server-status navigation url to know its expiration date.

I do not understand how to place the tags to do this, in the Vhost, where, what tags i need use.

I would really like the minimum required here, to simply display the status of the certificates in my browser, and not for auto renew.

**Comment by tlhackque** [comment]
mod_md only provides status for certificates that it manages.

If that's all you need, it's pretty easy to get this information yourself.

From the command line (no privileges are required):
````
2>&1  openssl s_client -connect wiki.visionduweb.fr:443 -CAfile /etc/ssl/ca_bundle.pem </dev/null | openssl x509 -subject -issuer -startdate -enddate -noout
subject=CN = wiki.visionduweb.fr
issuer=C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
notBefore=Jan 18 03:37:49 2020 GMT
notAfter=Apr 17 03:37:49 2020 GMT
````
You can turn this into a CGI script if you need it in a browser.

Or you can setup mod_md with static certificate files which will disable renewal
Something like
````
<MDomain wiki.visionduweb.fr>
MDCertificateFile /etc/ssl/wiki.visionduweb.fr.cert
MDCertificateKeyFile /etc/ssl/wiki.visionduweb.fr.key
</Mdomain>

Since you are using a LE certificate, why don't you want auto-renewal?

**Comment by ZerooCool** [comment]
In fact, I already use automatic renewal, with a cron stain, everything works fine.

My question mainly concerns the use of mod_status because I read that to display the certificate information from the server-status page, I had to configure my virtualhost, at least one, for mod_md

Currently, the server-status page shows me a lot of information about the server, but, I don't have the information about the expiration of the certificates, which I would like to obtain.

It is this rendering that I would like to obtain, see the image:

https://static.chez-oim.org/tuto_MD/cert1.png

I do not understand or should be placed the <MDomain .. tag because if I put this in my VirtualHost, Apache refuses to restart.

I have read many documentations of apache mod_md and mod_status but I fall back each time on the same documentations, with few examples, and very few are in French, not much more are in English. I only have 4 pages of results on Google, and, that does not allow me to understand how to do it.

I would like to manage to do it, and, write the method in French, on my wiki, to make it accessible to others.

Thank you for your advice.

**Comment by icing** [comment]
@ZerooCool if you want to continue using another ACME client for your certificates, that's fine. I assume you have the usual `SSLCertificateFile` and friends in your VirtualHost sections.

You can add these to a `MDomain` (since mod_md v.2.2.0) via the directives `MDCertificateFile` and `MDCertificateKeyFile` just as @tlhackque mentioned above.

The `MDomain` needs to be outside any `Virtualhost`. Hope this helps.

**Comment by ZerooCool** [comment]
# First i Create CA with certbot
sudo certbot certonly --webroot --agree-tos --email vision.du.web@free.fr -d tiger-green.fr -d www.tiger-green.fr -w /var/www/tiger-green.fr --rsa-key-size 4096

My VHost for :80 ( /etc/apache2/sites-available/tiger-green.fr.conf )
https://wiki.visionduweb.fr/index.php?title=VirtualHosts_des_domaines_enregistr%C3%A9s#tiger-green.fr_.C3.A9coute_du_port_HTTP_80

My VHost for :443  ( /etc/apache2/sites-available/tiger-green.fr.conf )
https://wiki.visionduweb.fr/index.php?title=VirtualHosts_des_domaines_enregistr%C3%A9s#tiger-green.fr_.C3.A9coute_du_port_SSL_443

I have this in the Vhost : 
```
<VirtualHost tiger-green.fr:443>
...
<IfModule mod_ssl.c>
SSLEngine on
SSLCertificateFile /etc/letsencrypt/live/tiger-green.fr/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/tiger-green.fr/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/tiger-green.fr/chain.pem

SSLProtocol all -SSLv2 -SSLv3
SSLHonorCipherOrder on
...
</VirtualHost>
```

Then i need add this, if i anderstand and outside any Virtualhost
```
<MDomain tiger-green.fr>
MDCertificateFile /etc/letsencrypt/live/tiger-green.fr/cert.pem
MDCertificateKeyFile /etc/letsencrypt/live/tiger-green.fr/privkey.pem
</Mdomain>
```

When you say, outside of a VirtualHost, That means, in the same file as the VirtualHost of Apache2, but, not in the VirtualHost tag ( <VirtualHost tiger-green.fr:443> ... </ .. >?

Or else, that means that this configuration should go directly to apache.conf or even to the conf of status.conf or md.conf (which by the way, in my case, does not exist. I do have a md.load in the available modules of apache, but, no associated configuration file for mod_md.)

My question was certainly not clear, but, I specify here the request. I would like to be sure to understand in which file I should add this code : 
```
<MDomain tiger-green.fr>
MDCertificateFile /etc/letsencrypt/live/tiger-green.fr/cert.pem
MDCertificateKeyFile /etc/letsencrypt/live/tiger-green.fr/privkey.pem
</Mdomain>
```

Currently, I understand that I must add this code at the very beginning of my configuration file for the apache site, therefore, /etc/apache2/sites-available/tiger-green.fr.conf

However, if I do so, apache2 refuses to restart.

Invalid command '<MDomain', perhaps misspelled or defined by a module not included in the server configuration

However, mod_md is activated

**Comment by ZerooCool** [comment]
MDomain visionduweb.fr

This command alone, on the top, at the very beginning of the file, will not create any problem of restarting. I do not think that helps me anything, to display the state of the certificates, on the page server-status (via mod_status).

Indeed, with this simple line, nothing is displayed in addition on the server-status page.

**Comment by tlhackque** [comment]
Your `<mdomain tiger-green.fr>` block is fine.

It has to be outside the virtual host, but after `LoadModule mod_md`.

Place it just before your `<VirtualHost tiger-green.fr:443>`

Please let us know where to find your write-up.  Translations are always welcome.

(And I can read French...but not write it well enough to publish.)

**Comment by ZerooCool** [comment]
```
LoadModule mod_md
<mdomain visionduweb.fr>
```

apache2: Syntax error on line 194 of /etc/apache2/apache2.conf: Syntax error on line 28 of /etc/apache2/sites-enabled/visionduweb.fr.conf: LoadModule takes two arguments, a module name and the name of a shared object file to load it from

My Vhost : https://paste.debian.net/1134798/

Some small notes here for mod_md
https://wiki.visionduweb.fr/index.php?title=Installer_Apache2_sur_Debian#Module_Apache2_mod_md

Some small notes here for mod_status
https://wiki.visionduweb.fr/index.php?title=Installer_Apache2_sur_Debian#Module_Apache2_mod_status

**Comment by ZerooCool** [comment]
Now, i have add in /etc/apache2/apache.conf
`LoadModule mod_md /usr/lib/apache2/modules/mod_md.so`

And, in my Vhost, i have add : 
`<mdomain visionduweb.fr>`

sudo service apache2 restart

apache2: Syntax error on line 7 of /etc/apache2/apache2.conf: Can't locate API module structure `mod_md' in file /usr/lib/apache2/modules/mod_md.so: /usr/lib/apache2/modules/mod_md.so: undefined symbol: mod_md

Resart work with :
```
LoadModule md_module /usr/lib/apache2/modules/mod_md.so
mdomain visionduweb.fr
```

But not work with : 
```
LoadModule md_module /usr/lib/apache2/modules/mod_md.so
<mdomain visionduweb.fr>
```

Pastebin from my VHost :

**Comment by tlhackque** [comment]
I'm sorry that we are not communicating clearly.

The `Loadmodule` statement is already somewhere else in your configuration.

What you need exactly is:
````
<MDomain tiger-green.fr>
MDCertificateFile /etc/letsencrypt/live/tiger-green.fr/cert.pem
MDCertificateKeyFile /etc/letsencrypt/live/tiger-green.fr/privkey.pem
</Mdomain>

<VirtualHost tiger-green.fr:443>
<IfModule mod_ssl.c>
SSLEngine on
SSLCertificateFile /etc/letsencrypt/live/tiger-green.fr/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/tiger-green.fr/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/tiger-green.fr/chain.pem

SSLProtocol all -SSLv2 -SSLv3
SSLHonorCipherOrder on
</VirtualHost>

The way that the distributions package `httpd` is very flexible, but can be confusing.

The `httpd` documentation describes the directives in the order that `httpd` processes them.

But that can be hard to discern from all the directories and files.

You might find it easier to understand how the files get put together if you use my [`mergeincludes` tool](https://github.com/tlhackque/httpd-tools).

**Comment by ZerooCool** [comment]
```
LoadModule md_module /usr/lib/apache2/modules/mod_md.so
<MDomain visionduweb.fr>
MDCertificateFile /etc/letsencrypt/live/visionduweb.fr/cert.pem
MDCertificateKeyFile /etc/letsencrypt/live/visionduweb.fr/privkey.pem
</Mdomain>
```

-->

apachectl[12693]: AH00526: Syntax error on line 3 of /etc/apache2/sites-enabled/visionduweb.fr.conf:
apachectl[12693]: Invalid command '<MDomain', perhaps misspelled or defined by a module not included in the server configuration
apachectl[12690]: Action 'start' failed.

**Comment by tlhackque** [comment]
Also - the `MDCertificateFile` should have (in this order) both the `cert.pem` and `chain.pem` files

Once `mod_md` is managing the domain, you can delete the `SSLCertificateFile`, `SSLCertificateKey` , and `SSLCertificateChainFile` directives.  The `MDCertificateFile` and `MDCertificateKeyFile` directives override them.  (It is harmless to leave the `SSL*` directives in.

So, at the very end you have:
````
<MDomain tiger-green.fr>
# certificates.pem has both cert.pem and chain.pem
# e.g. cat cert.pem chain.pem >certificates.pem
MDCertificateFile /etc/letsencrypt/live/tiger-green.fr/certificates.pem
MDCertificateKeyFile /etc/letsencrypt/live/tiger-green.fr/privkey.pem
</Mdomain>

<VirtualHost tiger-green.fr:443>
<IfModule mod_ssl.c>
SSLEngine on
# SSLCertificateFile /etc/letsencrypt/live/tiger-green.fr/cert.pem
#SSLCertificateKeyFile /etc/letsencrypt/live/tiger-green.fr/privkey.pem
# SSLCertificateChainFile /etc/letsencrypt/live/tiger-green.fr/chain.pem

SSLProtocol all -SSLv2 -SSLv3
SSLHonorCipherOrder on
</VirtualHost>
````

**Comment by ZerooCool** [comment]
I specify that I did not load the watchdog module because I did not find it for Debian and I read that it is surely preloaded.

I say it again, possibly, I was surprised not to see a configuration file in /etc/apache2/mods-available/md.conf but only a mod.load

At the moment, I don't see where i can search.

**Comment by ZerooCool** [comment]
Apache2 can't restart when i test your last proposition, 
# SSLCertificateFile ...
# SSLCertificateKeyFile ...
# SSLCertificateChainFile ...

https://paste.debian.net/1134809/

AH00526: Syntax error on line 2 of /etc/apache2/sites-enabled/visionduweb.fr.conf:
apachectl[12814]: Invalid command '<MDomain', perhaps misspelled or defined by a module not included in the server configuration
apachectl[12811]: Action 'start' failed.

Or, with Loadmodule : 
[so:warn] [pid 12834] AH01574: module md_module is already loaded, skipping
 apachectl[12834]: AH00526: Syntax error on line 2 of /etc/apache2/sites-enabled/visionduweb.fr.conf:
apachectl[12834]: Invalid command '<MDomain', perhaps misspelled or defined by a module not included in the server configuration
apachectl[12831]: Action 'start' failed.

Really sorry.

**Comment by tlhackque** [comment]
> LoadModule md_module /usr/lib/apache2/modules/mod_md.so

No.  Do not add a new `LoadModule` statement.  `mod_md` is loaded with the other modules.

You started by saying that mod_md is loaded.

I'm confused.
Do you have server-info enabled?  If so, please verify that mod_watchdog and mod_md are in fact loaded.  Can you post a screenshot?  Also, the full version of apache - 2.4.??

Mine looks like:
![image](https://user-images.githubusercontent.com/332018/76639471-90c0bd80-6524-11ea-9ab6-68f9734d0fba.png)


You may also want to run my tool that consolidates all the configuration files so that we can see what is happening.

**Comment by ZerooCool** [comment]
> You started by saying that mod_md is loaded.
Yes, i test with Loadmodule for read eventualy a other error log.

I look for server-info

I write your proposition for use your tool.

**Comment by tlhackque** [comment]
> apachectl[12814]: Invalid command '<MDomain', perhaps misspelled or defined by a module not included in the server configuration

Your post shows only part of your configuration.  Debian puts it in many pieces.

This says mod_md is not loaded.  Please show server-info - best if you post the whole thing.

Again, my `mergeincludes` tool will show how the pieces are put together.  Order matters.

I'm sorry that this has been so difficult for you.  We're missing some information - the answer will be simple :-)

**Comment by tlhackque** [comment]
Server-info is configured like this:

You need to enable mod_info.

````
<Location /server-info>
  SetHandler server-info
  require host xxx
 </Location>
````
xxx is the host that you are browsing from - you generally don't want server-info to be public.

**Comment by ZerooCool** [comment]
Can you confirm if you can read that ? ( This link was delete after you read )
https://privnote.com/Fc0R6ive#7BmffgjjU

**Comment by tlhackque** [comment]
I read it, but all it contains is:
````
https://www.visionduweb.fr/server-info
````

**Comment by ZerooCool** [comment]
Ofcourse, you ask me that, server-info , this is the link, and, i give you the link with privnote, the link whas delete for a next user ... Can you delete your answer with this link ? ;x )

And, when you have the info, i up the good right for this page, and, delete the 2 last messages here.

**Comment by ZerooCool** [comment]
Yes i have add mod_info : https://wiki.visionduweb.fr/index.php?title=Installer_Apache2_sur_Debian#Module_Apache2_mod_info

**Comment by tlhackque** [comment]
... which is publiclly accessible!
That is a well-known location - no point in trying to keep it secret.
I expected you to post the contents, not the link.  But OK, we can proceed.

mod_md IS loaded.
mod_watchdog IS also loaded.
you are running httpd 2.4.38 - the latest is 2.4.41

There is no configuration listed for mod_md 

Let's start with one host.  wiki.visionduweb.fr
You have this file (line numbers are from mod_info):
````
/etc/apache2/sites-enabled/wiki.visionduweb.fr.conf
  28: <VirtualHost wiki.visionduweb.fr:443>
 107:   SSLEngine on
 108:   SSLCertificateFile /etc/letsencrypt/live/wiki.visionduweb.fr/cert.pem
 109:   SSLCertificateKeyFile /etc/letsencrypt/live/wiki.visionduweb.fr/privkey.pem
 110:   SSLCertificateChainFile /etc/letsencrypt/live/wiki.visionduweb.fr/chain.pem
 112:   SSLProtocol all -SSLv2 -SSLv3
 113:   SSLHonorCipherOrder on
 114:   SSLCompression off
 115:   SSLOptions +StrictRequire
 116:   SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
    : </VirtualHost>
````
Let's try  this:

**in file:**
    `/etc/apache2/sites-enabled/wiki.visionduweb.fr.conf`
put exactly this:
````
<Mdomain wiki.visionduweb.fr>
  MDCertificateFile/etc/letsencrypt/live/wiki.visionduweb.fr/fullchain.pem
  MDCertificateKeyFile /etc/letsencrypt/live/wiki.visionduweb.fr/privkey.pem
</Mdomain>
 <VirtualHost wiki.visionduweb.fr:443>
   SSLEngine on
#   SSLCertificateFile /etc/letsencrypt/live/wiki.visionduweb.fr/cert.pem
#   SSLCertificateKeyFile /etc/letsencrypt/live/wiki.visionduweb.fr/privkey.pem
#   SSLCertificateChainFile /etc/letsencrypt/live/wiki.visionduweb.fr/chain.pem
   SSLProtocol all -SSLv2 -SSLv3
   SSLHonorCipherOrder on
   SSLCompression off
   SSLOptions +StrictRequire
   SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
 </VirtualHost>
````
and make NO other changes.
Then let's look at server-info and server-status

**Comment by ZerooCool** [comment]
Thank you. Let's go ... and ...

I can't restart apache2 if i comment this 3 line to the wiki Vhost. ( the same for all Vhost ).

**Comment by tlhackque** [comment]
> Yes i have add mod_info : https://wiki.visionduweb.fr/index.php?title=Installer_Apache2_sur_Debian#Module_Apache2_mod_info

I can't access that.  I'm OK with looking at it directly

I can't restart apache2 if i comment this 3 line to the wiki Vhost. ( the same for all Vhost ).

Not for all vhosts.  Just the one.
We will have to add `<MDomain>` blocks for the other vhosts later.
One thing at a time.

What version of mod_md?  It must be (as stefan said) at least v.2.2.0.

You've turnd off /server-info, so I can't see what you did.

**Comment by tlhackque** [comment]
Please add the 4 lines above the `<virtual host` at line 28, and comment out the 3 lines at 108-110.
Enable server-info and server-status.
No other changes.
Then, if it doesn't work, we need to see the server error log.

**Comment by ZerooCool** [comment]
Yes you can access to the wiki, server-info and server-status
( For the moment, it's open, or, closed if i restart the server. )

Ofcourse, i test only one, i have only comment 3 line ( not add MDomain or <MDomain> ) but i can't restart Apache if i comment this : 

```
<MDomain wiki.visionduweb.fr>
MDCertificateFile /etc/letsencrypt/live/wiki.visionduweb.fr/cert.pem
MDCertificateKeyFile /etc/letsencrypt/live/wiki.visionduweb.fr/privkey.pem
</Mdomain>

 <VirtualHost *:443>
   SSLEngine on
#   SSLCertificateFile /...
#   SSLCertificateKeyFile /...
#   SSLCertificateChainFile /...
```

> Version of mod_md? It must be (as stefan said) at least v.2.2.0. 

Ok i give you that later, i search how i can find the module version.
I restart the server.

**Comment by ZerooCool** [comment]
AH00526: Syntax error on line 28 of /etc/apache2/sites-enabled/wiki.visionduweb.fr.conf:
apachectl[17800]: Invalid command '<MDomain', perhaps misspelled or defined by a module not included in the server configuration
apachectl[17797]: Action 'start' failed.
apachectl[17797]: The Apache error log may have more information.

**Comment by tlhackque** [comment]
First, note that the MDCertificateFile should be, as I wrote, `fullchain.pem`, not `cert.pem`
````
<MDomain wiki.visionduweb.fr>
  MDCertificateFile/etc/letsencrypt/live/wiki.visionduweb.fr/fullchain.pem
  MDCertificateKeyFile /etc/letsencrypt/live/wiki.visionduweb.fr/privkey.pem
</MDomain>
````
The apache error log might tell us more.  

But at this point, my guess would be that you have an old version of `mod_md` - the `<Mdomain` directive syntax changed a VERY long time ago.  That may be the problem.

It looks like debian has libapache2-mod-md kits in backports with apache 2.4.41, as well as bullseye and sid.

Or you can build from source:

The latest release (made this week) is [here](https://github.com/icing/mod_md/releases/download/v2.3.2/mod_md-2.3.2.tar.gz)  

It's simple to build - usually as simple as
````
wget https://github.com/icing/mod_md/releases/download/v2.3.2/mod_md-2.3.2.tar.gz
tar -xzf mod_md-2.3.2.tar.gz
cd mod_md-2.3.2
./configure && make && make install
````
You need to install httpd-dev, libcurl-dev, and libjansson -dev first.

**Comment by tlhackque** [comment]
> i search how i can find the module version.
> But, i don't found how to find that.

`dpkg -s  <package>` or `aptitude versions <package>`

`<package>` is probably `libapache2-mod-md` - but I don't use it on Debian.

**Comment by ZerooCool** [comment]
Really nothing in the error.log

I have read for apache-dev but i have test 3 day ago, and, depends are not correct, then i need waiting, or, using debian testing. It's not really my objectif with my server stable, at this time.

Stable but not working for all, sorry for that.
Debian Buster 10 stable, KO for this test.
Then we make a pause for that.

We can test later, a few days or weeks.

```
sudo dpkg -l | grep libapache2
ii  libapache2-mod-php7.3              7.3.14-1~deb10u1                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libapache2-mod-security2           2.9.3-1+b1                          amd64        Tighten web applications security for Apache

ii  apache2                            2.4.38-3+deb10u3                    amd64        Apache HTTP Server
ii  apache2-bin                        2.4.38-3+deb10u3                    amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                       2.4.38-3+deb10u3                    all          Apache HTTP Server (common files)
ii  apache2-utils                      2.4.38-3+deb10u3                    amd64        Apache HTTP Server (utility programs for web servers)
```

**Comment by tlhackque** [comment]
Sorry to arrive at an unsatisfactory answer.

You can always use my first answer until Debian catches up - the `openssl` command line :-(

I hope that you will have better luck with `mod_md` when you are able to update.

It's pretty late in France - time for you to go home!
