### ISSUE TITLE
tls-alpn-01 challenges fail due to "random" keyspec used for responses

### ISSUE THREAD

**Issue by tlhackque** [icing/mod_md#200]
`md_acme_order_authz_respond` in `md_acme_orde.cr` chooses the first key specification named in `MDPrivateKeys` to be used for signing the `acme-tls/1` response certificate.

In theory, the validator should not require a signature, but according to the `draft-ietf-acme-tls-alpn-07` section 4, MAY refuse to accept a reponse that is not properly signed.

The problem with the current `mod_md` implementation is that the use may pick a set of key types for his certificates where the first one is not known to the CA's validator.  The list of acceptable signature types for a CA doesn't appear in the directory, so `mod_md` has no sure way to choose.

For now, RSA is probably a safe bet, and it's probably listed first in most configurations...

`mod_md` should probably have (yet another) configuration directive that is the key type for `acme-tls/1` response certificates.  It should be per-CA, and default to RSA 2048 - which is common.  There is no security implication as the contents of the response certificate are signed.  It just needs to be signed with something that a CA that requires a signature will accept.

**Comment by tlhackque** [comment]
And, I can now confirm that this is an actual operational issue.  After a **lot** of debugging (it took a day to rule everything else out):

If the first `MDPrivateKeys` specifier is `RSA 4096`, LE will reject `tls-apln-01` validation certificate` with the error:
````
[Thu Mar 19 16:09:36.116000 2020] [md:error] [pid 599340:tid 139864731019008] (22)Invalid argument: AH10056: processing wikiworld.li
tts.net: Incorrect validation certificate for tls-alpn-01 challenge. Missing acmeValidationV1 extension.
````
Worse, it will keep retrying...as frequently as 2x/min.

Work-around:  Use a smaller key.  RSA 2048 works.

Fix:
I'll come up with a patch and add it to my pull request later today.

Detail:
````
[Thu Mar 19 16:09:36.104918 2020] [md:error] [pid 599340:tid 139864731019008] ACME server authz: challenge 'invalid' for wikiworld.l
itts.net at https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/44567922. Exact response was: {"identifier":{"type":"dns","va
lue":"wikiworld.litts.net"},"status":"invalid","expires":"2020-03-26T20:08:54Z","challenges":[{"type":"tls-alpn-01","status":"invali
d","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"Incorrect validation certificate for tls-alpn-01 challenge. M
issing acmeValidationV1 extension.","status":403},"url":"https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/44567922/UhYA6w"
,"token":"yC55HQ8n0mNFy1pdBKXBE-qOhqGrGBzVUQW-MOz4r5M","validationRecord":[{"hostname":"wikiworld.litts.net","port":"443","addresses
Resolved":["96.233.62.58","2001:470:8f95:941::81"],"addressUsed":"2001:470:8f95:941::81"}]}]}
````

**Comment by tlhackque** [comment]
Well, curiouser and curiouser.

The LE Boulder people looked in their logs, and they say we're sending the fallback certificate.

That was my first thought - but all the logging I added said that wasn't the case.

I'm continuing to investigate now that we know what their logs say we sent....

**Comment by icing** [comment]
I am rather offline this week (as you might have noticed), but will have time again next week,

**Comment by tlhackque** [comment]
No problem.  It' been an interesting week.

I now have a network trace from our end showing mod_md sending the wrong cert, and a functional trace saying we did everything right, including writing the cert that we should to disk at the time we handed it to OpenSSL.  So I ought to be able to figure this one out... once I'm awake.  I stopped around 3AM local time...

It would be helpful if you could make a decision on the EnvVar situation.

Have a good weekend.

**Comment by tlhackque** [comment]
The problem is well understood, and iinvolves aspects of `mod_md`, `mod_ssl`, and `OpenSSL`..

The issue is that when `mod_md` was updated to support dual certificates (e.g. simulataneous RSA & EC), we thought it was OK for the validation certificate to stick with one key type. 

When two certificates are configured and no certificate from the CA is available, `mod_md` creates and preloads two "fallback certificates".

These are replaced when the CA certificates issue.

When a tls-alpn-01 challenge comes in, a validation response certificate is created and loaded.

Unfortunately due to the way `OpenSSL` handles certificate replacement, it displaces only **one** of the fallback certificates.  It treats EC, RSA, and DSA certificates independently.  If told to replace certificate (and/or key), it looks at the type of the new cert, and replaces any currently loaded certificate of the same type.  It leaves any certificates of other types alone.

Thus, depending on how the TLS negotiation turns out, the CA receives either the validation response, or the remaining fallback certificate. That depends on configuration of cipher preferences on both sides.  It's that which made it appear that certificate size was involved - it isn't.

Due to the way interfaces are defined between `mod_md`, `mod_ssl`, and `OpenSSL`, while the fix is conceptually simple, it's tricky to implement so that all combinations of versions will do something reaasonable.  The sticking point is that while it's possible to pass a list of certificates & keys for fallback and regular operation, the interface for supplying a validation certificate can only pass one pair.

It looks like supporting `tls-apln-01` with more than one certificate will require a patch for `mod_ssl` - I'm trying to arrange things so that the patched `mod_ssl` works with the "old" `mod_md`, and so the unpatched `mod_ssl` supports a single installed certificate (as today).

**Comment by tlhackque** [comment]
I am still chasing a case where `md_store_fs` is using the single cert filenames. Afraid fix will ripple upwards.

That, and some strange responses from LE-staging (perhaps quota?) have limited testing the above commit.  Testing with `s_client` and `wireshark` say it works.  We should synchronize efforts when you're back.
More later.

**Comment by icing** [comment]
Ah, now I understand the issue with challenge certificates for all key types. Hmm, the term "can or worms" comes to mind.

**Comment by icing** [comment]
To summarize what happens during an `tls-alpn-01` challenge:

 1. the SNI selects the vhost settings, e.g. ciphers and certificates
 1. the ALPN switches protocol to `acme-tls-1`. At this point, the modules knows that the connection is an ACME challenge
 1. mod_ssl needs to `use` the challenge certificates and override all certs loaded by SNI already.

Since, there seems to no way to get rid if certificats already installed in a `SSL*`, we need to load
as many pkey type challenge certificates as were already installed.

Urgs.

**Comment by tlhackque** [comment]
Exactly.  (What happens first is that we've installed the fallback certs for both ciphers,  That's why we have certs to override,)

I committed code that does exactly that.  The issue with mod_ssl is that the old interface doesn't allow supplying more than one validation cert.

You should be able to merge my current master.

**Comment by icing** [comment]
Solution was merged.
