### ISSUE TITLE
MDContactEmail

### ISSUE THREAD

**Issue by Rikk** [icing/mod_md#203]
Hi. I see MDContactEmail was added Feb 10. My server Ubuntu Focal 20.04 (dev) includes Apache/2.4.41 (built March 05). Apache doc (http://httpd.apache.org/docs/2.4/mod/mod_md.html) lists MDContactEmail there, but doesn't specify what version supports it. Readme on this repo also is not precise. Seems not enabled in 2.4.41 yet. Is it enabled only on trunk builds higher than 2.4.41?

Relying on ServerAdmin for each vhost is a bad idea.

```
AH00526: Syntax error on line 1 of /etc/apache2/sites-enabled/000-default.conf:
Invalid command 'MDContactEmail', perhaps misspelled or defined by a module not included in the server configuration
Action 'graceful' failed.
```

**Comment by icing** [comment]
It will be in the next release of httpd, probably 2.4.43. Alternatively, you may build the module from a release here against your 2.4.41 server.
