### ISSUE TITLE
Infinite retries with bad request...CA claims missing POST-as-GET

### ISSUE THREAD

**Issue by tlhackque** [icing/mod_md#204]
As previously noted, I've seen infinite retries and their consequences while testing.
I believe I've reduced this to a simple test case.  It reproduces with pebble - but I first saw it with LE, where the retries consumed rate-limiting quota....

The bottom line is that `mod_md` is retrying fatal errors forever.

I am not 100% sure what exactly triggers this error - though this configuration, run with a non-existent MDStoreDir, does.

Can you look into & fix the logic in drive so that it both avoids the error and handles the errors more gracefully?  I'd go further, but you know this logic, and I'm trying to reach another project milestone.

It should be stopping on a fatal error, and I think the reporting could be improved.  Note that the `POST-as-GET` error that I decoded in the data stream does not appear in the log as plaintext...it should.  I'm not sure if that error is real, or if it is the consequence of something else.

Here's the reproducer:

Configure a normal SLL vhost - no ACME certs.  It's not actually involved, but it gives httpd something to do.  Then see the `mod_md` configuration below.

Note that `test47.litts.info` does not exist in the DNS.  In my case, I'm testing a new branch of `mod_md` & wanted lots of jobs with certificates/sans  - I wanted the errors .  It real life, it could simply be a typo in specifying a SAN.

In any case, that seems to be sufficient to cause the misbehavior.  It will also happen if you use a hostname that does exist in DNS, but is not served by the `mod_md` instance of httpd.

Specifically:
 - We get a 400 error from the CA, which complains that we should be doing POST-AS-GET to retrieve account data.  (But this should be a 405 according to the RFC?)
 - md_acme reports "(22) Invalid argument, req sent
 - md_result says "while selecting account..." (but no detail)
 - md_acme_drive  says "retrieving rsa certificate chain"
 - md_result says "Internal error" ... "asked to retrieve chain, but no order in context"
 - md_reg repeats this error
 - Finally, we schedule a retry.
Retries will fail - on an internal error, we should stop trying and ask for help
Instead, eventually mod_md_drive decides to purge the staging area...

`mod_md` config, simplified:

````
LoadModule watchdog_module modules/mod_watchdog.so
LoadModule md_module modules/mod_md.so
LogLevel trace6
LogLevel md:trace6
MDStoreDir md-badname
<MDomain test47.litts.info>
        MDCertificateAuthority https://127.0.0.1:14000/dir
        MDMembers manual
        MDRenewMode always
        MDMember test47.litts.info
</Mdomain>
    MDCertificateProtocol "ACME"
    MDCertificateAgreement "accepted"
    MDPortMap http:-
    MDCAChallenges tls-alpn-01
    Protocols h2 http/1.1 acme-tls/1
    MDMustStaple on
    MDPrivateKeys RSA 4096 P-384
    MDRenewMode auto
    MDStapling on
    MDStapleOthers on
    MDServerStatus on
````
pebble is run out of the box, like this:

````bash
#!/bin/bash
cd /testing/kits/go/src/github.com/letsencrypt/pebble || exit 2
cat test/certs/pebble.minica.pem /etc/pki/tls/certs/ca-bundle.crt >test/certs/test-ca-bundle.pem
chcon unconfined_u:object_r:cert_t:s0 test/certs/test-ca-bundle.pem
SSL_CERT_FILE=test/certs/test-ca-bundle.pem PEBBLE_VA_ALWAYS_VALID=1 pebble -config ./test/config/pebble-config.json
````

Here are (I think) the key points:

````
 req[2]: header --> POST /my-account/2
 HTTP/2\r\nHost: 127.0.0.1:14000\r\nUser-Agent: Apache/2.4.41 mod_md/2.3.2-git\r\nAccept: */*\r\nContent-Type: application/jose+json\r\nContent-Length: 756\r\n\r\ninfo We are completely uploaded and fine\n
[Wed Apr 01 13:58:29.598122 2020] [md:trace4] [pid 895013:tid 139763535705856] md_curl.c(207): req[2]: header <-- HTTP/2 400 \r\n
[Wed Apr 01 13:58:29.598830 2020] [md:trace4] [pid 895013:tid 139763535705856] md_curl.c(207): req[2]: header <-- cache-control: public, max-age=0, no-cache\r\n
[Wed Apr 01 13:58:29.599751 2020] [md:trace4] [pid 895013:tid 139763535705856] md_curl.c(207): req[2]: header <-- content-type: application/problem+json; charset=utf-8\r\n
[Wed Apr 01 13:58:29.600605 2020] [md:trace4] [pid 895013:tid 139763535705856] md_curl.c(207): req[2]: header <-- link: <https://127.0.0.1:14000/dir>;rel="index"\r\n
[Wed Apr 01 13:58:29.601246 2020] [md:trace4] [pid 895013:tid 139763535705856] md_curl.c(207): req[2]: header <-- replay-nonce: tkGfxYTN0GVC_BggUhyWGg\r\n
[Wed Apr 01 13:58:29.601411 2020] [md:trace4] [pid 895013:tid 139763535705856] md_curl.c(207): req[2]: header <-- content-length: 161\r\n
[Wed Apr 01 13:58:29.601638 2020] [md:trace4] [pid 895013:tid 139763535705856] md_curl.c(207): req[2]: header <-- date: Wed, 01 Apr 2020 17:58:29 GMT\r\n
[Wed Apr 01 13:58:29.601857 2020] [md:trace4] [pid 895013:tid 139763535705856] md_curl.c(207): req[2]: header <-- \r\n
[Wed Apr 01 13:58:29.603259 2020] [md:trace4] [pid 895013:tid 139763535705856] md_curl.c(224): req[2]: data <-- 161 bytes
[Wed Apr 01 13:58:29.603972 2020] [md:trace5] [pid 895013:tid 139763535705856] md_curl.c(232): req[2]: data(hex) <-- 7b0a2020202274797065223a202275726e3a696574663a706172616d733a61636d653a6572726f723a6d616c666f726d6564222c0a2020202264657461696c223a202255736520504f53542d61732d47455420746f207265747269657665206163636f756e74206461746120696e7374656164206f6620646f696e6720616e20656d70747920757064617465222c0a20202022737461747573223a203430300a7d
--- perl -e'my $x = ""; while(<STDIN>){chomp; $x .= $_;} $x =~ s/(..)/chr(eval "0x$1")/ge;print "$x\n"'
{
   "type": "urn:ietf:params:acme:error:malformed",
   "detail": "Use POST-as-GET to retrieve account data instead of doing an empty update",
   "status": 400
}
---
[Wed Apr 01 13:58:29.605972 2020] [md:trace1] [pid 895013:tid 139763535705856] md_curl.c(399): request <-- 400
[Wed Apr 01 13:58:29.606740 2020] [md:trace1] [pid 895013:tid 139763535705856] md_acme.c(294): response: 400
[Wed Apr 01 13:58:29.607672 2020] [md:trace3] [pid 895013:tid 139763535705856] md_curl.c(363): (22)Invalid argument: req[2] fire callbacks
[Wed Apr 01 13:58:29.611038 2020] [md:debug] [pid 895013:tid 139763535705856] md_acme.c(435): (22)Invalid argument: req sent
[Wed Apr 01 13:58:29.611829 2020] [md:debug] [pid 895013:tid 139763535705856] md_result.c(254): md[test47.litts.info] while[Selecting account to use for test47.litts.info]
[Wed Apr 01 13:58:29.612725 2020] [md:debug] [pid 895013:tid 139763535705856] md_acme_drive.c(756): test47.litts.info: retrieving rsa certificate chain
[Wed Apr 01 13:58:29.613479 2020] [md:error] [pid 895013:tid 139763535705856] (20014)Internal error (specific information not available): test47.litts.info: asked to retrieve chain, but no order in context
[Wed Apr 01 13:58:29.614253 2020] [md:debug] [pid 895013:tid 139763535705856] md_result.c(254): (20014)Internal error (specific information not available): md[test47.litts.info] while[Retrieving rsa certificate chain for test47.litts.info] detail[Unable to retrieve rsa certificate chain.]
[Wed Apr 01 13:58:29.614929 2020] [md:debug] [pid 895013:tid 139763535705856] md_reg.c(1117): (20014)Internal error (specific information not available): test47.litts.info: staging done
[Wed Apr 01 13:58:29.615692 2020] [md:error] [pid 895013:tid 139763535705856] (20014)Internal error (specific information not available): AH10056: processing test47.litts.info: Unable to retrieve rsa certificate chain.
[Wed Apr 01 13:58:29.616240 2020] [md:info] [pid 895013:tid 139763535705856] AH10057: test47.litts.info: encountered error for the 9. time, next run in 21 minutes 19 seconds
````
Complete log: [pag_error_loop.zip](https://github.com/icing/mod_md/files/4417143/pag_error_loop.zip)

**Comment by icing** [comment]
I will look into this as soon as I find the time. Busy on paying customers right now...you know how it is. ;)

**Comment by tlhackque** [comment]
Understood.  I'm running behind too - but making forward progress.

**Comment by tlhackque** [comment]
I have solved two of the issues reported here.
 - The error responses were not being processed properly due to a parsing error
    - [this commit](https://github.com/tlhackque/mod_md/commit/4d9a42acdc2a76baca2792a689c080127fa31890) fixes.  Pebble includes a `;charset` parameter on the `Content-Type` header which was not allowed-for.  Thus, the error was neither reported nor handled correctly.
 - `POST-AS-GET` was intended, but not correctly issued. 
   - [another commit](https://github.com/tlhackque/mod_md/commit/ecdc8bc8fdac8bf0d0d7770e82cce9641431e153) fixes.  An empty JSON object was being sent instead of an empty body.

I don't know whether LE was doing the same thing earlier - those logs have been purged.  It's possible that LE tolerates the invalid `POST-AS-GET`... But these are definite bugs.

I am still investigating - will open a pull request later.

**Comment by icing** [comment]
I think with the recent test suite success against pebble, this is completely resolved.
