### ISSUE TITLE
Autodetect should not select V1 API in preference to V2

### ISSUE THREAD

**Issue by tlhackque** [icing/mod_md#207]
I happened to notice that the `buypass.com` directory provides V1 and V2 APIs in a single consolidated directory.

The `mod_md` logic to autodetect the API version selects V1 in this case.  This is not desirable.  V2 is newer, standard, and offers more features than the proprietary V1 API.  LE has deprecated the V1 API and is planning to retire it.

[This commit](https://github.com/tlhackque/mod_md/commit/ff94db1427c572507cc591ebfba78a53dcda7fd2) selects V2 in preference to V1.

[The buypass.com directory is here](https://api.test4.buypass.no/acme/directory)

I don't know much about the `buypass.com` service - this is a technicial note.  However, since `mod_md` supports ACME - not just LE - it should handle this case.  

`mod_md` should probably include other ACME providers in its testing.  From a quick look at this provider's forum, it seems that they are not using Boulder for their V2 API, and are making different implementation choices.

**Comment by tlhackque** [comment]
This also creates a corner case - it's not possible to force use of a particular version in such a (mult-version) directory.  For now, we will just use V2.

As a lower priority, I'm considering adding an argument to `MDCertificateProtocol` for that - e.g. `MDCertificateProtocol ACME [auto|1|2]`, with the default `auto`.  I don't see any reason to force V1 today (except perhaps for testing this case), but who knows what a V3 might bring.

**Comment by icing** [comment]
Would not make that configurable. If someone offers v2, we should take it.

**Comment by tlhackque** [comment]
> If someone offers v2, we should take it.

Today, that's the right **technical** answer, of course.  And I think "the latest" s probably the right long-term **default**.

But there may be other reasons for chosing a version.  For example, suppose a CA offers different products - e.g. free certificates with V1, but requires payment for V2.  Or suppose V3 drops wildcard (or RSA) support and a user needs time to adapt. Or...

I don't think these particular scenarios are likely - but then we didn't anticipate a multi-version directory deployment.  I tend to assume that the future will be different...

Making it configurable is not a high priority, but I'm not convinced that we should rule it out.

**Comment by icing** [comment]
I ripped out the support for ACMEv1. This question becomes purely theoretical until a new ACME version arrives that is not backward compatible. I work on something else in the meantime. ;-)
