### ISSUE TITLE
purge staging / perm denied

### ISSUE THREAD

**Issue by JohnyTee** [icing/mod_md#211]
Hello.
I am trying to enable  apache to handle certificates via md. I cant figure it out  what is the reason for this permission issue.
I applied 755 for accounts, challanges and staging folder.

[root@localhost md]# ll
total 4
drwxr-xr-x. 2 root     root   6 Apr 27 07:22 accounts
drwxr-xr-x. 2 http-web root   6 Apr 27 07:22 challenges
drwx------. 3 root     root  27 Apr 27 07:22 domains
-rw-------. 1 root     root 116 Apr 27 07:22 md_store.json
drwxr-xr-x. 2 http-web root   6 Apr 27 13:45 staging

--------------------------------------------------------------------------------------
Mon Apr 27 15:01:07.291745 2020] [md:debug] [pid 5135:tid 140153905051392] md_acme.c(438): req sent
  57595 [Mon Apr 27 15:01:07.291755 2020] [md:info] [pid 5135:tid 140153905051392] domain: setup staging
  57596 [Mon Apr 27 15:01:07.291769 2020] [md:debug] [pid 5135:tid 140153905051392] md_store_fs.c(688): (13)Permission denied: purge staging/domain (/etc/httpd/state/md/staging/domain)
 57597 [Mon Apr 27 15:01:07.291788 2020] [md:trace3] [pid 5135:tid 140153905051392] md_store_fs.c(498): mk_group_dir 4 (null)
  57598 [Mon Apr 27 15:01:07.291792 2020] [md:debug] [pid 5135:tid 140153905051392] md_acme_drive.c(754): (13)Permission denied: domain: save   57598 staged md
  57599 [Mon Apr 27 15:01:07.291809 2020] [md:debug] [pid 5135:tid 140153905051392] md_acme_drive.c(906): (13)Permission denied: domain: ACME,  57599  ACME staging
  57600 [Mon Apr 27 15:01:07.291812 2020] [md:debug] [pid 5135:tid 140153905051392] md_reg.c(909): (13)Permission denied: domain: staging done

**Comment by icing** [comment]
It looks as if the user running the httpd child processes is not what you or the module think it is. On one of my debian servers, it looks like this:

```
drwxr-xr-x   7 root     root 4096 Sep 30  2019 accounts
drwx------ 144 root     root 4096 Apr 17 00:00 archive
drwxr-xr-x   2 www-data root 4096 Apr 16 00:01 challenges
drwx------  10 root     root 4096 Apr 17 00:00 domains
-rw-------   1 root     root 1135 Sep 13  2017 fallback-cert.pem
-rw-------   1 root     root 1874 Sep 13  2017 fallback-privkey.pem
-rw-------   1 root     root   56 Oct 20  2017 httpd.json
-rw-------   1 root     root  116 Sep 15  2017 md_store.json
drwxr-xr-x   7 www-data root 4096 Nov  7 13:28 ocsp
drwxr-xr-x   2 www-data root 4096 Apr 17 00:00 staging
drwx------   9 root     root 4096 Apr 17 00:00 tmp
```

On what OS are you running?

**Comment by JohnyTee** [comment]
Sure, its centos8.

**Comment by tlhackque** [comment]
One thing that will cause this is SeLinux.

Try setenforce 0.  If that makes things, work there is a policy that works for me in `contrib/selinux`.  It's not elegant, but it does work.  See the `README` there.

If this is the case, have your distribution update their SeLinux policy.

Other things you can do are to move the `MDStoreDir` to a place writable by `httpd` and/or label 
 (with `chcon`) the `MDStoreDir` as something that `httpd` can write.

Also, note that once `mod_md` has tried to setup a directory tree, it doesn't try to reset the permissions again thereafter.  If interrupted by SeLinux (or anything else), it can leave the directory tree in a state where the permissions are wrong.  So you may have to either manually set the permissions/ownership - or just delete the tree once SeLinux is properly setup and let `mod_md` do everything.

**Comment by JohnyTee** [comment]
I think there seems to be issue with depricated protocol Acme v1 as I am getting connection from Acme-V01 server. I noticed that since new year new connections arent allowed,

So I added MDCertificateAuthority https://acme-staging-v02.api.letsencrypt.org/directory after MDomain to test it.
But I am getting invalid argument in log file.
 (22)Invalid argument: domain: setup ACME(https://acme-staging-v02.api.letsencrypt.org/directory)

**Comment by icing** [comment]
Which version of mod_md are you running?

**Comment by JohnyTee** [comment]
Hi, 
version below:
 yum list installed | grep mod_md
mod_md.x86_64                               2.4.37-16.module_el8.1.0+256+ae790463             @AppStream

**Comment by tlhackque** [comment]
@JohnyTee: 

1) Is your permissions issue resolved?  If so, recording what you did will help others.
2) The version # you supplied appears to be for `httpd` as packaged & patched by redhat.  @icing needs the `mod_md` version.  Look in the log for something like:
````
[md:info] [pid 1606033:tid 139962314723648]  AH10071: mod_md (v2.3.3), initializing...
````
The "Invalid argument" message can result from a number of conditions.  Set `LogLevel md:trace6` for more detail.

Please show the whole `mod_md` configuration stanza(s).

Also, when you have a new problem, please open a new issue... this is no longer about permissions.

**Comment by JohnyTee** [comment]
Sure I will open new topic.
