### ISSUE TITLE
invalid args

### ISSUE THREAD

**Issue by JohnyTee** [icing/mod_md#215]
Hi,
I am trying to set mod_md to work with lets encrypt. I found that I have to use Acmev2.
Current version is 
[Wed May 06 06:39:07.091402 2020] [md:info] [pid 2576:tid 139735152281856] AH10071: mod_md (v1.1.16), initializing...

I think I am connected to acme, but there seems to be something incorrect (added two httpd logs)
MD configuration is in ssl.conf.

[ssl.conf.txt](https://github.com/icing/mod_md/files/4585077/ssl.conf.txt)
[error_log.txt](https://github.com/icing/mod_md/files/4585066/error_log.txt)
[ssl_error_log.txt](https://github.com/icing/mod_md/files/4585067/ssl_error_log.txt)

.

**Comment by icing** [comment]
The module versions 1.x only support ACMEv1. You (or your distributor need an update). For ACMEv2 you will require a 2.x version of this module, preferably v2.2.7, the latest release and the one distributed with Apache httpd 2.4.43.
