### ISSUE TITLE
failure when finalize response does not include Location header

### ISSUE THREAD

**Issue by frasertweedale** [icing/mod_md#216]
RFC 8555 example finalize (success) response includes a `Location` header containing the URL of the order resource.  But the RFC does not state that this header is required, and intuitively it is not required, because the context of having POSTed to the finalize resource implies that the order URI is (or was at some point) known, and furthermore the order data in the finalize response contains the URI to the certificate resource.

Nevertheless, mod_md fails when the ACME server does not include a `Location` header in the finalize response.  This is no doubt an artifact of the older (pre-RFC draft) protocol where the `Location` header pointed to the issued certificate.

Other clients (well, Certbot at least), work fine when the finalize response does not include a Location header.

**Expected behaviour:** when speaking ACME v2, mod_md should not require the `Location` header in the response.

**Comment by tlhackque** [comment]
I believe I've seen this as well, but it's masked by some other issues I've been chasing with non-Boulder servers.

Is there an open server with this behavior that we can test against?

**Comment by frasertweedale** [comment]
@tlhackque no open server that I know of.  I can see about setting one up.
