### ISSUE TITLE
Unable to create certificate on windows

### ISSUE THREAD

**Issue by sridharb1** [icing/mod_md#220]
I am using mod_md v2.2.7 from Apache 2.4.43 from apachelounge.com.

I am trying to configure a couple of hosts. But I am getting the following errors.

Apache log:
[Thu Jun 25 20:26:05.131666 2020] [md:error] [pid 12916:tid 4] ACME server authz: challenge 'invalid' for vidyasridhar.no-ip.org at https://acme-v02.api.letsencrypt.org/acme/authz-v3/5471419350. Exact response was: {"identifier":{"type":"dns","value":"vidyasridhar.no-ip.org"},"status":"invalid","expires":"2020-07-02T14:55:58Z","challenges":[{"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"Invalid response from http://vidyasridhar.no-ip.org/.well-known/acme-challenge/xDZiHoccWDQV26wxi6gqk4mNI0rplRjWhhbyUujj9zA [210.18.181.30]: \\"                                              <HTML>\\\\n                                              <HEAD><TITLE>404 Not Found</T\\"","status":403},"url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/5471419350/qqgfcg","token":"xDZiHoccWDQV26wxi6gqk4mNI0rplRjWhhbyUujj9zA","validationRecord":[{"url":"http://vidyasridhar.no-ip.org/.well-known/acme-challenge/xDZiHoccWDQV26wxi6gqk4mNI0rplRjWhhbyUujj9zA","hostname":"vidyasridhar.no-ip.org","port":"80","addressesResolved":["210.18.181.30"],"addressUsed":"210.18.181.30"}]}]}

The same error is for another domain that I am trying to use as well, but I have not shown it because the information is simply repeated.

md-status:
[errors.txt](https://github.com/icing/mod_md/files/4832183/errors.txt)

Is it because there is already a certificate (says that it expires 2020-07-02)?

Also, how do I set the name property in the conf file? I am referring to the "name": "vidyasridhar.no-ip.org".

Thanks,
Sridhar

**Comment by icing** [comment]
Thanks for the details. As I read it, the ACME validation is not allowed to access the url `http://vidyasridhar.no-ip.org/.well-known/acme-challenge/xDZiHoccWDQV26wxi6gqk4mNI0rplRjWhhbyUujj9zA` on your server (it gets status 403 which is HTTP for `access denied`).

`mod_md` is designed to handle these resources before common user authentication happens. Do you have other security modules, such as mod_security installed or is there a proxy in front of your server that does authentication?

**Comment by icing** [comment]
The other cause could be your ISP that denies access to port 80 in general. Some are known to do so.

The alternative is to setup the TLS-ALPN authenticaton which only uses port 443. Look in the README for some how-tos.

**Comment by sridharb1** [comment]
Thank you for the prompt response.

I do not have mod_security. I am able to access http://vidyasridhar.no-ip.org/.well-known/acme-challenge/

I created a test file called testfile.txt and I am able to view that.

However, what is strange is that the contents of the file is changing. It contains gYV5uJWEDjikGxVpnv4bBkzmSMfDN3y5IUnDfLdK9J0.F-rtkc_GNZ3tB9AlOOI_ZqkQWLB5hCo07q6O3-_muig which is the same content that is returned by http://vidyasridhar.no-ip.org/.well-known/acme-challenge/xDZiHoccWDQV26wxi6gqk4mNI0rplRjWhhbyUujj9zA

When I created that file, I just had 12345 for testing purposes.

What could be happening here?

BTW, I had been using win-acme before and I had gotten it to work. That's why I suspected that the certificate may still be there (says 2020-07-02) and that could be causing a problem. All this started when I wanted to add a new domain and I got the same problem with win-acme and I decided to try it with mod_md.

Thanks.

**Comment by sridharb1** [comment]
Added some more logging, but getting the same error. This is an extract from apache's error_log. Please help.

[error_log.txt](https://github.com/icing/mod_md/files/4835346/error_log.txt)

**Comment by icing** [comment]
If you experience the same problem with 2 acme clients, as I understand you, the problem is probably not in a particular  client. General acme problems are best discussed at https://community.letsencrypt.org where there are several very helpful people with lots of experience.

**Comment by sridharb1** [comment]
Yes, same problem with multiple clients (win-acme, certbot and now, mod_md). Will try that forum as you suggested. Thanks.

**Comment by sridharb1** [comment]
I wanted to note that this turned out to be a problem with the ISP modem running a webserver on port 80 so that "external" clients couldn't navigate to the web server. This was not "visibile" because when I requested the same URL from "internal" machines, I was getting the correct result as the internal router was sending the request correctly to the webserver without touching the modem (which acted as an external gateway).

**Comment by icing** [comment]
You're welcome! And thanks for the follow up here.
