### ISSUE TITLE
After Apache upgrade: MDPortMap is not allowed inside an '<MdomainSet' Context

### ISSUE THREAD

**Issue by ingarb** [icing/mod_md#221]
Hi! After trying to upgrade my Apache to a newer version I am unable to start Apache, and it gives me this error:

AH00526: Syntax error on line 130 of C:/Apache24.1/conf/extra/httpd-ssl.conf:
MDPortMap is not allowed inside an '<MDomainSet' context

I have been using this for quite a while and it's working fine, but I would like to update my Apache server to the latest version.

I really need each MDomain to have different port mappings. For example domain1.com is running locally on port 9000/9001 and domain2.com is running on 9002(https)/9003(http). So I used the MDPortMap directive inside each MdomainSet and was very happy.

Now it seems I have to change something, but I can't put the "MDPortmap" outside the MDomainSet  as each MDomain needs to have different ports configured.

Any help is appreciated, thank you.

**Comment by icing** [comment]
`MDPortmap` always was a global configuration setting. But earlier versions did not check that it was only used as such.

`MDPortmap` helps the module to find out how your Apache can be reached by Lets Encrypt. It then can decide which method to use for obtaining certificates. It helps when you have one interface to the outside world, but use non-standard ports. Behind a firewall, for example.

Ultimately, you can serve your domains on any interface or port you like. That does not matter with `mod_md`. What matters is how the Lets Encrypt (LE) servers can talk to a domain of yours.

LE uses either port 80 (challenge type `http-01`) or port 443 (challenge type `tls-alpn-01`). Or, it can use `dns-01` and just talk to the DNS server(s) of your domain names - but we can leave that out for now.

If all your domains you want certificates for are reachable via `http:` (for LE), simply configure globally:

```
MDCAChallenges http-01
```

If you have a domain `domain1.com` where you *know* that LE can connect via `https:`, you can simple configure:

```
<MDomain domain1.com>
  MDCAChallenges tls-alpn-01
</MDomain>
```

However, `MDPortmap` is not enough in every possible Apache setup. Apache offers many, many ways to configure it. The module is sometimes not smart enough to figure out things on its own. The admin then needs to configure [MDCAChallenges](https://github.com/icing/mod_md#mdcachallenges) for MDomains.

**Comment by icing** [comment]
Does this help?

**Comment by ingarb** [comment]
Hi! Thank you for your help (again).

Yes, this helps.

In fact, even with sites running on different local ports (mapped to different public IPs) it works out of the box after I just removed the "MDPortmap setting on each MDomainSet.
