### ISSUE TITLE
FeatureReq: Add more complete RFC support (Support for External Account Binding)

### ISSUE THREAD

**Issue by Bjorn-H** [icing/mod_md#226]
Hi,

There are functions that are missing to be able to use external CA's.

This is used by the CA we are using:
7.3.4.  External Account Binding
This allows binding the certificates to a specific predefined CA account.

But adding so it is fully RFC8555 compliant would be nice. 

This is maybe the most attractive ACME option i have found, but is currently unusable for us.

/BjornH

**Comment by commonism** [comment]
Support for External Account Binding is important.

Geant moved from DigiCert to Sectigo in 2020.
Now there is a lot (thousands) of education facilities in need for EAB in order to use ACME.

https://wiki.geant.org/display/TCSNT/TCS+Participants+Sectigo
https://wiki.surfnet.nl/display/SCERTS/ACME

Could you adjust the feature requests subject to include "Support for External Account Binding"?

**Comment by icing** [comment]
I currently have no plans to add that feature. If someone is offering a PR, I might take it in. The biggest obstacle I see is that there are no test servers and such an extension will be painful to maintain.

**Comment by cpu** [comment]
> The biggest obstacle I see is that there are no test servers 

@icing You could use [Pebble](https://github.com/letsencrypt/pebble/pull/288) for this part :-)

**Comment by icing** [comment]
Ah! Thanks for the link, will have a look. Had Pebble on my list for some time, maybe when I get bored during the holidays... \o/

**Comment by Sectigo-MarcW** [comment]
@icing - Would you be open to discussing this project? We may be willing to fund the effort.  Hope to hear from you.  Thanks.

marc.williams@sectigo.com

**Comment by uschwarz** [comment]
My (limited) understanding of EAB is that it's only performed when creating the account, so in the interim, I _guess_ it's possible to do the initial registration with some other ACME client and create a fake account.json from outside `mod_md`? 
(I'm still in the "what files get put where and why" stage, so take this with a grain of salt. It looks easier than building an ACME proxy that takes its EAB data from someplace else somehow, like the CA endpoint URI, and passes everything through other than register, which it signs with the EAB data. Neither is more than a disgusting stopgap hack until there's EAB support in `mod_md` itself.)

**Comment by commonism** [comment]
to my experience, mod_md does not use a single/static account.
the acme eab proxy you mentioned already exists:
https://github.com/noahkw/acmetk.git & https://acmetk.readthedocs.io/en/latest/index.html

**Comment by icing** [comment]
FYI: I'll be working on EAB support in the coming weeks.

**Comment by icing** [comment]
First release with experimental EAB support: https://github.com/icing/mod_md/releases/tag/v2.4.8

**Comment by icing** [comment]
EAB support has also landed in Apache 2.4.52 last year. Closing this. Thanks for all the help.
