### ISSUE TITLE
mod_md fails badly when domainname is >64 characters

### ISSUE THREAD

**Issue by afcady** [icing/mod_md#227]
If you try, from a fresh `MDStoreDir`, to create a certificate for a set of domain names that are all over 64 chars long (resulting in a `CN` field of >64 characters), Let's Encrypt refuses to sign it, and `mod_md` keeps making new accounts and sending new  CSRs (with the same problem), causing the server to become rate-limited by IP for new account creation.

This is related to #222 -- here, as there, `mod_md` should understand that retrying is hopeless.  (Arguably, it shouldn't even send the CSR if LE would reject it; but regardless, after LE _does_ reject it, `mod_me` should not retry.)

Also, it shouldn't even be retrying account creation if that worked.

It should be possible eventually, or maybe it is right now, to make the >64 case actually work -- by creating a CSR that leaves the `CN` field  off entirely.  See https://github.com/letsencrypt/boulder/issues/2093 https://github.com/letsencrypt/boulder/issues/1488 where they discuss how this is supposed to become possible in the future.

**Comment by icing** [comment]
Everything feels pretty hopeless today, but you cannot blame a little module for trying... ;)

It should be easy to make a test case for this and the solution I would have in mind is to shorten the CN. It is disregarded in today's browsers anyway.

As to when I find the time for it, I cannot say.

**Comment by afcady** [comment]
Shortening the CN won't work, because then it won't match the domain name.

**Comment by icing** [comment]
Test case and work around for domain names > 64 octets. Fixes #227.
   When the first DNS name of an MD is longer than 63 octets, the certificate
   request will not contain a CN field, but leave it up to the CA to choose one.
   Currently, Lets Encrypt looks for a shorter name in the SAN list given and
   fails the request if none is found. But it is really up to the CA (and what
   browsers/libs accept here) and may change over the years. That is why
   the decision is best made at the CA.
