### ISSUE TITLE
Please improve support for non-ACME wildcard certs

### ISSUE THREAD

**Issue by akorn** [icing/mod_md#229]
Naïvely I would assume that something like the following should work:

```
<MDomain mydomain.tld *.mydomain.tld>
   MDCertificateFile /path/to/cert
   MDCertificateKeyFile  /path/to/key
</MDomain>

<VirtualHost *:443>
  ServerName foo.mydomain.tld
  SSLEngine On
  ...
</VirtualHost>
```

But it does not: `AH02572: Failed to configure at least one certificate and key for foo.mydomain.tld:443`.

Apparently I need to enumerate all specific hosts from mydomain.tld in the `<MDomain>` line, like this:

```
<MDomain mydomain.tld *.mydomain.tld foo.mydomain.tld bar.mydomain.tld ... host9999.mydomain.tld>
   MDCertificateFile /path/to/cert
   MDCertificateKeyFile  /path/to/key
</MDomain>

<VirtualHost *:443>
  ServerName foo.mydomain.tld
  ...
</VirtualHost>
```

This is both unwieldy and counterintuitive. `*.mydomain.tld` obviously matches all specific hosts under mydomain.tld; it shouldn't be necessary to enumerate them all in `<MDomain>`. This makes adding new virtualhosts more fragile because you can't just drop a (symlink to a) file with the new virtualhost in e.g. `sites-enabled`, you also need to modify a global `<MDomain>` directive.

With `mod_ssl`, I can `Include ssl-mydomain.conf` in all my virtualhosts, including future ones; in `ssl-mydomain.conf` I can then specify `SSLCertificateFile` and `SSLCertificateKeyFile`. My first attempt with `mod_md` was the same, just with `MDCertificateFile` and `MDCertificateKeyFile`, and I was surprised to see that didn't work, because these directives were only allowed in `<MDomain>` contexts.

Ideally, I think `mod_md` should:

 * allow re-using `SSLCertificateFile` and `SSLCertificateKeyfile` directives;
 * if `MDStapleOthers` is `On`, allow the admin to specify a list of certificates (not domains!) to staple (defaulting to all);
 * not require `<MDomain>` for certificates it is not expected to renew.

**Comment by icing** [comment]
Thanks for your opinion.

In case there is any confusion: 

* you can continue to use `SSLCertificateFile` in `VirtualHost` when the host is not managed by mod_md.
 * you just have to declare one domain name in a `MDomain`. All `ServerAlias` from match VirtualHosts are auto-added.

**Comment by akorn** [comment]
Thanks for the quick reply.

> * you can continue to use `SSLCertificateFile` in `VirtualHost` when the host is not managed by mod_md.

Yes, but then `mod_md` won't be part of the SSL handshake and thus won't provide the OCSP stapling from its cache, will it?

If it will, then I think the documentation needs an example like the following one:

"Tell `mod_md` about your wildcard certificate:

```
<MDomain mydomain.tld *.mydomain.tld>
   MDCertificateFile /path/to/cert
   MDCertificateKeyFile  /path/to/key
</MDomain>
```
Enable `mod_md` stapling:
```
MDStapling on
MDStapleOthers on
```
In VirtualHosts, you can keep doing what you did with `mod_ssl`:
```
<VirtualHost *:443>
   ServerName foo.mydomain.tld
   SSLCertificateFile /path/to/cert
   SSLCertificateKeyFile  /path/to/key
</VirtualHost>
```
"
> * you just have to declare one domain name in a `MDomain`. All `ServerAlias` from match VirtualHosts are auto-added.

In one sense yes, in another sense no (see the example I gave, where I need to have all ServerNames in MDomain for mod_md to provide the certificate and key declared using MDCertificateFile/MDCertificateKeyFile to mod_ssl, even though the ServerNames match *.mydomain.tld).

**Comment by icing** [comment]
I see, you want to configure a single (static) certificate for all vhosts that match the name, instead of manually adding all names. ```ServerAlias``` names are added automatically, but your case is different.

First of all, when you have a running server with ```SSLCertificateFile...```, you only need to load mod_md and configure

```
MDStapling on
MDStapleOthers on
```

to have OCSP stapling provided by the implementation in mod_md. No need to configure and MDomain. Is that what you are looking for?

**Comment by akorn** [comment]
Yes, that's exactly what I'm looking for, and I'll try to see if it works like that later today.

The documentation led me to believe I needed to have `<MDomain>` and `MDCertificateFile`.

**Comment by akorn** [comment]
It works, thanks!

So apparently the feature is there and it's just the documentation that would benefit from improvement. Currently (as of when I filed this issue) it's not clear that `MDomain` is not needed for stapling "foreign" (not-managed-by-mod_md) certificates.
