### ISSUE TITLE
Windows crash mod_md v0.6.1 :: ServerName = ManagedDomain

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#23]
Have:
ManagedDomain domaind.nl www.domaind.nl
ServerName domaind.nl (in server config)

This gives a crash in mod_md:
Faulting application path: C:\apache24\bin\httpd.exe
Faulting module path: C:\apache24\modules\mod_md.so

Debug log:

[md:debug] [pid 7184:tid 364] mod_md.c(706): AH: initializing post config dry run
[md:debug] [pid 7184:tid 364] mod_md.c(100): AH: server seems not reachable via http: (port 80->80) and reachable via https: (port 443->444) 
[md:debug] [pid 7184:tid 364] mod_md.c(157): AH: Added MD[domaind.nl, CA=https://acme-staging.api.letsencrypt.org/directory, Proto=ACME, Agreement=https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf, Drive=1, renew=-1580777472]
[md:debug] [pid 7184:tid 364] mod_md.c(199): AH: Server www.domaind.nl:0 matches md domaind.nl (config srv[default])
[md:debug] [pid 7184:tid 364] mod_md.c(215): AH: Managed Domain domaind.nl applies to vhost www.domaind.nl:0
[md:debug] [pid 7184:tid 364] mod_md.c(222): AH: Managed Domain domaind.nl assigned server admin postmaster@domaind.nl

**Comment by icing** [comment]
Can you reproduce this with ```LogLevel md:trace2```?

**Comment by SteffenAL** [comment]
Above was already md:trace2.

**Comment by SteffenAL** [comment]
Still crash with 0.6.1

**Comment by icing** [comment]
@michael-koeller please have a look and add a test case for this. Seems that when ```ServerName _managed_domain``` is used global, e.g. outside a ```VirtualHost``` we stumble and fall.

**Comment by michael-koeller** [comment]
The described effect is reproducable for me. I'll prepare a dedicated test case.

**Comment by michael-koeller** [comment]
The issue should be solved by v0.7.0. 
@SteffenAL: Can you confirm this?

**Comment by SteffenAL** [comment]
Yes, no crash anymore. Thanks.
