### ISSUE TITLE
ACME account private key account.pem is readable by all users on the Apache server

### ISSUE THREAD

**Issue by macrotex** [icing/mod_md#230]
The account private key created is readable by all users:

```
$ ls -l /etc/apache2/md/accounts/ACME-.letsencrypt.org-0000/account.pem
-rw-r--r-- 1 root root 2654 Oct 19 09:22 /etc/apache2/md/accounts/ACME-.letsencrypt.org-0000/account.pem
```
Shouldn't read access be restricted? Otherwise any user (or process) on the server can read the account.pem private key.

The directory `domains/` has permissions set to 600. Why not set accounts to the same thing?

**Comment by icing** [comment]
It is be design, but it is also encrypted with a passphrase.

The reason for this is that the accounts key are needed to be accessed by the running httpd. That process uses, under most installations, another user id. The passphrase is stored in `md_store.json` and read at startup when the server still has privileges.

Hope that makes sense.
