### ISSUE TITLE
Timeout while looking up CAA for wrong host

### ISSUE THREAD

**Issue by erik-f** [icing/mod_md#231]
I am using mod_md with Apache 2.4.46 and I have a list of hosts in the `ServerAlias` directive where the alias is `***.****.com`.
One of these hosts is `dev.free.****.cf`. This subdomain exists, but the subdomain `free.****.cf` does not.
mod_md keeps failing with this message:
```
[Tue Nov 03 10:51:01.132025 2020] [md:error] [pid 17823] ACME server authz: challenge 'invalid' for dev.****.cf at https://acme-v02.api.letsencrypt.org/acme/authz-v3/******. Exact response was: {...}
[Tue Nov 03 10:51:01.134847 2020] [md:error] [pid 17823] (22)Invalid argument: AH10056: processing ***.****.com: DNS problem: query timed out looking up CAA for free.****.cf     
```
I removed the unformatted JSON data from the log. This is the properly formatted response:
```
{
  "identifier": {
    "type": "dns",
    "value": "dev.free.****.cf"
  },
  "status": "invalid",
  "expires": "2020-11-10T09:43:11Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "DNS problem: query timed out looking up CAA for free.****.cf",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/******************",
      "token": "FLLgPjPD9yW_NF0pdQqlDLMC7HRfRapMB9lWV_yRHug",
      "validationRecord": [
        {
          "url": "http://dev.free.****.cf/.well-known/acme-challenge/FLLgPjPD9yW_NF0pdQqlDLMC7HRfRapMB9lWV_yRHug",
          "hostname": "dev.free.****.cf",
          "port": "80",
          "addressesResolved": [
            "***.***.***.***"
          ],
          "addressUsed": "***.***.***.***"
        }
      ]
    }
  ]
}
```
So for some reason it looks for `free.****.cf` and times out (of course, this subdomain doesn't exist). The URL in `challenges.validationRecord.url` does work as expected.

**Comment by erik-f** [comment]
Okay, this happens with certbot too. I posted the question in the Let's Encrypt community.

**Comment by icing** [comment]
Let's Encrypt wants to verify that you control the domain `free.****.cf` in order to give you the certificate. It's security policy, but they can probably explain all the details to you on the community site.
