### ISSUE TITLE
Cluster race conditions

### ISSUE THREAD

**Issue by morph027** [icing/mod_md#233]
Hi!

I'm using multiple Apache2 with mod_md where the certstore is shared using NFS. This does work great in general, but sometimes there are rare race conditions when 2 or more servers are trying to renew the certs at the same time.

This is the log of an erroring server while another was successful

```
 [Fri Jan 15 07:48:30.752230 2021] [md:debug] [pid 19446:tid md_reg.c(1121): (20014)Internal error (specific information not available): example.com: staging done
 [Fri Jan 15 07:48:30.753136 2021] [md:error] [pid 19446:tid (20014)Internal error (specific information not available): AH10056: processing example.com: Unable to retrieve rsa certificate chain.
 [Fri Jan 15 07:48:30.753196 2021] [md:info] [pid 19446:tid AH10057: example.com: encountered error for the 2. time, next run in 9 seconds
 [Fri Jan 15 07:48:30.762813 2021] [md:debug] [pid 19446:tid mod_md_drive.c(219): AH10107: next run in 9 seconds
 [Fri Jan 15 07:48:32.372186 2021] [mpm_prefork:notice] [pid 19444:tid AH00169: caught SIGTERM, shutting down
 [Fri Jan 15 07:54:35.740563 2021] [md:error] [pid 19555:tid failed to load JSON file /mnt/nfs/mod_md/ssl/md_store.json: '[' or '{' expected near end of file (line 1:0)
 [Fri Jan 15 07:54:35.740832 2021] [md:error] [pid 19555:tid (22)Invalid argument: init fs store at /mnt/nfs/mod_md/ssl
 [Fri Jan 15 07:54:35.740845 2021] [md:error] [pid 19555:tid (22)Invalid argument: AH10046: setup store for /mnt/nfs/mod_md/ssl
 [Fri Jan 15 07:54:35.740850 2021] [md:error] [pid 19555:tid (22)Invalid argument: AH10072: setup md registry
AH00016: Configuration Failed
```

It would be great to either add some kind of check, if there's already a folder inside the staging directory. If so, then backoff for a small amount of random time and restart the renew process (including check if still necessary - in case the cert was renewed by another server already).

If this is too much work in the current code, you could also introduce a new event for `MDMessageCmd`, e.g. `renewing` which indicates that a renewal process is about to start. Then the user could add some logic to the script/program his or herself.

**Comment by icing** [comment]
Hmm, I see. I like the idea. MDMessageCmd or something like that could be called on a starting renewal and that a != 0 return code would indicate "no, do not renew this now".

**Comment by morph027** [comment]
Jip...exactly. It then still needs to check if the cert has been renewed by another node on it's next own cycle to pick up the changes (e.g. trigger `MDNotifyCmd`).

Unfortunately, i'm not good at coding c, so i can just help with the logic. Anyways, thanks for the quick response! :rocket:

**Comment by root360-AndreasUlm** [comment]
Hi,

I've tested some modifications concerning this issue.
With the following changes the described behaviour seems to be possible:
```
diff --git a/src/mod_md.c b/src/mod_md.c
index 5e27daf..5024316 100644
--- a/src/mod_md.c
+++ b/src/mod_md.c
@@ -141,6 +141,7 @@ typedef struct {
 } notify_rate;
 
 static notify_rate notify_rates[] = {
+    { "renewing", apr_time_from_sec(MD_SECS_PER_HOUR) }, /* once per month */
     { "renewed", apr_time_from_sec(28 * MD_SECS_PER_DAY) }, /* once per month */
     { "installed", apr_time_from_sec(MD_SECS_PER_DAY) }, /* once per day */
     { "expiring", apr_time_from_sec(MD_SECS_PER_DAY) },     /* once per day */
diff --git a/src/mod_md_drive.c b/src/mod_md_drive.c
index c45ef61..8182287 100644
--- a/src/mod_md_drive.c
+++ b/src/mod_md_drive.c
@@ -108,6 +108,14 @@ static void process_drive_job(md_renew_ctx_t *dctx, md_job_t *job, apr_pool_t *p
         ap_log_error( APLOG_MARK, APLOG_DEBUG, 0, dctx->s, APLOGNO(10052) 
                      "md(%s): state=%d, driving", job->mdomain, md->state);
 
+        rv = md_event_raise("renewing", md->name, job, result, ptemp);
+        if (APR_SUCCESS != rv) {
+                ap_log_error(APLOG_MARK, APLOG_INFO, 0, dctx->s, APLOGNO(10060)
+                             "%s: event-handler for 'renewing' event failed",
+                             job->mdomain);
+                goto expiry;
+        }
+
         if (!md_reg_should_renew(dctx->mc->reg, md, dctx->p)) {
             ap_log_error( APLOG_MARK, APLOG_DEBUG, 0, dctx->s, APLOGNO(10053) 
                          "md(%s): no need to renew", job->mdomain);
```

@icing What do you think about this?
If you are fine with it, I could create a PR.

Regards,
Andreas

**Comment by morph027** [comment]
@root360-AndreasUlm thank you. Just tested the patch and it's working :rocket: 

Example with script `exit 1`:

```
 [Fri Jan 15 14:34:38.718730 2021] [md:debug] [pid 66749:tid mod_md_drive.c(205): AH10055: md watchdog run, auto drive 1 mds
 [Fri Jan 15 14:34:38.719352 2021] [md:debug] [pid 66749:tid mod_md_drive.c(109): AH10052: md(example.com): state=1, driving
 [Fri Jan 15 14:34:38.725083 2021] [md:error] [pid 66749:tid (20014)Internal error (specific information not available): md[example.com] problem[urn:org:apache:httpd:log:AH10109:] detail[MDMessageCmd /usr/local/bin/MDMessageCmd failed with exit code 1.]
 [Fri Jan 15 14:34:38.725170 2021] [md:info] [pid 66749:tid AH10060: example.com: event-handler for 'renewing' event failed
 [Fri Jan 15 14:34:38.743296 2021] [md:debug] [pid 66749:tid mod_md_drive.c(227): AH10107: next run in 11 hours 59 minutes 59 seconds
```

**Comment by icing** [comment]
Looks great! Please make a PR for this, if you feel like. Probably we want to make sure that such a cancelled run is not counted as an error and that the retry mechanism is more lazy with new attempts.

**Comment by root360-AndreasUlm** [comment]
@icing What do you mean by retry being more lazy?

**Comment by icing** [comment]
I started adding support for some ACME errors to immediately trigger the largest retry interval (1 day now). When the input values are rejected by the ACME server, it does not make sense to run more often. Most likely, the configuration values are not correct.

In this case I wonder if the aborted renew will trigger the retry mechanism with 1 minute, 2min, ... and if that is good or bad. But I am not sure. Today I lean towards good. ;-) So, please ignore my statement.

**Comment by root360-AndreasUlm** [comment]
@icing created PR with the patch.
I also tried to find all documentation and unit tests.
I couldn't get the pebble based test setup up and running thus haven't tested the unit test change.
But as far as I understand the pytest scripts it should work.

**Comment by icing** [comment]
Fixed test cases, release as v.2.3.6 beta.
