### ISSUE TITLE
FreeBSD  Version 2-x status: unknown, see #124.

### ISSUE THREAD

**Issue by igalic** [icing/mod_md#238]
the readme says that the status of mod_md is unclear on freebsd. i would like to clarify it:

thanks to my pushing, https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237726 mod_md is enabled by default on freebsd's apache24 package

however, the newer mod_md-devel has not yet been resurrected since its deletion

**Comment by icing** [comment]
Thanks a lot, Mina!
