### ISSUE TITLE
Wildcard-Domains with Apache 2.4.46-4~bpo10+1 on Debian 10?

### ISSUE THREAD

**Issue by renne** [icing/mod_md#239]
Hi,

we're trying to use the mod_md integrated in Apache 2.4.46 with wildcard certificates. The configuration
```
MDCertificateAgreement accepted
MDCertificateAuthority https://acme-v02.api.letsencrypt.org/directory
MDChallengeDns01 /usr/local/bin/apache2_mod_MDChallengeDns01
MDContactEmail infrastruktur@mydomain
MDMembers auto
MDMessageCmd /usr/local/bin/apache2_mod_MDMessageCmd
MDPrivateKeys RSA 4096
MDRenewMode auto

<MDomain *.mydomain>
    MDCAChallenges dns-01
    MDRequireHttps temporary
</MDomain>
```
prevents an Apache start-up with the error
```
[Mon Feb 01 19:36:15.583088 2021] [ssl:emerg] [pid 18528] AH02572: Failed to configure at least one certificate and key for vkbtest2.mydomain:443
[Mon Feb 01 19:36:15.583136 2021] [ssl:emerg] [pid 18528] SSL Library Error: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no certificate assigned
```
Same result with
```
<MDomain mydomain>
    MDCAChallenges dns-01
    MDRequireHttps temporary
</MDomain>
```
Doesn't mod_md in Apache 2.4.46 support wildcard domains or is there something wrong with the configuration?

**Comment by icing** [comment]
I see where the confusion comes in. The module wants to have a 'first' name in MDomain that is not a wildcard. So 

```
<MDomain www.host.net *.host.net>
  ...
</MDomain>
```

should work. It would be useful to not need that, maybe, but that is how the module currently works right now.

**Comment by renne** [comment]
Does
```
<MDomain host.net *.host.net>
  ...
</MDomain>
```
work, too?
I suggest to clarify this in the documentation.

**Comment by icing** [comment]
It should. But it would be helpful to know what you find out on your installation, before I document it. ;-)

**Comment by icing** [comment]
Well, just adding a test case for this and it seems not doing what you need. Working on it...

**Comment by icing** [comment]
Sorry to report that the version you have will not work for this case. I just released a v2.3.7 BETA version that allows exactly what you ask for. If you are able to build the module from this repository, you can load it into your 2.4 server. Otherwise you unfortunately have to wait for the next apache release.

**Comment by renne** [comment]
Which apache version will that be?

**Comment by renne** [comment]
```
<MDomain host.net *.host.net>
    MDCAChallenges dns-01
</MDomain>
```
This works:
```
<Virtualhost *:443>
   Servername host.net
   ...
</Virtualhost>

```
These do not work:
```
<Virtualhost *:443>
   Servername hello.host.net
   ...
</Virtualhost>

<Virtualhost *:443>
   Servername world.host.net
   ...
</Virtualhost>

<Virtualhost *:443>
   Servername *.host.net
   ...
</Virtualhost>
```
Is it somehow possible to use multiple subdomains of a wildcard certificate in different vhosts?

**Comment by icing** [comment]
Yes, that is what I found as well. Before the last fix, the module was not collecting all virtualhosts that match ```*.host.net```.

As to the double 'dns-01': your dns-01 script should be called twice: once for setup, once for teardown. Is that what you are seeing?

**Comment by renne** [comment]
When we use a wildcard certificate with 10 domains (10x <host.net> + 10x <*.host.net>) the dns-01 script gets 20 setup calls  (2x setup <host.net> per domain) and 10 teardown calls (1x teardown per domain). The double setup calls collide with the cache TTL of Let's Encrypt boulder. Our workaround is a "&& sleep 70s" after each nsupdate command which needs nearly half an hour for the 10x wildcard-domain certificate.

In our setup each vhost needs at least one subdomain of a common wildcard domain and a certificate for an additional <host.net> + www.<host.net>. There is also a catchall vhost with that 10-domains wildcard certificate.

Are current versions of mod_md capable to do real NxM relations between certificates and Vhosts?

**Comment by tbjornli** [comment]
From my understanding of wildcard SSL before mod_md v2.4.0, if I want to secure more than one sub-domain I need to include them all in the MDomain directive.

However what about multi-level subdomains? I.e.

```
<MDomain sub.domain.tld sub1.domain.tld multi-level.sub.domain.tld>                                                           
  MDMember *.domain.tld                                                           
  MDCAChallenges dns-01                                                         
  MDChallengeDns01 /usr/local/sbin/dns-challenge --                             
</MDomain>                                                                      
MDCertificateAgreement accepted
```

This for some reason seems to not work after restarting apache2 and the status in _**/server-status**_ for the domain in question has been changed to '**Incomplete**'

Anyone have any experience with this?
