### ISSUE TITLE
NoGo Windows :: After restart changes not activated with Access is denied in log

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#24]
Have:
LoadModule md_module modules/mod_md.so
ManagedDomain domaind.nl www.domaind.nl
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf

Initial it says all fine and ask for restart.
After restart I see  **(OS 5)Access is denied** and asking again for restart.

It happens both when the Apache server is running with System or Administrator account.

**Inititial:**

[md:info] [pid 5776:tid 456] AH: mod_md (v0.5.0-git), initializing...
[md:info] [pid 10184:tid 372] AH: mod_md (v0.5.0-git), initializing...
[md:info] [pid 10184:tid 1964] domaind.nl: setup staging
[md:info] [pid 10184:tid 1964] domaind.nl: need certificate
[md:info] [pid 10184:tid 1964] registered new account https://acme-staging.api.letsencrypt.org/acme/reg/2907888
[md:info] [pid 10184:tid 1964] domaind.nl: check Terms-of-Service agreement
[md:info] [pid 10184:tid 1964] domaind.nl: setup new authorization
[md:info] [pid 10184:tid 1964] domaind.nl: setup new challenges
[md:info] [pid 10184:tid 1964] updated authz https://acme-staging.api.letsencrypt.org/acme/authz/jDHZI1F9a7KplK0RKN--ZOF9atEZfhwsM9IhTRgwdOU
[md:info] [pid 10184:tid 3020] [client 66.133.109.36:52256] AH: f972ca5e2bdcc62b9ff607c4a1e8e2bd.64d86ecf28901402270935aa2f61ba94.acme.invalid: is a tls-sni-01 challenge host
[md:info] [pid 10184:tid 1964] updated authz https://acme-staging.api.letsencrypt.org/acme/authz/KRS9-Fu2BVoETVbbmxvf6xGpgNF9xCYejs-7ks2sIdw
[md:info] [pid 10184:tid 1964] domaind.nl: monitoring challenge status
[md:info] [pid 10184:tid 3020] [client 66.133.109.36:52328] AH: 7237dd3a897d38e80ae12788930936f7.c605a08202905d490a609ccdaaba57a3.acme.invalid: is a tls-sni-01 challenge host
[md:info] [pid 10184:tid 1964] domaind.nl: checked all domain authorizations
[md:info] [pid 10184:tid 1964] domaind.nl: creating certificate request
[md:info] [pid 10184:tid 1964] domaind.nl: received certificate
[md:info] [pid 10184:tid 1964] domaind.nl: retrieving certificate chain
[md:notice] [pid 10184:tid 1964] AH: 1 Managed Domain has been setup and changes will be activated on next (graceful) server restart.

**After restart:**

[md:info] [pid 5776:tid 456] AH: mod_md (v0.5.0-git), initializing...
[md:notice] [pid 10184:tid 1964] AH: 1 Managed Domain has been setup and changes will be activated on next (graceful) server restart.
[md:error] [pid 5776:tid 456] (OS 5)Access is denied.  : rename from D:/servers/apacheS/md/domains/domaind.nl to D:/servers/apacheS/md/archive/domaind.nl.1
[md:error] [pid 5776:tid 456] (OS 5)Access is denied.  : AH: domaind.nl: error loading staged set
[md:error] [pid 10520:tid 364] (OS 183)Cannot create a file when that file already exists.  : creating archive dir: D:/servers/apacheS/md/archive/domaind.nl.1
[md:error] [pid 10520:tid 364] (OS 183)Cannot create a file when that file already exists.  : AH: domaind.nl: error loading staged set
[md:info] [pid 10520:tid 364] AH: mod_md (v0.5.0-git), initializing...
[md:error] [pid 10520:tid 364] (OS 183)Cannot create a file when that file already exists.  : creating archive dir: D:/servers/apacheS/md/archive/domaind.nl.1
[md:error] [pid 10520:tid 364] (OS 183)Cannot create a file when that file already exists.  : AH: domaind.nl: error loading staged set
[md:info] [pid 10520:tid 2044] domaind.nl: all data staged
[md:notice] [pid 10520:tid 2044] AH: 1 Managed Domain has been setup and changes will be activated on next (graceful) server restart.

**Comment by SteffenAL** [comment]
After ~12 hours I see in the log:

[md:warn] [pid 1864:tid 1964] md(domaind.nl): looks complete, but has unknown expiration date.

**Comment by SteffenAL** [comment]
When I run a2md, the result is: Unrecognized Win32 error code 1

>a2md -vvv -a https://acme-staging.api.letsencrypt.org/directory -d d:\apache24\md  drive domaind.nl

Output:

[src\md_store_fs.c:350 trace2][ok] loading type 1 from d:\apache24\md/domains/domaind.nl/md.json
[src\md_store_fs.c:350 trace2][2(No such file or directory)] loading type 2 from d:\apache24\md/domains/domaind.nl/cert.pem
[src\md_store_fs.c:350 trace2][2(No such file or directory)] loading type 3 from d:\apache24\md/domains/domaind.nl/pkey.pem
[src\md_store_fs.c:350 trace2][2(No such file or directory)] loading type 4 from d:\apache24\md/domains/domaind.nl/chain.pem
[src\md_reg.c:166 debug][ok] md{domaind.nl}: incomplete, without private key
[md_cmd_reg.c:275 info][ok] domaind.nl: incomplete, sign up
[src\md_store_fs.c:350 trace2][ok] loading type 1 from d:\apache24\md/httpd.json
[src\acme\md_acme_drive.c:628 trace1][ok] domaind.nl: init driver
[src\md_store_fs.c:350 trace2][ok] loading type 1 from d:\apache24\md/staging/domaind.nl/md.json
[src\acme\md_acme_drive.c:631 trace1][ok] domaind.nl: checked stage md
[src\md_store_fs.c:350 trace2][ok] loading type 2 from d:\apache24\md/staging/domaind.nl/cert.pem
[src\md_store_fs.c:350 trace2][ok] loading type 3 from d:\apache24\md/staging/domaind.nl/pkey.pem
[src\md_store_fs.c:350 trace2][ok] loading type 4 from d:\apache24\md/staging/domaind.nl/chain.pem
[src\acme\md_acme_drive.c:661 debug][ok] domaind.nl: checked creds
[src\md_reg.c:847 debug][ok] domaind.nl: run staging
[src\acme\md_acme_drive.c:680 debug][ok] domaind.nl: staging started, state=1, can_http=0, can_https=1, challenges='tls-sni-01 http-01'
[src\acme\md_acme_drive.c:689 info][ok] domaind.nl: all data staged
[src\acme\md_acme_drive.c:803 debug][ok] domaind.nl: ACME, staging done
[src\md_reg.c:850 debug][ok] domaind.nl: staging done
[md_cmd_reg.c:278 info][ok] domaind.nl: loading
[src\md_store_fs.c:350 trace2][ok] loading type 1 from d:\apache24\md/domains/domaind.nl/md.json
[src\md_store_fs.c:350 trace2][2(No such file or directory)] loading type 2 from d:\apache24\md/domains/domaind.nl/cert.pem
[src\md_store_fs.c:350 trace2][2(No such file or directory)] loading type 3 from d:\apache24\md/domains/domaind.nl/pkey.pem
[src\md_store_fs.c:350 trace2][2(No such file or directory)] loading type 4 from d:\apache24\md/domains/domaind.nl/chain.pem
[src\md_reg.c:166 debug][ok] md{domaind.nl}: incomplete, without private key
[src\md_store_fs.c:350 trace2][ok] loading type 1 from d:\apache24\md/httpd.json
[src\acme\md_acme_drive.c:628 trace1][ok] domaind.nl: init driver
[src\md_store_fs.c:350 trace2][ok] loading type 1 from d:\apache24\md/staging/domaind.nl/md.json
[src\acme\md_acme_drive.c:631 trace1][ok] domaind.nl: checked stage md
[src\md_store_fs.c:350 trace2][ok] loading type 2 from d:\apache24\md/staging/domaind.nl/cert.pem
[src\md_store_fs.c:350 trace2][ok] loading type 3 from d:\apache24\md/staging/domaind.nl/pkey.pem
[src\md_store_fs.c:350 trace2][ok] loading type 4 from d:\apache24\md/staging/domaind.nl/chain.pem
[src\acme\md_acme_drive.c:661 debug][ok] domaind.nl: checked creds
[src\md_reg.c:915 debug][ok] domaind.nl: run load
[src\acme\md_acme_drive.c:821 debug][ok] domaind.nl: preload start
[src\md_store_fs.c:350 trace2][ok] loading type 1 from d:\apache24\md/staging/domaind.nl/md.json
[src\md_store_fs.c:350 trace2][ok] loading type 2 from d:\apache24\md/staging/domaind.nl/cert.pem
[src\md_store_fs.c:350 trace2][ok] loading type 4 from d:\apache24\md/staging/domaind.nl/chain.pem
[src\md_store_fs.c:350 trace2][ok] loading type 3 from d:\apache24\md/staging/domaind.nl/pkey.pem
[src\md_store_fs.c:350 trace2][ok] loading type 1 from d:\apache24\md/staging/domaind.nl/account.json
[src\md_store_fs.c:350 trace2][ok] loading type 3 from d:\apache24\md/staging/domaind.nl/account.pem
[src\md_store_fs.c:350 trace2][720002(Unrecognized Win32 error code 2)] loading type 1 from d:\apache24\md/staging/domaind.nl/authz.json
[src\md_store_fs.c:503 debug][ok] start remove of md staging/domaind.nl/authz.json
[src\acme\md_acme_drive.c:862 debug][ok] domaind.nl: staged data load, purging tmp space
[src\md_store_fs.c:562 debug][ok] purge tmp/domaind.nl (d:\apache24\md/tmp/domaind.nl)
[src\acme\md_acme_drive.c:879 debug][ok] domaind.nl: saved ACME account ACME-.letsencrypt.org-0003
[src\acme\md_acme_drive.c:913 debug][ok] domaind.nl: ACME, preload done
[src\md_store_fs.c:683 err][720183(Unrecognized Win32 error code 1)] creating archive dir: d:\apache24\md/archive/domaind.nl.1
[src\md_reg.c:937 debug][720183(Unrecognized Win32 error code 1)] domaind.nl: load done
[md_cmd_reg.c:297 info][720183(Unrecognized Win32 error code 1)] domaind.nl: error activating new credentials

**Comment by icing** [comment]
How does your ```md\archive``` dir look? I assume there already is a sub directory named ```domaind.nl.1```?

**Comment by SteffenAL** [comment]
yes, and no files in it.

**Comment by icing** [comment]
@SteffenAL I just pushed a new version where I changed the archiving handling on Windows.

The downside: I needed to restructure the source tree to become similar to how it will look in Apache subversion. Not sure how much that breaks your build or if it makes it easier.

**Comment by SteffenAL** [comment]
One source tree is much better, and a2md in modules is no problem for me (more or less it belongs in support). You renamed also some files. 

Building 0.6.0  all fine.

Now it configures a certificate, although it is not a valid certificate,  I can browse https with it, you can try https://www.vosadministraties.nl/  The certificate says: Issued by: Fake LE Intermediate X1.

Runs on the https://www.apachelounge.com/ production server which has more (vhost)domains with  valid certificates.

**Config:**
LoadModule watchdog_module modules/mod_watchdog.so
LoadModule md_module modules/mod_md.so
ManagedDomain vosadministraties.nl www.vosadministraties.nl

And the vhosts:
<VirtualHost *:443>
ServerName ........
ServerAlias ........
.....
SSLEngine on    
SSLCertificateFile conf/apachelounge.com-chain.pem 
SSLCertificateKeyFile conf/apachelounge.com-key.pem
< /VirtualHost>
...
...
<VirtualHost *:443>
ServerName www.vosadministraties.nl
ServerAlias vosadministraties.nl
.....
SSLEngine on 
< /VirtualHost>

**Log:**
[md:info] [pid 11524:tid 448] AH: vosadministraties.nl: staged set activated
[md:info] [pid 11524:tid 448] AH: mod_md (v0.6.0-git), initializing...
[ssl:info] [pid 11524:tid 448] AH01914: Configuring server www.vosadministraties.nl:443 for SSL protocol
[ssl:info] [pid 11524:tid 448] AH02568: Certificate and private key www.vosadministraties.nl:443:0 configured from D:/servers/apacheS/md/domains/vosadministraties.nl/cert.pem and D:/servers/apacheS/md/domains/vosadministraties.nl/pkey.pem
