### ISSUE TITLE
Could not renew unless MDCAChallenges http-01 set

### ISSUE THREAD

**Issue by Jon8RFC** [icing/mod_md#240]
I don't see md logs, I guess those get deleted upon restarting the server and only save upon success?

Here's what I spotted watching the status page:
```
Error[Internal error (specific information not available)]: Unable to retrieve rsa certificate chain.

Error[Invalid argument]: urn:ietf:params:acme:error:unauthorized Incorrect validation certificate for tls-alpn-01 challenge. Missing acmeValidationV1 extension.
```

Setting "MDCAChallenges http-01" again, as in the past, allowed for success.  This time, however, the error message pointed me in the right direction, but it may not be the same problem as before.  The fix was the same as before.
Apache 2.4.46c and mod_md 2.3.7

**Comment by icing** [comment]
Do you have the ACME challenge protocol enabled in your server?

```
Protocols http/1.1 acme-tls/1
# of if you also enable HTTP/2
Protocols h2 http/1.1 acme-tls/1
```

The error message looks as of you do not.

**Comment by Jon8RFC** [comment]
I believe so.
```
Protocols h2 h2c http/1.1 acme-tls/1
ProtocolsHonorOrder on
H2EarlyHints on
H2Direct on
H2ModernTLSOnly on
```

**Comment by icing** [comment]
@Jon8RFC could you try the latest version from here? I fixed a bug in 2.4.4 related to botched `tls-alpn-01` handling.

**Comment by Jon8RFC** [comment]
@icing I just ran a renewal and it worked with tls-alpn-01
Thanks!

**Comment by Jon8RFC** [comment]
All is well with 2.4.7!
