### ISSUE TITLE
Reloading apache2 gracefully using MDMessageCmd

### ISSUE THREAD

**Issue by koen-serneels** [icing/mod_md#241]
I'm trying to auto reload apache2 gracefully after a certificate is renewed using the trigger provided by mod_md via MDMessageCmd, but somehow it's giving me a hard time. So two questions about this. First, is this actually supported? I can imagine that reloading the config (graceful or not) while mod_md is doing it's thing might intervene. Either way, here is my current setup:

```                                                                       
               LogLevel md:debug
               ServerName mydomain
                Protocols h2 http/1.1 acme-tls/1
                MDCertificateAuthority https://acme-staging-v02.api.letsencrypt.org/directory
                MDCertificateAgreement accepted
                MDPortMap http:-
                MDMessageCmd /etc/apache2/reload.sh

                <MDomain mydomain>
                  MDRenewMode auto
                  MDCAChallenges tls-alpn-01
                  MDRenewWindow 99%
                </MDomain>
```

Reload script:

```
#!/bin/bash
now=$(date)

echo $now $1 $2 >> /tmp/command.log

if [ $1 = "renewed" ]; then
 #/usr/sbin/apache2ctl -k graceful
 echo "$now Reloaded apache2 because of md trigger" >> /tmp/reload.log
fi
exit 0
```

Secondly, MDRenewWindow cannot be set higher than 99%. This means that after a change I'll have to wait ~24h to see if this is working. Is there a way to trigger mod_md to do the renewal faster/on-demand? I tried fiddling with the config files in md/mydomain but this is not working. This is a fairly specific case as I really need a 'renewal' (so deleting the certificate and installing it again is another 'flow' and not really simulatiing my case).

**Comment by icing** [comment]
The `MDMessageCmd` is invoked from a running child process that has, on most installations, the user `www-data` while the server's parent process runs as `root`. This means the script has insufficient rights to restart your server.

I use a daily graceful restart via `systemd`, since the traffic on my server is low. If you want to avoid that, your message script could create a file `restart.asap` somewhere where your cron job picks it up.

As to the waiting part: the easiest is probably to just delete the .pem files in `md/domains/<your-domain>/*pem` and reload the server. When you need a lot of this, it's probably best to use the Let's Encrypt `staging` servers, because the real ones to rate-limiting. 

Hope this helps.

**Comment by koen-serneels** [comment]
I was under the impression that `MDMessageCmd` always executes as root, but after checking the manual again, root is only mentioned with installed and not renewed, so fair enough. This also explains why it sometimes worked and sometimes not during testing.

```
'renewed' means that a new certificate has been obtained and is stored in the 'staging' area in the MD store. It will be activated on the next server restart/reload.

'installed' is triggered when a new certificate has been transferred from staging into the domains location in MD store. This happens at server startup/reload. Different to all other invocations, MDMessageCmd is run with root permissions (on *nix systems) and has access to the certificate files (and keys). Certificates needed for other applications or in different formats can be processed on this event.
```
Your suggestion working via 'messages' is also a good one, but currently I'm trying with sudo rights for the www-data user for this specific script and having an async delay via `at`, thinking that security will not really be impacted. Any thoughts on this?
