### ISSUE TITLE
How to increase Strict-Transport-Security max-age

### ISSUE THREAD

**Issue by IRHM** [icing/mod_md#245]
I'd like to increase the `Strict-Transport-Security max-age` set by using `MDRequireHttps permanent`. I can't find anything in the [readme](https://github.com/icing/mod_md#permanent-and-security) that shows how to do this. I can only find it saying it sets it to about half a year by default.

Is this possible, or should I not use MDRequireHttps and set my own header?

I have set my own header manually (whilst still using MDRequireHttps), but then it sends multiple HSTS headers instead of just the one I've defined (I don't know if there is a way to overwrite headers in apache so that it doesn't sent two, but doing that doesn't seem right to me anyways. Maybe I should do this?).

**Comment by icing** [comment]
`MDRequireHttps` is just an easy options for setting headers and redirecting which is possible with other apache directives as well. If you have specific requirements as to the HSTS header content, you should not use it and configure it yourself, as you wrote.

I'd like to keep it simple and easy to use. What could be enhanced is that it does not add a second header, if one is already present. But for that to work, I need to check the order in which these are added.
