### ISSUE TITLE
MDMessageCmd and graceful restart

### ISSUE THREAD

**Issue by martinkoehler** [icing/mod_md#246]
Especially in a Docker environment where there is no crontab etc running it would be nice to be able to use `MDMessageCmd` to gracefully restart the server.

Currently this can be done only with some workarounds as far as I can see and requires  `sudo` to be installed:
- As stated in #241 MDMessageCmd is run as the child user (e.g. unsually www-data in e.g. debian, ubuntu). This means one has to use sudo (which is another packet to be installed).
- It seems that at the time the MDMessageCmd is executed, it is too early for an installation. 

If I execute the restart command (e.g. `sudo -u root /usr/sbin/apachectl -k graceful`) directly in the MDMessageCmd, I see a graceful restart in the apache logs and only afterwards the message form mod_md that a gracefull restart installs the newly obtained certificate. With a 30s sleep in a background process, everything works fine.

I do have two suggestion: 
Either call MDMessageCmd  with renewed at the end of the renewal process so that the restart from the script succeeds or add an additional hook (e.g. `restart` ?) that is run as the root user when a graceful restart will actually install the new cert.

Another option would be a flag (e.g. `MDAutoRestart` - on|off with default off) that sends the signal USR1 to the parent process once a certificate is ready to be rolled out).

My md_message shell script is:

``` 
#! /bin/sh
# Handle Let's encrypt certificates in the Docker case
# called by MDMessgeCmd
ARGV="$@"
case "$1" in
renewed)
    echo "renewed requested "
    ( sleep 30 && sudo -u root /usr/sbin/apachectl -k graceful ; echo "done") &
    echo restart in 30s
    ;;
*)
    echo $ARGV
esac
```

In `/etc/suduers.d/mod_md` I used

```
# Sudo additions for mod_md
#
www-data        ALL=(root)      NOPASSWD:       /usr/sbin/apachectl
```

**Comment by icing** [comment]
> Especially in a Docker environment where there is no crontab etc running it would be nice to be able to use `MDMessageCmd` to gracefully restart the server.
> 
> Currently this can be done only with some workarounds as far as I can see and requires `sudo` to be installed:
> 
> * As stated in [Reloading apache2 gracefully using MDMessageCmd #241](https://github.com/icing/mod_md/issues/241) MDMessageCmd is run as the child user (e.g. unsually www-data in e.g. debian, ubuntu). This means one has to use sudo (which is another packet to be installed).
> * It seems that at the time the MDMessageCmd is executed, it is too early for an installation.
> 
> If I execute the restart command (e.g. `sudo -u root /usr/sbin/apachectl -k graceful`) directly in the MDMessageCmd, I see a graceful restart in the apache logs and only afterwards the message form mod_md that a gracefull restart installs the newly obtained certificate. With a 30s sleep in a background process, everything works fine.

Hmm, the graceful restart from the script might immediately tear down child processes. The restart does not care about watchdogs running (those are used by md).
I'll add a saving of job data before running the 'renewed' script.

> 
> I do have two suggestion:
> Either call MDMessageCmd with renewed at the end of the renewal process so that the restart from the script succeeds or add an additional hook (e.g. `restart` ?) that is run as the root user when a graceful restart will actually install the new cert.

See above.

> Another option would be a flag (e.g. `MDAutoRestart` - on|off with default off) that sends the signal USR1 to the parent process once a certificate is ready to be rolled out).

I tried that before, but `www-data` has no permission to signal the parent root process.

> My md_message shell script is:
> 
> ```
> #! /bin/sh
> # Handle Let's encrypt certificates in the Docker case
> # called by MDMessgeCmd
> ARGV="$@"
> case "$1" in
> renewed)
>     echo "renewed requested "
>     ( sleep 30 && sudo -u root /usr/sbin/apachectl -k graceful ; echo "done") &
>     echo restart in 30s
>     ;;
> *)
>     echo $ARGV
> esac
> ```
> 
> In `/etc/suduers.d/mod_md` I used
> 
> ```
> # Sudo additions for mod_md
> #
> www-data        ALL=(root)      NOPASSWD:       /usr/sbin/apachectl
> ```

Personally, I would not recommend adding `www-data` to sudoers in any way, but it's your system.

An alternative for a docker images might be to run the whole apache as www-data, since you start it yourself anyway, right? You commonly do not have to use privileged ports. But I have not tried that, it might run into other problems.

**Comment by icing** [comment]
I see no general way of addressing the self-restart from within Apache httpd. My recommended setup remains to be a cron job / systemd restart schedule for a server. But ymmv.
