### ISSUE TITLE
req->pool can be NULL if internals_setup() fails in curl_easy_init()

### ISSUE THREAD

**Issue by sjorge** [icing/mod_md#247]
I noticed a segfault on OmniOS when using mod_md.

I believe I tracked it down to a failure of curl_easy_init(), not sure why it is failing, but mod_md should probably not segfault httpd if it does.

```
> $C
fffffc7fe35c3a70 libapr-1.so.0.7.0`apr_allocator_free+0x57()
fffffc7fe35c3a90 libaprutil-1.so.0.6.1`heap_bucket_destroy+0x20()
fffffc7fe35c3ac0 libaprutil-1.so.0.6.1`apr_brigade_cleanup+0x45()
fffffc7fe35c3af0 libapr-1.so.0.7.0`apr_pool_destroy+0x6e()
fffffc7fe35c3b40 mod_md.so`md_curl_perform+0x44()
fffffc7fe35c3b80 mod_md.so`md_http_POSTd_perform+0x78()
fffffc7fe35c3be0 mod_md.so`md_acme_req_send+0x42b()
fffffc7fe35c3c10 mod_md.so`get_cert+0x64()
fffffc7fe35c3c60 mod_md.so`md_util_try+0xa2()
fffffc7fe35c3ca0 mod_md.so`md_acme_drive_cert_poll+0xc5()
fffffc7fe35c3d30 mod_md.so`acme_driver_renew+0x2bc()
fffffc7fe35c3d90 mod_md.so`run_renew+0x16d()
fffffc7fe35c3eb0 mod_md.so`md_util_pool_vdo+0xf9()
fffffc7fe35c3ee0 mod_md.so`md_reg_renew+0x2e()
fffffc7fe35c3f40 mod_md.so`run_watchdog+0x6ec()
fffffc7fe35c3fb0 mod_watchdog.so`wd_worker+0x403()
fffffc7fe35c3fe0 libc.so.1`_thrp_setup+0x6c(fffffc7fea8d5a40)
fffffc7fe35c3ff0 libc.so.1`_lwp_start()
```
From the stack, it appears apr tries to free memory it doesn't have.

```
> md_curl_perform+0x44::dis
mod_md.so`md_curl_perform+0x23: xorl   %eax,%eax
mod_md.so`md_curl_perform+0x25: call   -0xb7a   <mod_md.so`internals_setup>
mod_md.so`md_curl_perform+0x2a: movl   %eax,%r12d
mod_md.so`md_curl_perform+0x2d: testl  %eax,%eax
mod_md.so`md_curl_perform+0x2f: je     +0x37    <mod_md.so`md_curl_perform+0x68>
mod_md.so`md_curl_perform+0x31: movq   %r15,%rdi
mod_md.so`md_curl_perform+0x34: movl   %r12d,%esi
mod_md.so`md_curl_perform+0x37: call   -0xc4c   <mod_md.so`fire_status>
mod_md.so`md_curl_perform+0x3c: movq   %r15,%rdi
mod_md.so`md_curl_perform+0x3f: call   +0x3dac  <mod_md.so`md_http_req_destroy>
mod_md.so`md_curl_perform+0x44: movq   -0x38(%rbp),%rax
mod_md.so`md_curl_perform+0x48: subq   0x0(%r13),%rax
mod_md.so`md_curl_perform+0x4c: jne    +0x146   <mod_md.so`md_curl_perform+0x198>
mod_md.so`md_curl_perform+0x52: leaq   -0x28(%rbp),%rsp
mod_md.so`md_curl_perform+0x56: movl   %r12d,%eax
mod_md.so`md_curl_perform+0x59: popq   %rbx
mod_md.so`md_curl_perform+0x5a: popq   %r12
mod_md.so`md_curl_perform+0x5c: popq   %r13
mod_md.so`md_curl_perform+0x5e: popq   %r14
mod_md.so`md_curl_perform+0x60: popq   %r15
mod_md.so`md_curl_perform+0x62: popq   %rbp
```

Looking at the output of the disassembler for md_curl_perform

https://github.com/icing/mod_md/blob/5e34c14e2b7ad195f662290c26481cbc3a249fe0/src/md_curl.c#L381

As there is no call listed to curl_easy_perform, but there is a call to internals_setup I think we hit the goto leave here: https://github.com/icing/mod_md/blob/5e34c14e2b7ad195f662290c26481cbc3a249fe0/src/md_curl.c#L388

That seems the only way to end up calling fire_status followed by md_http_req_destroy.

Looking at https://github.com/icing/mod_md/blob/5e34c14e2b7ad195f662290c26481cbc3a249fe0/src/md_curl.c#L242

https://github.com/icing/mod_md/blob/5e34c14e2b7ad195f662290c26481cbc3a249fe0/src/md_curl.c#L251-L255

Seems to be the only way to exit there without having `req->pool` set.

**Comment by icing** [comment]
Hey @sjorge!

I think your analysis is correct. The fix should be to check in md_http_req_destroy() if `req->pool` is not NULL, I guess. Can you build from master here? Then we could easily verify this or you try yourself.

The curious thing is then how/when/why curl_easy_init fails. But one thing after the other.

**Comment by sjorge** [comment]
> I think your analysis is correct. The fix should be to check in md_http_req_destroy() if `req->pool` is not NULL, I guess. Can you build from master here? Then we could easily verify this or you try yourself.

I can, I'll give it a shot tonight.

> The curious thing is then how/when/why curl_easy_init fails. But one thing after the other.

Same :) As I think even with the extra check, httpd is not going to segfault, but  doubt mod_md will work.

**Comment by sjorge** [comment]
> > The curious thing is then how/when/why curl_easy_init fails. But one thing after the other.
> 
> Same :) As I think even with the extra check, httpd is not going to segfault, but doubt mod_md will work.

I'm not super familiar with the libcurl api, but from https://curl.se/libcurl/c/curl_easy_init.html I gather that it's probably curl_global_init() that would be returning an error, as curl_easy_init() would just return NULL.

I'll try a simple change to internals_setup first, if that goes well I'll see if I can add some sort of error checking hre:
https://github.com/icing/mod_md/blob/5e34c14e2b7ad195f662290c26481cbc3a249fe0/src/md_curl.c#L569

Although I'm not really well versed in C.

**Comment by sjorge** [comment]
I tried with ```
void md_http_req_destroy(md_http_request_t *req)
{
    if (req->internals) {
        req->http->impl->req_cleanup(req);
        req->internals = NULL;
    }
    if (req->pool) {
        apr_pool_destroy(req->pool);
    }
}
```

Which results in the same segfault

**Comment by icing** [comment]
Coming back to this (after a too long time), the crashing `apr_allocator_free` can only happen, when a curl request has been performed and a response from the server has (at least partially) been read. 

That means, the curl_easy_init cannot be the cause.

This is a bit worrying since it means that memory seems to have gone out of whack here. In Apache runtime, various objects created register their cleanups when the memory pool is destroyed and that is what you see in the stack trace. The request is done, the pool gets destroyed and the response body frees the "heap buckets" it has created (it only does that when response data has been received).

Can you still reproduce this?
