### ISSUE TITLE
Windows v0.6.0 Build warnings

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#25]
See attached logs.

See a lot: warning C4003: not enough actual parameters for macro 'APLOGNO'

And attention for:  md_store_fs.c(143): warning C4700: uninitialized local variable 's' used

[mod_md.txt](https://github.com/icing/mod_md/files/1208761/mod_md.txt)
[a2md.txt](https://github.com/icing/mod_md/files/1208762/a2md.txt)

**Comment by icing** [comment]
Is this still an issue in v0.7.0?

**Comment by SteffenAL** [comment]
Not anymore warnings APLOGNO and  uninitialized local variable

Still other  warnings, see:

[a2md.txt](https://github.com/icing/mod_md/files/1259784/a2md.txt)
[mod_md.txt](https://github.com/icing/mod_md/files/1259785/mod_md.txt)

**Comment by icing** [comment]
Please check v0.8.0. I removed many gcc warnings in that version.

**Comment by SteffenAL** [comment]
Better, still some left and diff 32 and 64:

conversion from '__int64' to 'long (only in 64)
signed/unsigned mismatch (only in 32)
unknown pragma (both)
not enough actual parameters for macro 'APLOGNO' (both)

[a2md-32.txt](https://github.com/icing/mod_md/files/1269729/a2md-32.txt)
[mod_md-32.txt](https://github.com/icing/mod_md/files/1269731/mod_md-32.txt)

[mod_md-64.txt](https://github.com/icing/mod_md/files/1269732/mod_md-64.txt)
[a2md-64.txt](https://github.com/icing/mod_md/files/1269733/a2md-64.txt)

**Comment by SteffenAL** [comment]
Good news with 0.9.7:

a2md 32 and 64:
md_json.c(28): warning C4068: unknown pragma
md_json.c(29): warning C4068: unknown pragma
md_json.c(30): warning C4068: unknown pragma
md_json.c(31): warning C4068: unknown pragma
md_json.c(32): warning C4068: unknown pragma
md_json.c(39): warning C4068: unknown pragma
md_json.c(40): warning C4068: unknown pragma

mod_md 32 and 64:
md_json.c(28): warning C4068: unknown pragma
md_json.c(29): warning C4068: unknown pragma
md_json.c(30): warning C4068: unknown pragma
md_json.c(31): warning C4068: unknown pragma
md_json.c(32): warning C4068: unknown pragma
md_json.c(39): warning C4068: unknown pragma
md_json.c(40): warning C4068: unknown pragma
mod_md.c(262): warning C4003: not enough actual parameters for macro 'APLOGNO'
mod_md.c(284): warning C4003: not enough actual parameters for macro 'APLOGNO'
mod_md.c(710): warning C4003: not enough actual parameters for macro 'APLOGNO'
mod_md.c(1019): warning C4003: not enough actual parameters for macro 'APLOGNO'
mod_md.c(1026): warning C4003: not enough actual parameters for macro 'APLOGNO'

**Comment by icing** [comment]
Thanks!
