### ISSUE TITLE
Wrong filepath for downloading mod_md tarball

### ISSUE THREAD

**Issue by uhliarik** [icing/mod_md#250]
Hi Stefan,

I don't know, if it is a mistake or intention, but following link does not work:

https://github.com/icing/mod_md/releases/download/v2.4.0/mod_md-2.4.0.tar.gz

but this one does:

https://github.com/icing/mod_md/releases/download/v.**2.4.0**/mod_md-2.4.0.tar.gz (there is extra dot in front of version)

**Comment by icing** [comment]
Ah, I mistyped initially and corrected it afterwards, but github seems to have remembered my typo in the release.

I think I probably just make a next release with some accumulated minor changes and publish that.

**Comment by icing** [comment]
Just release v2.4.2 which has the correct link again.

**Comment by uhliarik** [comment]
Thanks Stefan.
