### ISSUE TITLE
Write access problem?

### ISSUE THREAD

**Issue by nickgearls** [icing/mod_md#253]
I'm trying to use mod_md (httpd 2.4 on CentOS 8) and, when trying to ceate a certificate, it complains it cannot write onto the disk (at least that's what I understand).
I cannot find any permission problems in /var/log/audit/audit.log,  /var/log/messages, nor "journalctl -xe".
All connections to LetsEncrypt are correct and the certificate is, I think, generated.

I have the following errors:
[md:error] (20014)Internal error (specific information not available): AH10056: processing mysite.mycompany.com: Unable to retrive certificate chain.
[...]
[md:trace1] (1)Operation not permitted: mysite.mycompany.com: saving job props

ls -alZ /var/run/httpd/md/:
> drwxr-xr-x. 6 root apache system_u:object_r:httpd_var_run_t:s0     120 Jun 21 11:17 staging

Same permissions for all files in it, like staging/mysite.mycompany.com/ md.json
In case it matters, the site is chrooted and /var/run/httpd/md points to the one in the chroot with exactly the same permissions.

Any idea where I could look for more info?
Thanks a lot

Here is the complete relevant part of the error log, in full debug:
[2021-06-21 11:17:50.488908] [md:trace1] [pid 424510:tid 140357450503936] request --> POST https://acme-v02.api.letsencrypt.org/acme/new-acct
*   Trying 172.65.32.248...
* TCP_NODELAY set
* Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=acme-v01.api.letsencrypt.org
*  start date: Jun  3 22:30:18 2021 GMT
*  expire date: Sep  1 22:30:18 2021 GMT
*  subjectAltName: host "acme-v02.api.letsencrypt.org" matched cert's "acme-v02.api.letsencrypt.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> POST /acme/new-acct HTTP/1.1
Host: acme-v02.api.letsencrypt.org
User-Agent: Apache/2.4.37 mod_md/2.0.8-git
Accept: */*
Content-Type: application/jose+json
Content-Length: 1574
Expect: 100-continue

< HTTP/1.1 100 Continue
< HTTP/1.1 201 Created
< Server: nginx
< Date: Mon, 21 Jun 2021 09:17:51 GMT
< Content-Type: application/json
< Content-Length: 733
< Connection: keep-alive
< Boulder-Requester: 127753501
< Cache-Control: public, max-age=0, no-cache
< Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
< Link: <https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf>;rel="terms-of-service"
< Location: https://acme-v02.api.letsencrypt.org/acme/acct/127753501
< Replay-Nonce: 0003IWS9CGYrN6SxjrANpXAuvvX0NUfJt6pPqwOxm-qzPVs
< X-Frame-Options: DENY
< Strict-Transport-Security: max-age=604800
<
Connection #0 to host acme-v02.api.letsencrypt.org left intact
[2021-06-21 11:17:51.275576] [md:trace1] [pid 424510:tid 140357450503936] request <-- 201
[2021-06-21 11:17:51.275611] [md:trace1] [pid 424510:tid 140357450503936] response: 201
[2021-06-21 11:17:51.275764] [md:trace2] [pid 424510:tid 140357450503936] response: {\n  "key": {\n    "kty": "RSA",\n "n": "mn-82COwom_LwiMH_U75P7vNZpFHXEkWwDdnZI500p_9PvPwZscmu1gQQ489F8a1FhrY3iBShBN-m3kb8KRLAZ7WXwBExHLbwr9ZOrVl44ivrey0L6do7L4S3ZYhcGgKXgDmFT66vSN-Hl315AY8eVDhekRAzIYj0qh3KNYPbkn_zJJlWHOO805jUbXC21WE-02kvZ9bAhbx3L8qSmhz1E8ScrUIXpZ128lefH66YlUCAmAkbtBlsg4eMN2h_SR4U4UPRzp--2Echf7GGYMYwkLgcP-KQNZT5bnPHEByB7YvBGdic-sZ9lWYWsZGBPO-ircJqqn5hCrOfPuc0iDotF3WM0H-BkVJ9nhhII2VXnNV6jjmz1xcuIU-zcctic8iTbONmlusRY_dkzXwutm63RclnZ_SLthF51geqbdL-2_4J4wWklu6SXhidNQvg-r0PuqhZTBgan_MZ3zrqcQJfEUpqMy2IOWnNbaKRA2emwA9K3_Je73RYdOvkE9aOKJx",\n "e": "AQAB"\n  },\n  "contact": [\n "mailto:dnsmaster@idloom.com"\n  ],\n  "initialIp": "86.39.202.101",\n  "createdAt": "2021-06-21T09:17:51.197951792Z",\n  "status": "valid"\n}
[2021-06-21 11:17:51.275864] [md:debug] [pid 424510:tid 140357450503936] updated acct https://acme-v02.api.letsencrypt.org/acme/acct/127753501
[2021-06-21 11:17:51.277869] [md:debug] [pid 424510:tid 140357450503936] req sent
[2021-06-21 11:17:51.277898] [md:info] [pid 424510:tid 140357450503936] registered new account https://acme-v02.api.letsencrypt.org/acme/acct/127753501
[2021-06-21 11:17:51.277975] [md:trace3] [pid 424510:tid 140357450503936] mk_group_dir /var/run/httpd/md/staging perm set
[2021-06-21 11:17:51.277985] [md:trace3] [pid 424510:tid 140357450503936] mk_group_dir 4 (null)
[2021-06-21 11:17:51.278004] [md:debug] [pid 424510:tid 140357450503936] md[mysite.mycompany.com] while[Creating new ACME account for mysite.mycompany.com]
[2021-06-21 11:17:51.278027] [md:info] [pid 424510:tid 140357450503936] mysite.mycompany.com: retrieving certificate chain
[2021-06-21 11:17:51.278036] [md:error] [pid 424510:tid 140357450503936] (20014)Internal error (specific information not available): mysite.mycompany.com: asked to retrieve chain, but no order in context
[2021-06-21 11:17:51.278057] [md:debug] [pid 424510:tid 140357450503936] (20014)Internal error (specific information not available): md[mysite.mycompany.com] while[Retrieving certificate chain for mysite.mycompany.com] detail[Unable to retrive certificate chain.]
[2021-06-21 11:17:51.278067] [md:debug] [pid 424510:tid 140357450503936] (20014)Internal error (specific information not available): mysite.mycompany.com: staging done
[2021-06-21 11:17:51.278081] [md:error] [pid 424510:tid 140357450503936] (20014)Internal error (specific information not available): AH10056: processing mysite.mycompany.com: Unable to retrive certificate chain.
[2021-06-21 11:17:51.278094] [md:trace1] [pid 424510:tid 140357450503936] md(mysite.mycompany.com): check expiration
[2021-06-21 11:17:51.278120] [md:info] [pid 424510:tid 140357450503936] AH10057: mysite.mycompany.com: encountered error for the 1. time, next run in 04 seconds
[2021-06-21 11:17:51.278158] [md:trace3] [pid 424510:tid 140357450503936] mk_group_dir /var/run/httpd/md/staging perm set
[2021-06-21 11:17:51.278167] [md:trace3] [pid 424510:tid 140357450503936] mk_group_dir 4 (null)
[2021-06-21 11:17:51.278174] [md:trace1] [pid 424510:tid 140357450503936] (1)Operation not permitted: mysite.mycompany.com: saving job props
[2021-06-21 11:17:51.278188] [md:debug] [pid 424510:tid 140357450503936] AH10107: next run in 04 seconds
[2021-06-21 11:17:56.289509] [md:debug] [pid 424510:tid 140357450503936] AH10055: md watchdog run, auto drive 1 mds
[2021-06-21 11:17:56.289624] [md:trace3] [pid 424510:tid 140357450503936] (2)No such file or directory: loading type 1 from /var/run/httpd/md/staging/mysite.mycompany.com/job.json
[2021-06-21 11:17:56.289665] [md:debug] [pid 424510:tid 140357450503936] AH10052: md(mysite.mycompany.com): state=1, driving
[2021-06-21 11:17:56.289709] [md:trace1] [pid 424510:tid 140357450503936] mysite.mycompany.com: init driver
[2021-06-21 11:17:56.289719] [md:debug] [pid 424510:tid 140357450503936] mysite.mycompany.com: init done
[2021-06-21 11:17:56.289727] [md:debug] [pid 424510:tid 140357450503936] mysite.mycompany.com: run staging
[2021-06-21 11:17:56.289737] [md:debug] [pid 424510:tid 140357450503936] mysite.mycompany.com: staging started, state=1, can_http=0, can_https=1, challenges='tls-alpn-01'
[2021-06-21 11:17:56.289926] [md:trace3] [pid 424510:tid 140357450503936] loading type 1 from /var/run/httpd/md/staging/mysite.mycompany.com/md.json
[2021-06-21 11:17:56.290003] [md:debug] [pid 424510:tid 140357450503936] get directory from https://acme-v02.api.letsencrypt.org/directory
[2021-06-21 11:17:56.290937] [md:trace1] [pid 424510:tid 140357450503936] request --> GET https://acme-v02.api.letsencrypt.org/directory

**Comment by icing** [comment]
You are on the right track. The problem seems to be that Apache cannot set the directory permissions it needs on the `staging` directory. You can try removing `staging` manually and restart the server to check if a new creation also fails in your setup.

I am not familiar with the CentOS chroot configuration. I think you have to turn to them for support if my suggestions do not help.

**Comment by nickgearls** [comment]
Thanks Stafan.
      What is supposed to be the correct permissions on the staging?
      
    
    On 21-06-2021 14:37, Stefan Eissing
      wrote:
    
    
      
      You are on the right track. The problem seems to be that Apache
        cannot set the directory permissions it needs on the staging
        directory. You can try removing staging manually
        and restart the server to check if a new creation also fails in
        your setup.
      I am not familiar with the CentOS chroot configuration. I think
        you have to turn to them for support if my suggestions do not
        help.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/icing/mod_md/issues/253#issuecomment-864998429",
"url": "https://github.com/icing/mod_md/issues/253#issuecomment-864998429",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by icing** [comment]
On systems I am more familiar with, like debian, the `User` in the server is configured as `www-data` and then the permissions inside the `md` directory look like this:

```
drwxr-xr-x   7 root     root  4096 Sep 30  2019 accounts
drwx------ 200 root     root 12288 Jun 20 00:00 archive
drwxr-xr-x   2 www-data root  4096 Jun 19 12:13 challenges
drwx------  11 root     root  4096 Jun 20 00:00 domains
-rw-------   1 root     root  1135 Sep 13  2017 fallback-cert.pem
-rw-------   1 root     root  1874 Sep 13  2017 fallback-privkey.pem
-rw-------   1 root     root    56 Oct 20  2017 httpd.json
-rw-------   1 root     root   116 Sep 15  2017 md_store.json
drwxr-xr-x   9 www-data root  4096 Jun 21 15:09 ocsp
drwxr-xr-x   2 www-data root  4096 Jun 20 00:00 staging
drwx------  10 root     root  4096 Jun 20 00:00 tmp
```

All the work that `mod_md` does is happening in the child processes of httpd and those run as `www-data` and not as `root`. So, for the to store the new certificates and other information, the `staging` area is prepared and given to `www-data` to write to.

**Comment by nickgearls** [comment]
Thanks a lot.
      It's very weird that the listeneers must have write access to the
      filesystem.
      Not the most secure :-(
      
    
    On 21-06-2021 15:22, Stefan Eissing
      wrote:
    
    
      
      On systems I am more familiar with, like debian, the User
        in the server is configured as www-data and then
        the permissions inside the md directory look like
        this:
      drwxr-xr-x   7 root     root  4096 Sep 30  2019 accounts
drwx------ 200 root     root 12288 Jun 20 00:00 archive
drwxr-xr-x   2 www-data root  4096 Jun 19 12:13 challenges
drwx------  11 root     root  4096 Jun 20 00:00 domains
-rw-------   1 root     root  1135 Sep 13  2017 fallback-cert.pem
-rw-------   1 root     root  1874 Sep 13  2017 fallback-privkey.pem
-rw-------   1 root     root    56 Oct 20  2017 httpd.json
-rw-------   1 root     root   116 Sep 15  2017 md_store.json
drwxr-xr-x   9 www-data root  4096 Jun 21 15:09 ocsp
drwxr-xr-x   2 www-data root  4096 Jun 20 00:00 staging
drwx------  10 root     root  4096 Jun 20 00:00 tmp

      All the work that mod_md does is happening in the
        child processes of httpd and those run as www-data
        and not as root. So, for the to store the new
        certificates and other information, the staging
        area is prepared and given to www-data to write
        to.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/icing/mod_md/issues/253#issuecomment-865029021",
"url": "https://github.com/icing/mod_md/issues/253#issuecomment-865029021",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by icing** [comment]
You would be more comfortable with this running in the `root` part of the server?

**Comment by nickgearls** [comment]
Definitely.
      In case a listener is compromised, it cannot access the keys (or
      the files used to generate the certificates).
      This is the behaviour of the conf part.
      
    
    On 22-06-2021 09:28, Stefan Eissing
      wrote:
    
    
      
      You would be more comfortable with this running in the root
        part of the server?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/icing/mod_md/issues/253#issuecomment-865669255",
"url": "https://github.com/icing/mod_md/issues/253#issuecomment-865669255",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by icing** [comment]
Well, it cannot access to keys the server uses. Those remain root only. It accesses the data in `staging` and keys in `staging` are stored encrypted.

Running in root has its own challenges: any compromised response or middle man inject could corrupt your system. `mod_md` is communicating with foreigners as well.


Some thought went into that, but I am open to ideas how to improve it.

**Comment by nickgearls** [comment]
mod_md is communicating with
      foreigners as well.
    Indeed, you got a point
    
    keys in staging are stored
      encrypted
    Good mitigation
    
    Maybe you found the best trade-off
    
    Thanks
    
    On 22-06-2021 09:40, Stefan Eissing
      wrote:
    
    
      
      Well, it cannot access to keys the server uses. Those remain
        root only. It accesses the data in staging and
        keys in staging are stored encrypted.
      Running in root has its own challenges: any compromised
        response or middle man inject could corrupt your system. mod_md
        is communicating with foreigners as well.
      Some thought went into that, but I am open to ideas how to
        improve it.

**Comment by marcstern** [comment]
I found the problem: mod_md recreates the md directory every time!
Here's the situation:
httpd is chrooted (in /chroot/apache).
I created a directory /chroot/apache/var/run/httpd/md.
I made a symlink from /chroot/apache/var/run/httpd/md to /var/run/httpd/md.
I fixed all permissions and SELinux contexts.
When I start httpd, it deletes the symlink and recreates the /var/run/httpd/md directory, so the master and the listeners never have the same content => game over.
Is there any way to avoid that problem?

**Comment by marcstern** [comment]
mod_md recreates the md directory if it's not owned by root:root
Probably not a bad idea, but these permissions and checks could be documented, this would have saved me hours troubleshooting ;-)

**Comment by icing** [comment]
I am accepting PRs! ;-)

Being busy right now, but this sounds fixable. If a dir/symlink exists, mod_md should probably leave it alone, I guess is the lesson to be learned here.

**Comment by marcstern** [comment]
At least, these actions should appear in the log at the "warn" level, to notify an operator that something unusual happened.
Thanks for your support Stefan

**Comment by marcstern** [comment]
Even when owned by root:root, it continues to recreate the directory!
What else can I check? There nothing in the log

**Comment by icing** [comment]
Can you build from `master` branch here? I just added some more logging in the store initialization that may help us finding out what is happening on your system.

**Comment by marcstern** [comment]
I tried but the trunk version is not compatible with 2.4.37

**Comment by icing** [comment]
@marcstern do you have a mod_md version number for me, as given in the initial md:info log on your system?

**Comment by marcstern** [comment]
It's the standard CentOS 8 version. It seems it's version 2.0.8 (bundled with httpd 2.4.37)

**Comment by icing** [comment]
Pls checkout https://github.com/icing/mod_md/tree/maintenance-2.0.x or switch on a cloned repository to branch `maintenance-2.0.x`.  That one should build against your Apache. I added the changes for more logging there.

**Comment by marcstern** [comment]
I'll do that and I'll let you know as soon as I get some feedback

**Comment by icing** [comment]
> I noticed that root has no "write" permission for staging:
drwxr-xr-x. 10 apache root  268 Jun 27 11:22 staging
> Is that normal?

Yes, read access is sufficient.

> Also, root has no access to /var/run/httpd/md/staging/registration.festival-of-science.com/*
-rw-r--r--. 1 apache apache 31846 Jun 28 09:49 job.json

Same here.


> Thanks a lot for your help

On a restart, while the server is root, it looks for a "staging/<domain>" directory which is complete, e.g. holds a new cert and key. It the *reads* cert and key (decrpyting key), archives the existing "domains/<domain>", creates a new "domains/<domain>" and writes the cert, key (unencrypted) and md.json etc.

All the "Permission denied" errors indicate that this is not working in your setup:

(13)Permission denied: purge staging/talisker.rewildgb.com (/var/run/httpd/md/staging/talisker.rewildgb.com)

The first thing in setting up a new staging directory is to purge any existing one. And that fails. Meaning, the server which commonly starts as root, is seemingly not root in your setup but already in the chroot jail and lacks the rights to manipulate the "md" store directories as it needs to.

At this point, you have to take the discussion to the CentOS guys who thought of this setup. Either they can make this work, or they need to exclude "mod_md" from their system. 

Please understand, I do not want to spend time analysing their thinking. But of course, I'll answer any questions they might have.

**Comment by marcstern** [comment]
I understand, but why delete the staging directory and not only its content?

**Comment by marcstern** [comment]
I think I found the way to have it working in the chroot.
I you want to add it in the doc:
the chrooted "md" directory must be have the following properties:
 - owner: root -> rwx
 - group: apache (or www-data or equivalent) -> rwx

Under Redhat (tested on 8), the normal & chrooted "md" directories must be have the following SELinux context:
system_u:object_r:httpd_var_lib_t:s0

**Comment by icing** [comment]
Would you want to make a PR against the README.md?

**Comment by icing** [comment]
Excellent news that you got it working!

**Comment by marcstern** [comment]
I don't have the time for the moment to learn the syntax, etc. but I'll try to get back on this later

**Comment by icing** [comment]
It's ok. I'll add it.

**Comment by marcstern** [comment]
thanks

**Comment by icing** [comment]
Added it. Hopes this works now for you and you'll get fresh certificates as needed!

**Comment by marcstern** [comment]
Thanks a lot for the wonderful support

**Comment by icing** [comment]
Thanks for staying patient. 😌
