### ISSUE TITLE
Config example with proxy balancer

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [icing/mod_md#254]
Hi folks,
how to configure mod_md with mod_proxy_balancer?
any sample?
thanks!

**Comment by icing** [comment]
These modules do not have any functional relation. Perhaps you could explain how you would like to combine them?

**Comment by ROBERT-MCDOWELL** [comment]
I just need to know where to set MD stuff. from the proxy-balancer.conf or vhost-ssl.conf?
i.e this is my actual config
---------------------
proxy-balancer.conf:
--------------------------------------------
SSLSessionCache        "shmcb:/usr/local/apache2/logs/ssl_scache(512000)"
SSLSessionCacheTimeout  300

# intermediate configuration, tweak to your needs
SSLProtocol             all -SSLv3
SSLCipherSuite          ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES128-CBC3-SHA:DES-CBC3-SHA:!DSS

SSLHonorCipherOrder     on
SSLCompression          off
SSLSessionTickets       off
SSLOptions              +StrictRequire +StdEnvVars

# OCSP Stapling
SSLUseStapling          on
SSLStaplingResponderTimeout 5
SSLStaplingReturnResponderErrors off
SSLStaplingCache        shmcb:/run/ocsp(128000)

<VirtualHost 192.168.0.100:443>
        ServerName secure.mywebsite.net

        Header add Set-Cookie "ROUTEID=.%{BALANCER_WORKER_ROUTE}e; path=/" env=BALANCER_ROUTE_CHANGED
        Header add Strict-Transport-Security "max-age=8740000; includeSubDomains; preload"

        SSLEngine on
        SSLProxyEngine on
        # followed 2 directives were set for being able to use self-signed certificates on farm nodes
        #SSLProxyCheckPeerCN off
        #SSLProxyCheckPeerName off

        <Proxy balancer://live-school>
                BalancerMember https://host1.mywebsite.net:4430 route=1
                BalancerMember https://host2.mywebsite.net:4430 route=2
                BalancerMember https://host3.mywebsite.net:4430 route=3
                BalancerMember https://host4.mywebsite.net:4430 route=4
                ProxySet stickysession=ROUTEID
        </Proxy>

        ProxyPass "/" "balancer://mywebsite/"
        ProxyPassReverse "/" "balancer://mywebsite/"

        SSLCertificateFile /etc/letsencrypt/live/mywebsite.net/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mywebsitenet.net/privkey.pem
</VirtualHost>

--------------------
vhost-ssl.conf
------------

<VirtualHost 192.168.0.111:4430>
        ServerName host1.mywebsite.net
        Protocols h2 http/1.1 http/1.0
        DocumentRoot /home/httpd/html/WebSites/mywebsite.net/html
        ServerPath /home/httpd/html/WebSites/mywebsite.net/html
        SSLEngine On
        SSLCertificateFile /etc/letsencrypt/live/mywebsite/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mywebsite/privkey.pem
</VirtualHost>

-----------------

Thanks for your advice!

**Comment by ROBERT-MCDOWELL** [comment]
I just need to know where to set MD stuff. from the proxy-balancer.conf or vhost-ssl.conf?
i.e this is my actual config

proxy-balancer.conf:

SSLSessionCache        "shmcb:/usr/local/apache2/logs/ssl_scache(512000)"
SSLSessionCacheTimeout  300

SSLProtocol             all -SSLv3
SSLCipherSuite          ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES128-CBC3-SHA:DES-CBC3-SHA:!DSS

SSLHonorCipherOrder     on
SSLCompression          off
SSLSessionTickets       off
SSLOptions              +StrictRequire +StdEnvVars

SSLUseStapling          on
SSLStaplingResponderTimeout 5
SSLStaplingReturnResponderErrors off
SSLStaplingCache        shmcb:/run/ocsp(128000)

<VirtualHost 192.168.0.100:443>
        ServerName secure.mywebsite.net

        Header add Set-Cookie "ROUTEID=.%{BALANCER_WORKER_ROUTE}e; path=/" env=BALANCER_ROUTE_CHANGED
        Header add Strict-Transport-Security "max-age=8740000; includeSubDomains; preload"

        SSLEngine on
        SSLProxyEngine on

        <Proxy balancer://live-school>
                BalancerMember https://host1.mywebsite.net:4430 route=1
                BalancerMember https://host2.mywebsite.net:4430 route=2
                BalancerMember https://host3.mywebsite.net:4430 route=3
                BalancerMember https://host4.mywebsite.net:4430 route=4
                ProxySet stickysession=ROUTEID
        </Proxy>

        ProxyPass "/" "balancer://mywebsite/"
        ProxyPassReverse "/" "balancer://mywebsite/"

        SSLCertificateFile /etc/letsencrypt/live/mywebsite.net/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mywebsitenet.net/privkey.pem
</VirtualHost>

vhost-ssl.conf

<VirtualHost 192.168.0.111:4430>
        ServerName host1.mywebsite.net
        Protocols h2 http/1.1 http/1.0
        DocumentRoot /home/httpd/html/WebSites/mywebsite.net/html
        ServerPath /home/httpd/html/WebSites/mywebsite.net/html
        SSLEngine On
        SSLCertificateFile /etc/letsencrypt/live/mywebsite/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mywebsite/privkey.pem

</VirtualHost>

Thanks for your advice!

**Comment by icing** [comment]
It is only a matter of taste. Apache configuration directives work in whatever file you place them. httpd starts with one file (commonly `httpd.conf` or `apache2.conf`, depending on your OS) and from there uses `Include` and [`IncludeOptional`](http://httpd.apache.org/docs/2.4/mod/core.html#includeoptional) to read other config files (which again my include yet other files).

All these are basically treated as one configuration text. The name of the file holds no special meaning.

You could make a general `md.conf` and include that somehere (some setups include all `*.conf` files on certain directories, so you'd just place it there and it gets picked up). In that general file, I would put the common setting s for `mod_md`. At least a [`MDCertificateAgreement accepted`](https://github.com/icing/mod_md#mdcertificateagreement--terms-of-service) is needed there.

In your conf files that define `VirtualHost`s you can add the configuration parts specific to those hosts. There are a bunch of how-to examples in the README.

**Comment by ROBERT-MCDOWELL** [comment]
Thanks icing for your advice, I knew already all what you said, my doubt is more about is it necessary to set the front-end reverse proxy with mod_md and the backends, or does it need  only the backends to be set with mod_md?

**Comment by icing** [comment]
`mod_md` provides certificates for your frontend https connections to `mod_ssl`, e.g. the `VirtualHost *:443` you define (or whatever port you use https on). It has nothing to do with `Proxy` settings.

**Comment by ROBERT-MCDOWELL** [comment]
ok understood. but as you can see on my config above I have to specify the SSLCert again on backends to make it work correctly or if I remove them the protocol is broken and all websites shows error 500.
I didn't find any good explanation of why should the backend must have SSLCert settings again.

**Comment by icing** [comment]
I see that you have a vhost for `host1.mywebsite.net`, have you added a `MDomain  host1.mywebsite.net` in your config so that mod_md knows it should provide a certificate for it?

**Comment by ROBERT-MCDOWELL** [comment]
not yet, I'm going to test it now. I just need to clarify my question which is
should mod_md must be set on the proxy balander server AND on the backends to
run properly?

**Comment by icing** [comment]
I assume your backend servers are other machines somewhere with their own SSL certificate. It's a bit confusing since your sample connection uses the same domain name for the frontend vhost and the backend urls.

```
browser  ---->  frontent (host1.mywebsite.net) --- proxy_balancer --> backend (someother.net)
                                           ^                                                                           ^
                                            |--- certificate1                                                    |--- certificate2
```

We are talking about `certificate1` here, right? proxy_balancer itself needs no certificate.

**Comment by ROBERT-MCDOWELL** [comment]
yes we are talking about certs only. so it confirms that both frontend and back end must have mod_md set to take care of the certificate. But does it mean that  the renew will be asked from both too and can create trouble?

**Comment by icing** [comment]
You get me a bit confused here. You have the same domain names for your frontend and backend servers?

**Comment by icing** [comment]
Let's Encrypt will only give you certificates for domains it can reach. Let's say you want a certificate for `mywebsite.net` and `backend.mywebsite.net` then both these domains need to be known in the public DNS. They can point to the same IP address.

So, you might have a setup like:
```
Internet <--> NAT Firefall <------ machine1 (Apache reverse proxy)
                              |--- machine2 (Apache backend)
```
and the firewall maps all incoming traffic for port 443 to machine1 443.

Then machine1 is the one that should talk to Lets Encrypt (LE). Since LE does itself connections to `mywebsite.net` and `backend.mywebsite.net` to make sure you own those domains, these "challenges" by LE arrive on your machine1 and it needs to answer them.

For this, you enable mod_md and configure:

```
MDomain mywebsite.net backend.mywebsite.net
```

which will give you (when everything works) one certificate valid for both domains.

To use this on your machine2 you need copy certificate and key there (or have a shared file system) and configure the apache on machine2 to use it. Easiest is probably to use the `SSLCertificateFile` as you have that already.

To make this copy every time your certificate is renewed, you an use `MDMessageCmd` to run a script of yours on the various events during renewal.

**Comment by ROBERT-MCDOWELL** [comment]
yes

**Comment by ROBERT-MCDOWELL** [comment]
ok gotcha, but in case of wildcard?

**Comment by icing** [comment]
See https://github.com/icing/mod_md#mdchallengedns01 for a description of what is involved for that.

**Comment by ROBERT-MCDOWELL** [comment]
argh, that's the point, dns01 is the reason why I came here.
it's hell to renew certs with dns validation with nsupdate because of the _acme-challenge key latency ...
So I think it's better to forget the wildcard.
now let's say I use the same host name for frontend and backend,
it just needs the frontend set with mod_md right?

**Comment by icing** [comment]
Yes. You can configure `mod_md` to obtain certificate even for names where you do not have `VirtualHost`s defined for. They just need to be reachable from the internet.

The easiest:

```
MDomain mywebsite.net
<VirtualHost *:443>
  ServerName mywebsite.net
  ServerAlias test1.mywebsite.net
  ServerAlias test2.mywebsite.net
  ...
  SSLEngine on
</Virtualhost>
```

**Comment by ROBERT-MCDOWELL** [comment]
Thanks for your help @icing!
I need now to switch my letsencrypt wildcard certs to single cert since I managed wildcards through dns-01 and rfc2136 certbot plugins which I hope I will never waste my time again on it! :)
