### ISSUE TITLE
Quoting domains for MDomain

### ISSUE THREAD

**Issue by chriscroome** [icing/mod_md#257]
I have found if you use this syntax:

```apache
  <MDomain "foo.example.com">
    MDStapling on
    MDRequireHttps permanent
  </MDomain>
```

It results in a directory named `/etc/apache2/md/domains/"foo.example.com"` -- the quotes are not removed and this is also the case in the JSON files, I expected the quotes to be removed, this might be a documentation oversight or a bug?

**Comment by icing** [comment]
True. The module does not follow the common Apache quoting mechanism, as DNS names may not contain spaces. However, I understand that this can be confusing to users.

I will add support for quoting to it configuration parameter overall in mod_md.
