### ISSUE TITLE
apache2ctl configtest

### ISSUE THREAD

**Issue by chriscroome** [icing/mod_md#260]
I realise that `apache2ctl configtest` doesn't always flag up errors in Apache configuration but it appears that there is currently no support for checking `mod_md` config -- you can get a `Syntax OK` and then find that a restart results in Apache not running due to `mod_md`  certificate issues.

Are they any plans to extend the tests run via `apache2ctl configtest` to include `mod_md` configuration and status?

**Comment by icing** [comment]
The syntax checks should run just like for any other module. When it comes to verifying the values, md is delaying some things to the post-config phase. Maybe that should be improved.

What exactly are the problems you encounter?

**Comment by chriscroome** [comment]
If a `VirtualHost` / `MDDomain` is configured and working with a RSA public key, for example:

```apache
<IfModule md_module>
  <MDomain example.org>
    MDPrivateKeys rsa3072
  </MDomain>
</IfModule>
```

If you then add an additional key:

```apache
<IfModule md_module>
  <MDomain example.org>
    MDPrivateKeys rsa3072 secp384r1
  </MDomain>
</IfModule>
```

And check the configuration:

```bash
apache2ctl configtest
Syntax OK
```
If you then restart it fails:

```bash
service apache2 restart
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
```

I don't know what is involved so perhaps it isn't possible for `apache2ctl configtest` to detect configuration issues like this, which prevent Apache starting?

Or perhaps I'm misunderstanding how to configure this module?

**Comment by icing** [comment]
Your understanding is correct. The code is not handling this right. Just added a test case.

**Comment by icing** [comment]
Ok, just committed a fix. If you can build here from master branch, it would be great to get a verification. But if not, my test case reproduced the startup fail, so I am quite confident this works.

If you are unable to build a new version, a workaround for now would be to
  
  * add the second private key spec
  * move the `md/domains/example.org` to `md/domains/example.org.old`
  * reload the server, your domain will then have a fallback certificate not recognized by browsers
  * await the renewal with all keys
  * reload the server again to activate

I'm aware that this leads to an interruption not feasible for live sites.

**Comment by chriscroome** [comment]
Thanks, [the instructions](https://github.com/icing/mod_md#build-and-install-mod_md) are based on there being a `configure` script, but I can't seem to find it?

```bash
git clone https://github.com/icing/mod_md.git
cd mod_md
./configure --with-apxs=/usr/bin/apxs --enable-werror
-bash: ./configure: No such file or directory
find ./ -name configure
```
What am I missing?

**Comment by chriscroome** [comment]
Ah, sorry I should have worked this out myself, I needed to also install `apache2-ssl-dev`, going to do some testing now...

**Comment by icing** [comment]
Sorry, was afk a bit yesterday. But you seem to have figured it out yourself.😀

**Comment by chriscroome** [comment]
No problem, I think it's all working (have only tested with one cert, I will test with some more later this morning), thanks very much for the swift fix :+1: .

**Comment by icing** [comment]
Please let me know if things continue to work, then I make a release version with this.

**Comment by chriscroome** [comment]
The problem with the Apache config causing Apache restarts to fail has been solved, at least I haven't been able to reproduce that issue since upgrading.

However for some domains the additional keys don't appear to be generated, even though for all domains I have ` MDPrivateKeys secp384r1 rsa3072`, for example with one domain I have:

```bash
tree static.example.org
static.example.org
|-- job.json
|-- md.json
|-- privkey.pem
`-- pubcert.pem
```

But others have:

```bash
tree www.example.org
www.example.org
|-- job.json
|-- md.json
|-- privkey.pem
|-- privkey.secp384r1.pem
|-- pubcert.pem
`-- pubcert.secp384r1.pem
```
But for these domains with both the JSON is only listing one, under the `cert` element.

This could be because of all my testing and manually messing around with the files, I should be able to spend some more time looking at this next week, thanks again for you very prompt help.

**Comment by icing** [comment]
Thanks for verifying.  maybe you can see more in `server-status` page or the `md-status` handler that shows if a domain is considered to need renewal or not.

It seems that not a lot of people have tested much with additional key types. There might be some surprises left that did not show in my own testing so far.

Anyways, I will make a release with this.

**Comment by icing** [comment]
v2.4.7 out. I will close this issue. Feel free to re-open if you find things not quite as they should be.

**Comment by chriscroome** [comment]
I've a development server I'm testing this on and I'm not sure if things are working as designed or if there is an issue, for example for [this VirtualHost](https://www.blog.wsh.webarchitects.org.uk/) I have this Apache config:

```apache
<IfModule md_module>
  <MDomain blog.wsh.webarchitects.org.uk>
    MDStapling on
    MDRequireHttps permanent
    MDPrivateKeys secp384r1 rsa3072
    MDCertificateFile /etc/ssl/le/blog.wsh.webarchitects.org.uk.fullchain.pem
    MDCertificateKeyFile /etc/ssl/le/blog.wsh.webarchitects.org.uk.key.pem
  </MDomain>
</IfModule>
...
<VirtualHost *:443>
  ServerName blog.wsh.webarchitects.org.uk
...
  SSLEngine on
  SSLCertificateFile            /etc/ssl/le/blog.wsh.webarchitects.org.uk.cert.pem
  SSLCertificateKeyFile         /etc/ssl/le/blog.wsh.webarchitects.org.uk.key.pem
  SSLCertificateChainFile       /etc/ssl/le/blog.wsh.webarchitects.org.uk.ca.pem
...
</VirtualHost>
```

I'm using Ansible to manage the server and I'm removing the `MDCertificateFile`, `MDCertificateKeyFile`, `SSLCertificateFile`, `SSLCertificateKeyFile` and `SSLCertificateChainFile` directives [when the status for all the keys specified in `MDPrivateKeys` is found to be set to `0`](https://git.coop/webarch/apache/-/blob/master/tasks/md_status.yml) and for this `VirtualHost` both keys and certs appear to be present on the filesystem:

```bash
cd domains/blog.wsh.webarchitects.org.uk/
tree
.
|-- job.json
|-- md.json
|-- privkey.pem
|-- privkey.secp384r1.pem
|-- pubcert.pem
`-- pubcert.secp384r1.pem

0 directories, 6 files
```
But the status is only reported for one of them, the `secp384r1` key:

```bash
lynx -dump http://localhost/md-status/blog.wsh.webarchitects.org.uk | jq
{
  "name": "blog.wsh.webarchitects.org.uk",
  "domains": [
    "blog.wsh.webarchitects.org.uk",
    "prod.blog.wsh.webarchitects.org.uk",
    "blog.wsh.webarch.org.uk",
    "www.blog.wsh.webarchitects.org.uk",
    "www.prod.blog.wsh.webarchitects.org.uk"
  ],
  "contacts": [
    "mailto:support@webarchitects.coop"
  ],
  "transitive": 1,
  "ca": {
    "account": "ACME-.letsencrypt.org-0000",
    "proto": "ACME",
    "url": "https://acme-v02.api.letsencrypt.org/directory",
    "agreement": "accepted"
  },
  "privkey": [
    {
      "type": "EC",
      "curve": "secp384r1"
    },
    {
      "type": "RSA",
      "bits": 3072
    }
  ],
  "state": 2,
  "renew-mode": 1,
  "renew-window": "45d",
  "warn-window": "10%",
  "require-https": "permanent",
  "must-staple": false,
  "proto": {
    "acme-tls/1": [
      "blog.wsh.webarchitects.org.uk",
      "prod.blog.wsh.webarchitects.org.uk",
      "blog.wsh.webarch.org.uk",
      "www.blog.wsh.webarchitects.org.uk",
      "www.prod.blog.wsh.webarchitects.org.uk"
    ]
  },
  "cert-files": [
    "/etc/ssl/le/blog.wsh.webarchitects.org.uk.fullchain.pem"
  ],
  "pkey-files": [
    "/etc/ssl/le/blog.wsh.webarchitects.org.uk.key.pem"
  ],
  "stapling": true,
  "cert": {
    "secp384r1": {
      "valid": {
        "from": "Tue, 14 Sep 2021 12:35:01 GMT",
        "until": "Mon, 13 Dec 2021 12:35:00 GMT"
      },
      "serial": "03CB64AA9AC10219C23E53A35DAC00D230BD",
      "sha256-fingerprint": "c21316a0eddad4634a15e5e86c1a5aa2f67d554e8733cd802ee16abcd692c88e",
      "ocsp": {
        "status": "good",
        "valid": {
          "from": "Fri, 17 Sep 2021 01:00:00 GMT",
          "until": "Fri, 24 Sep 2021 01:00:00 GMT"
        },
        "renewal": {
          "name": "blog.wsh.webarchitects.org.uk",
          "finished": true,
          "notified": false,
          "notified-renewed": false,
          "last-run": "Fri, 17 Sep 2021 09:51:40 GMT",
          "errors": 0,
          "last": {
            "status": 0,
            "detail": "certificate status is GOOD, status valid Fri, 17 Sep 2021 01:00:00 GMT - Fri, 24 Sep 2021 01:00:00 GMT",
            "activity": "status of certid c38fa7df926902922eed016246bda65e37214958, reading response"
          },
          "log": {
            "entries": [
              {
                "when": "Fri, 17 Sep 2021 09:51:41 GMT",
                "type": "message-ocsp-renewed"
              },
              {
                "when": "Fri, 17 Sep 2021 09:51:41 GMT",
                "type": "finished"
              },
              {
                "when": "Fri, 17 Sep 2021 09:51:41 GMT",
                "type": "progress",
                "detail": "status of certid c38fa7df926902922eed016246bda65e37214958, reading response: certificate status is GOOD, status valid Fri, 17 Sep 2021 01:00:00 GMT - Fri, 24 Sep 2021 01:00:00 GMT"
              },
              {
                "when": "Fri, 17 Sep 2021 09:51:41 GMT",
                "type": "progress",
                "detail": "status of certid c38fa7df926902922eed016246bda65e37214958, reading response"
              },
              {
                "when": "Fri, 17 Sep 2021 09:51:40 GMT",
                "type": "progress",
                "detail": "status of certid c38fa7df926902922eed016246bda65e37214958, contacting http://r3.o.lencr.org"
              },
              {
                "when": "Fri, 17 Sep 2021 09:51:40 GMT",
                "type": "starting"
              }
            ]
          }
        }
      }
    },
    "valid": {
      "from": "Tue, 14 Sep 2021 12:35:01 GMT",
      "until": "Mon, 13 Dec 2021 12:35:00 GMT"
    }
  },
  "renew-at": "Fri, 29 Oct 2021 12:35:00 GMT",
  "watched": true
}
```
Is this to be expected? Will the other key also be used when the cert is due for renewal?

**Comment by icing** [comment]
You should remove the `MDCertificateFile` and `MDCertificateKeyFile` from the MDomain. The module gets confused by the mixing of static files and ACME related directives. That is why you see the partial status reporting.

**Comment by chriscroome** [comment]
Thanks, the status for both certs is reported after commenting out `MDCertificateFile` and `MDCertificateKeyFile`, I was automatically removing these directives using Ansible when both `cert.secp384r1.renewal.last.status` and `cert.rsa.renewal.last.status`  were both equal to `0`, should I be removing these directives (and the `SSLCertificateFile`, `SSLCertificateKeyFile` and `SSLCertificateChainFile` directives) when just one of the certs has a status of `0` or should I be checking for something else?

**Comment by icing** [comment]
I would just check on `status['renewal']['finished'] == True` which should be sufficient to verify that the renewal was successful.
