### ISSUE TITLE
error: undefined symbol: EVP_MD_CTX_new

### ISSUE THREAD

**Issue by juvenrui** [icing/mod_md#261]
Hi:

     Update to version 1.15.24. Run 'apachectl graceful', but error: 'mod_http2.so: undefined symbol: EVP_MD_CTX_new'.

**Comment by icing** [comment]
Did you build it yourself? Is the openssl library you build it with the same that is used in your server?

**Comment by juvenrui** [comment]
Use centos's yum upgrade.

**Comment by icing** [comment]
Hmm, then you have to talk to the CentOS people, I'm afraid, since what they built does not match your other installation. OpenSSL says:

```
The EVP_MD_CTX_create() and EVP_MD_CTX_destroy() functions were 
renamed to EVP_MD_CTX_new() and EVP_MD_CTX_free() in OpenSSL 1.1.0, respectively.
```

Also: <https://stackoverflow.com/questions/46768071/openssl-linking-undefined-reference-evp-md-ctx-new-and-fre>

You seem to have an OpenSSL v1.0 on your system?

**Comment by juvenrui** [comment]
> Hmm, then you have to talk to the CentOS people, I'm afraid, since what they built does not match your other installation. OpenSSL says:
> 
> ```
> The EVP_MD_CTX_create() and EVP_MD_CTX_destroy() functions were 
> renamed to EVP_MD_CTX_new() and EVP_MD_CTX_free() in OpenSSL 1.1.0, respectively.
> ```
> 
> Also: https://stackoverflow.com/questions/46768071/openssl-linking-undefined-reference-evp-md-ctx-new-and-fre
> 
> You seem to have an OpenSSL v1.0 on your system?

Yes, openssl version is: 'OpenSSL 1.0.2k-fips  26 Jan 2017'.  I can try to upgrade to v1.11.

Thank you 🙏

**Comment by icing** [comment]
So, whoever built the mod_md package was using an OpenSSL v1.1. In case you cannot move to that version, I believe you have to downgrade your mod_md package, unfortunately, it seems. Or talk to the persons building the packages.

Since there is nothing I can do about this, I will close this ticket.
