### ISSUE TITLE
Let's encrypt alternate chain selection

### ISSUE THREAD

**Issue by cedric-marcone** [icing/mod_md#264]
Hello @icing !

Today is the day "DST Root CA X3" expired... :(
Some consumers of my API endpoints are not happy with current Letsencrypt default certificates chain.

`End-entity certificate ← R3 ← ISRG Root X1 ← DST Root CA X3`

I'd like to select the alternate chain :

`End-entity certificate ← R3 ← ISRG Root X1`

With certbot I could specify a `--preferred-chain "ISRG Root X1"` option.

Is there something similar for mod_md ?

**Comment by icing** [comment]
Hi @cedric-marcone!

I wrote a description and a script on how to remove the problematic chain certificate: 

https://github.com/icing/mod_md#the-lets-encrpyt-expiration

This can be installed to run automatically on every renewal. Hope this works for you!

**Comment by cedric-marcone** [comment]
Woahh ! Straight to the point on such a short notice !
Very clever
...and ou made me discover MdMessageCmd.
Thank you @icing, you're the best :)

**Comment by moschlar** [comment]
Quick note, since I made a PR to fix the typo in the headline, the link above doesn't work anymore, but this one does:
https://github.com/icing/mod_md#the-lets-encrypt-expiration
;-)

**Comment by whereisaaron** [comment]
Thanks @icing for the fix script. I can see that would be quite effective as it amends the chain before the certificate is ever installed. Unless you can unlucky timing with a restart that would catch most cases.

I think though there is (now) a proper/official way to do this. The ACME v2 spec allows the CA to provide alternate chains as part of the certificate download (ACME draft v18 section 7.4.2). And Let's Encrypt does this for "ISRG Root X1" alternative chain.

https://datatracker.ietf.org/doc/html/draft-ietf-acme-acme-18#section-7.4.2
![image](https://user-images.githubusercontent.com/1109585/197389843-6efacc25-5656-484d-b261-a3637a10e994.png)

Selecting which chain to use is left up to the ACME client, but other ACME clients like `acme.sh`, `Certbot`, and `cert-manager` include the option to nominate a 'preferred chain' (name, sub-string, or ordered list of) and then that is the one the ACME client installed. `mod_md` could add e.g. `MDPreferredChain` to select which chain in the cert download to use. Something for the backlog anyway! 😀

https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain
```
acme.sh  --issue -d example.com .....  --test    --preferred-chain  "X1"
```

https://cert-manager.io/docs/configuration/acme/#alternative-certificate-chains
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
```

https://eff-certbot.readthedocs.io/en/stable/using.html#certbot-command-line-options
![image](https://user-images.githubusercontent.com/1109585/197390051-5c327eae-07c1-4bf2-9978-1998f9447b71.png)
