### ISSUE TITLE
Challenge renewal: Connection refused

### ISSUE THREAD

**Issue by cfxda** [icing/mod_md#268]
Hi icing,
I am currrently facing the following issue in testsetup with the the letsencrypt staging env:
When requesting the challenge verification(tls-alpn-01) it can happen that the host is not reachable from the letsencrypt staging 
Resulting in an error:
`ACME server authz: challenge 'invalid' for ***domain*** at https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/id . Exact response was: {"identifier":{"type":"dns","value":"***domain***"},"status":"invalid","expires":"2021-10-15T15:48:53Z","challenges":[{"type":"tls-alpn-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:connection","detail":"Connection refused","status":400},"url":"https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/id/tCNB2g","token":"HIrAlkWbO-MVwsF-pp92geBF2iXlOt8KE0ZUgtyzG5Ut6w","validationRecord":[{"hostname":"***domain***","port":"443","addressesResolved":["ip"],"addressUsed":"ip"}],"validated":"2021-10-08T15:48:55Z"}]}`

Mod md than starts a retry with the same challenge some minutes later ending in the exact same error message again.
Any ideas why? Might it be related to the boulder retry limitation "Boulder does not implement the ability to retry challenges or the Retry-After header"(https://github.com/letsencrypt/boulder/blob/master/docs/acme-divergences.md#section-82)

**Comment by icing** [comment]
I read this as lets encrypt is unable to open a connection to your host on port 443. 

Apache will retry with increasing delays. Have you verified that your domain is reachable on that port from the public internet?

**Comment by cfxda** [comment]
Sorry took a bit longer. It solves my problem, but maybe introduces a potential new one:
Through the new order the error counter is reset as well as the timing:
Example log "encountered error for the 1. time, next run in 2 seconds"
This will lead to a high risk spamming the CA with tons of request before e.g. fixing the connection issue.
Would it be possible to start a new "throttled order"?
