### ISSUE TITLE
who restarts httpd?

### ISSUE THREAD

**Issue by igalic** [icing/mod_md#270]
I've now run a few times into the issue where a site was presenting an invalid certificate.
It's not clear from the documentation here, or @ apache: http://httpd.apache.org/docs/2.4/mod/mod_md.html that mod_md will restart httpd.

I can see a function that would be useful for that purpose: 
https://github.com/icing/mod_md/blob/5e34c14e2b7ad195f662290c26481cbc3a249fe0/src/mod_md_os.c#L76-L85
but I don't see it called anywhere!

**Comment by igalic** [comment]
okay thank you very much for clarifying this.
i've now added `@weekly` cron job to do graceful reloads.

I think a hint towards this should be put into the getting started doc, and yeah, that code should be removed 😅

**Comment by icing** [comment]
Added a section to the README: https://github.com/icing/mod_md#how-to-manage-server-reloads

Please review.
