### ISSUE TITLE
Question on MDStapleOthers

### ISSUE THREAD

**Issue by daum3ns** [icing/mod_md#274]
Hello, 

Is it possible to only staple a subset of the "other" domains?
Lets say i have 3 domains:

- a.com (MDomain)
- b.com ("other")
- c.com ("other")

Is it possible to use mod_md for OCSP Stapling for domains a.com and b.com, but not c.com?? 

My understanding of the directive is that this will not work at the moment.. 
What do you think about an extension like this:

MDStapleOthers off                           --> same as it is at the moment
MDStapleOthers all                           --> Staple ALL other domains (same as _MDStapleOthers on_ at the moment)
MDStapleOthers [list of domains]   --> only staple the domains configured in the directive

So to achieve above example the configuration would be:
```
<MDomain a.com>
   MDStapling On
</MDomain> 
MDStapleOthers b.com

```
thanks in advance for your help!

**Comment by icing** [comment]
Assuming you use this with `mod_ssl`, it would result in mod_ssl's stapling to become active for c.com. But your intention is that there should be no stapling at all for c.com?

Can you elaborate a bit when that would be useful?

**Comment by daum3ns** [comment]
Yes you are correct, the idea is to have no stapling at all for c.com. 
But if i would disable mod_ssl's stapling with _SSLUseStapling off_ , then only mod_md is active right? 

It's just about the ability to configure stapling per VHost like it is possible with mod_ssl...

**Comment by icing** [comment]
Without time to verify myself right now, I think when mod_ssl stapling is not on, it will not ask mod_md for the actual stapling data.

**Comment by daum3ns** [comment]
hm in my experiments it looks like it works.
config: 
```
  SSLEngine on
  SSLCertificateKeyFile key.pem
  SSLCertificateFile cert.pem
  SSLCACertificateFile ca.cert.pem
  SSLUseStapling off

  MDStapling On
  MDStapleOthers On
```
after a graceful mod_md performs the ocsp request

so this would in general allow the modification i assume...

**Comment by daum3ns** [comment]
i did some more testing and i found out that this seems to work already... 
configuration:

```
# globally set MDStapleOthers to Off
MDStapling On
SSLEngine on
SSLUseStapling off
MDStapleOthers Off

<VirtualHost  .... >
  ServerName a.com
  SSLCertificateKeyFile a.com.key.pem
  SSLCertificateFile a.com.cert.pem
  SSLCACertificateFile ca.cert.pem
  SSLUseStapling off
  MDStapleOthers On
</VirtualHost>

<VirtualHost .... >
  ServerName b.com
  SSLCertificateKeyFile b.com.key.pem
  SSLCertificateFile b.com.cert.pem
  SSLCACertificateFile ca.cert.pem
  SSLUseStapling off
  MDStapleOthers Off
</VirtualHost>
```

both domains are not managed by mod_md, but i can switch it on and off per VHost.
maybe this is worth a testcase and a note in the docs...? 

unfortunately the ocsp tests get skipped in my setup, i don't yet know why (pebble is installed)

**Comment by icing** [comment]
I need to mention that in the docs, yes. This use case just never occurred to me. 

Pebble does not have a OCSP responder and does not place such urls in the certificates. One needs to test with boulder to have thoses tests run.
