### ISSUE TITLE
Issue with TLS-ALPN-01 challenge

### ISSUE THREAD

**Issue by Jan-E** [icing/mod_md#277]
Let’s Encrypt will be revoking active certificates:

> All active certificates that were issued and validated with the TLS-ALPN-01 challenge before 00:48 UTC on 26 January 2022 when our fix was deployed are considered mis-issued.

https://community.letsencrypt.org/t/2022-01-25-issue-with-tls-alpn-01-validation-method/170450 

Should mod_md users take action?

**Comment by icing** [comment]
I have written a blog about how to see if you are affected and what to do about it: https://github.com/icing/blog/blob/main/lets-encrypt-trouble.md

**Comment by Jan-E** [comment]
Ok, thanks. I will leave this issue open for a while for others that have the same question. Can be closed in a few days.
