### ISSUE TITLE
one new domain fail

### ISSUE THREAD

**Issue by fuzzy17** [icing/mod_md#278]
On Windows Apache 2.4.52 trying to add another host that does not have ssl setup yet.  The server does not start.

Trace enabled:

LogLevel info md:trace2 ssl:notice

main server log:

[Mon Feb 07 16:39:35.328406 2022] [md:trace1] [pid 3808:tid 704] mod_md.c(451): AH10037: server seems reachable via http: and reachable via https:
[Mon Feb 07 16:39:35.328406 2022] [md:trace1] [pid 3808:tid 704] mod_md.c(705): AH10039: Completed MD[www.myhost.com, CA=(null), Proto=ACME, Agreement=accepted, renew-mode=1 renew_window=33%, warn_window=10%
[Mon Feb 07 16:39:35.328406 2022] [md:debug] [pid 3808:tid 704] mod_md.c(596): AH10041: Server www.myhost.com:0 matches md www.myhost.com (config www.myhost.com[default, default]) for domain www.myhost.com, has now 1 MDs
[Mon Feb 07 16:39:35.328406 2022] [md:debug] [pid 3808:tid 704] md_reg.c(818): sync MDs, start
[Mon Feb 07 16:39:35.328406 2022] [md:debug] [pid 3808:tid 704] md_reg.c(881): sync MDs, 0 existing, 1 moved, 0 new.
[Mon Feb 07 16:39:35.328406 2022] [md:trace2] [pid 3808:tid 704] md_reg.c(1155): www.myhost.com: nothing staged
[Mon Feb 07 16:39:35.344031 2022] [ssl:emerg] [pid 3808:tid 704] AH02311: Fatal error initialising mod_ssl, exiting. See (null) for more information
AH00016: Configuration Failed

vhost log

[Mon Feb 07 16:39:35.344031 2022] [md:trace1] [pid 3808:tid 704] mod_md.c(1236): hook ssl_add_cert_files for www.myhost.com
[Mon Feb 07 16:39:35.344031 2022] [md:debug] [pid 3808:tid 704] mod_md.c(1120): AH10113: get_certificates called for vhost www.myhost.com.
[Mon Feb 07 16:39:35.344031 2022] [md:trace1] [pid 3808:tid 704] mod_md.c(1268): hook ssl_add_fallback_cert_files for www.myhost.com
[Mon Feb 07 16:39:35.344031 2022] [md:debug] [pid 3808:tid 704] mod_md.c(1120): AH10113: get_certificates called for vhost www.myhost.com.
[Mon Feb 07 16:39:35.344031 2022] [ssl:emerg] [pid 3808:tid 704] AH02572: Failed to configure at least one certificate and key for www.myhost.com:443
[Mon Feb 07 16:39:35.344031 2022] [ssl:emerg] [pid 3808:tid 704] SSL Library Error: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no certificate assigned

Relevant httpd.conf:

`Listen 10.15.1.10:80

<VirtualHost *:80>

ServerName [www.myhost.com](http://www.myhost.com/)

Include conf/rewrites.conf

CustomLog "|D:/Apache_files/cronolog.exe D:/logs/access_%Y-%m-%d.log" combined
ErrorLog  "|D:/Apache_Files/cronolog.exe D:/logs/error_%Y-%m-%d.log"

</VirtualHost>

MDomain [www.myhost.com](http://www.myhost.com/)

LISTEN 11.22.33.44:443

<VirtualHost 11.22.33.44:443>
   ServerName [www.myhost.com](http://www.myhost.com/)
   ServerAlias myhost.com

   SSLEngine on

SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH

	SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1

	SSLOptions +StrictRequire +StdEnvVars -ExportCertData
	SSLProtocol -all +TLSv1.2 +TLSv1.3
	SSLCompression Off
	SSLHonorCipherOrder On
	SSLCipherSuite SSL ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384
	SSLCipherSuite TLSv1.3 TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384

	SSLOpenSSLConfCmd ECDHParameters secp521r1
	SSLOpenSSLConfCmd Curves sect571r1:sect571k1:secp521r1:sect409k1:sect409r1:secp384r1:sect283k1:sect283r1:secp256k1:prime256v1

	SSLOpenSSLConfCmd SignatureAlgorithms rsa_pss_rsae_sha512:rsa_pss_rsae_sha256:ECDSA+SHA512:ECDSA+SHA256:RSA+SHA512:RSA+SHA256
	SSLOpenSSLConfCmd ClientSignatureAlgorithms rsa_pss_rsae_sha512:rsa_pss_rsae_sha256:ECDSA+SHA512:ECDSA+SHA256:RSA+SHA512:RSA+SHA256	

	SSLHonorCipherOrder On

	Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
	Header always set X-Frame-Options DENY
	Header always set X-Content-Type-Options nosniff

	# Requires Apache >= 2.4
	# prevent CRIME attack
	SSLCompression off 

	# Requires Apache >= 2.4  (2.5?)
	#SSLUseStapling on 
	#SSLStaplingCache "shmcb:logs/stapling-cache(150000)" 

	# Requires Apache >= 2.4.11, Using them without restarting the web server with an appropriate frequency (e.g. daily) compromises perfect forward secrecy.
	SSLSessionTickets Off
   
   Include conf/_rewrites.conf

   CustomLog "|D:/Apache_files/cronolog.exe D:/logs/access_%Y-%m-%d.log" combined
   ErrorLog  "|D:/Apache_Files/cronolog.exe D:/logs/error_%Y-%m-%d.log"

</VirtualHost>
`

**Comment by fuzzy17** [comment]
I changed virtualhost from ip:443 to *:443 and ended up creating cert with certbot and configuring the cert from cerbot.   The server at least starts, but I get:

main log appears to be ok:


[Tue Feb 08 07:48:22.309462 2022] [md:trace1] [pid 7660:tid 700] mod_md.c(868): AH10070: initializing post config dry run
[Tue Feb 08 07:48:22.309462 2022] [md:trace1] [pid 7660:tid 700] mod_md.c(451): AH10037: server seems reachable via http: and reachable via https:
[Tue Feb 08 07:48:22.309462 2022] [md:trace1] [pid 7660:tid 700] mod_md.c(705): AH10039: Completed MD[www.myhost.com, CA=(null), Proto=ACME, Agreement=accepted, renew-mode=1 renew_window=33%, warn_window=10%
[Tue Feb 08 07:48:22.309462 2022] [md:debug] [pid 7660:tid 700] mod_md.c(596): AH10041: Server www.myhost.com:0 matches md www.myhost.com (config www.myhost.com[default, default]) for domain www.myhost.com, has now 1 MDs
[Tue Feb 08 07:48:22.309462 2022] [md:debug] [pid 7660:tid 700] md_reg.c(818): sync MDs, start
[Tue Feb 08 07:48:22.309462 2022] [md:debug] [pid 7660:tid 700] md_reg.c(881): sync MDs, 1 existing, 0 moved, 0 new.
[Tue Feb 08 07:48:22.309462 2022] [md:trace1] [pid 7660:tid 700] md_acme_drive.c(531): www.myhost.com: init_base driver
[Tue Feb 08 07:48:22.309462 2022] [md:debug] [pid 7660:tid 700] md_reg.c(1076): www.myhost.com: init done
[Tue Feb 08 07:48:22.309462 2022] [md:debug] [pid 7660:tid 700] md_acme_drive.c(912): www.myhost.com: preload start
[Tue Feb 08 07:48:22.325087 2022] [md:trace1] [pid 7660:tid 700] md_store_fs.c(688): start remove of md staging/www.myhost.com/order.json
[Tue Feb 08 07:48:22.325087 2022] [md:debug] [pid 7660:tid 700] md_acme_acct.c(397): acct_id_for_md www.myhost.com -> (null)
[Tue Feb 08 07:48:22.340712 2022] [md:trace2] [pid 7660:tid 700] md_store_fs.c(634): storing in D:/apache24/md/accounts/ACME-.letsencrypt.org-0000/account.json
[Tue Feb 08 07:48:22.340712 2022] [md:trace2] [pid 7660:tid 700] md_store_fs.c(634): storing in D:/apache24/md/accounts/ACME-.letsencrypt.org-0000/account.pem
[Tue Feb 08 07:48:22.356339 2022] [md:trace2] [pid 7660:tid 700] md_store_fs.c(634): storing in D:/apache24/md/tmp/www.myhost.com/md.json
[Tue Feb 08 07:48:22.356339 2022] [md:trace2] [pid 7660:tid 700] md_store_fs.c(634): storing in D:/apache24/md/tmp/www.myhost.com/privkey.pem
[Tue Feb 08 07:48:22.356339 2022] [md:trace2] [pid 7660:tid 700] md_store_fs.c(634): storing in D:/apache24/md/tmp/www.myhost.com/pubcert.pem
[Tue Feb 08 07:48:22.356339 2022] [md:debug] [pid 7660:tid 700] md_result.c(254): md[www.myhost.com] while[saving staged md/privkey/pubcert] detail[saved staged data successfully]
[Tue Feb 08 07:48:22.356339 2022] [md:debug] [pid 7660:tid 700] md_result.c(254): md[www.myhost.com] while[saving staged md/privkey/pubcert] detail[saved staged data successfully]
[Tue Feb 08 07:48:22.356339 2022] [md:trace2] [pid 7660:tid 700] md_store_fs.c(634): storing in D:/apache24/md/tmp/www.myhost.com/job.json
[Tue Feb 08 07:48:22.371959 2022] [md:trace1] [pid 7660:tid 700] md_store_fs.c(981): (OS 2)The system cannot find the file specified.  : using archive dir: D:/apache24/md/archive/www.myhost.com.1
[Tue Feb 08 07:48:22.403216 2022] [md:trace2] [pid 7660:tid 700] md_store_fs.c(749): purge staging/www.myhost.com (D:/apache24/md/staging/www.myhost.com)
[Tue Feb 08 07:48:22.403216 2022] [md:trace2] [pid 7660:tid 700] md_store_fs.c(634): storing in D:/apache24/md/tmp/www.myhost.com/job.json
[Tue Feb 08 07:48:22.403216 2022] [md:trace1] [pid 7660:tid 700] md_reg.c(1190): www.myhost.com: load done
[Tue Feb 08 07:48:22.403216 2022] [md:info] [pid 7660:tid 700] AH10068: www.myhost.com: staged set activated
[Tue Feb 08 07:48:22.434464 2022] [md:trace2] [pid 7660:tid 700] mod_md.c(1016): post_config done
AH00558: httpd.exe: Could not reliably determine the server's fully qualified domain name, using 207.18.someip. Set the 'ServerName' directive globally to suppress this message
[Tue Feb 08 07:48:23.731342 2022] [md:info] [pid 7660:tid 700] AH10071: mod_md (v2.4.10), initializing...
[Tue Feb 08 07:48:23.731342 2022] [md:debug] [pid 7660:tid 700] mod_md.c(451): AH10037: server seems reachable via http: and reachable via https:
[Tue Feb 08 07:48:23.731342 2022] [md:debug] [pid 7660:tid 700] mod_md.c(705): AH10039: Completed MD[www.myhost.com, CA=(null), Proto=ACME, Agreement=accepted, renew-mode=1 renew_window=33%, warn_window=10%
[Tue Feb 08 07:48:23.731342 2022] [md:debug] [pid 7660:tid 700] mod_md.c(596): AH10041: Server www.myhost.com:0 matches md www.myhost.com (config www.myhost.com[default, default]) for domain www.myhost.com, has now 1 MDs
[Tue Feb 08 07:48:23.731342 2022] [md:debug] [pid 7660:tid 700] md_reg.c(818): sync MDs, start
[Tue Feb 08 07:48:23.731342 2022] [md:debug] [pid 7660:tid 700] md_reg.c(881): sync MDs, 1 existing, 0 moved, 0 new.
[Tue Feb 08 07:48:23.731342 2022] [md:trace2] [pid 7660:tid 700] md_reg.c(1155): www.myhost.com: nothing staged
[Tue Feb 08 07:48:23.731342 2022] [ssl:warn] [pid 7660:tid 700] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Tue Feb 08 07:48:23.746970 2022] [md:trace1] [pid 7660:tid 700] mod_md.c(742): checking duplicate ssl assignments
[Tue Feb 08 07:48:23.746970 2022] [md:trace2] [pid 7660:tid 700] mod_md.c(968): md{www.myhost.com}: auto_add
[Tue Feb 08 07:48:23.746970 2022] [md:trace1] [pid 7660:tid 700] mod_md.c(515): md[www.myhost.com]: auto add domains
[Tue Feb 08 07:48:23.746970 2022] [md:debug] [pid 7660:tid 700] mod_md.c(550): AH10168: www.myhost.com: no https server_rec found for www.myhost.com
[Tue Feb 08 07:48:23.746970 2022] [md:trace2] [pid 7660:tid 700] mod_md.c(973): md{www.myhost.com}: check_usage
[Tue Feb 08 07:48:23.746970 2022] [md:trace2] [pid 7660:tid 700] mod_md.c(977): md{www.myhost.com}: sync_finish
[Tue Feb 08 07:48:23.746970 2022] [md:trace2] [pid 7660:tid 700] md_reg.c(214): md{www.myhost.com}: check cert rsa
[Tue Feb 08 07:48:23.746970 2022] [md:debug] [pid 7660:tid 700] md_reg.c(234): md{www.myhost.com}: certificate(0) is ok
[Tue Feb 08 07:48:23.746970 2022] [md:trace2] [pid 7660:tid 700] md_reg.c(253): md{www.myhost.com}: state=2, (null)
[Tue Feb 08 07:48:23.746970 2022] [md:debug] [pid 7660:tid 700] md_reg.c(908): loading md www.myhost.com
[Tue Feb 08 07:48:23.746970 2022] [md:debug] [pid 7660:tid 700] md_reg.c(910): loaded md www.myhost.com
[Tue Feb 08 07:48:23.746970 2022] [md:debug] [pid 7660:tid 700] md_reg.c(947): saving md www.myhost.com
[Tue Feb 08 07:48:23.746970 2022] [md:trace2] [pid 7660:tid 700] md_store_fs.c(634): storing in D:/apache24/md/domains/www.myhost.com/md.json
[Tue Feb 08 07:48:23.762591 2022] [md:debug] [pid 7660:tid 700] md_reg.c(951): sync MDs, finish done
[Tue Feb 08 07:48:23.762591 2022] [md:trace2] [pid 7660:tid 700] mod_md.c(985): init_cert_watch
[Tue Feb 08 07:48:23.762591 2022] [md:trace1] [pid 7660:tid 700] md_acme_drive.c(531): www.myhost.com: init_base driver
[Tue Feb 08 07:48:23.762591 2022] [md:trace1] [pid 7660:tid 700] md_acme_drive.c(611): www.myhost.com: init driver
[Tue Feb 08 07:48:23.762591 2022] [md:debug] [pid 7660:tid 700] md_reg.c(1076): www.myhost.com: init done
[Tue Feb 08 07:48:23.762591 2022] [md:trace2] [pid 7660:tid 700] mod_md.c(988): cleanup challenges
[Tue Feb 08 07:48:23.762591 2022] [md:debug] [pid 7660:tid 700] mod_md.c(997): AH10074: 1 out of 1 mds need watching
[Tue Feb 08 07:48:23.762591 2022] [md:trace1] [pid 7660:tid 700] mod_md_drive.c(309): md(www.myhost.com): state=2, created drive job
[Tue Feb 08 07:48:23.762591 2022] [md:debug] [pid 7660:tid 700] mod_md_drive.c(342): AH10067: register md renew watchdog(_md_renew_)
[Tue Feb 08 07:48:23.762591 2022] [md:trace1] [pid 7660:tid 700] mod_md.c(1008): no ocsp to manage
[Tue Feb 08 07:48:23.762591 2022] [md:trace2] [pid 7660:tid 700] mod_md.c(1016): post_config done
[Tue Feb 08 07:48:23.762591 2022] [mpm_winnt:notice] [pid 7660:tid 700] AH00455: Apache/2.4.52 (Win64) OpenSSL/1.1.1m configured -- resuming normal operations
[Tue Feb 08 07:48:23.762591 2022] [mpm_winnt:notice] [pid 7660:tid 700] AH00456: Apache Lounge VS16 Server built: Dec 17 2021 10:17:38
[Tue Feb 08 07:48:23.762591 2022] [core:notice] [pid 7660:tid 700] AH00094: Command line: 'D:\\Apache24\\bin\\httpd.exe -d D:/apache24'
[Tue Feb 08 07:48:23.840713 2022] [mpm_winnt:notice] [pid 7660:tid 700] AH00418: Parent: Created child process 6988
AH00558: httpd.exe: Could not reliably determine the server's fully qualified domain name, using 207.18.someip. Set the 'ServerName' directive globally to suppress this message
[Tue Feb 08 07:48:28.871974 2022] [md:trace1] [pid 6988:tid 636] mod_md.c(868): AH10070: initializing post config dry run
[Tue Feb 08 07:48:28.871974 2022] [md:trace1] [pid 6988:tid 636] mod_md.c(451): AH10037: server seems reachable via http: and reachable via https:
[Tue Feb 08 07:48:28.871974 2022] [md:trace1] [pid 6988:tid 636] mod_md.c(705): AH10039: Completed MD[www.myhost.com, CA=(null), Proto=ACME, Agreement=accepted, renew-mode=1 renew_window=33%, warn_window=10%
[Tue Feb 08 07:48:28.871974 2022] [md:debug] [pid 6988:tid 636] mod_md.c(596): AH10041: Server www.myhost.com:0 matches md www.myhost.com (config www.myhost.com[default, default]) for domain www.myhost.com, has now 1 MDs
[Tue Feb 08 07:48:28.871974 2022] [md:debug] [pid 6988:tid 636] md_reg.c(818): sync MDs, start
[Tue Feb 08 07:48:28.871974 2022] [md:debug] [pid 6988:tid 636] md_reg.c(881): sync MDs, 1 existing, 0 moved, 0 new.
[Tue Feb 08 07:48:28.871974 2022] [md:trace2] [pid 6988:tid 636] md_reg.c(1155): www.myhost.com: nothing staged
[Tue Feb 08 07:48:28.903227 2022] [md:trace2] [pid 6988:tid 636] mod_md.c(1016): post_config done
AH00558: httpd.exe: Could not reliably determine the server's fully qualified domain name, using 207.18.someip. Set the 'ServerName' directive globally to suppress this message
[Tue Feb 08 07:48:30.293850 2022] [md:info] [pid 6988:tid 636] AH10071: mod_md (v2.4.10), initializing...
[Tue Feb 08 07:48:30.293850 2022] [md:debug] [pid 6988:tid 636] mod_md.c(451): AH10037: server seems reachable via http: and reachable via https:
[Tue Feb 08 07:48:30.293850 2022] [md:debug] [pid 6988:tid 636] mod_md.c(705): AH10039: Completed MD[www.myhost.com, CA=(null), Proto=ACME, Agreement=accepted, renew-mode=1 renew_window=33%, warn_window=10%
[Tue Feb 08 07:48:30.293850 2022] [md:debug] [pid 6988:tid 636] mod_md.c(596): AH10041: Server www.myhost.com:0 matches md www.myhost.com (config www.myhost.com[default, default]) for domain www.myhost.com, has now 1 MDs
[Tue Feb 08 07:48:30.293850 2022] [md:debug] [pid 6988:tid 636] md_reg.c(818): sync MDs, start
[Tue Feb 08 07:48:30.293850 2022] [md:debug] [pid 6988:tid 636] md_reg.c(881): sync MDs, 1 existing, 0 moved, 0 new.
[Tue Feb 08 07:48:30.293850 2022] [md:trace2] [pid 6988:tid 636] md_reg.c(1155): www.myhost.com: nothing staged
[Tue Feb 08 07:48:30.309477 2022] [ssl:warn] [pid 6988:tid 636] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Tue Feb 08 07:48:30.325103 2022] [md:trace1] [pid 6988:tid 636] mod_md.c(742): checking duplicate ssl assignments
[Tue Feb 08 07:48:30.325103 2022] [md:trace2] [pid 6988:tid 636] mod_md.c(968): md{www.myhost.com}: auto_add
[Tue Feb 08 07:48:30.325103 2022] [md:trace1] [pid 6988:tid 636] mod_md.c(515): md[www.myhost.com]: auto add domains
[Tue Feb 08 07:48:30.325103 2022] [md:debug] [pid 6988:tid 636] mod_md.c(550): AH10168: www.myhost.com: no https server_rec found for www.myhost.com
[Tue Feb 08 07:48:30.325103 2022] [md:trace2] [pid 6988:tid 636] mod_md.c(973): md{www.myhost.com}: check_usage
[Tue Feb 08 07:48:30.325103 2022] [md:trace2] [pid 6988:tid 636] mod_md.c(977): md{www.myhost.com}: sync_finish
[Tue Feb 08 07:48:30.325103 2022] [md:trace2] [pid 6988:tid 636] md_reg.c(214): md{www.myhost.com}: check cert rsa
[Tue Feb 08 07:48:30.325103 2022] [md:debug] [pid 6988:tid 636] md_reg.c(234): md{www.myhost.com}: certificate(0) is ok
[Tue Feb 08 07:48:30.325103 2022] [md:trace2] [pid 6988:tid 636] md_reg.c(253): md{www.myhost.com}: state=2, (null)
[Tue Feb 08 07:48:30.325103 2022] [md:debug] [pid 6988:tid 636] md_reg.c(908): loading md www.myhost.com
[Tue Feb 08 07:48:30.325103 2022] [md:debug] [pid 6988:tid 636] md_reg.c(910): loaded md www.myhost.com
[Tue Feb 08 07:48:30.325103 2022] [md:debug] [pid 6988:tid 636] md_reg.c(951): sync MDs, finish done
[Tue Feb 08 07:48:30.325103 2022] [md:trace2] [pid 6988:tid 636] mod_md.c(985): init_cert_watch
[Tue Feb 08 07:48:30.325103 2022] [md:trace1] [pid 6988:tid 636] md_acme_drive.c(531): www.myhost.com: init_base driver
[Tue Feb 08 07:48:30.325103 2022] [md:trace1] [pid 6988:tid 636] md_acme_drive.c(611): www.myhost.com: init driver
[Tue Feb 08 07:48:30.325103 2022] [md:debug] [pid 6988:tid 636] md_reg.c(1076): www.myhost.com: init done
[Tue Feb 08 07:48:30.325103 2022] [md:trace2] [pid 6988:tid 636] mod_md.c(988): cleanup challenges
[Tue Feb 08 07:48:30.325103 2022] [md:debug] [pid 6988:tid 636] mod_md.c(997): AH10074: 1 out of 1 mds need watching
[Tue Feb 08 07:48:30.325103 2022] [md:trace1] [pid 6988:tid 636] mod_md_drive.c(309): md(www.myhost.com): state=2, created drive job
[Tue Feb 08 07:48:30.325103 2022] [md:debug] [pid 6988:tid 636] mod_md_drive.c(342): AH10067: register md renew watchdog(_md_renew_)
[Tue Feb 08 07:48:30.325103 2022] [md:trace1] [pid 6988:tid 636] mod_md.c(1008): no ocsp to manage
[Tue Feb 08 07:48:30.325103 2022] [md:trace2] [pid 6988:tid 636] mod_md.c(1016): post_config done
[Tue Feb 08 07:48:30.356352 2022] [mpm_winnt:notice] [pid 6988:tid 636] AH00354: Child: Starting 64 worker threads.
[Tue Feb 08 07:48:30.376218 2022] [md:debug] [pid 6988:tid 320] mod_md_drive.c(202): AH10054: md watchdog start, auto drive 1 mds
[Tue Feb 08 07:48:30.477226 2022] [md:debug] [pid 6988:tid 320] mod_md_drive.c(207): AH10055: md watchdog run, auto drive 1 mds
[Tue Feb 08 07:48:30.477226 2022] [md:debug] [pid 6988:tid 320] mod_md_drive.c(108): AH10052: md(www.myhost.com): state=2, driving
[Tue Feb 08 07:48:30.477226 2022] [md:trace2] [pid 6988:tid 320] md_reg.c(667): md[www.myhost.com]: certificate(0) valid[Tue, 08 Feb 2022 11:44:08 GMT - Mon, 09 May 2022 11:44:07 GMT] renewal[Sat, 09 Apr 2022 18:56:08 GMT - Mon, 09 May 2022 11:44:07 GMT]
[Tue Feb 08 07:48:30.478219 2022] [md:debug] [pid 6988:tid 320] mod_md_drive.c(112): AH10053: md(www.myhost.com): no need to renew
[Tue Feb 08 07:48:30.478219 2022] [md:trace2] [pid 6988:tid 320] md_reg.c(709): md[www.myhost.com]: certificate(0) life[Tue, 08 Feb 2022 11:44:08 GMT - Mon, 09 May 2022 11:44:07 GMT] warn[Sat, 30 Apr 2022 11:44:08 GMT - Mon, 09 May 2022 11:44:07 GMT]
[Tue Feb 08 07:48:30.478219 2022] [md:debug] [pid 6988:tid 320] mod_md_drive.c(229): AH10107: next run in 11 hours 59 minutes 59 seconds

virtualhost log:

[Tue Feb 08 07:48:22.418837 2022] [md:debug] [pid 7660:tid 700] mod_md.c(1120): AH10113: get_certificates called for vhost www.myhost.com.
[Tue Feb 08 07:48:22.418837 2022] [ssl:warn] [pid 7660:tid 700] AH01909: www.myhost.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Feb 08 07:48:23.746970 2022] [md:trace1] [pid 7660:tid 700] mod_md.c(1236): hook ssl_add_cert_files for www.myhost.com

**Comment by icing** [comment]
You mean, you see now:

```
[Tue Feb 08 07:48:22.418837 2022] [ssl:warn] [pid 7660:tid 700] AH01909: [www.myhost.com:443:0](http://www.myhost.com:443:0) server certificate does NOT include an ID which matches the server name
```

? 

How exactly did you add the certificate from `certbot`? Did you put it into the `md/domains/myhost.com` directory yourself?

**Comment by fuzzy17** [comment]
I ended up commenting out mod_md and the mdomain (servername).  I did not put the cert files in md/domains/myhost.com.  I used certbot to create the cert and I left it in c:\certbot\live directories.
