### ISSUE TITLE
SSLCertificateChainFile obsolete, feature request

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#28]
I see that mod_md is generating the certs:  cert.pem and chain.pem 

Nowadays you must combine that two. This since  it  became obsolete with version 2.4.8,  when SSLCertificateFile was extended to also load intermediate CA certificates from the server certificate file.

I am now not auto compatible with my (mail)servers, it needs a cert.pem with **both** cert.pem and chain.pem. Have to manual combine the two.

**Request** is that mod_md generates also a combined file.
Like to see a cert.pem, chain.pem and a chain+cert.pem

Note: The tool that I used  is generating a combined file.

**Comment by Jan-E** [comment]
I did not know that SSLCertificateChainFile had become obsolete. The template for httpd-ssl.conf does not reflect that. It still contains the directive:
https://svn.apache.org/viewvc/httpd/httpd/branches/2.4.x/docs/conf/extra/httpd-ssl.conf.in?view=markup#l158

**Comment by Jan-E** [comment]
See the 2.4 docs as well.
http://httpd.apache.org/docs/2.4/ssl/ssl_faq.html#gid

> **Why do browsers complain that they cannot verify my server certificate?**
> One reason this might happen is because your server certificate is signed by an intermediate CA. Various CAs, such as Verisign or Thawte, have started signing certificates not with their root certificate but with intermediate certificates.
> 
> Intermediate CA certificates lie between the root CA certificate (which is installed in the browsers) and the server certificate (which you installed on the server). In order for the browser to be able to traverse and verify the trust chain from the server certificate to the root certificate it needs need to be given the intermediate certificates. The CAs should be able to provide you such intermediate certificate packages that can be installed on the server.
> 
> You need to include those intermediate certificates with the SSLCertificateChainFile directive.

**Comment by Jan-E** [comment]
Aha, found it. It is in the mod_ssl docs:
https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcertificatechainfile

**Comment by jsha** [comment]
I'd like to second this request. One of the biggest sources of failure in Certbot is that people mistakenly use cert.pem instead of fullchain.pem (containing the EE cert and the chain). We are prevented from fixing it by backwards compatibility, but I think you can save a lot of heartache by only generating fullchain.pem (or something equivalent).

**Comment by jsha** [comment]
Relatedly, pkey.pem should probably be named privkey.pem, since 'p' could indicate either public or private.

**Comment by icing** [comment]
In v0.8.0 the files ```privkey.pem``` and ```pubcert.pem``` are generated. The latter one contains the certificate and the rest of the chain. The old ```cert.pem``` and ```chain.pem``` will be left untouched for existing data, but future renewals will no longer generate them.

**Comment by icing** [comment]
Please check and re-open if not satisfactory. Thanks!
