### ISSUE TITLE
Segmentation fault after updating to httpd 2.4.52

### ISSUE THREAD

**Issue by dalelotts** [icing/mod_md#280]
I have a simple host configuration that started causing segmentation faults after updating to  httpd 2.4.52

> systemctl restart httpd
> Job for httpd.service failed because a fatal signal was delivered to the control process. See "systemctl status httpd.service" and "journalctl -xe" for details.

> systemctl status httpd.service
> ● httpd.service - The Apache HTTP Server
>    Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
>    Active: failed (Result: signal) since Thu 2022-02-10 06:24:14 UTC; 53s ago
>      Docs: man:httpd.service(8)
>   Process: 28735 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=killed, signal=SEGV)
>  Main PID: 28735 (code=killed, signal=SEGV)
>    Status: "Reading configuration..."
> 
> Feb 10 06:24:14 ip-10-0-0-161.ec2.internal systemd[1]: Starting The Apache HTTP Server...
> Feb 10 06:24:14 ip-10-0-0-161.ec2.internal systemd[1]: httpd.service: main process exited, code=killed, status=11/SEGV
> Feb 10 06:24:14 ip-10-0-0-161.ec2.internal systemd[1]: Failed to start The Apache HTTP Server.
> Feb 10 06:24:14 ip-10-0-0-161.ec2.internal systemd[1]: Unit httpd.service entered failed state.
> Feb 10 06:24:14 ip-10-0-0-161.ec2.internal systemd[1]: httpd.service failed.

> journalctl -xe 
> ...
> -- Unit httpd.service has begun starting up.
> Feb 10 06:24:14 ip-10-0-0-161.ec2.internal systemd[1]: httpd.service: main process exited, code=killed, status=11/SEGV
> Feb 10 06:24:14 ip-10-0-0-161.ec2.internal systemd[1]: Failed to start The Apache HTTP Server.
> -- Subject: Unit httpd.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit httpd.service has failed.
> --
> -- The result is failed.
> 

Commenting out `MDomain ...` and `SSLEngine on` stops the fault from happening so this leads me to think it is related to a configuration problem but I'm not sure how to get more information - commenting out only one of them does not stop the fault.

```
MDomain mydomain.org

<VirtualHost *:443>
    ServerName "www.mydomain.org"
    ServerAlias "mydomain.org"

    UseCanonicalName On

    SSLEngine on
    Protocols h2 http/1.1 acme-tls/1

    # don't lose time with IP address lookups
    HostnameLookups Off

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "443"

    ProxyRequests Off
    ProxyVia On
    ProxyPreserveHost On

    <Proxy *>
        Order deny,allow
        Allow from all
    </Proxy>

    RewriteEngine On

    RewriteCond http://localhost:12100 ^(.+)$
    RewriteRule ^/?(.*)$ %1/$1 [P]

</VirtualHost>
```

**Comment by icing** [comment]
Hmm. Could you provide a log with `LogLevel md:trace2 ssl:trace2` on such a startup? I have not seen such a failure.

If you comment the `MDomain`, the configuration will fail as `mod_ssl` has no certificate configured. But it should not segfault. If it indeed does, this points to something messed up on your installation.

If it does not segfault on the commented MDomain, just fails to start, the segfault with MDomain points to an error in `mod_md` itself and maybe the log gives us some idea what is going on.

**Comment by dalelotts** [comment]
I rolled back to the previous versions of httpd and mod_md and the configuration worked.  

Sure, I'll reproduce and grab some logs for you.  Thanks for having a look

**Comment by dalelotts** [comment]
I set the instance to automatically install updates, so naturally it updated httpd and mod_md and it won't come back up again. 🤷 

I added the log levels and am getting very little useful info:

```
systemctl restart httpd
Job for httpd.service failed because a fatal signal was delivered to the control process. See "systemctl status httpd.service" and "journalctl -xe" for details.
[root@ip-10-0-0-161 logs]# ls
access_log  error_log  ssl_access_log  ssl_error_log  ssl_request_log
[root@ip-10-0-0-161 logs]# cat error_log
[Mon Apr 18 03:32:39.713270 2022] [suexec:notice] [pid 16461:tid 281473242404096] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Apr 18 03:32:39.713328 2022] [md:trace1] [pid 16461:tid 281473242404096] mod_md.c(869): AH10070: initializing post config dry run
[Mon Apr 18 03:32:39.713407 2022] [md:trace1] [pid 16461:tid 281473242404096] mod_md.c(453): AH10037: server seems reachable via http: and reachable via https:
[Mon Apr 18 03:32:39.713415 2022] [md:trace1] [pid 16461:tid 281473242404096] mod_md.c(710): AH10039: Completed MD[c-domain-name-removed.com, CA=(null), Proto=ACME, Agreement=accepted, renew-mode=1 renew_window=33%, warn_window=10%
[Mon Apr 18 03:32:39.713420 2022] [md:trace1] [pid 16461:tid 281473242404096] mod_md.c(710): AH10039: Completed MD[w-domain-name-removed.com, CA=(null), Proto=ACME, Agreement=accepted, renew-mode=1 renew_window=33%, warn_window=10%
[Mon Apr 18 03:32:39.713424 2022] [md:debug] [pid 16461:tid 281473242404096] mod_md.c(600): AH10041: Server www.c-domain-name-removed.com:0 matches md c-domain-name-removed.com (config www.c-domain-name-removed.com[default, default]) for domain c-domain-name-removed.com, has now 1 MDs
[Mon Apr 18 03:32:39.713428 2022] [md:debug] [pid 16461:tid 281473242404096] mod_md.c(600): AH10041: Server www.wisconsinlimo.org:0 matches md w-domain-name-removed.com (config www.w-domain-name-removed.com[default, default]) for domain w-domain-name-removed.com, has now 1 MDs
[Mon Apr 18 03:32:39.713433 2022] [md:debug] [pid 16461:tid 281473242404096] md_reg.c(818): sync MDs, start
[Mon Apr 18 03:32:39.713465 2022] [md:debug] [pid 16461:tid 281473242404096] md_reg.c(881): sync MDs, 2 existing, 0 moved, 0 new.
[Mon Apr 18 03:32:39.713475 2022] [md:trace1] [pid 16461:tid 281473242404096] md_acme_drive.c(531): c-domain-name-removed.com: init_base driver
[Mon Apr 18 03:32:39.713478 2022] [md:debug] [pid 16461:tid 281473242404096] md_reg.c(1076): c-domain-name-removed.com: init done
[Mon Apr 18 03:32:39.713481 2022] [md:debug] [pid 16461:tid 281473242404096] md_acme_drive.c(912): c-domain-name-removed.com: preload start
[Mon Apr 18 03:32:39.715279 2022] [md:trace1] [pid 16461:tid 281473242404096] md_store_fs.c(688): start remove of md staging/c-domain-name-removed.com/order.json
```

```
systemctl status httpd.service
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; disabled; vendor preset: disabled)
   Active: failed (Result: signal) since Mon 2022-04-18 03:32:39 UTC; 5min ago
     Docs: man:httpd.service(8)
  Process: 24362 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful (code=exited, status=0/SUCCESS)
  Process: 16461 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=killed, signal=SEGV)
 Main PID: 16461 (code=killed, signal=SEGV)
   Status: "Reading configuration..."

Apr 18 03:32:39 ip-10-0-0-161.ec2.internal systemd[1]: Starting The Apache HTTP Server...
Apr 18 03:32:39 ip-10-0-0-161.ec2.internal systemd[1]: httpd.service: main process exited, code=killed, status=11/SEGV
Apr 18 03:32:39 ip-10-0-0-161.ec2.internal systemd[1]: Failed to start The Apache HTTP Server.
Apr 18 03:32:39 ip-10-0-0-161.ec2.internal systemd[1]: Unit httpd.service entered failed state.
Apr 18 03:32:39 ip-10-0-0-161.ec2.internal systemd[1]: httpd.service failed.
[root@ip-10-0-0-161 logs]#
```

Anything else I can try to get useful information?

**Comment by icing** [comment]
It looks lie your apache has some new certificate staged and wants to activate it on the restart. So,
there should be data in `md/staging/yourdomain`. What is new in the recent mod_md here is that
the certificate/pkey in staging is checked if they really match.

What version exactly of mod_md does your sever load? you should see this in your captures log at info level.

As a short term solution, you could rename `md/staging/yourdomain` to `md/staging/yourdomain.fishy` and check of the server loads again fine. if so, I'd be interested to get a copy of that fishy dir.

**Comment by dalelotts** [comment]
That's fascinating because there is no new domain or other configuration change. Renaming staging entirely worked. I had two different instances that were failing to start, but renaming staging worked. 

Thanks for your help!!
