### ISSUE TITLE
Dereferencing NULL pointer in md_json_set_timeperiod()

### ISSUE THREAD

**Issue by marcstern** [icing/mod_md#282]
In md_json.c, in md_json_set_timeperiod(), we have
```
if (!tp || tp->start || tp->end) {
        jn = json_object();
        apr_rfc822_date(ts, tp->start);
```

In case tp is NULL, "if (!tp || ...)" will succeed, thus "apr_rfc822_date(ts, tp->start);" will be exacuted, dereferencing a NULL pointer

It should be
```
if (tp && tp->start && tp->end) {
```

**Comment by icing** [comment]
You are totally right. What was I thinking?

I'll make a release with this soon.
