### ISSUE TITLE
Compatibility with Rehat 8 (httpd 2.4.37)

### ISSUE THREAD

**Issue by marcstern** [icing/mod_md#283]
I'd like to compile the latest version of mod_md because I have huge memory leaks. Unfortunately, I cannot compile with Redhat-provided version.
I removed all OCSP functions (I can accept this as a limitation), but I still have 2 problems:
 I defined ap_ssl_conn_is_ssl to opt_ssl_is_https as it was done before:
> /usr/include/apr-1/apr_optional.h:42:36: error: unknown type name ‘apr_OFN_ssl_is_https_t’
>  #define APR_OPTIONAL_FN_TYPE(name) apr_OFN_##name##_t

The second problem is with the ap_hook_ssl_... (ap_hook_ssl_answer_challenge, ap_hook_ssl_add_cert_files, ap_hook_ssl_add_fallback_cert_files):
> mod_md.c:1545:23: error: unknown type name ‘ssl_HOOK_add_cert_files_t’; did you mean ‘ap_HOOK_insert_filter_t’?
>      APR_OPTIONAL_HOOK(ssl, add_cert_files, md_add_cert_files, NULL, NULL, APR_HOOK_MIDDLE);

Any idea?
Thanks a lot

**Comment by icing** [comment]
You need a recent Apache httpd. As it says "the current release requires apache httpd >= 2.4.48".

**Comment by marcstern** [comment]
That was all the point. It seems Redhat version contains a memory leak and I want to replace it, but without recompiling (and maintaining) the whole httpd stack.

**Comment by marcstern** [comment]
Thanks
