### ISSUE TITLE
2.4.12 & 2.4.13 memory leak?

### ISSUE THREAD

**Issue by nono303** [icing/mod_md#284]
Hi @icing,
I've just noticed strange httpd memory usage (Windows - httpd 2.4.53 x64 vs17) with latest mod_md:
![image](https://user-images.githubusercontent.com/2869665/165256019-3d1e6b6c-b117-4f87-a0be-dca35a9c395e.png)

1) `2.4.11`
2) bump to `2.4.12`
3) rollback to `2.4.11`
4) bump to `2.4.13`

Is there any major change that can imply a memory leak since 2.4.12?
I'll try to provide additional information - if needed - but it will be Windows related....

**Comment by icing** [comment]
Hmm, the changes between 2.4.11 and 2.4.12 were related to the `server-status` information.

How many managed domains do you have?

**Comment by nono303** [comment]
> How many managed domains do you have?

20

**Comment by icing** [comment]
Do you monitor `server-status` regularly? or have you enabled it at all?

**Comment by icing** [comment]
Please give v2.4.14 a try.

**Comment by nono303** [comment]
`2022-04-26 16:32:36.220666 - - - md:info mod_md.c(874) pid:9000 tid:836 [AH10071: mod_md (v2.4.14-git), initializing...]`
we'll see tomorrow ;)

**Comment by nono303** [comment]
![image](https://user-images.githubusercontent.com/2869665/165452739-d7cb143c-2f96-44d3-aec9-094dba70d7a5.png)
sounds good!

**Comment by nono303** [comment]
![image](https://user-images.githubusercontent.com/2869665/168036971-5db83bb6-ff54-4d4e-a3b2-940e0a338e58.png)
