### ISSUE TITLE
Can mod_md perform account updates (such as changing contact emails?)

### ISSUE THREAD

**Issue by moschlar** [icing/mod_md#286]
Could this work through changing the account.json?

**Comment by icing** [comment]
No, I'm afraid there is no functionality for changing an existing account on the ACME server.

If you remove an account in the file system, a new one will be created on the next renew, but that will of course not help for notifications on existing certificates.

**Comment by moschlar** [comment]
But I think, it would be possible to convert account data, including the key, to the format that certbot uses and then use the certbot update_account command.

I'll post here when I actually need to do that and have it figured out, so that others with that crazy need can benefit.

**Comment by moschlar** [comment]
I finally came around to writing the script that does this:

https://gist.github.com/moschlar/03ab7d87e5584e4b9663cefa3a69fa47
