### ISSUE TITLE
How intrusive are the changes to mod_ssl

### ISSUE THREAD

**Issue by oerdnj** [icing/mod_md#3]
Hi, 

sorry for abusing the issues for question... 

If I were to provide packaged mod_md via my PPA as a separate package, how intrusive are the changes to mod_ssl? Could I just patch it for everybody without breaking anything? 

Or when do you expect to land these required changes in 2.4.x upstream?

**Comment by icing** [comment]
Not a problem at all. Loving your PPA and using it for a long time!

The patch in ```patches/mod_ssl_md-2.4.x-v0.diff``` is at the moment very small. It will grow a bit when I add the ACME challenges via TLS-SNI support. But...

The overall design goal is: nothing will change in a deployed Apache installation, ***unless*** you start configuring ```mod_md```. So, it should be safe to include it, even load it by default, in your PPA.

When I have the module function complete and gotten more feedback, I will add it to ```httpd/trunk```. When and if that will make it into 2.4.x is a matter of the team to vote on. But I sure would like it to come there.

**Comment by icing** [comment]
Thanks a lot for the PPA. Got my first green lock with it!
