### ISSUE TITLE
Corrections to README.md

### ISSUE THREAD

**Issue by albert-github** [icing/mod_md#308]
Some small problems regarding links:

https://github.com/icing/mod_md/blob/28207d0a3eddf6c07719336e5cd8aca2a21ea2a7/README.md?plain=1#L61

`(#acme_failover)` should be `(#acme-failover)`

https://github.com/icing/mod_md/blob/28207d0a3eddf6c07719336e5cd8aca2a21ea2a7/README.md?plain=1#L1584
`[Simple Usage](#simple-usage)` should probably be `[Basic Usage](#basic-usage)`

https://github.com/icing/mod_md/blob/28207d0a3eddf6c07719336e5cd8aca2a21ea2a7/README.md?plain=1#L1735

`(#MDWarnWindow--When-to-warn)` should be `(#mdwarnwindow--when-to-warn)`

**Comment by icing** [comment]
Thanks!
