### ISSUE TITLE
Recovering from missing terms-of-service agreement fails

### ISSUE THREAD

**Issue by jsha** [icing/mod_md#31]
Steps to reproduce:

Start Apache with mod_md and `ManagedDomain powerdns.crud.net`
Note error in logs:

```
[Sat Aug 19 15:39:09.499585 2017] [md:error] [pid 6] need to accept terms-of-service <https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf> for account (null)
[Sat Aug 19 15:39:09.500467 2017] [md:error] [pid 6] (13)Permission denied: AH10056: processing powerdns.crud.net
```

Add `MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf` to Apache config and restart.

Expected result: MD continues with registration process and issues a certificate.

Actual result: MD continues to log:

```
[Sat Aug 19 15:41:15.584970 2017] [md:error] [pid 8] need to accept terms-of-service <https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf> for account (null)
[Sat Aug 19 15:41:15.585283 2017] [md:error] [pid 8] (13)Permission denied: AH10056: processing powerdns.crud.net
```

Note that there are a few things in the logs that could be improved:

 - "for account (null)" should probably say something other than "(null)"
 - Permission denied doesn't say for what operation or what file
 - The error log should ideally include instructions on what directive to add in order to agree to terms

**Comment by michael-koeller** [comment]
I failed to reproduce this issue locally in my test environment. MD picked up the changed config as exected and transfered the agreement info into the md store.

**Comment by icing** [comment]
@jsha Could you verify if this still happens in v0.7.0? (I assume you tested the version before?)

**Comment by jsha** [comment]
I was testing v0.7.0. I'll try to repro again and come up with more detailed instructions.

**Comment by jsha** [comment]
Using v0.8.0 I get the same problem. Here's a trace-level log, and the contents of my /etc/apache2/md/staging/ directory:

[terms-of-service-bad-staging.txt](https://github.com/icing/mod_md/files/1268507/terms-of-service-bad-staging.txt)
[md-staging-account.txt](https://github.com/icing/mod_md/files/1268510/md-staging-account.txt)

Here's the MD part of my config:

```
ManagedDomain powerdns.crud.net
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
MDCertificateAuthority  https://acme-staging.api.letsencrypt.org/directory
```

One thing I forgot to mention initially: The first time I started Apache with mod_md, I just had `ManagedDomain powerdns.crud.net`. I then added the two `MDCertificate...` directives. Note that the second one points at staging rather than prod. Is it possible that switching the MDCertificateAuthority URL while there was still a half-formed account in the staging directory caused the problem?

**Comment by icing** [comment]
@michael-koeller can you on Monday try to reproduce the different update cases and see if we can trigger this case?

```mod_md``` checks, before driving the protocol, if the ```md.json``` in ```domains``` is newer than an evtl. copy in ```staging```. If so, ```staging``` is thrown away and the drive starts fresh. This should also trigger here, but obviously does not.

@jsha if you ```touch md/domains/powerdns.crud.net/md.json``` and reload, does that change anythign?

**Comment by michael-koeller** [comment]
I added a test case that reproduces the scenario. The wrong TOS url in staging is not replaced by the corrected value from config.

**Comment by icing** [comment]
I consider this fixed in the last releases.
