### ISSUE TITLE
Segmentation fault possible in `md_acme_order.c:check_challenges()`

### ISSUE THREAD

**Issue by bitscher** [icing/mod_md#324]
In function https://github.com/icing/mod_md/blob/1e105f8382513eab42653e64e4b2d7883441d7f6/src/md_acme_order.c#L497

Call to [`md_acme_authz_retrieve()` ](https://github.com/icing/mod_md/blob/1e105f8382513eab42653e64e4b2d7883441d7f6/src/md_acme_authz.c#L82-L94) can fail and `authz` will be set to NULL.
Dereferencing it in the error handling will result in a segmentation fault.

https://github.com/icing/mod_md/blob/1e105f8382513eab42653e64e4b2d7883441d7f6/src/md_acme_order.c#L510-L511
https://github.com/icing/mod_md/blob/1e105f8382513eab42653e64e4b2d7883441d7f6/src/md_acme_order.c#L538-L542

**Comment by icing** [comment]
Thanks for the report! This indeed looks wrong. Please see #325 for a fix.

**Comment by icing** [comment]
release in v2.4.25
