### ISSUE TITLE
Additional (non-existen) domains being automatically added

### ISSUE THREAD

**Issue by vanowm** [icing/mod_md#335]
I have this in my apache config:
```
MDomain example.com anotherdomain.com.example.com
```
(just 2 domains)
mod_md fails renew certificate because it can't verify `anotherdomain.com` - what???

In `md/domains/example.com/md.json` it has:
```
{
  "domains": [
    "example.com",
    "anotherdomain.com.example.com",
    "anotherdomain.com",
    "www.anotherdomain.com"
  ]
 ...
}
```
There is no `anotherdomain.com` anywhere in my configurations.
I've tried delete `md` directory, but after apache restart it still trying renew certificates for `anotherdomain.com`

P.S.
At some point in the past, I did have `anotherdomain.com` at the `MDomain` line, but after removing it, it still being automatically added.

**Comment by vanowm** [comment]
I do have virtualhost setup for that domain:
```
<VirtualHost *:443>
  ServerName anotherdomain.com
  ServerAlias www.anotherdomain.com
  ServerAlias anotherdomain.com.example.com
 ...
```
Which seems like `mod_md` is picking up, because removing these aliases fixes this issue.
Perhaps there should be an option to ignore any aliases, since they could be only local and let user actually dictate which domains they want to use?

**Comment by icing** [comment]
There is [MDMembers manual](https://github.com/icing/mod_md?tab=readme-ov-file#mdmembers) which should do what you want.
