### ISSUE TITLE
User agent doesn't need "like certbot"

### ISSUE THREAD

**Issue by jsha** [icing/mod_md#34]
Right now the user agent string for ACME requests contains "(Something, like certbot)". This shouldn't be necessary; Boulder does almost zero User-Agent detection. Ideally that string should just be removed, unless there's some reason to include it that I'm unaware of?

**Comment by icing** [comment]
This was more a pun on Browser UAs than anything else. It's definitely not necessary.

**Comment by icing** [comment]
Available in v0.7.1
