### ISSUE TITLE
Formatting bug in mod_status auto output 

### ISSUE THREAD

**Issue by wwuck** [icing/mod_md#343]
I'm testing mod_md status output for use with https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/apache-httpd-status.

Apache version: `Apache/2.4.62 (Debian) OpenSSL/3.0.14`

I am seeing a formatting error when I check the mod_status auto output format:
```
...
ManagedDomain[0]Status: good
ManagedDomain[0]ValidUntil: 2024-12-17
ManagedDomain[0]CAName: LetsEncrypt
ManagedDomain[0]CAURL: https://acme-v02.api.letsencrypt.org/directory
ManagedDomain[0]: onManagedDomain[0]CheckAtType: rsa
ManagedDomain[0]CheckAtName: crt.sh
...
```

It looks like it is missing a newline character in the output.

I also tried compiling the latest `v2.24.28` release from this repository but it gives the same format error in mod_status output.

**Comment by icing** [comment]
Thanks for the report. This is fixed via #345.
