### ISSUE TITLE
Feature request/question: how to exclude virtual host

### ISSUE THREAD

**Issue by GBBx** [icing/mod_md#347]
Hi,

I have three virtual hosts:
- example.com:443
- example.com:1443
- example.com:2443.

If I set `MDomain example.com` it will use the MD certificate for all three subdomains.
Is there a way to exclude one of the virtual hosts somehow?

**Comment by icing** [comment]
No, there is not. If these hosts use SSL, they will get the certificate from mod_md, if it has one.

**Comment by GBBx** [comment]
I see. Thanks for the clarification.
