### ISSUE TITLE
Read-only file system /etc/apache2/md/ocsp

### ISSUE THREAD

**Issue by chriscroome** [icing/mod_md#349]
I'm having another go at switching a testing server to use `mod_md` after last trying [4 years ago](https://github.com/icing/mod_md/issues/260)&hellip;

The issue I currently have is that no certs are being generated and the Apache error log is reporting:

```
[Thu Dec 12 21:12:42.443274 2024] [md:error] [pid 3256500:tid 3256514] (30)Read-only file system: mk_group_dir 7 /etc/apache2/md/ocsp
```

This directory has the following mode / ownership:

```bash
ls -lah /etc/apache2/md
total 32K
drwxr-xr-x  7 root     root 4.0K Dec 12 21:11 .
drwxr-xr-x 12 root     root 4.0K Dec 12 21:13 ..
drwxr-x---  2 root     root 4.0K Dec 12 21:11 accounts
drwxr-x---  2 www-data root 4.0K Dec 12 21:11 challenges
drwx------  3 root     root 4.0K Dec 12 21:11 domains
-rw-------  1 root     root  116 Dec 12 21:11 md_store.json
drwxr-x---  2 www-data root 4.0K Dec 12 21:11 ocsp
drwxr-x---  2 www-data root 4.0K Dec 12 21:11 staging
```

And there are no files in the `ocsp` directory:

```bash
ls -lah /etc/apache2/md/ocsp
total 8.0K
drwxr-x--- 2 www-data root 4.0K Dec 12 21:11 .
drwxr-xr-x 7 root     root 4.0K Dec 12 21:11 ..
```

Also there is a similar error for the `staging` directory:

```
[Thu Dec 12 23:36:27.344790 2024] [md:error] [pid 3324612:tid 3324614] (30)Read-only file system: mk_group_dir 4 /etc/apache2/md/staging
```

And this is also an empty directory:

```bash
ls -lah /etc/apache2/md/staging/
total 8.0K
drwxr-x--- 2 www-data root 4.0K Dec 12 21:11 .
drwxr-xr-x 7 root     root 4.0K Dec 12 21:11 ..
```

This is with the Debian Bookworm Apache:

```bash
apache2 -v
Server version: Apache/2.4.62 (Debian)
Server built:   2024-10-04T15:21:08
```

And the default user / group:

```bash
grep APACHE_RUN /etc/apache2/apache2.conf
DefaultRuntimeDir ${APACHE_RUN_DIR}
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}

grep APACHE_RUN /etc/apache2/envvars
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
export APACHE_RUN_DIR=/var/run/apache2$SUFFIX
```

This is with the latest version of `mod_md`.

What would you suggest I check / try next to debug and fix this issue?

**Comment by chriscroome** [comment]
Sorry I had forgotten that that Apache was chrooted&hellip; :roll_eyes:

```bash
grep ChrootDir /etc/apache2/apache2.conf
# ChrootDir: Directory for apache to run chroot(8) after startup.
ChrootDir /chroots/www-data
```

The `/chroots/www-data` file system is read-only but I have now mounted `/etc/apache2/md` read-write, in `/etc/fstab` I have:

```
# Apache chroot
/chroot /chroots/www-data ext4 ro,nosuid,bind,private 0 0
# mod_md needs rw access to /etc/apache2/md
/etc/apache2/md /chroots/www-data/etc/apache2/md ext4 rw,nodev,nosuid,bind,private 0 0
```

And I have tested that this works:

```bash
chroot /chroots/www-data
cd /etc/apache2
touch foo
touch: cannot touch 'foo': Read-only file system
cd md
touch bar
ls -lah
total 32K
drwxr-xr-x  7 root     root 4.0K Dec 13 00:54 .
drwxr-xr-x 11 root     root 4.0K Dec 13 00:42 ..
drwxr-x---  2 root     root 4.0K Dec 12 21:11 accounts
-rw-r--r--  1 root     root    0 Dec 13 00:54 bar
drwxr-x---  2 www-data root 4.0K Dec 12 21:11 challenges
drwx------ 13 root     root 4.0K Dec 12 21:46 domains
-rw-------  1 root     root  116 Dec 12 21:11 md_store.json
drwxr-x---  2 www-data root 4.0K Dec 12 21:11 ocsp
drwxr-x---  2 www-data root 4.0K Dec 12 21:11 staging
exit
ls -lah /etc/apache2/md
total 32K
drwxr-xr-x  7 root     root 4.0K Dec 13 00:54 .
drwxr-xr-x 12 root     root 4.0K Dec 12 23:54 ..
drwxr-x---  2 root     root 4.0K Dec 12 21:11 accounts
-rw-r--r--  1 root     root    0 Dec 13 00:54 bar
drwxr-x---  2 www-data root 4.0K Dec 12 21:11 challenges
drwx------ 13 root     root 4.0K Dec 12 21:46 domains
-rw-------  1 root     root  116 Dec 12 21:11 md_store.json
drwxr-x---  2 www-data root 4.0K Dec 12 21:11 ocsp
drwxr-x---  2 www-data root 4.0K Dec 12 21:11 staging
rm /etc/apache2/md/bar
```

And after a reboot mod_md is working, sorry for the noise!

One thought though, before closing this issue, does mod_md consider if Apache is chrooted? And if it doesn't should it, for example, could it write files outside the chroot to avoid the need to mount `/etc/apache2/md` read-write within the chroot?

**Comment by icing** [comment]
No problem, we all make mistakes.

If I understand your question correctly, you can set [`MDStoreDir](https://github.com/icing/mod_md?tab=readme-ov-file#mdstoredir) to whatever location that suits you, avoiding this mount.

**Comment by chriscroome** [comment]
Thanks @icing I think ideally when Apache is chrooted the mod_md files wouldn't be inside the chroot, but I guess that might well not be a possibility due to the nature of the manner in which chrooting works? :shrug: In any case I doubt many people chroot Apache, I'm doing it for [suEXEC](https://httpd.apache.org/docs/current/suexec.html).
