### ISSUE TITLE
Missing Test Cases

### ISSUE THREAD

**Issue by icing** [icing/mod_md#37]
The following scenarios are not covered by test cases:

 * Tests for MDRenewWindow (percentage and absolute) 
 * Tests for MDPrivateKeys options 
 * There is logic to delay activation of *renewed* certificates when the old ones are still valid. Test by creating a staging directory with appropriate notBefore, notAfter values?

**Comment by michael-koeller** [comment]
Created test cases for MDRenewWindow and MDPrivateKeys.

**Comment by icing** [comment]
Fixed various bugs found by @michael-koeller in v0.9.1. No rest without test!

**Comment by michael-koeller** [comment]
Create test case to verify delayed activation after cert renewal.
So all mentioned subjects should be covered now.
