### ISSUE TITLE
mod_ssl_md-2.4.x-v3.diff  not same as in Trunk

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#43]
Noticed that in trunk is a diff  on 1 Sept in  ssl_engine_init.c  :

...
"Init: %s will respond with '503 Service Unavailable' for now. This " ....

I do not see this in the V3 patch. Did not check more diff.

**Comment by icing** [comment]
Thanks, @SteffenAL ! Somehow a change in the log message did not make it. Rechecked against trunk and that was indeed the only difference. Included now v4 of the patch that is exactly as the changes in trunk so far.
