### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by Sp1l** [icing/mod_md#47]
1. Add a BIG FAT WARNING at the top of the [2.4.x Installation](https://github.com/icing/mod_md/wiki/2.4.x-Installation) wiki page that mod_ssl _**must**_ be patched for `mod_md` to work.
1. Start with generic build instructions on [2.4.x Installation](https://github.com/icing/mod_md/wiki/2.4.x-Installation) and then add specifics for OS's.
1. Add link to the [mod_md](https://httpd.apache.org/docs/trunk/mod/mod_md.html) on the Apache httpd website to the top of the [mod_md docs](https://github.com/icing/mod_md/wiki/mod_md-docs) and [Directives](https://github.com/icing/mod_md/wiki/mod_md-docs) wiki pages
1. Add missing directives, e.g. `MDPrivateKeys`, to the [Directives](https://github.com/icing/mod_md/wiki/mod_md-docs) wiki page (alternative: redirect to the docs/trunk/mod/mod_md.html page on httpd.apache.org)

Re. 1. That was just me not reading _all_ the docs...

**Comment by Sp1l** [comment]
Creating a diff locally, will attach in a bit.

**Comment by Sp1l** [comment]
My 10 cents. Not sure if all parts are relevant... Thought it was unfair to make you do all the work!
[patch-mod_md.wiki.txt](https://github.com/icing/mod_md/files/1290518/patch-mod_md.wiki.txt)

* Added installation instructions for FreeBSD
* Added BIG FAT WARNING about patching mod_ssl
* Re-ordered Installation page
* Re-ordered and completed Directives page
* Add link to trunk documents on Directives page.

**Comment by Sp1l** [comment]
[patch-mod_md.wiki.2.txt](https://github.com/icing/mod_md/files/1290533/patch-mod_md.wiki.2.txt)
Some cosmetic changes, typo fixes, etc.
Modified pages visible on my [fork](https://github.com/Sp1l/mod_md/wiki)

**Comment by Jan-E** [comment]
While you are at it: change 'pre-build' everywhere in 'prebuilt'. It is perfect tense. And one word in English.

**Comment by Jan-E** [comment]
It is in sentences like https://github.com/icing/mod_md/wiki/2.4.x-Installation#windows
> There are pre-build binaries available from apachelounge.

Which is not in your fork, I see now.

**Comment by icing** [comment]
Thanks a lot for the changes. I found out in the meantime that a wiki is a github repro. Have not tested a fork and PR etc, but the repro url is:

```
origin	git@github.com:icing/mod_md.wiki.git 
```
