### ISSUE TITLE
Invalid argument: unexpected AUTHZ state 3

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#52]
mod_md 0.9.7 is **trying to renew** and was getting errors:

..
..
[md:info] [pid 7072:tid 1964] apachelounge.nl: need certificate
[md:info] [pid 7072:tid 1964] apachelounge.nl: check Terms-of-Service agreement
[md:info] [pid 7072:tid 1964] apachelounge.nl: setup new authorization
[md:info] [pid 7072:tid 1964] apachelounge.nl: setup new challenges
[md:error] [pid 7072:tid 1964] (22)Invalid argument: apachelounge.nl: unexpected AUTHZ state 3 at https://acme-v01.api.letsencrypt.org/acme/authz/iDqjBmUgvLmip0QQDvfSuvQTtZYWJnXjQ87cgURSU28
[md:error] [pid 7072:tid 1964] (22)Invalid argument: AH10056: processing apachelounge.nl
[md:info] [pid 7072:tid 1964] AH10057: apachelounge.nl: **encountered error for the 11. time**, next run in  1:00:00 hours

I **stopped and started** Apache again and same error and trying it over and over again:

see trace2:  
[mod_md-error.txt](https://github.com/icing/mod_md/files/1348358/mod_md-error.txt)

I disabled mod_md.

**Comment by SteffenAL** [comment]
Same error  with 0.9.6, which worked before.

Maybe some changed at letsencypt.org ?

Tried letsencrypt-win-simple other certs, no issues with that.

**Comment by jsha** [comment]
If you click through to the authorization object, you can see the error:

```
"error": {
        "type": "urn:acme:error:unauthorized",
        "detail": "Invalid response from http://apachelounge.nl/.well-known/acme-challenge/A8IkI2k9RRd_TxQcgjtvJlPoliAo_MH6aSOWGa9dl5k: \"\u003c!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"\u003e\n\u003chtml\u003e\u003chead\u003e\n\u003ctitle\u003e404 Not Found\u003c/title\u003e\n\u003c/head\u003e\u003cbody\u003e\n\u003ch1\u003eNot Found\u003c/h1\u003e\n\u003cp\"",
        "status": 403
      },
```

Is it possible you've got the domain name pointed at a different server than the one you're running mod_md on?

@icing maybe you could improve the error message to print symbolic state names rather than numeric ones? And output the error from the authz directly into the logs?

**Comment by SteffenAL** [comment]
It is https only server : -sni-01tls 

AH10037: server seems not reachable via http: (port 80->80) and reachable via https: (port 443->443) 

But s strange :  state=2, **can_http=1**, can_https=1, challenges=**'http-01** -sni-01tls'

and in httpd.json:
{
  "proto": {
    **"http": false,**
    "https": true
  }
}

Btw.
The exact same config  was working for more then a month and renewing every 5 days.

**Comment by jsha** [comment]
I'd recommend enabling port 80 just for redirects to port 443. See https://https.cio.gov/guide/#do-i-need-to-shut-off-port-80%3f for details.

That said, in your current situation, it looks like `mod_md` is choosing the wrong challenge. If it can figure out that HTTP is not available, it should be using the TLS-SNI challenge. Also, it may be better to just use the TLS-SNI challenge by default if it's implemented, since we know that most people trying to get certificates will have 443 open and available.

**Comment by icing** [comment]
Why did you close the issue? Has the problem been solved?

@jsha agree that the log should give more from the server's answer.

@SteffenAL it looks as if the server reports that it gets a 403 response. Someone seems to be responding on port 80, it seems?

**Comment by SteffenAL** [comment]
Looks like letsencrypt.org is now want to go on port 80 too. So I closed because it looks no mod_md issue, but my config (ssl in front). is not supported anymore. Using now letsencrypt-win-simple.

I did work before.

But still strange:

AH10037: server seems **not reachable** via http: (port 80->80) and reachable via https: (port 443->443)

....  state=2, **can_http=1**, can_https=1, **challenges='http-01** -sni-01tls'

and in httpd.json:
 {
 "proto": {
**"http": false,**
 "https": true
 }
 }

**Comment by icing** [comment]
letsencrypt will use the method that ```mod_md``` tells it to use. There has been no change regarding that in the v0.9.6 -> 0.9.7 release. And as you said, v0.9.6 worked before.

So, something else is the problem. Can you get me a 

```
LogLevel md:trace2
```
of such a case?

**Comment by SteffenAL** [comment]
See second post above: 0.9.6 is also not working anymore.

See first post above : trace 2 log

**Comment by SteffenAL** [comment]
Here the log and folder md after I **removed the md** folder 

[log-md-removed.txt](https://github.com/icing/mod_md/files/1355533/log-md-removed.txt)

[md-removed.zip.txt](https://github.com/icing/mod_md/files/1355534/md-removed.zip.txt) (remove.txt)

**Comment by icing** [comment]
Think I found it. Could you check release v0.9.8 when you find the time? Thanks!

**Comment by SteffenAL** [comment]
Still wrong.

I see now:   staging started, state=1, **can_http=0**, can_https=1, challenges=**'http-01** tls-sni-01'

And I see that he is using:  "port": "80",

[error.txt](https://github.com/icing/mod_md/files/1356021/error.txt)

**Comment by icing** [comment]
Ok, added two new test cases, fixed the issue, release v0.9.9. Sorry about that.

**Comment by SteffenAL** [comment]
Fine again with 0.9.9:
AH10059: The Managed Domain apachelounge.nl has been setup and changes will be activated on next (graceful) server restart.

Have you an answer why it was suddenly not working anymore ?

**Comment by icing** [comment]
As it was, it should have stopped working some releases ago. The new tests will catch it.
