### ISSUE TITLE
Meaningful module name mod_acme

### ISSUE THREAD

**Issue by ibakirov** [icing/mod_md#53]
What not to use meaningful and understandable module name?

**Comment by bazzadp** [comment]
This was discussed previously: https://github.com/icing/mod_md/issues/46

**Comment by non7top** [comment]
Right, the referenced discussion points to the fact that "md is a good name" for module that implements **ACME** protocol. You know, they both have M in their names.

**Comment by De-Luxis** [comment]
mod_markdown? lol. mod_mod is the best name.

**Comment by icing** [comment]
You seem to have time. Could anyone of your please write a patch that resets the staging area when domains have been remove from a Managed Domain? Would be very helpful. Thanks!

**Comment by icing** [comment]
Nevermind, did it myself. ;-)
