### ISSUE TITLE
How do we tell Honest Achmed we're an existing customer?

### ISSUE THREAD

**Issue by tialaramex** [icing/mod_md#54]
In the current list of directives I don't see any way (short of maybe the email address which would be badly overloaded for this purpose) to signal to a CA that we're one of their existing customers.

ACME includes a method to bind the ACME account to some sort of per-CA customer account, see e.g. 7.3.5 "External Account Binding" in the most recent draft. We can expect that if ACME takes off with Commercial CAs they will want a simple way for sysadmins at a larger customer to bind all their machines to the company's account.

Ideally there'd be one directive to support this: to both specify a customer ID and to specify a MAC key which proves you're that customer, since it makes no sense to have one without the other, or for one to vary without the other. The documentation and preferably directive name should make clear that the latter is _secret_ and not to be shared.

For Let's Encrypt obviously this is largely irrelevant, but for a commercial CA this is vital to distinguish random people with mod_md installed from legitimate paying customers and one customer from another.

I can imagine that I'd be able to tell a new Apache install, here's the URL for Honest Achmed, here's my customer ID 123456, and here's a gibberish ASCII-encoded MAC to prove I'm 123456. Then my certificates would get an EV OID and O="EXA Metal Pole Europe LTD" which I've paid Achmed $100 per year to verify with an extra $10 to pay every extra hundred certificates. DV would take place as usual for the specific names that Apache is configured with.

**Comment by icing** [comment]
Well, that would be a feature of ACMEv2, not the version currently supported by ```mod_md```. There are currently no ongoing activities to implement v2 of the procotol. Let's Encrypt will start that in January (I think), but plans to support the current services indefinitely, basically.
