### ISSUE TITLE
be more forgiving in configured dns names

### ISSUE THREAD

**Issue by icing** [icing/mod_md#56]
```ServerName``` and ```ServerAlias``` names may carry port numbers, as in ```greenbytes.de:443``` and ```mod_md``` needs to strip those silently when matching MDs against vhosts.

**Comment by randolf** [comment]
The ServerName does support that, but according to the documentation the ServerAlias directive does not:

https://httpd.apache.org/docs/2.4/mod/core.html#serveralias

**Comment by icing** [comment]
You are correct. The ```ServerName``` needs to be normalized in checks.
