### ISSUE TITLE
ACME challenges other than http/https

### ISSUE THREAD

**Issue by janipewter** [icing/mod_md#58]
Will other ACME challenge methods than http/tls be available in this? I use cloudflare-dns challenge for the majority of my domains.

**Comment by icing** [comment]
There are currently no plans to support other challenge methods. DNS challenges, it seems to me, are most suitable for certificate management in close coop with a name server, not the http server. So, Apache does not seem to be the right place for it.

What I have vaguely in mind for some future time is a ```MDCAProtocol``` like ```external``` where an external application is spawned for sign-up/renewal. That would place the new certs/keys into the staging area and mod_md would take care of the provisioning into Apache. That could be an integration point for other cert management methods.

But, to reiterate, there is no plan yet to do that.

**Comment by Akhond-Zada** [comment]
I am very  upset  and tired  looking  for  my credit  card  details  I need  to  get  paid
