### ISSUE TITLE
upstream status of the mod_ssl patch

### ISSUE THREAD

**Issue by drzraf** [icing/mod_md#59]
In the hope this module could be soon massively used, I'd be interesting to know whether the mod_ssl patch has been upstreameed.
In Debian it has not yet been integrated to the binary package ( https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877341 / https://anonscm.debian.org/cgit/pkg-apache/apache2.git/tree/debian/patches?h=stretch ).
What's the status of Apache's httpd w.r.t?

**Comment by icing** [comment]
We just released 2.4.29, still without it. I will propose it for backporting into the next release.

**Comment by drzraf** [comment]
was it finally merged?

**Comment by icing** [comment]
The mod_ssl patch was accepted for backport, will merge today.

**Comment by icing** [comment]
Landed in r1820075 in Apache httpd branches/2.4.x, ready for next release.

**Comment by drzraf** [comment]
More precision:
http://svn.apache.org/viewvc?view=revision&revision=1820075
https://fisheye.apache.org/changelog/httpd?cs=1820075
Hopefully in 2.4.30 : https://www.apachelounge.com/Changelog-2.4.html
