### ISSUE TITLE
httpd.json file not found

### ISSUE THREAD

**Issue by mandymiller** [icing/mod_md#60]
Hi, I installed mod_md on Apache 2.4X, running on windows 7. Up to now I installed letsencrypt certificates manually, so I wanted to try the new possibility to automate this process via mod_md. But unfortunatelly I run into errors. The first error says: 
"[md:trace2] [pid 6892:tid 408] md_store_fs.c(434): (OS 2)Das System kann die angegebene Datei nicht finden.  : loading type 1 from C:/path/to/directory/md/httpd.json" md cant find that file.
But there are more problems. If you don`t mind I would sent the error Log directly to you. Please let me know if this is ok.

**Comment by icing** [comment]
Hey, sure. The "not found" at trace2 level is normal when mod_md checks if files exist already. But send the log to stefan.eissing at greenbytes.de and I will look into it.

**Comment by icing** [comment]
Also [apachelounge](https://www.apachelounge.com/viewtopic.php?p=36054#36054) has builds with mod_md and other people using it on Windows. They might be able to help, too!
