### ISSUE TITLE
Compile error on ARMv5 (embedded uClibc)

### ISSUE THREAD

**Issue by MrDini123** [icing/mod_md#61]
Hi,

I am also experiencing a similar error like described in this issue ticket #29  when I try to build the mod_md on an embedded ARMv5 NAS:

```
configure: summary of build options:

    Version:        1.0.1 shared 11:0:6
    Host type:      armv5tel-unknown-linux-uclibceabi
    Install prefix: /ffp/apache
    APXS:           /ffp/bin/apxs
    HTTPD-VERSION:  2.4.18
    C compiler:     gcc -std=gnu99
    CFLAGS:         -g -O2 -I/ffp/include -DMD_HAVE_ARC4RANDOM
    WARNCFLAGS:
    LDFLAGS:         -L/ffp/apache/lib
    LIBS:           -lcurl -ljansson -lcrypto  -L/ffp/lib -lcurl
    CPPFLAGS:        -I/ffp/apache/include -I/ffp/include/apr-1
    curl            curl
    curl-config     curl-config
    jansson         -
    openssl         openssl

root@NSA320S:/i-data/bf835951/build/mod_md# make
Making all in src
make[1]: Entering directory '/i-data/bf835951/build/mod_md/src'
  CC       mod_md_la-mod_md_config.lo
mod_md_config.c: In function 'inside_section':
mod_md_config.c:217:8: error: implicit declaration of function 'ap_cstr_casecmp' [-Werror=implicit-function-declaration]
        if (!ap_cstr_casecmp(d->directive, section)) {
        ^
cc1: all warnings being treated as errors
Makefile:759: recipe for target 'mod_md_la-mod_md_config.lo' failed
make[1]: *** [mod_md_la-mod_md_config.lo] Error 1
make[1]: Leaving directory '/i-data/bf835951/build/mod_md/src'
Makefile:489: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

What Can I do?

Thanks.

**Comment by jsha** [comment]
I think most likely you need to download the most recent version of the Apache source, build it, and install the headers and dynamic libraries.

**Comment by icing** [comment]
Right, @jsha. The 2.4.18 is too old and lacks, among other things, the referenced function.

**Comment by MrDini123** [comment]
I have installed the latest stabile Apache (2.4.29), but I got this error during the make:

```
  CC       libmd_la-md_crypt.lo
md_crypt.c: In function 'seed_RAND':
md_crypt.c:66:5: error: implicit declaration of function 'arc4random_buf' [-Werror=implicit-function-declaration]
     arc4random_buf(seed, sizeof(seed));
     ^
cc1: all warnings being treated as errors
Makefile:696: recipe for target 'libmd_la-md_crypt.lo' failed
make[1]: *** [libmd_la-md_crypt.lo] Error 1
make[1]: Leaving directory '/i-data/bf835951/build/mod_md/src'
akefile:489: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by icing** [comment]
That has nothing to do with Apache 2.4.29, @MrDini123.

The ```mod_md``` configure script, for some time now, checks if ```arc4random``` exists (but not explicitly for ```arc4random_buf```, I just notice). The function ist part of the system stdlib in OpenBSD and other platforms may or may not have it.

Which platform and version of mod_md are you using?

**Comment by MrDini123** [comment]
I have tried to compile the mod_md 1.0.2 from git, and I got that error during the compile.

It is an embedded NAS with a custom 2.6.31.8 linux and FHS. It has uClibc library.

**Comment by MrDini123** [comment]
Up! It would be really awesome, if I Could replace the currently working acme.sh script to this module.

Please help me, what Can I do?

Thanks.

**Comment by icing** [comment]
Sorry for the late reply, let's continue this discussion over on Issue #67, ok?
