### ISSUE TITLE
Stuck in "Partial results are valid but processing is incomplete"

### ISSUE THREAD

**Issue by mss** [icing/mod_md#62]
I already deployed a few dozen LE enabled sites with certbot and dehydrated but for a private project I decided to give mod_md a try. I hope this is really an issue with mod_md and not a configuration issue on my side. This isn't supposed to be a support request; I think even if this is a dumb configuration issue, the error message I am staring at for a few hours now could be improved to point into the right direction.

A short history of steps I performed (with config reloads in between):

1. Installed `apache2` and `libapache-mod-md` v1.0.1 from the PPA.
2. Configured a minimal HTTP and HTTPS config (current state below).
3. Configured the vhost as a `ManagedDomain`.
4. Found out from the very helpful log message (:+1:) that I had to set `MDCertificateAgreement`. Did so.
5. Remembered that my `Redirect` based config for port 80 is too broad and found out about `MDRequireHttps` instead.
6. Poked around in `/etc/apache2/md` and noticed that the `initialIp` has an IPv6 address and thus added the `AAAA` record to my domain just in case.
7. A few hours later: Still waiting for a proper cert to be deployed and wondering what the folliowing messages mean:

```
[Sun Nov 12 18:42:19.156053 2017] [md:debug] [pid 17202] mod_md.c(757): AH10055: md watchdog run, auto drive 1 mds
[Sun Nov 12 18:42:19.156116 2017] [md:debug] [pid 17202] mod_md.c(686): AH10052: md(cloud.msquadrat.de): state=1, driving
[Sun Nov 12 18:42:19.156141 2017] [md:debug] [pid 17202] md_reg.c(886): cloud.msquadrat.de: run staging
[Sun Nov 12 18:42:19.156148 2017] [md:debug] [pid 17202] md_acme_drive.c(666): cloud.msquadrat.de: staging started, state=1, can_http=1, can_https=1, challenges='http-01'
[Sun Nov 12 18:42:19.156256 2017] [md:debug] [pid 17202] md_acme_drive.c(888): (70008)Partial results are valid but processing is incomplete: cloud.msquadrat.de: ACME, ACME staging
[Sun Nov 12 18:42:19.156268 2017] [md:debug] [pid 17202] md_reg.c(893): (70008)Partial results are valid but processing is incomplete: cloud.msquadrat.de: staging done
[Sun Nov 12 18:42:19.156280 2017] [md:error] [pid 17202] (70008)Partial results are valid but processing is incomplete: AH10056: processing cloud.msquadrat.de
[Sun Nov 12 18:42:19.156288 2017] [md:info] [pid 17202] AH10057: cloud.msquadrat.de: encountered error for the 10. time, next run in  0:42:40 hours
[Sun Nov 12 18:42:19.156303 2017] [md:debug] [pid 17202] mod_md.c(779): AH: next run in  0:42:39 hours
```

According to my `access.log` there wasn't a single request from LE. Querying `/.well-known/acme-challenge/foo` woks though (ie. gives a 404 instead of a redirect).

If required, I can provide the full `error.log` and any of the files from `/etc/apache2/md`:
```
/etc/apache2/md
├── accounts
├── challenges
├── domains
│   └── cloud.msquadrat.de
│       ├── fallback-cert.pem
│       ├── fallback-privkey.pem
│       └── md.json
├── httpd.json
├── md_store.json
└── staging
    └── cloud.msquadrat.de
        ├── account.json
        ├── account.pem
        └── md.json
```

My current config (not stripped down, I just redacted the `ServerAdmin`):
```
<ManagedDomain cloud.msquadrat.de>
        MDCAChallenges http-01
        MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
        MDRequireHttps permanent
</ManagedDomain>

<VirtualHost *:443>
        ServerName cloud.msquadrat.de
        ServerAdmin webmaster@example.com

        Protocols h2 http/1.1
        SSLEngine on

        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

<VirtualHost *:80>
        ServerName cloud.msquadrat.de
        ServerAdmin webmaster@example.com

        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by icing** [comment]
Heya, @mss. Thanks for giving this a shot and providing the nice details.

From the log, I can see that your staging area was not reset , as it should, when you added the certificate agreement to your configuration. I addressed that in the new v1.0.2 release.

What you can do now is simply to ```rm -r /etc/apache2/md/staging/could.msquadrat.de``` and do a ```service apache2 reload```. This starts the signup from scratch and, since the certificate agreement is in place, this should run through. You config looks all fine.

In case of any other probs, let me know.

**Comment by mss** [comment]
Thanks for the quick reply! Do you want me to keep the current state around to see if your v1.0.2 will fix the issue? I won't have time to work on this until next weekend anyway.

**Comment by icing** [comment]
If you can wait it would be a nice verification.

**Comment by icing** [comment]
Ok, other people are reporting the same problem. Data provided indicates that ```mod_md```is buggy when it comes to handling new certificate agreements properly.

Let's Encrypt updated their license agreement to "MDCertificateAgreement as https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf" and ```mod_md``` can get stuck, even if you configure the new url.

**Comment by icing** [comment]
People experiencing this problem, please perform the following steps until I can make a new release:

 * Configure the new MDCertificateAgreement url in your Apache config
 * remove all directories in the md store underneath ```staging```
 * ```reload``` your server

Sorry for the inconveniences.

**Comment by icing** [comment]
Ok, reproduced the problem and applied various cures: please try [v1.0.3](https://github.com/icing/mod_md/releases/tag/v1.0.3).

**Comment by mss** [comment]
I'll test the ipdate once it is available via @oerdnj's PPA.

**Comment by mss** [comment]
The PPA isn't updated yet but I rebuilt/bumped the package myself and after an apache restart followed by two reloads (one for the new EULA URL, the second to have the cert actually deployed) everything looks fine now. Thanks!

**Comment by icing** [comment]
Thanks! Glad to hear that it works now for you also.
