### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by boldt** [icing/mod_md#64]
Following the [documentation provided in this Wiki](https://github.com/icing/mod_md/wiki/Simple-Usage
), some things are not clear:

# 1) SSLEngine required

## Error

```
Invalid command 'SSLEngine', perhaps misspelled or defined by a module not included in the server configuration
```

## Solution

`mod_ssl` still needs to be enabled (a2enmod ssl)

# 2) ServerAdmin required

## Error

```
[Mon Nov 13 14:29:51.987135 2017] [md:error] [pid 30:tid 140356995012352] (22)Invalid argument: no contact information for md example.com
```

## Solution

I added the `ServerAdmin`

[This mentioned at the last section](https://github.com/icing/mod_md/wiki/Directives#serveradmin--contact-information).

# 3) MDCertificateAgreement required

## Error

```
[Mon Nov 13 14:53:17.692973 2017] [md:error] [pid 29:tid 140457350256384] (70008)Partial results are valid but processing is incomplete: example.com: the CA requires you to accept the terms-of-service as specified in <https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf>. Please read the document that you find at that URL and, if you agree to the conditions, configure "MDCertificateAgreement url" with exactly that URL in your Apache. Then (graceful) restart the server to activate.
```

[EDIT]: Even after a restart, I cannot access my domain via https.

## Solution

I added

```
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
```

# 4) Server restart required

## Error

Now, everything is configured, the server tells me the following:

```
[Mon Nov 13 14:55:52.800165 2017] [md:notice] [pid 29:tid 139962436892416] AH10059: The Managed Domain example.com has been setup and changes will be activated on next (graceful) server restart.
```

I expeted, that the certifcates are fully installed and renewed automatically without further reload/restart. 

## Resoution

Unknown. What do you recommend?

**Comment by boldt** [comment]
I just realized, that [you mention 3) and 4) under apache already](https://httpd.apache.org/docs/trunk/mod/mod_md.html#manageddomain):

>  There are 2 additional settings that are necessary for a Managed Domain: ServerAdmin and MDCertificateAgreement. The mail address of ServerAdmin is used to register at the CA (Let's Encrypt by default). The CA may use it to notify you about changes in its service or status of your certificates.
> 
> The second setting, MDCertificateAgreement, is the URL of the Terms of Service of the CA. When you configure the URL, you confirm that you have read and agree to the terms described in the linked document. Before you do that, the CA will not hand out certificates to you.

**Comment by icing** [comment]
For now (and the documentation needs to be more clear on that), the server needs a graceful restart (e.g. what of often called ```reload```) when new certificates have been obtained. This will not interrupt any ongoing requests and therefore should not pose a problem to a site.

The typical lifetime of certs is 90 days and renewal is weeks before that. So, adding a cron job that reloads the server once a week should be sufficient to keep it running with valid certificates indefinitely.

As to the reasons for this: the main one is security. The certificate signup runs in a child process as user ```www-data``` (or such, depends on the OS) and that user has no permission to even read the real certificates. Instead, mod_md saves them somewhere else and on reload, the part of the server running as ```root``` can take the new certificates into the store and prep children to use them.

It is possible to do that differently and more automated, but that'd need some weeks of focussed work which are not available atm.

**Comment by boldt** [comment]
Thx for the quick feedback. Right, the certs are valid for 90 days. How many weeks before expiration do you refresh them?

In my case, I configured a Docker container, thus, I will handle the reload as follows:

```
docker exec -it my-ubuntu /etc/init.d/apache2 reload
```

**Comment by boldt** [comment]
I edited my inital post, maybe you havn't seen it:

> Even after a restart, I cannot access my domain via https.

**Comment by icing** [comment]
```/etc/apache2/md``` is the standard directory (on ubuntu) where the information is kept. You will find key and certificates and some json files there. When the module reports that everything is ready and needs a restart, you should see the cert and other stuff in ```/etc/apache2/md/staging/<your_domain>```. After the restart those should be gone and the files now reside in ```/etc/apache2/md/domains/<your_domain>``` from where they area loaded.

**Comment by boldt** [comment]
Staging is empty and I can see this files unter `/etc/apache2/md/domains/<your_domain>`:

* md.json 
* privkey.pem
* pubcert.pem

I found my issue: Since I use docker, I forgot to publish the port 443.

I can access my domain via https now.

Btw: all mod_md logs are written to `error.log`. Is that intended?

**Comment by boldt** [comment]
[You say](https://github.com/icing/mod_md/wiki/Migration#phase-in-https):

> In the latest Apache httpd version, there is a short-hand for this:
>
> SSLPolicy modern

Maybe its better to be specific here, that this is only available from Apache 2.5.

**Comment by icing** [comment]
Nice that it works now for you. I updated parts of the wiki where you missed information/config.

Unfortunately, github seems to miss collaboration on the wiki, but if you want to contribute any makrdown, I'd be happy to add it.

**Comment by boldt** [comment]
Maybe you can [here](https://github.com/icing/mod_md/wiki/Directives#basic-configuration)  the same note as in the apache docs:

>  There are 2 additional settings that are necessary for a Managed Domain: ServerAdmin and MDCertificateAgreement. The mail address of ServerAdmin is used to register at the CA (Let's Encrypt by default). The CA may use it to notify you about changes in its service or status of your certificates.
> 
> The second setting, MDCertificateAgreement, is the URL of the Terms of Service of the CA. When you configure the URL, you confirm that you have read and agree to the terms described in the linked document. Before you do that, the CA will not hand out certificates to you. 

Or meantion at least, that these two are required.
