### ISSUE TITLE
Windows installing service reports log messages as error

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_md#66]
See with mod_md a behavior which is not standard as with other modules. The module mod_md is the only one where I see this behavior.

When installing as service log messages info/warn are reported as errors:
```
C:\apache24\bin>httpd -k install
Installing the 'Apache2.4' service
The 'Apache2.4' service is successfully installed.
Testing httpd.conf....
Errors reported here must be corrected before the service can be started.
[Tue Nov 28 10:03:43.126510 2017] [md:info] [pid 7364:tid 392] AH10071: mod_md (v1.0.3-git), initializing...
C:\apache24\bin>
```
Please fix.

ps.
On the httpd dev list I posted other situations where log messages are reported as errors.

**Comment by icing** [comment]
INFO level logging fixed in v1.0.5.
