### ISSUE TITLE
I want to use 'Issues' for support

### ISSUE THREAD

**Issue by icing** [icing/mod_md#67]
This is fine, but only on this, single issue. Don't just append your questions to already fixed and closed bug reports. Write them here. 

Thanks.

**Comment by icing** [comment]
@MrDini123 wrote over on #61: "I have mod_md compile for my NAS, what can I do now?"

That depends. And most importantly it depends on two things:
 1. Is your NAS httpd reachable from the Internet on ports 80 and/or 443?
 1. Do you have a Domain Name for the address where your NAS can be reached? (not a dynamic one)

If one of the questions is no, then ```mod_md``` can not get you Let's Encrypt certificates. You can still use it to:
 * redirect http: traffic to https: if you have certificates from elsewhere
 * provide certificates you have to the ```VirtualHost```s they are for, if you prefer ```mod_md```s way over the explicit configuration of ```mod_ssl```.

**Comment by MrDini123** [comment]
_I have mod_md compile for my NAS, what can I do now?_

Nope, unfortunately I couldn't compile the module. I have the `arc4random_buf`issue.

**Comment by icing** [comment]
Ok, specially for you: v1.0.6

There was a mistake in configure that checked for the wrong function. Please reconfigure and then it should compile for you - I hope.

**Comment by MrDini123** [comment]
Thanks @icing. It compiles now. I am going to try it ASAP. :)

**Comment by MrDini123** [comment]
I configured the server on my root domain, it works on port 80 and 443 too. I Can reach the server, and I get an Apache domain fallback key, but not a Let's encrypt key...

Here is the error:

```
[Thu Dec 21 09:12:32.111322 2017] [md:error] [pid 16490] secret.com: the server seems neither reachable via http (port 80) nor https (port 443). The ACME protocol needs at least one of those so the CA can talk to the server and verify a domain ownership.
[Thu Dec 21 09:12:32.111602 2017] [md:error] [pid 16490] (20014)Internal error (specific information not available): AH10056: processing secret.com
```

What Can I do?

**Comment by icing** [comment]
Hmm, the module thinks that your server does not ```Listen``` on either port 80, nor port 443. Without those, ACME authentication can not happen. 

This seems to be wrong. Do you have a setup that you can mail me? (icing at apache org) Then I can have a look and try to reproduce.

**Comment by MrDini123** [comment]
I have pasted my VirtualHost config at #68.

```
MDomain secret.com
<VirtualHost *:12344>
    DocumentRoot "/var/www/external"
    ServerName not.secret.com
    ServerAlias secret.com
    SSLEngine on
</VirtualHost>
```

And the apache listens on the 12344 port. And this is forwarded in my router to the external 80 and 443 ports. Because I have another apache server running on the internal 80 port.

**Comment by icing** [comment]
OK, then have a look [here](https://github.com/icing/mod_md/wiki/Directives#mdportmap). This was made especially for you. You would configure:

```
MDPortMap 443:12344
```
and reload.

**Comment by MrDini123** [comment]
Oh, thanks. That was exactly what I was looking for. Really useful. Now I have a wonderful Let's encrypt key without using automated shell scripts. And it is done by an Apache module. Awesome!

BTW I would recommend an update in the linked reference, because the ManagedDomain directive is deprecated now.

**Comment by icing** [comment]
Thanks, have done.

**Comment by MrDini123** [comment]
I think that was a good idea to have an open issue for all the support related questions for any new mod_md users. :)

Why did you close it?

**Comment by icing** [comment]
:-D Not fully awake yet... sorry.

**Comment by MrDini123** [comment]
No problem. I just got scared, because I have another question now.

As you may know, I have a non standard port forwarded to the external 80 & 443 ports. If I try to access my site using HTTP. it gives me a Bad request error. I have to edit manually the URL to point to HTTPS.

I want a redirect from every HTTP request to the corresponding HTTPS site. For this purpose I modified my VirtualHost config a little:

```
<VirtualHost *:12345>
    DocumentRoot "/var/www/ext"
    ServerName domain.tld
    SSLEngine on
    
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>

<VirtualHost *:12346>
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>
```

If I forward the 12345 port to the 80 & 443 ports, it doesn't redirect the users, but gives the bad request... However if I forward the 12346 port to the external 80, and the 12345 remains listening on external port 443 everything works as expected. I don't understand why the same rule doesn't work with the first VHost...

I have found a cool directive in mod_md, and this is the `MDRequireHttps`. That works perfectly, but it redirects the users to the root. Like from http://domain.tld/some/path/file.extension to the https://domain.tld. I need to have been redirected to the https://domain.tld/some/path/file.extension path.

**Comment by icing** [comment]
Ok, you found ```MDRequireHttps``` and that should do exactly what you want. On my server it does not loose the path. Maybe you have too many rewrites and they step on each others toes?

As to port forwarding: you better assign one port for ```http:``` and one to ```https:```. So, on your router you send port router:80 to server:12345 and router:443 to server:123456. And then add on the server ```MDPortmap 80:12345 443:12346```.

**Comment by MrDini123** [comment]
```
:~# curl http://domain.tld/test.txz
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://domain.tld/">here</a>.</p>
</body></html>
```

Config:

```XML
MDomain domain.tld
MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
MDPortMap 443:8081
MDRequireHttps temporary
<VirtualHost *:8081>
    DocumentRoot "/var/www/ext"
    ServerName domain.tld
    ServerAlias domain.tld
    SSLEngine on
</VirtualHost>
```

I thought that is a CloudFlare bug first, because my Apache server is behind a CF proxy, but not. I forced the real host IP in my DNS server, and created a firewall rule. after that I Can also see the redirect to the root.

**Comment by icing** [comment]
Update: I recommend users with support questions to go to the ```users``` mailing list for Apache httpd, see https://httpd.apache.org/lists.html People  observing suspicious behaviour or have improvement suggestions are very welcome at the ```dev``` mailing list also.

You will reach more people there than just me here. And get faster help.
