### ISSUE TITLE
MDRequireHttps behavior on unmanaged domains

### ISSUE THREAD

**Issue by nono303** [icing/mod_md#72]
Hi,

I would like a precision on MDRequireHttps Directive Scope
I understand reading https://httpd.apache.org/docs/trunk/mod/mod_md.html#mdrequirehttps that `MDRequireHttps `permanent will only apply on managed domains but it seems not to be the case on unmanaged virtual host.

Here is my vhost configuration:
```
<Macro VhRedirect $vh>
  ServerName $vh
  Include conf/vhosts/$vh.alias.conf
  Redirect permanent / https://$vh/ 
</Macro>

<Macro VhServe $vh>
  ServerName $vh
  Include conf/vhosts/$vh.alias.conf
  ...
</Macro>

<Macro VHostLets $vh>
  MDomain $vh
  <VirtualHost ${IP_LISTEN}:${HTTP_PORT}>
    Use VhRedirect $vh
    # Use VhServe $vh
  </VirtualHost>
  <VirtualHost ${IP_LISTEN}:${HTTPS_PORT}>
    SSLEngine on
    Use VhServe $vh
  </VirtualHost>
</Macro>

Use VHostLets a.exemple.com
Use VHostLets b.exemple.com
...
# local http
<VirtualHost ${IP_LISTEN}:${HTTP_PORT}>
  Use VhServe localhost
</VirtualHost>
```

My goal is to suppress `VhRedirect `for vhost using macro `VHostLets `(which are all managed by mod_md)
But for my last vhost ‘’localhost’’ using macro `VhServe `(which is not managed by mod_md) must be accessible only in http.
If I set `MDRequireHttps` permanent on this configuration, localhost will only be accessible in https. 

Is that the normal behavior or maybe a bug?
Thanks for your feedback!

Regards

**Comment by nono303** [comment]
@icing, additionally you can mention on your main wiki page my repo for mod_md windows VC15 builds (x86 & x64) if you want.
https://github.com/nono303/mod_md 
I'll keep it up to date.

Windows users feedback @ https://www.apachelounge.com/viewtopic.php?p=36294

**Comment by icing** [comment]
Added the link to your github repository on the installation wiki page, thanks!

As to your problem with localhost. Are you sure that ```localhost``` is not somehow appearing in one of you managed domains? You can look into the ```md.json``` files on your disk.

Because ```mod_md``` should only take over for vhosts where server names/aliases match. That makes me think: what is the content of ```localhost.alias.conf? Any ```ServerAlias``` definitions in there that might cause the module to care about that vhost?

**Comment by nono303** [comment]
Hi Icing, Thanks for your fedback!
 -  Localhost doesn’t appear as a directory in **{MDStoreDir}/domains**. Only have 1 directory by md managed vhost.
 -  With `MDMustStaple` permanent, localhost vhost always use the ssl certificate of the first declared managed vhost (in my config: `a.exemple.com`). I’ve swap it to verify
 -  The declaration position of localhost vhost (before or after other md managed vhost) doesn’t change anything on the described behavior
 -  Localhost doesn’t apper in **{MDStoreDir}/domains/ a.exemple.com/md.json** domains array, neither in all other **md.json** off all others vhosts
 -  localhost.alias.conf contain `ServerAlias` name of all binding IP and corresponding computer name with dns suffix 
 -  No one of these `ServerAlias` appear too in all **md.json**…  

Hope it clarify and don’t hesitate to submit me some testing

**Comment by icing** [comment]
Ok, can you provide me a log with

```
LogLevel md:trace1
```

from server start to first request to localhost? Thanks!

**Comment by nono303** [comment]
Hi Stefan,
I’d sent you traces on your email (with all my vhost dns name…).

I had not seen differences in traces between `MDRequireHttps `permanent and off
Precision: with `MDRequireHttps `permanent, an http localhost hit is always taken by first md managed vhost and redirected to https with consequently a bas certificate. 

To summarize: **with `MDRequireHttps `permanent unmanaged localhost vhost is unreachable.**

**Comment by icing** [comment]
Hei, a question while trying to read the logs: do you have a ```ServerName``` directive in the global context? If so, do you get the same, wrong behaviour when you comment it out?

Thanks for all the data!

**Comment by nono303** [comment]
**This is it!!**

Setting `ServerName `null in main config (outside vhost conf) resolve the problem.
Note that deleting `ServerName `in main config can cause trouble because apache seems to set the default `ServerName `with computer hostname which that may interact with one of the existing vhost `ServerName `ou `ServerAlias `(it was my case)
...May be good to add this point on your wiki

So I’ve tested and checked most of the mod_md config on Windows (vc15 x64) and all seems OK.

Now I'm waiting for letencrypt ACME v2 API and wildcard cert capabilities, hope that will come soon ;)

**Comment by icing** [comment]
Thanks for verifying. I will think about how to best fix that. Should not be the admin's problem.
