### ISSUE TITLE
v1.1.8 [ssl:warn] SSLSrvConfigRec shared

### ISSUE THREAD

**Issue by nono303** [icing/mod_md#75]
Hi,
Testing v1.1.8 (Windows vc15 x64), I’ve noticed strange **[ssl:warn] 'SSLSrvConfigRec shared'** in vhost error logs.
- It doesn’t appear with v1.1.7 with same vhsot config
- It didn't see any regression...
- It doesn’t appear for all vhost and have the line 3 time written every startup
```
[ssl:warn] AH10104: a.example.com:80, SSLSrvConfigRec shared from b.example.com:80
[ssl:warn] AH10104: a.example.com:80, SSLSrvConfigRec shared from b.example.com:80
[ssl:warn] AH10104: a.example.com:80, SSLSrvConfigRec shared from b.example.com:80
```
where `a.example.com` is declared before `b.example.com`

Nothing had change in my config and i had test both with new directive MDBaseServer on and off
tested with v1.1.8 from httpd 2.4.x-mod_md and v1.1.8-git tagged on your github.

Note that had to remove [`#include "mod_md.h"` l.33](https://github.com/apache/httpd/blob/2.4.x-mod_md/modules/ssl/ssl_engine_init.c) on 2.4.x-mod_md

I'll sent you full trace by mail.

Regards,

**Comment by nono303** [comment]
Not in mod_md but in mod_ssl, change [1820314](https://svn.apache.org/viewvc/httpd/httpd/branches/2.4.x-mod_md/modules/ssl/ssl_engine_init.c?r1=1816423&r2=1820314&pathrev=1820314)
Arf... I don't really understand what the problem with `sc->vhost_id already set. This should only happen if this config rec is shared with another server. Argh!` ;)

**Comment by icing** [comment]
Well, do not build against ```2.4.x-mod_md``` please. Use only ```2.4.x```. The former is a utility branch to help backporting changes, not something you should run.

**Comment by nono303** [comment]
Thanks Stefan!
All sounds good now with [2.4.29](https://github.com/apache/httpd/tree/2.4.29) & mod_ssl [patched ](https://github.com/icing/mod_md/blob/master/patches/mod_ssl_md-2.4.x-v5.diff);)  

----
Note: (nothing to deal with this ticket...)  About [MDRequireHttps ...This adds the header Strict-Transport-Security to responses... ](https://github.com/icing/mod_md/wiki/Directives#MDRequireHttps) 
For those who want to override your Strict-Transport-Security builtin directive, you must remove it before setting new one. 
Ex.:  
```
Header unset "Strict-Transport-Security"
Header always set Strict-Transport-Security "max-age=31536000; includeSubdomains; preload"
```
If not, ssllabs and maybe some browsers warn about more than one HSTS headers... (I didn't read it beforehand and passed some time to understand it ;)
Maybe a tips to add to the wiki...
