### ISSUE TITLE
Can't build without boulder installation

### ISSUE THREAD

**Issue by Sp1l** [icing/mod_md#76]
I see that as of e2d589c2f774160afbb910966c9e6cedbbb82fd5 mod_md requires a boulder directory for the tests.

Configuring `--without-boulder-dir` fails with

> configure: error: boulder installation not found as specified in no.

I can't find a `--without-tests` flag either.

THis may well be intentional, then deserves documenting in wiki.

**Comment by icing** [comment]
You are correct. This should not be a configure check but a precondition to ```make test``` only. Will fix.
