### ISSUE TITLE
MDCAChallenges tls-sni-01 not available anymore ?

### ISSUE THREAD

**Issue by nono303** [icing/mod_md#77]
Hi,

Today testing with `MDCAChallenges tls-sni-01` return the following error :

`# (22)Invalid argument: example.com: the server offers no ACME challenge that is configured for this MD. The server offered 'dns-01 http-01' and available for this MD are: 'tls-sni-01' (via https://acme-v01.api.letsencrypt.org/acme/authz/XXX).`

This had worked few days ago...
API change or Let's Encrypt temporary bug ??

**Comment by cpu** [comment]
> API change or Let's Encrypt temporary bug ??

@nono303 [This post](https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811) has all of the relevant background. 

TLS-SNI-01 has been disabled by Let's Encrypt except for specific whitelisted conditions. It will not be re-enabled.

**Comment by nono303** [comment]
Thanks @cpu! 
So only `MDCAChallenges http-01` now
