### ISSUE TITLE
Failing tests due to json_t* refcount issues

### ISSUE THREAD

**Issue by jchampio** [icing/mod_md#8]
With the patch in #7, some failing tests are exposed. I'm currently working with `test_600_000`, which is triggering the new corruption check in that patch and leading to an `APR_EINVAL` return code.

I haven't root-caused completely yet, but it looks like `md_acme_authz_set_to_json()` and/or `md_json_seta()` are not handling the `json_t` refcounts correctly. Some of the JSON values we need are being released, and others are being given refcounts that seem overly large.

Is there documentation (or a rule of thumb) on how each JSON utility function is supposed to be manipulating refcounts?

(Also, has there been any discussion on a C-based test suite to complement pytest, so we can test the internals as well?)

**Comment by icing** [comment]
The jansson doc says that when you create a json_t (e.g. via json_object()), it has a refcount of 1. Which makes sense. So the surrounding md_json_t is the sole owner. Same with a md_json_copy()/md_json_clone() object.

When jselect_set_new() is called, it gets a new json_t (ref==1) assigned via json_object_set_new(). That, according to jansson docs, steals the refcount.

Strings assigned via ```md_json_sets()``` get copied by jansson. Strings retrieved via ```md_json_gets()``` are only valid as long as the json property exists. For safe access, there is ```md_json_dups()```which hands out a copy.

Trickier are the ```md_json_setj()``` and ```md_json_getj()``` variants that actually increment refcount and share json_t instances. 

As to serialization: I originally used a 2.10 function ```json_dumpb()```, but needed to replace that to work with older jansson versions. 

#### So, back to the original issue:
Scanning jansson ```json_dump_callback()``` implementation, the most likely reasons for it failing are:

 *  ```utf-8``` string checking fails (any control chars in your domain names?)
 * buffer memory allocation fails (unlikely)

We could add a ERR log output of where the serialization failed by listing the so far accumulated dump?

**Comment by jchampio** [comment]
> Scanning jansson json_dump_callback() implementation, the most likely reasons for it failing are:

It's 100% a refcount problem. Pieces of the JSON structure are getting released and then the `json_t*` points to madness, which causes `json_dump_callback` to return -1 when it sees an invalid object type.

**Comment by icing** [comment]
Ok, then we need to track that down. It might be just my crazy MacOS memory layout that is does not show up here like on any sane *NIX installation. Or the versions behave differently. Either way. Is there a specific file that fails for your fairly often? Which?

**Comment by jchampio** [comment]
It seems to be related to `md_acme_authz_set_to_json()` and/or `md_json_seta()`. The test that fails is `test_600_000`, and the failure is 100% reproducible -- but remember, it didn't "fail" before the patch added in #7; the truncated JSON was completely ignored instead.

I can see refcounts going to zero in the implementation of `md_json_seta()`, but stepping through with a debugger, I don't know which functions are supposed to be manipulating refcounts and which aren't. I don't really understand what `md_json_seta` is doing with its `wrap.j` stuff, or why it's `decref`ing anything at all.

Sorry this isn't very helpful yet; I was hoping you'd be able to reproduce on your box.

**Comment by icing** [comment]
@jchampio could you try out the current master? I think I went a bridge too far in md_json_seta() and made it simpler again.

**Comment by jchampio** [comment]
@icing Looks like that fixed it on my machine.

Is `md_json_seta` supposed to be stealing the reference to the `md_json_t` returned by the client callback? Right now it's calling `json_array_append`, which further increases the refcount of `wrap.j` to 3.

**Comment by icing** [comment]
So, current master uses append_new() which keeps the refcount to 2 at the end of the md_json_seta(). Which drops to 1 when the pool for the created md_json_t instances goes away. Unless its the same pool, in which case it should go to 0.

I agree that a test suite just for this would be good to have. ^^

**Comment by jchampio** [comment]
> I agree that a test suite just for this would be good to have. ^^

Any preferences on what that should look like? My suite in httpd uses [Check](https://libcheck.github.io/check/), but if you have other ideas I'm all ears.

**Comment by icing** [comment]
> Am 26.07.2017 um 20:27 schrieb Jacob Champion <notifications@github.com>:
> 
> I agree that a test suite just for this would be good to have. ^^
> 
> Any preferences on what that should look like? My suite in httpd uses Check, but if you have other ideas I'm all ears.
> 
I have not much experience with C test frameworks. If you like Check and we have it in httpd that's good enough for me.

Is otherwise mod_md doing sth for you now? I am short of getting the tls sni challenge to work. Unfortunately will be busy with other things tomorrow.

**Comment by jchampio** [comment]
> Is otherwise mod_md doing sth for you now? I am short of getting the tls sni challenge to work.

I'm still working on getting the test suite to pass 100% on my machine. Looks like possibly more memory issues elsewhere, but I haven't started digging yet. This specific issue seems resolved for now, though -- thanks!
