### ISSUE TITLE
Building 1.1.8 on Ubuntu 16.04 fails w/ 'error: boulder installation not found in default location'

### ISSUE THREAD

**Issue by Alphakilo** [icing/mod_md#80]
Hi! I've followed the instructions from the [wiki](https://github.com/icing/mod_md/wiki/2.4.x-Installation/9b8103ce2f78a88c2a2f870817a8a2f887e72b88#ubuntu).

I've added the ondrej/apache2 PPA and installed all named depencies:
`apt install -y apache2 apache2-dev build-essential autoconf make libtool libssl-dev libjansson-dev libcurl4-openssl-dev`

This is what I got:
```
root@[REDACTED]:/usr/local/src# wget --quiet https://github.com/icing/mod_md/releases/download/v1.1.8/mod_md-1.1.8.tar.gz && sha256sum *.gz
c0fe8ab146e43f2d9123f405fbb09c4890dcc780e81bd7fedcea2e7e4467690e  mod_md-1.1.8.tar.gz
root@[REDACTED]:/usr/local/src# tar -xf mod_md-1.1.8.tar.gz
root@[REDACTED]:/usr/local/src# cd mod_md-1.1.8/ && echo -e 'apxs is here: ' && which apxs && ./configure --with-apxs=$(which apxs) --enable-werror
apxs is here:
/usr/bin/apxs
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
# [Omitted, for full details check: https://pastebin.com/T2YR70gX]
checking for pkg-config... no
configure: error: boulder installation not found in default location /src/github.com/letsencrypt/boulder. Please use --with-boulder-dir to specify the correct location.
```

Here's what I did to work around the issue:
```
git clone https://github.com/letsencrypt/boulder /usr/local/src/boulder && \
./configure --with-apxs=$(which apxs) --enable-werror --with-boulder-dir=/usr/local/src/boulder/
```

Anyways. Thanks for the great work!

**Comment by icing** [comment]
Hey, thanks for the report! Yes, that dependency was wrongly added to ```configure``` in 1.1.8. It is removed in the master branch, but I did not push a new release yet. If you'd like, you can clone master and try it from there.

In any case, the next release will not carry this any longer.

**Comment by Alphakilo** [comment]
I can confirm that it's fixed in master.
Thank you very much 👍
