### ISSUE TITLE
directory permissions to re-use certs for other apps ?

### ISSUE THREAD

**Issue by opsec** [icing/mod_md#84]
If a cert is created or re-created, mod_md sets the directory and file permissions to owner root, mode 700 or 600. If other applications like exim or dovecot want to use those certs, they need their own copy or some MDNotifyCmd hook.

Would it be possible to provide options to configure the permissions and group ownership of the directories and files create ? For example:

MDGroup [group]
MDUmask 0277

Thanks!

**Comment by icing** [comment]
Not to say this isn't necessary, but I myself have such a setup where Apache's certificate is used by postfix and dovecot. For curiosity sake: in which setup does sharing the certificate from root not work?

**Comment by opsec** [comment]
exim config:

tls_certificate = /usr/local/etc/apache24/certs/domains/thedomaininquestion/pubcert.pem
tls_privatekey = /usr/local/etc/apache24/certs/domains/thedomaininquestion/privkey.pem

dovecot works.

**Comment by opsec** [comment]
exim docs say:
http://www.exim.org/exim-html-current/doc/html/spec_html/ch-encrypted_smtp_connections_using_tlsssl.html

These files need to be PEM format and readable by the Exim user [...]

**Comment by icing** [comment]
Thanks, learned something again. Seems that Exim has shot itself in the foot by evaluating certificate path dynamically at runtime, when privileges have already been dropped.

Well, I do not particularly look forward to manage the complexity of group/permission exceptions. Is [MDNotifyCmd](https://httpd.apache.org/docs/trunk/mod/mod_md.html#mdnotifycmd) something which would let you make a copy for the Exim setup?

**Comment by opsec** [comment]
A script to copy files and restart exim smells a bit 8-). If one has more than a few domains on a mailserver, it gets messy, because they might renew at different times, how would the script know about which to renew etc ?

**Comment by icing** [comment]
The script gets as parameter the ManagedDomain names that were renewed. But the script is run as ```www-data```, so it will not have the proper permissions to do the job anyway, I suppose. Hmm.

I am a bit hesitant to add complexity and weaken security for exim, where any other service does things in a better way. 

How about copying the files on exim start script? I assume it does not reload the certificate/keys on every new connection and needs a restart anyway?

**Comment by opsec** [comment]
I have not yet tested if exim reloads the certs if they are modified. And: If the mod_md script runs with the wrong permissions, it can't fix the permissions itself or restart exim, so the script is out in general.

Looks like the MDUmask / MDGroup option is simpler ? I can try to provide a patch, but I probably need longer to get me up to speed 8-}

**Comment by icing** [comment]
If exim does not reload every time, it needs a restart anyway. That would be the opportune moment to copy.

The mask/group thing needs not only the code to set, but also the code to upgrade/change/remove again. That is where the complexity creeps in...

**Comment by opsec** [comment]
Other cert-using apps are probably affected as well -- I have openvpn in my mind, but there will be other apps, I'm sure 8-}

**Comment by opsec** [comment]
How do I sync a re-issue with an exim restart ?

**Comment by opsec** [comment]
[mdchnotify.txt](https://github.com/icing/mod_md/files/1845180/mdchnotify.txt)
[mdchnotify-wrapper.txt](https://github.com/icing/mod_md/files/1845181/mdchnotify-wrapper.txt)

I have a somehow working solution which includes a wrapper script which calls sudo with this in /usr/local/etc/sudoers:

# for MDNotifyCmd /client/libexec/mdchnotify-wrapper
www ALL=(root) NOPASSWD: /client/libexec/mdchnotify

There still are a few open issues.
- If we have several domains to set up for certificates, how often and with which arguments is the script called ?
- why do we have to first 'graceful' the apache instance and then sleep ? because otherwise the files are not there yet to change their permissions/groups.

While it works for now, it's definitly not pretty.

**Comment by opsec** [comment]
Restarting apache causes the permissions to be changed back to more restrictive 8-( No MDNotifyCmd runs 8-(

**Comment by icing** [comment]
Hmm, it's clearly designed too secure! ;-)

The log error you mentioned, could you elaborate on how that happens?

**Comment by opsec** [comment]
I'm not sure I can reproduce that -- if I find a way, I'll report more details.

**Comment by icing** [comment]
Closing this. No plans to implement this in the module.

**Comment by chriscroome** [comment]
FWIW I've written [a Bash script for this](https://git.coop/webarch/apache/-/blob/74a5bace356ed5ca3887e60494a85d49c30dd459/templates/apache_md_cert_cp.sh.j2), templated using Ansible, which can be run via a daily crontab, this is the result when it has been installed for Exim4 on Debian:

```bash
#!/usr/bin/env bash

# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.

set -eE

jc_min_version="1.22.0"

service="exim4"
privkey_src="/etc/apache2/md/domains/example.org/privkey.pem"
privkey_dest="/etc/exim4/exim.key"
privkey_owner="Debian-exim"
privkey_group="ssl-cert"
privkey_mode="0640"
pubcert_src="/etc/apache2/md/domains/example.org/pubcert.pem"
pubcert_dest="/etc/exim4/exim.crt"
pubcert_owner="Debian-exim"
pubcert_group="ssl-cert"
pubcert_mode="0640"

# This script needs to be run as root
if [[ "$(id -u)" != "0" ]] ; then
  echo "The ${0} script can only be run by root"
  exit 1
fi

# Check that jc is available
if ! command -v jc &> /dev/null
then
  echo "jc could not be found"
  exit 1
else
  jc_version=$(jc -v | head -n1 | awk '{ print $3 }')
  if [[ "${jc_version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    jc_version_check=$(printf "${jc_version}\n${jc_min_version}" | sort -V | head -n1)
    if [[ "${jc_version_check}" != "${jc_min_version}" ]]; then
      echo "jc version ${jc_min_version} is the minimum version required"
      exit 1
    fi
  else
    echo "There was an error parsing jc -v"
    echo "${jc_version_check}"
    exit 1
  fi
fi

# Check that the server is using UTC
localtime=$(readlink -f /etc/localtime)
tz=$(basename "${localtime}")
if [[ "${tz}" != "UTC" && "${tz}" != "UCT" ]]; then
  echo "The clock needs to be set to UTC"
  echo "${tz}"
  exit 1
fi

# Check that jp is available
if ! command -v jp &> /dev/null
then
  echo "jp could not be found"
  exit 1
fi

# Check that jq is available
if ! command -v jq &> /dev/null
then
  echo "jq could not be found"
  exit 1
fi

# Check that openssl is available
if ! command -v openssl &> /dev/null
then
  echo "openssl could not be found"
  exit 1
fi

# Check that the pubcert exists
if [[ ! -f "${pubcert_src}" ]];
then
  echo "No file found at ${pubcert_src}"
  exit 1
else
  # Check that it is a x509 cert
  openssl=$(openssl x509 -noout -text -in "${pubcert_src}" | head -n1)
  if [[ "${openssl}" != "Certificate:" ]]; then
    echo "No certificate found at ${pubcert_src}"
    echo "${openssl}"
    exit 1
  fi
fi

# Check that the privkey exists
if [[ ! -f "${privkey_src}" ]];
then
  echo "No file found at ${privkey_src}"
  exit 1
else
  # Check that it is a key
  openssl=$(openssl ec -noout -text -in "${privkey_src}" 2>/dev/null | head -n1 | awk '{ print $1 }')
  if [[ "${openssl}" != "Private-Key:" ]]; then
    echo "No private key found at ${privkey_src}"
    echo "${openssl}"
    exit 1
  fi
fi

# Check that the cert dest directory exists
pubcert_dest_dir=$(dirname "${pubcert_dest}")
if [[ ! -d "${pubcert_dest_dir}" ]]; then
  echo "The cert dest directory doesn't exist"
  echo "${pubcert_dest_dir}"
  exit 1
fi

# Check that the private key dest directory exists
privkey_dest_dir=$(dirname "${privkey_dest}")
if [[ ! -d "${pubcert_dest_dir}" ]]; then
  echo "The private key dest directory doesn't exist"
  echo "${privkey_dest_dir}"
  exit 1
fi

# Get the date the src cert was created in UNIX time
src_created=$(jc -q -m --x509-cert < "${pubcert_src}" | jq -r . | jp -c -u '[].tbs_certificate.validity.not_before | [0]')
# Get the date the dest cert was created in UNIX time
dest_created=$(jc -q -m --x509-cert < "${pubcert_dest}" | jq -r . | jp -c -u '[].tbs_certificate.validity.not_before | [0]')
# Check that the src cert created date is a positive number
if [[ "${src_created}" == +([0-9]) ]]; then
  # Check that the dest cert created date is a positive number
  if [[ "${dest_created}" == +([0-9]) ]]; then
    # Check if the dest cert created date is older that the src cert created date
    if (( src_created > dest_created )); then
      # Copy the pubcert_src to the pubcert_dest
      cp --remove-destination -a "${pubcert_src}" "${pubcert_dest}"
      # Chown the pubcert_dest
      chown ${pubcert_owner}:${pubcert_group} "${pubcert_dest}"
      # Chmod the pubcert_dest
      chmod ${pubcert_mode} "${pubcert_dest}"
      # Copy the privkey_src to the privkey_dest
      cp --remove-destination -a "${privkey_src}" "${privkey_dest}"
      # Chown the privkey_dest
      chown ${privkey_owner}:${privkey_group} "${privcert_dest}"
      # Chmod the privkey_dest
      chmod ${privkey_mode} "${privkey_dest}"
    fi
  else
    echo "Error the dest cert created date should be a positive number"
    echo "${dest_created}"
    exit 1
  fi
else
  echo "Error the src cert created date should be a positive number"
  echo "${src_created}"
  exit 1
fi

# Get the service started date
started=$(systemctl show "${service}" | jc -q -m --ini | jq -r . | jp -c -u ActiveEnterTimestamp | jc -q -m --date | jq -r . | jp -c -u epoch)
# Check that the service started date is a positive number
if [[ "${started}" == +([0-9]) ]]; then
  # Check if the created date is more recent than the started date
  if (( src_created > started )); then
      # Restart the service
      service "${service}" restart && echo "${service} restarted for new cert"
  fi
else
  echo "Error getting the service started date"
  echo "${started}"
  exit 1
fi

# vim: syntax=bash
```
