### ISSUE TITLE
<IfModule> syntax?

### ISSUE THREAD

**Issue by Harvie** [icing/mod_md#85]
I haven't found what's proper ID to use Ifmodule with mod_md. Can you please add it to README? I've found this on some obscure website, but i am not sure if that's correct:

```html
<IfModule md_module>
MDomain ...
</IfModule>
```

**Comment by icing** [comment]
Please see [the documentation of IfModule directive](https://httpd.apache.org/docs/current/mod/core.html#ifmodule) for its usage. All Apache module identifiers follow the ```<name>_module``` pattern for naming, while the source files are - by convention - using the pattern ```mod_<name>```.

You can find the ```mod_md``` module identifier also [at the top of the documentation page](https://httpd.apache.org/docs/2.4/en/mod/mod_md.html).

So, when in doubt for a specific module, look at its documentation page which should list its name.
