### ISSUE TITLE
Is the required apache patch available in apache 2.4.33

### ISSUE THREAD

**Issue by mlocati** [icing/mod_md#87]
From [README.md](https://github.com/icing/mod_md/blob/05c230f31eb1499dc36824c9f3ea200fd2c44cd1/README.md#status):

> The module has been backported to Apache 2.4.x branch and will be part of the next release (or is when 2.4.33 is out).

Reading the [Apache release notes](http://www.apache.org/dist/httpd/CHANGES_2.4), I don't see any reference to the required patch for apache 2.4.33.
I see references to mod_md for apache 2.4.30: so, should the above sentence in README.md be the following?

> The module has been backported to Apache 2.4.x branch (since Apache 2.4.30).

**Comment by icing** [comment]
The Apache release handling is a tad bit broken there. There were interim tags 2.4.30, 2.4.31 which were never made available to the public, but the CHANGES reported did not report all this dead releases together.

And, if people never can download a 2.4.30, it might be confusing to point them there. The first real release people can get with mod_md is 2.4.33. One needs to read the release notes a bit more carefully, unfortunately.

**Comment by icing** [comment]
I added some extra stuff to README. I hope it suffices.

**Comment by mlocati** [comment]
Yes, thank you!!
