### ISSUE TITLE
MDNotifyCmd not executed

### ISSUE THREAD

**Issue by FV-Valraiso** [icing/mod_md#89]
Hi icing,

I have to update certificates in a GoogleCloud Load Balancer on renewal of a certificate.
I'm trying to test the  MDNotifyCmd property for that (actually I'm just logging something in a file), but my script is never called.
My Apache 2.4 server on Ubuntu 18.04 is launched by the root user.

Any idea ?

**Comment by icing** [comment]
You could turn logging in mod_md up to see what is going on:

```
LogLevel md:debug
```
(or trace1/trace2). If the command failed to run, it should produce an ERROR log entry, anyway. 

Do you see NOTICE log entries of the form ```The Manged Domain XXX has been setup...``` in your logs?

**Comment by FV-Valraiso** [comment]
> [Wed May 30 13:23:54.414080 2018] [md:debug] [pid 3043:tid 140059036031936] mod_md.c(1015): AH10070: initializing post config dry run
[Wed May 30 13:23:54.414134 2018] [md:debug] [pid 3043:tid 140059036031936] mod_md.c(356): AH10037: server seems reachable via http: (port 80->80) and reachable via https: (port 443->443)
[Wed May 30 13:23:54.414147 2018] [md:debug] [pid 3043:tid 140059036031936] mod_md.c(216): AH10041: Server instance-group.my-domain.com:0 matches md instance-group.my-domain.com (config instance-group.my-domain.com[my-vm.c.my-group.internal, default])
[Wed May 30 13:23:54.414152 2018] [md:debug] [pid 3043:tid 140059036031936] mod_md.c(246): AH10043: Managed Domain instance-group.my-domain.com applies to vhost instance-group.my-domain.com:0
[Wed May 30 13:23:54.414156 2018] [md:debug] [pid 3043:tid 140059036031936] mod_md.c(216): AH10041: Server instance-group.my-domain.com:0 matches md instance-group.my-domain.com (config instance-group.my-domain.com[my-vm.c.my-group.internal, default])
[Wed May 30 13:23:54.414159 2018] [md:debug] [pid 3043:tid 140059036031936] mod_md.c(246): AH10043: Managed Domain instance-group.my-domain.com applies to vhost instance-group.my-domain.com:0
[Wed May 30 13:23:54.414163 2018] [md:debug] [pid 3043:tid 140059036031936] mod_md.c(276): AH10044: instance-group.my-domain.com: added contact mailto:mailto@mailto.com
[Wed May 30 13:23:54.414166 2018] [md:debug] [pid 3043:tid 140059036031936] mod_md.c(387): AH10039: Completed MD[instance-group.my-domain.com, CA=https://acme-v01.api.letsencrypt.org/directory, Proto=ACME, Agreement=https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf, Drive=1, renew=300000000]
[Wed May 30 13:23:54.414812 2018] [md:debug] [pid 3043:tid 140059036031936] md_reg.c(235): md{instance-group.my-domain.com}: is complete
[Wed May 30 13:23:54.437359 2018] [md:info] [pid 3045:tid 140059036031936] AH10071: mod_md (v1.1.0-git), initializing...
[Wed May 30 13:23:54.437382 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(356): AH10037: server seems reachable via http: (port 80->80) and reachable via https: (port 443->443)
[Wed May 30 13:23:54.437390 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(216): AH10041: Server instance-group.my-domain.com:0 matches md instance-group.my-domain.com (config instance-group.my-domain.com[my-vm.c.my-group.internal, default])
[Wed May 30 13:23:54.437396 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(246): AH10043: Managed Domain instance-group.my-domain.com applies to vhost instance-group.my-domain.com:0
[Wed May 30 13:23:54.437400 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(216): AH10041: Server instance-group.my-domain.com:0 matches md instance-group.my-domain.com (config instance-group.my-domain.com[my-vm.c.my-group.internal, default])
[Wed May 30 13:23:54.437403 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(246): AH10043: Managed Domain instance-group.my-domain.com applies to vhost instance-group.my-domain.com:0
[Wed May 30 13:23:54.439188 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(276): AH10044: instance-group.my-domain.com: added contact mailto:mailto@mailto.com
[Wed May 30 13:23:54.439200 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(387): AH10039: Completed MD[instance-group.my-domain.com, CA=https://acme-v01.api.letsencrypt.org/directory, Proto=ACME, Agreement=https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf, Drive=1, renew=300000000]
[Wed May 30 13:23:54.439413 2018] [md:debug] [pid 3045:tid 140059036031936] md_reg.c(691): sync: found 1 mds in store
[Wed May 30 13:23:54.439772 2018] [md:debug] [pid 3045:tid 140059036031936] md_reg.c(235): md{instance-group.my-domain.com}: is complete
[Wed May 30 13:23:54.439949 2018] [md:debug] [pid 3045:tid 140059036031936] md_reg.c(478): update md instance-group.my-domain.com
[Wed May 30 13:23:54.441305 2018] [md:debug] [pid 3045:tid 140059036031936] md_reg.c(235): md{instance-group.my-domain.com}: is complete
[Wed May 30 13:23:54.441412 2018] [md:debug] [pid 3045:tid 140059036031936] md_reg.c(817): md instance-group.my-domain.com updated
[Wed May 30 13:23:54.441420 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(1090): AH10074: 1 out of 1 mds are configured for auto-drive
[Wed May 30 13:23:54.441727 2018] [md:debug] [pid 3045:tid 140059036031936] md_reg.c(235): md{instance-group.my-domain.com}: is complete
[Wed May 30 13:23:54.441871 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(929): AH10064: md(instance-group.my-domain.com): state=2, driving
[Wed May 30 13:23:54.441883 2018] [md:debug] [pid 3045:tid 140059036031936] mod_md.c(961): AH10067: register md watchdog(_md_)
[Wed May 30 13:23:54.444257 2018] [md:debug] [pid 3045:tid 140059036031936] md_reg.c(235): md{instance-group.my-domain.com}: is complete
[Wed May 30 13:23:54.449977 2018] [md:debug] [pid 3048:tid 140058839824128] mod_md.c(751): AH10054: md watchdog start, auto drive 1 mds
[Wed May 30 13:23:54.550220 2018] [md:debug] [pid 3048:tid 140058839824128] mod_md.c(763): AH10055: md watchdog run, auto drive 1 mds
[Wed May 30 13:23:54.550277 2018] [md:debug] [pid 3048:tid 140058839824128] mod_md.c(707): AH10053: md(instance-group.my-domain.com): is complete, cert expires Mon, 27 Aug 2018 13:22:02 GMT
[Wed May 30 13:23:54.550283 2018] [md:debug] [pid 3048:tid 140058839824128] mod_md.c(785): AH: next run in 11:59:59 hours
>

**Comment by icing** [comment]
```
is complete, cert expires Mon, 27 Aug 2018 13:22:02 GMT
```

Since all is fine and it renewed earlier this week (I assume), it does not try again. Next try will be end of July. To trigger the renewal, you can move the directory for that domain in ```md/domains``` away and reload your server.

If you do that too often, however, Let's Encrypt will block your domain for a while.

**Comment by FV-Valraiso** [comment]
Hi Stefan,
If I move the directory, I have an error on Apache restart.
I added an new domain in my vhost and on the restart I had a new certificate.

I have this error in the log file :
[md:error] [pid 11979:tid 140158542849792] (20022)The given path is incomplete: AH: executing configured MDNotifyCmd /tmp/letsencrypt_hooks.sh

It's a step forward, but the script wasn't executed.

**Comment by icing** [comment]
Hmm, the script is executed as the user the server changes to, on most systems someone like ```www-data```. Could that play a role here? What are the permissions on the script?

**Comment by FV-Valraiso** [comment]
It's actually a test server so I put 777 permissions on the script to be sure it would be executed.
The stranger thing is the message, "The given path is incomplete" but I put the full path.
Should I try to put it in folder in /etc/apache2/md/ ?

**Comment by icing** [comment]
Reading my code again, the error code ```APR_EINCOMPLETE``` gives the text description you see (which is not really informative, I admit). And ```APR_EINCOMPLETE``` is raised, if the exit code of the started program was >127. 

So, while we can probably agree that the log message should be more telling, what is causing your script to fail? Try a simpler version of it, maybe, to track down the issue?

**Comment by FV-Valraiso** [comment]
My script is really simple :
#!/bin/bash
  
echo "Hooks was run" >> /tmp/hooks.log
echo "$@" >> /tmp/hooks.log

exit 0

And nothing is executed, I have no message in /tmp/hooks.log
I tried with and without the exit 0, but I have the same issue.

:-(

**Comment by icing** [comment]
Your server is not running in a ```chroot``` jail somewhere?

Are you capable of building and testing a new version I could make here on github that adds more logging to the command execution?

**Comment by FV-Valraiso** [comment]
I didn't use chroot for the Apache server.

I think it will be OK to build and test the new version. I have people arround to help if I fail ;-)

**Comment by icing** [comment]
Please give v1.1.12 a spin. I improved logging a bit and now allow arguments for the command to be specified in the configuration (which I admit, was handy for the additional test cases I wrote).

**Comment by FV-Valraiso** [comment]
Hi,
No problem for the installation.
I got this error in the log : AH10109: executing MDNotifyCmd /tmp/letsencrypt_hooks.sh returned 255

**Comment by icing** [comment]
Well, it looks as if your script ran and returned -1.

**Comment by icing** [comment]
Hmm, if you promise me all your worldly belongings that your script, permissions and everything around is 1A OK, I will dig deeper on another installation here.

What OS are you running on?

**Comment by icing** [comment]
Did the same test on my ubuntu 16.04 image. The script ran and afterwards ```/tmp``` looks like:

```
> ls -l /tmp
total XX
-rw-r--r-- 1 www-data www-data    31 Jun 12 10:22 hooks.log
-rwxrwxrwx 1 root     root        88 Jun 12 10:20 letsencrypt_hooks.sh
...
```

and hooks.log has the correct content. No entry in the apache log. Plain apache 2.4.33.

Question: why do you run a 2.4.29? Is this the one Ubuntu ships in 18.04?

**Comment by FV-Valraiso** [comment]
Version 2.4.29 is actually the default one for Ubuntu 18.04, I just tried to upgrade.
I just check after doing "chown www-data:www-data hooks.log", but I have still the same issue.
I deleted hooks.log, I have the same error and the file isn't created.
I tried the minimum script : 
#!/bin/bash
exit 0
And I still have error code 255 in the log file.

**Comment by icing** [comment]
Very strange. Need to install an ubuntu 18.04 image then and see what they did. I assume you basically use the default apache2 install then?

**Comment by FV-Valraiso** [comment]
Yes my boss didn't want that I install the 2.4.33 from ppa:ondrel/apache2 that already include mod_md.

**Comment by icing** [comment]
I am not seeing anything in a 18.04 installation that is different from 16.04. One more thing to test on your system. Configure

```
MDNotifyCmd /bin/false
LogLevel md:debug
```
and trigger a renewal. You should get something like:
```
[DateTime] [md:debug] [pid NN:tid NN] mod_md.c(821): AH10108: notify command '/bin/false' returned 1```

and not a 255  or something else.

**Comment by FV-Valraiso** [comment]
I have the attend log :  AH10108: notify command '/bin/false' returned 1
 
I finally spawned a new GCP VM and did the install from scratch.
I added ppa:ondrej/apache2 and installed Apache 2.4.33 + libapache2-mod-md.

And I still have the initial error : (20022)The given path is incomplete: AH10109: executing configured MDNotifyCmd /tmp/letsencrypt_hooks.sh

I did the test with an Ubuntu 16.04, and I have the same issue.
I put in the install-script.sh.zip the sequence I use to install my server for the test, I hope it will help.

[install-script.sh.zip](https://github.com/icing/mod_md/files/2098005/install-script.sh.zip)

**Comment by icing** [comment]
The log from ```/bin/false``` shows that executables are properly run and report the expected return code. I have no idea what is happening with your script.

The install script does not include a ```VirtualHost``` on port 443 with ssl, so ```mod_md``` will only sign up for a certificate if you also set the ```MDDriveMode always``` directive. [See MDDriveMode](https://github.com/icing/mod_md/wiki/Directives#mddrivemode--drive-mode). Hope we not confusing ourselves here...

**Comment by FV-Valraiso** [comment]
Even if I don't have a VirtualHost for the port 443, the script is called because I have the error in log files.
I created a script in an other folder and it seems to work :
mod_md.c(823): AH10108: notify command '/etc/apache2/md/scripts/hooks.sh' returned 0

The problem is when the script is in /tmp

**Comment by icing** [comment]
Something like this? https://askubuntu.com/questions/311438/how-to-make-tmp-executable

**Comment by FV-Valraiso** [comment]
I put the script in /tmp for my test, but I won't need it when I'll use it in production.
So everything is OK for me now :-)
