### ISSUE TITLE
Enabling `MDomain` makes unrelated domain fail

### ISSUE THREAD

**Issue by djc** [icing/mod_md#90]
I am just now experimenting with `mod_md` for the first time from the upstream 2.4.33 release. In doing so, I noticed a number of surprising issues:

- Enabling `MDomain` for one domain made restart fail with `AH01909` for another domain. As it is, it may be correct that the certificate for that other domain doesn't contain the correct domain name, but it's still pretty surprising that enabling `MDomain` for one domain makes another vhost fail.

- After making sure the non-`md`-enabled domain had all the domain names in the certificate, `mod_md` still prevented apache from starting, this time with `AH01903`.

- This situation made apache fail to start. Since my distribution runs `apache -t` to test the configuration before stopping the server, I would expect these kinds of errors to be surfaced as part of the configuration test rather than causing the server start to fail (leading to outages).

- Some log messages concerning the domain I actually enabled ended up in the log file for the vhost that had the incorrectly configured domain.

- Enabling `mod_md` seems to make it impossible to access `acme-challenge` directories that actually exist on the filesystem in a document root.

**Comment by icing** [comment]
You may see ```AH1909``` for the ```MDomain``` while the certificate is being retrieved for the first time. Note that this is a ```WARNING``` only and will not prevent your server from working.

Note that ```MDomain``` drags in all ```ServerName``` and ```ServerAlias```. May that explains the unexpected _other_ vhosts you seem to see. Please provide an example of vhosts that you find affected unexpectedly.

```AH1903``` is an error with certificate chains related to Proxy configurations. This seems totally unrelated to anything ```mod_md``` does. If you can provide me sample configurations that reproduce the issues, I will look into it.

**Comment by djc** [comment]
This is from my `httpd.conf`:

```
diff --git a/apache2/httpd.conf b/apache2/httpd.conf
index 87ec239..e4d0b77 100644
--- a/apache2/httpd.conf
+++ b/apache2/httpd.conf
@@ -97,6 +97,9 @@ LoadModule info_module modules/mod_info.so
 </IfDefine>
 LoadModule log_config_module modules/mod_log_config.so
 LoadModule logio_module modules/mod_logio.so
+<IfDefine SSL>
+#LoadModule md_module modules/mod_md.so
+</IfDefine>
 LoadModule mime_module modules/mod_mime.so
 LoadModule mime_magic_module modules/mod_mime_magic.so
 <IfDefine PROXY>
@@ -129,7 +132,7 @@ LoadModule userdir_module modules/mod_userdir.so
 </IfDefine>
 LoadModule usertrack_module modules/mod_usertrack.so
 LoadModule vhost_alias_module modules/mod_vhost_alias.so
+LoadModule watchdog_module modules/mod_watchdog.so
 
 # If you wish httpd to run as a different user or group, you must run
 # httpd as root initially and it will switch.
@@ -174,6 +177,11 @@ SSLStaplingResponderTimeout 5
 SSLStaplingReturnResponderErrors Off
 SSLStaplingCache shmcb:/var/run/ocsp(128000)
 
+ServerAdmin root@xavamedia.nl
+#MDRequireHttps permanent
+#MDCertificateAgreement https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
+#MDMustStaple on
+
 <Directory /var/www/localhost/icons>
 	Require all granted
 </Directory>
```

Then, in a vhost configuration file, I set up `MDomain` for one domain:

diff --git a/apache2/vhosts.d/my.example.com.conf b/apache2/vhosts.d/my.example.com.conf
index 63190c5..2b30699 100644
--- a/apache2/vhosts.d/my.example.com.conf
+++ b/apache2/vhosts.d/my.example.com.conf
@@ -1,3 +1,5 @@
+#MDomain dirkjan.ochtman.nl
+

There are two vhosts for `my.example.com`, for `*:80` and for `*:443`. The one for `*:80`:

```
<VirtualHost *:80>
    ServerName my.example.com
    Redirect permanent / https://my.example.com/
</VirtualHost>

<VirtualHost *:443>

    ServerName my.example.com
    DocumentRoot /var/www/my.example.com/http
    <Directory /var/www/my.example.com/http>
        Require all granted
    </Directory>

    LogFormat combined
    ErrorLog /var/www/my.example.com/logs/error_log
    TransferLog /var/www/my.example.com/logs/access_log

    SSLEngine on
    #SSLCertificateFile /etc/ssl/apache2/my.example.com.crt
    #SSLCertificateKeyFile /etc/ssl/apache2/my.example.com.key
    #SSLCertificateChainFile /etc/ssl/apache2/le-intermediate-x3.pem
    #Header always set Strict-Transport-Security "max-age=63072000"

</VirtualHost>
```

**Comment by icing** [comment]
There is nothing unusual in the example. Such configs I have in my test suite as well. Something else must be different that causes problems.

Let's step back a bit. You say that your apache did not start with ```AH1909```, but that is only a warning. So, something else was preventing the start. Let's find out what that is. Can you reproduce this again? Do you find anything else in the log?

**Comment by djc** [comment]
`/var/log/apache2/error_log` says:

```
[Mon Jun 04 10:30:28.141824 2018] [ssl:emerg] [pid 12397:tid 139748493226496] AH02311: Fatal error initialising mod_ssl, exiting. See /var/www/example3.com/logs/error_log for more information
AH00016: Configuration Failed
```

`/var/log/example3.com/logs/error_log` says:

```
[Mon Jun 04 10:30:28.141800 2018] [ssl:emerg] [pid 12397:tid 139748493226496] AH01903: Failed to configure CA certificate chain!
```

**Comment by icing** [comment]
This is rather surprising. When I look at the code, ```AH1903``` is raised if you configure a ```SSLCertificateChainFile``` that is missing, unreadable or contains invalid data.

**Comment by djc** [comment]
Right. My configuration file for `example3.com` has two vhosts with `SSLEngine on` in them, and both of these have a `SSLCertificateChainFile` that references the same `le-intermediate-x3.pem` that's used in other vhosts.

Should I raise a bug against `mod_ssl`, instead?

**Comment by icing** [comment]
What happens if you comment that out, in the first or in all vhosts? It seems we still have not really understood what is going on in your system...

**Comment by djc** [comment]
Sorry, comment what out? The `SSLCertificateChainFile` directives?

**Comment by icing** [comment]
Yes, just to see if the problems are isolated to those. Divide and conquer. :)

**Comment by djc** [comment]
So commenting out all `SSLCertificateChainFile` directives across all vhosts allowed apache to start up even with `MDomain` enabled for the initial `my.example.com`.

**Comment by djc** [comment]
And, after re-enabling all these `SSLCertificateChainFile` directives again, it still seems to work...

**Comment by icing** [comment]
I think I can see what is going on. If you specify a ```SSLCertificateChainFile``` for a vhost managed by ```mod_md``` this will lead to ```AH1903``` if the chain does not match the certificate installed. OpenSSL then rejects this.

```mod_md``` installs a temporary, self-signed certificate during the first retrieval. That will not work with your chain and cause the error. Once it has a LE certificate, this works with your chain and openssl is happy.

Note: you should not configure a chain file for a ```MDomain``` as ```mod_md``` takes care of that itself and it will only lead to trouble should Let's Encrypt in the future make changes to its chain.

**Comment by djc** [comment]
Okay, so I should be able to onboard more vhosts with `MDomain` as long as I make sure to disable the `SSL*` options (except `SSLEngine on`) at the same time, and it should work?

**Comment by icing** [comment]
SSL protocol, ciphers, stapling etc. will all be fine. Just leave the certificate related things alone.

And, yes, mod_md/mod_ssl should reject/ignore a specific chain file for a managed domain, IMO.

**Comment by djc** [comment]
So, I tried to onboard another of my domains by adding `MDomain example1.com` and commenting out certificate-related `SSL*` directives from the vhost config. However, it seems to get stuck on the `fallback-cert.pem`, so that it's now blocked by the browser. Any way to resolve that?

**Comment by djc** [comment]
(Also, thanks for the awesome support! I'm really excited about `mod_md` so I just hope this deployment can help find any rough edges to make `mod_md` usable sooner.)

**Comment by icing** [comment]
Sound like it failed to obtain a certificate from Let's Encrypt for that domain. Anything to be found in the logs?

**Comment by djc** [comment]
```
[Mon Jun 04 11:39:29.166658 2018] [ssl:warn] [pid 16525:tid 140639255446016] AH10085: Init: xavamedia.nl:443 will respond with '503 Service Unavailable' for now. This host is part of a Managed Domain, but no SSL certificate is available (yet).
[Mon Jun 04 11:39:29.166838 2018] [ssl:error] [pid 16525:tid 140639255446016] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=Apache Managed Domain Fallback / issuer: CN=Apache Managed Domain Fallback / serial: 240BCEBE0030330B0661FD6C5EF0EF9D128FD933 / notbefore: Jun  4 09:39:29 2018 GMT / notafter: Jun 18 09:39:29 2018 GMT]
[Mon Jun 04 11:39:29.166844 2018] [ssl:error] [pid 16525:tid 140639255446016] AH02604: Unable to configure certificate xavamedia.nl:443:0 for stapling
[Mon Jun 04 11:39:29.186339 2018] [ssl:warn] [pid 16526:tid 140639255446016] AH10085: Init: xavamedia.nl:443 will respond with '503 Service Unavailable' for now. This host is part of a Managed Domain, but no SSL certificate is available (yet).
[Mon Jun 04 11:39:29.186527 2018] [ssl:error] [pid 16526:tid 140639255446016] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=Apache Managed Domain Fallback / issuer: CN=Apache Managed Domain Fallback / serial: 240BCEBE0030330B0661FD6C5EF0EF9D128FD933 / notbefore: Jun  4 09:39:29 2018 GMT / notafter: Jun 18 09:39:29 2018 GMT]
[Mon Jun 04 11:39:29.186532 2018] [ssl:error] [pid 16526:tid 140639255446016] AH02604: Unable to configure certificate xavamedia.nl:443:0 for stapling
```

**Comment by djc** [comment]
Supposedly this is the same thing as #94, so it can be closed.
