### ISSUE TITLE
Incorrect version number check

### ISSUE THREAD

**Issue by Sp1l** [icing/mod_md#96]
https://github.com/icing/mod_md/blob/b541be63dfb0f80f9ff4a96307d09eff6afbd39a/src/md_crypt.c#L482

Missing a 0
```
                                   LIBRESSL_VERSION_NUMBER < 0x2070000f
```
```
                                   LIBRESSL_VERSION_NUMBER < 0x20700000f
```
~~~Running into a build error here with LibreSSL 2.7.4 here at the moment even after fixing this. Not sure how/why yet.~~~
`MD_USE_OPENSSL_PRE_1_1_API` is not set when building with LibreSSL 2.7, feels like a regression

**Comment by Sp1l** [comment]
https://github.com/icing/mod_md/blob/b541be63dfb0f80f9ff4a96307d09eff6afbd39a/src/md_crypt.c#L55

It is LibreSSL 2.7 that implements the 1.1 API so this check should be against 2.7 not 2.8 (and the missing `0` is correct)

**Comment by icing** [comment]
Thanks, either I copied it wrongly from httpd subversion's mod_ssl or it is also wrong there. Could you have a look?

**Comment by Sp1l** [comment]
It's equally wrong there 😃 
```
#if defined(LIBRESSL_VERSION_NUMBER)
/* Missing from LibreSSL */
#define MD_USE_OPENSSL_PRE_1_1_API (LIBRESSL_VERSION_NUMBER < 0x2080000f)
#else /* defined(LIBRESSL_VERSION_NUMBER) */
#define MD_USE_OPENSSL_PRE_1_1_API (OPENSSL_VERSION_NUMBER < 0x10100000L)
#endif
```
Just grabbed apache/httpd@b9b32e8 for a new build.
Will file a bug there.
